### ISSUE TITLE
Create a project for the CIP vulnerability check

### ISSUE THREAD

**Issue by yodahekinsew** [kubernetes/k8s.io#1000]
Currently, the Container Image Promoter promotes images without checking the image for any vulnerabilities. A vulnerability check is being added to the promoter to guard against this case which will use google cloud's Container Analysis Service. In order to test this check, we need a new project (k8s-cip-vuln-scanning) which can be used to host images with known vulnerabilities at different severity levels.

**Comment by thockin** [comment]
Can you say more about what exactly this is doing? Is it just to hold any GCR images that have vulnerabilities?  What about images that we promote and then a new vuln is found later?  Or is it trying to exercise the images?  Or something else?

**Comment by yodahekinsew** [comment]
The design for this check has changed, so I will no longer be needing this project (at least for the original purpose of testing by hosting test images). Closing for now.
