### ISSUE TITLE
Ingress instances should use networking.k8s.io api group instead of extensions

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/k8s.io#1031]
Currently extensions is what RBAC defines https://github.com/kubernetes/k8s.io/blob/master/infra/gcp/namespaces/namespace-user-role.yml#L20-L21

I think we should change the role and migrate the ingress instances

ref: https://github.com/kubernetes/k8s.io/pull/1025#discussion_r456128532

**Comment by ameukam** [comment]
I think this issue is addressed in #990.

**Comment by bartsmykla** [comment]
I will work on this today

**Comment by bartsmykla** [comment]
Actually I maybe not able to sit on it today, so I'll try to do it at Monday.

**Comment by spiffxp** [comment]
/assign @spiffxp @ameukam 
/milestone v1.21
We discussed moving on this as part of moving aaa to release channel

**Comment by spiffxp** [comment]
https://github.com/kubernetes/k8s.io/pull/990#pullrequestreview-503325802 - what needs to happen is actually migrating the ingress resources

```
$ ag -l extensions/v1beta1 | sort
artifactserver/manifest.yaml
gcsweb.k8s.io/ingress.yaml
k8s.io/ingress-canary-v6.yaml
k8s.io/ingress-canary.yaml
k8s.io/ingress-prod-v6.yaml
k8s.io/ingress-prod.yaml
node-perf-dash.k8s.io/ingress.yaml
perf-dash.k8s.io/ingress.yaml
slack-infra/resources/ingress.yaml
triage-party/release-team/ingress.yaml
```

In an "everyone owns their app" model I would create and assign issues.  This made me notice that I can't easily do that here:
- owners files are either missing or seem out of date
- no quick way to infer @kubernetes.io group from dir
- no tie between github usernames and @kubernetes.io group membership

**Comment by rikatz** [comment]
/assign

Check all objects with Kubepug and raise an umbrella issue

**Comment by spiffxp** [comment]
Current status: `$ rg -l extensions/v1beta1 | sort | sed -e 's/^/- [ ] &/g'`
- [ ] artifactserver/manifest.yaml
- [ ] gcsweb.k8s.io/ingress.yaml
- [ ] k8s.io/ingress-canary-v6.yaml
- [ ] k8s.io/ingress-canary.yaml
- [ ] k8s.io/ingress-prod-v6.yaml
- [ ] k8s.io/ingress-prod.yaml
- [ ] node-perf-dash.k8s.io/ingress.yaml

**Comment by ameukam** [comment]
@spiffxp `artifactserver` is not deployed on `aaa`. I'll exclude it in this issue.

**Comment by ameukam** [comment]
All ingresses have been migrated. I'll consider this done. 

```shell
kubectl get ingress.networking.k8s.io --all-namespaces
NAMESPACE             NAME                   HOSTS   ADDRESS              PORTS     AGE
gcsweb                gcsweb                 *       35.190.8.208         80, 443   492d
k8s-io-canary         k8s-io                 *       34.102.239.89        80, 443   421d
k8s-io-canary         k8s-io-v6              *       2600:1901:0:552b::   80, 443   168d
k8s-io-prod           k8s-io                 *       34.107.204.206       80, 443   421d
k8s-io-prod           k8s-io-v6              *       2600:1901:0:26f3::   80, 443   168d
node-perf-dash        node-perf-dash         *       35.227.254.215       80, 443   328d
perfdash              perfdash               *       34.102.200.94        80, 443   372d
sippy                 sippy                  *       35.244.255.27        80, 443   3d4h
slack-infra           slack-infra            *       34.107.195.71        80, 443   357d
thockin-test-certs    k8s-io                 *       34.102.202.147       80        19d
thockin-test-certs    k8s-io-v6              *       2600:1901:0:b267::   80        19d
triageparty-release   triage-party-release   *       35.186.239.70        80, 443   52d
```
/close
