### ISSUE TITLE
staging registry for kubernetes/website

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/k8s.io#1033]
We require a staging registry / cloud-build project for [kubernetes/website] to publish a build image ([hugo] + other deps).

**Background**: kubernetes/website has a containerized build environment for building the site.
In the past a simple `hugo` binary on the host at the correct version was sufficient, but with the docsy migration npm / postcss / autoprefixer are also required. Additionally recent changes are leading to "Too many open files" on darwin.

In order to facilitate standardizing development on the containerized environment, we should publish the website environment image pre-built. Currently contributors must manually invoke a target to build the image locally and then it is used in other targets.

see: https://github.com/kubernetes/website/issues/22515, https://github.com/kubernetes/website/pull/22518

[kubernetes/website]: https://github.com/kubernetes/website
[hugo]: https://gohugo.io/

**Comment by BenTheElder** [comment]
cc @dims @spiffxp

**Comment by dims** [comment]
+1 i'd support this @BenTheElder

**Comment by BenTheElder** [comment]
should I just PR this? I forgot what all we need to do to act on something like this.

**Comment by BenTheElder** [comment]
cc @jimangel

**Comment by jimangel** [comment]
I'm not sure the approval process, but I'm in support of moving this forward if other folks agree.

**Comment by spiffxp** [comment]
>should I just PR this? I forgot what all we need to do to act on something like this.

Yes, follow instructions here https://github.com/kubernetes/k8s.io/tree/master/k8s.gcr.io#creating-staging-repos
