### ISSUE TITLE
CNCF AWS account for kubernetes-sigs/cluster-api-provider-aws AMIs

### ISSUE THREAD

**Issue by ncdc** [kubernetes/k8s.io#1116]
We are currently publishing cluster-api-provider-aws Kubernetes AMIs to a VMware-owned AWS account. This account is the hard-coded default account to use when looking up AMIs (this is overridable). It would be nice if we could transition the AMIs to a CNCF-owned AWS account.

There are probably lots of moving parts here:

- [x] Find a sponsor/champion with access to create a new CNCF AWS account
- [ ] Determine security/access controls to the account
- [ ] Determine the process to build & publish a new AMI (this will use kubernetes-sigs/image-builder)
- [ ] Bonus points if we can automate this with OWNERS + a PR + Prow to request and build new AMIs
- [x] Grant access to the AWS account to @ncdc @detiber @randomvariable @rudoi @vincepri (current set of active CAPA maintainers) (let me know if you don't want access and/or if we should add others)

Corresponding cluster-api-provider-aws issue: https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/1861

cc @randomvariable @detiber @rudoi @vincepri

**Comment by nikhita** [comment]
> Find a sponsor/champion with access to create a new CNCF AWS account

@ncdc can you create an issue like https://github.com/kubernetes/funding/issues/10 in the funding repo?

**Comment by ncdc** [comment]
https://github.com/kubernetes/funding/issues/12

**Comment by dims** [comment]
@idvoretskyi i've updated CNCFSD-492 with the email address of the people who need access. Please let @ncdc know when this is ready.

**Comment by ncdc** [comment]
Closing this as we have the access we need to proceed. If we need additional support, we can open new issues. Thanks!

/close
