### ISSUE TITLE
Groups reconciler should support option to keep conversation history

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/k8s.io#1171]
E-mails sent to leads@kubernetes.io are accessible as email _only_, I can't go to https://groups.google.com/u/0/a/kubernetes.io/g/leads to see what's been posted to the group

I manually enabled "Group Settings -> Posting Policies -> Conversation: ON"

This should be configurable via the group reconciler (and enforced via tests for groups that should support history)

/sig contribex
/area access
/help

**Comment by bartsmykla** [comment]
@spiffxp I have created PR with the feature you've been asking: https://github.com/kubernetes/k8s.io/pull/1332

**Comment by cblecker** [comment]
@spiffxp @bartsmykla THANK YOU for tracking this down. I was so confused.

cc @nikhita

**Comment by justaugustus** [comment]
YASSSSSSSSSSSS. Very awesome! 🎉

**Comment by nikhita** [comment]
@bartsmykla Thank you so much!! This was definitely very confusing!
