### ISSUE TITLE
Investigate creating prow build cluster as a private build cluster

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/k8s.io#1178]
This would allow us to avoid in-use IP address quota as a limiting factor.  We were having a hard time getting in-use IP address quota.  (ref: https://github.com/kubernetes/k8s.io/issues/1132#issuecomment-678389503)

https://cloud.google.com/kubernetes-engine/docs/how-to/private-clusters

Things to consider:
- k8s-prow-builds (where jobs are migrating from) uses external IP's for its nodes
- thus we may run into job-specific issues in a private cluster not previously encountered
- we may need to use something like Cloud NAT for egress
- we may want to watch out for rate limiting from 3rd parties (eg: github, dockerhub) if doing so makes our N node cluster look like a single IP

**Comment by spiffxp** [comment]
/remove-lifecycle rotten
/reopen
Since we bumped into IP quota https://github.com/kubernetes/k8s.io/issues/1616#issuecomment-774342368

I don't have bandwidth for this, not sure it's appropriate for new contributors so leaving unassigned w/o /help

**Comment by spiffxp** [comment]
/remove-priority important-longterm
/priority backlog
I would bucket this under nice-to-have, so I'm almost tempted to suggest awaiting-more-evidence unless we notice we're having issues with IP quota again.

**Comment by spiffxp** [comment]
/remove-priority backlog
/priority awaiting-more-evidence
Couldn't resist the temptation

**Comment by ameukam** [comment]
There  is no need to do this. We currently have multiple public build clusters over some cloud providers.

/close
