### ISSUE TITLE
Add documentation to describe how to backfill pre-VDF images into post-VDF subdir path

### ISSUE THREAD

**Issue by listx** [kubernetes/k8s.io#1282]
Problem: After the [vanity domain flip][vdf] happened, there are now N subprojects with their own subdirs underneath `k8s.gcr.io/<SUBDIR>`. This is fine. But now we would like to backfill pre-VDF images that currently live in `k8s.gcr.io/<OLD_IMAGE>` into `k8s.gcr.io/<SUBDIR>/<OLD_IMAGE>`. This way, any new post-VDF references that use the SUBDIR prefix can also refer to old images that were built before the VDF happened, using the same SUBDIR prefix.

In other words, all images in `k8s.gcr.io` that don't live under a staging subproject's SUBDIR *should* be given a SUBDIR and copied there.

What we want to do is just list the old images in `images.yaml` to make sure they also exist under the subproject's SUBDIR. However, this won't work on its own because the staging repo won't have these images. So there are at least 2 steps involved:

1. Copy pertinent old images from `k8s.gcr.io` root into `gcr.io/k8s-staging-SUBPROJECT`.
2. Add images from Step 1 into the `images.yaml` for `gcr.io/k8s-staging-SUBPROJECT`, to promote into `k8s.gcr.io/SUBPROJECT-SUBDIR/<old_image>`.

This involves some trivial shell logic, probably. But we could just start with some docs.

[vdf]: https://github.com/kubernetes/release/issues/270

**Comment by listx** [comment]
Which sample projects need backfilling first? @thockin @justaugustus

**Comment by spiffxp** [comment]
/kind documentation
/wg k8s-infra
/area artifacts
/sig release
/area release-eng
/assign @justaugustus @hasheddan 
FYI @kubernetes/release-engineering 
Is this still relevant?

**Comment by justaugustus** [comment]
Given we've done the VDF in https://github.com/kubernetes/release/issues/270 and all images were backfilled, I'd say let's close this.

For RelEng, I copied the last two or three versions of our images and promoted those ahead of VDF.
I'd suggest subprojects that need similar to do the same in a post-VDF world, instead of having us sign up for the discovery work, which I think ultimately will be low-value in comparison.

/close
