### ISSUE TITLE
get k8s.io/Kubernetes failed

### ISSUE THREAD

**Issue by fruitboy1226** [kubernetes/k8s.io#130]
Hi,
i met one issue when i get the kubernets from k8s.io.
media@media-desktop:~/k8s$ go get k8s.io/kubernetes
package k8s.io/kubernetes: unrecognized import path "k8s.io/kubernetes" (https fetch: Get https://k8s.io/kubernetes?go-get=1: proxyconnect tcp: EOF)

is there any env setup errors? thanks very much.

**Comment by thockin** [comment]
In general, kubernetes/kubernetes is not go-get friendly.
