### ISSUE TITLE
Migrate k8s-gubernator:builds dataset to wg-k8s-infra

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/k8s.io#1307]
Part of migrating away from gcp-project k8s-gubernator: https://github.com/kubernetes/k8s.io/issues/1308

This dataset: https://console.cloud.google.com/bigquery?p=k8s-gubernator

It's used by:
- kettle, which writes to it (migration ref: https://github.com/kubernetes/k8s.io/issues/787)
- go.k8s.io/triage, which uses results from queries against it (migration ref: https://github.com/kubernetes/k8s.io/issues/1305)
- metrics jobs, which run queries against it and store results in gcs (migration ref: https://github.com/kubernetes/k8s.io/issues/1306)

It's publicly readable (though compute time for queries will be charged to their own GCP account), but not publicly writable

It's not quite clear to me what strategies are available to us:
- stop-the-world: stop writing data, copy to new dataset, point everything at new dataset
- sync-the-world: replicate data from old dataset to new dataset, point reporting tools to replicated dataset, then point kettle at new dataset
- backfill-the-world: cut everything over to the new dataset, then backfill (day, then week, then all)

Given that this is a public artifact I'm inclined to suggest we home this under the kubernetes-public gcp project.  We should examine billing briefly to understand if there are associated network/compute costs we would want billed elsewhere.

**Comment by spiffxp** [comment]
/milestone v1.21
/assign @spiffxp @MushuEE 
to investigate possible approaches

**Comment by ameukam** [comment]
@spiffxp With kettle currently down, we can go with 
> stop-the-world : 
I can add a BQ dataset in kubernetes-public and data transfer job.

**Comment by spiffxp** [comment]
Pretty sure I've seen activity on this in PRs related to kettle:
- https://github.com/kubernetes/k8s.io/pull/2737
- https://github.com/kubernetes/k8s.io/pull/2747
- https://github.com/kubernetes/k8s.io/pull/2749

**Comment by ameukam** [comment]
> Pretty sure I've seen activity on this in PRs related to kettle:
> 
>     * [kubernetes-public: Add BigQuery dataset for kettle #2737](https://github.com/kubernetes/k8s.io/pull/2737)
> 
>     * [kubernetes-public: BigQuery Data transfer to k8s-infra-kettle #2747](https://github.com/kubernetes/k8s.io/pull/2747)
> 
>     * [kubernetes-public: Enable BigQuery Data Transfer #2749](https://github.com/kubernetes/k8s.io/pull/2749)

Next steps are : 
- enable monitoring for `gs://kubernetes-jenkins`: https://github.com/kubernetes/test-infra/tree/master/kettle#pubsub
- deploy a staging instance on `aaa`

**Comment by ameukam** [comment]
We can close this. From: https://github.com/kubernetes/k8s.io/issues/789. 

All the datasets are gone. 

cc @BenTheElder 

/close

**Comment by BenTheElder** [comment]
Yeah, this should be in k8s-infra already. Thanks for closing.
