### ISSUE TITLE
Images aren't being promoted into k8s.gcr.io

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/k8s.io#1361]
/assign @listx @justaugustus 

Both CIP-related jobs started failing over the weekend:
- https://k8s-testgrid.appspot.com/wg-k8s-infra-k8sio#post-k8sio-cip
- https://k8s-testgrid.appspot.com/wg-k8s-infra-k8sio#ci-k8sio-cip

```
I1026 18:57:29.085994      12 inventory.go:318] *looking at "/home/prow/go/src/github.com/kubernetes/k8s.io/k8s.gcr.io"
E1026 18:58:56.477551      12 token.go:57] could not execute cmd /usr/bin/gcloud auth --account=k8s-infra-gcr-promoter@k8s-ci-images.iam.gserviceaccount.com print-access-token
E1026 18:58:56.477616      12 inventory.go:1157] could not get service account token for k8s-infra-gcr-promoter@k8s-ci-images.iam.gserviceaccount.com
F1026 18:58:56.477636      12 cip.go:254] exit status 1
```

The error seems to indicate whatever service account they're trying to use has disappeared or become inaccessible.  My guess is they should be using the service account provided by workload identity.  It appears right now they do not?
- https://github.com/kubernetes/test-infra/blob/3118d2e26b19cb63217233d36108ecbe25ac7dcb/config/jobs/kubernetes/test-infra/test-infra-trusted.yaml#L1075
- https://github.com/kubernetes/test-infra/blob/3118d2e26b19cb63217233d36108ecbe25ac7dcb/config/jobs/kubernetes/test-infra/test-infra-trusted.yaml#L729

Thus far the only impacted PR is https://github.com/kubernetes/k8s.io/pull/1355 which didn't promote anything (setup a new staging repo)

However, until this is addressed, nothing is going to get promoted into k8s.gcr.io

**Comment by justaugustus** [comment]
Opened https://github.com/kubernetes/test-infra/pull/19698 for this.

**Comment by justaugustus** [comment]
`ci-k8sio-cip` has bounced back in https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-k8sio-cip/1320862336466030592, so hopefully `post-k8sio-cip` should follow suit on the next merge that touches `{images,manifests}`.

ref: https://kubernetes.slack.com/archives/CJH2GBF7Y/p1603757150461600?thread_ts=1603745644.459600&cid=CJH2GBF7Y

**Comment by justaugustus** [comment]
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-k8sio-cip/1321089778111746048 was a successful run of the postsubmit, so this can be closed now.

ref: https://github.com/kubernetes/k8s.io/pull/1362
/close
