### ISSUE TITLE
Document webui access to k8s.gcr.io

### ISSUE THREAD

**Issue by mrueg** [kubernetes/k8s.io#1371]
Maybe I couldn't find it, but is there a way to have a webui read-only access and see what's available on k8s.gcr.io? 
I'm looking for something like https://console.cloud.google.com/gcr/images/k8s/GLOBAL which one can access for staging repositories e.g. https://console.cloud.google.com/gcr/images/k8s-staging-metrics-server/GLOBAL

It would be great from a user perspective to have read-only visibility into that.

**Comment by dims** [comment]
@mrueg please see https://console.cloud.google.com/gcr/images/k8s-artifacts-prod

**Comment by zencircle** [comment]
I am trying to find the metrics-server and its not available here ?
