### ISSUE TITLE
Setup a gitops-driven workflow for google cloud monitoring dashboards

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/k8s.io#1376]
The use case here is ensuring we don't lose dashboards.  By backing them up into git, we can keep track of when/why they have changed, and restore them if they're deleted from google cloud monitoring.

I really wish the UI provided import/export options to make this easier.  That said, it is possible via the API or `gcloud`: https://cloud.google.com/blog/products/management-tools/cloud-monitoring-dashboards-using-an-api

One workflow could be:
- human manually edits dashboard via ui
- human exports to file via `gcloud monitoring dashboards describe`
- human opens PR
- other humans review PR
- presubmit job ensures file's etag value is up to date (tide will use to verify just prior to merge)
- when PR merges, postsubmit job updates dashboard from file via `gcloud monitoring dashboards update`

This workflow could also allow:
- human edits file
- human updates file with etag
- (same PR workflow as above)

An alternative workflow is:
- periodic job exports dashboard(s) to files
- if dashboards have changed vs. what's in file, period job updates/opens a PR (same workflow as above)

And finally, it may be possible to automate away the etag toil iff we are smart/consistent about when to avoid stomping overtop of unexpected changes.

/priority important-longterm
/wg k8s-infra
/sig testing
since the dashboards I have in mind are for k8s-infra-prow-build

Specifically, I have these two dashboards in mind (must be member of [k8s-infra-prow-viewers@kubernetes.io](https://github.com/kubernetes/k8s.io/blob/master/groups/groups.yaml#L630-L660) to view, feel free to PR yourself in if you would like)
- https://console.cloud.google.com/monitoring/dashboards/custom/10925237040785467832?project=k8s-infra-prow-build&timeDomain=1d
- https://console.cloud.google.com/monitoring/dashboards/custom/10510319052103514664?project=k8s-infra-prow-build&timeDomain=1d

**Comment by spiffxp** [comment]
FYI @kubernetes/ci-signal if anyone is interested in this

/help
I am willing to give someone appropriate credentials to develop this workflow, answer questions and review PR's

/area infra/monitoring

**Comment by spiffxp** [comment]
/remove-lifecycle stale
/lifecycle frozen
Keeping this around as a good help-wanted issue, unless/until we decide on some other easily "git-ops-able" dashboard solution

**Comment by spiffxp** [comment]
The UI makes import/export much easier these days, and we now export dashboards as part of audit

So we still can't immediately recreate dashboards at the run of a script for DR purposes, but we're better off than we used to be

**Comment by spiffxp** [comment]
Could also try using terraform, as is being done here: https://github.com/GoogleCloudPlatform/oss-test-infra/tree/master/prow/oss/terraform

**Comment by spiffxp** [comment]
There is an intent to eventually move away from Grafana for monitoring.prow.k8s.io if it continues to run on google.com infra for too much longer, due to a license change.  This would be a good opportunity to prototype

**Comment by ameukam** [comment]
> There is an intent to eventually move away from Grafana for monitoring.prow.k8s.io if it continues to run on google.com infra for too much longer, due to a license change. This would be a good opportunity to prototype

Is the license change is about Grafana's [switch](https://grafana.com/blog/2021/04/20/grafana-loki-tempo-relicensing-to-agplv3/) to APLv3 ?

**Comment by rajibmitra** [comment]
I am interested to work on this @spiffxp 
/assign

**Comment by ameukam** [comment]
We are not doing this anymore. We have public monitoring dashboards:

- https://monitoring-gke.prow.k8s.io
- https://monitoring-eks.prow.k8s.io
