### ISSUE TITLE
Sweep for dead links

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/k8s.io#140]
In reviewing https://github.com/kubernetes/community/pull/2408, I noticed that http://cherrypick.k8s.io/#/queue times out. We should sweep the nginx config for dead links and remove them.

/sig contributor-experience
/help

**Comment by ixdy** [comment]
Yeah, I believe cherrypick.k8s.io was part of the old mungegithub service, which has since been turned down.

**Comment by nzoueidi** [comment]
I see that the PR  #2408 has been merged. If it doesn't close this issue. I would like to work on it. Thanks :)

**Comment by nikhita** [comment]
> I see that the PR #2408 has been merged. If it doesn't close this issue. I would like to work on it. Thanks :)

That PR just checks for the cherry-pick link, so please feel free to work on this!

Checking if all the links mentioned here https://github.com/kubernetes/k8s.io/tree/master/k8s.io work + fixing them/mentioning them in the issue here should be good enough. :)

**Comment by nzoueidi** [comment]
There is an invalid URLs which are: `https://go.k8s.io` and `https://go.kubernetes.io`
The missing one are: `https://blog.kubernetes.io` and `https://kubernetes.io`
And there is only one URL which is `https://kubernetes.submit-queue.k8s.io`, the correct one is `https://submit-queue.kubernetes.io`
