### ISSUE TITLE
Upgrade terraform provider for aaa cluster to version 3.*

### ISSUE THREAD

**Issue by ameukam** [kubernetes/k8s.io#1403]
The version 2 of the Terraform Google provider is no longer maintained (last version is 2.20.3). 

Current version used:
https://github.com/kubernetes/k8s.io/blob/a64cb47f635eac64f576c783e5bc846910d23be8/infra/gcp/clusters/projects/kubernetes-public/aaa/00-inputs.tf#L17-L21

We should upgrade to the version 3 of the provider. 

Migration guide: https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/version_3_upgrade#provider-version-configuration. 

/area cluster-mgmt

**Comment by spiffxp** [comment]
If you'd like a starting point, I had started on this while setting up the prow clusters earlier this year.  I got stuck on `create_subnetwork`, more info in the commit message:

https://github.com/spiffxp/k8s.io/commit/435b335dd17368889a4455c654ffa420334b6cca

**Comment by spiffxp** [comment]
/wg k8s-infra
/milestone v1.21
/assign @ameukam 
please unassign if you don't have bandwidth to work on this

**Comment by ameukam** [comment]
/unassign
/help
@spiffxp It would be great to have a sandbox project ( and maybe with a pre-defined budget) where people can safely work on this issue.

**Comment by ameukam** [comment]
With a simple change of the provider: 

```
  required_providers {
    google      = "<= 3.46"
    google-beta = "<= 3.46"
  }
 ```
 
Terraform will try to create the cluster : 
```

Warning: Resource targeting is in effect

You are creating a plan with the -target option, which means that the result
of this plan may not represent all of the changes requested by the current
configuration.
		
The -target option is not for routine use, and is provided only for
exceptional situations such as recovering from errors or mistakes, or when
Terraform specifically suggests to use it as part of an error message.


Error: Instance cannot be destroyed

  on 10-cluster-configuration.tf line 62:
  62: resource "google_container_cluster" "cluster" {

Resource google_container_cluster.cluster has lifecycle.prevent_destroy set,
but the plan calls for this resource to be destroyed. To avoid this error and
continue with the plan, either disable lifecycle.prevent_destroy or reduce the
scope of the plan using the -target flag.
```

**Comment by onlydole** [comment]
Jumping in to help triage/groom/etc.

/assign

**Comment by rikatz** [comment]
/assign 
Wanna follow and help in this one :D

**Comment by spiffxp** [comment]
Upgrading terraform ref: https://github.com/kubernetes/k8s.io/issues/2020
