### ISSUE TITLE
Migrate away from google.com gcp project kubernetes-ci-images

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/k8s.io#1460]
Part of umbrella issue to migrate away from google.com gcp projects: https://github.com/kubernetes/k8s.io/issues/1469

Part of umbrella to migrate kubernetes e2e test images/registries to community-owned infrastructure: kubernetes/k8s.io#1458

Pulling this out of https://github.com/kubernetes/test-infra/issues/19483 which covered running `ci-kubernetes-build` on community-owned infrastructure

The community-owned job now writes artifacts to:
- `gs://k8s-release-dev` instead of `gs://kubernetes-release-dev`
- `gcr.io/k8s-staging-ci-images` instead of `gcr.io/kubernetes-ci-images`

We need to migrate away from `gcr.io/kubernetes-ci-images`, which will involve:
- announce deprecation of `gcr.io/kubernetes-ci-images`
- migrating jobs/subprojects to use `gcr.io/k8s-staging-ci-images` instead

During the deprecation window, we will need to either:
- continue running a google.com job that publishes to `gcr.io/kubernetes-ci-images`
- setup a job that syncs from `gcr.io/k8s-staging-ci-images` to `gcr.io/kubernetes-ci-images`

Once the window has passed, we can:
- delete the old job
- delete the old project

**Potential impact** (ref: https://github.com/kubernetes/test-infra/issues/19483#issuecomment-733258839)
- anyone downstream who consumes `gcr.io/kubernetes-ci-images`
- clusters using `kubeadm` without a custom image repository and with a `ci/foo` version
  - may impact `cluster-api` and its implementations
  - may impact `kinder`

I'm starting this as an umbrella issue here.  It may require a KEP, or it may be better homed in kubernetes/kubeadm.

**Comment by spiffxp** [comment]
Per https://github.com/kubernetes/test-infra/issues/19483#issuecomment-735899029

- `kinder` doesn't use `gcr.io/kubernetes-ci-images`, so it's not impacted; it needs to be updated to use `gs://k8s-release-dev` (ref: https://github.com/kubernetes/kubeadm/issues/2355)
- `kubeadm` needs to change to use a new default value, either via a new API version, or across all existing APIs (ref: https://github.com/kubernetes/kubeadm/issues/2356)

**Comment by neolit123** [comment]
just logged a cluster-api ticket (req changes appear to be minimal and non-blocking):
https://github.com/kubernetes-sigs/cluster-api/issues/4103

for kubeadm, the GCR change is done:
https://github.com/kubernetes/kubeadm/issues/2356
(and cherry picked to the support skew)

just merged the GCS change for kinder too:
https://github.com/kubernetes/kubeadm/issues/2355

**Comment by neolit123** [comment]
it seems we aren't publishing the latest artifacts to the new GCS?
https://github.com/kubernetes/kubeadm/issues/2380#issuecomment-766401628

> looks like the problem is the new bucket we switched to [here](https://github.com/kubernetes/kubeadm/pull/2379).
> 
> https://console.cloud.google.com/storage/browser/_details/k8s-release-dev/ci/latest-1.20.txt resolves to `v1.20.0-beta.2.96+98bc258bf5516b`
> 
> the latest version reported by https://dl.k8s.io/ci/latest-1.20.txt is the valid one:
> `v1.20.3-rc.0.15+18194169ac684f`
> but this version and the artifacts are missing in the new bucket.

**Comment by spiffxp** [comment]
I did a quick comparison of build parity between kubernetes-release-dev (which currently backs dl.k8s.io) and k8s-release-dev here: https://github.com/kubernetes/test-infra/pull/20964#issuecomment-784354491

There are times where one of the build jobs flakes, and the other doesn't.  If the flake happens on the job writing to `gs://k8s-release-dev`, then you may occasionally hit this if you're pulling from dl.k8s.io

**Comment by BobyMCbobs** [comment]
There appears to be a few missing images in _k8s-staging-ci-images_:
```
bazel							      <
cloud-controller-manager				      <
cloud-controller-manager-amd64				      <
cloud-controller-manager-arm				      <
cloud-controller-manager-arm64				      <
cloud-controller-manager-ppc64le			      <
cloud-controller-manager-s390x				      <
conformance							conformance
conformance-amd64						conformance-amd64
conformance-arm							conformance-arm
conformance-arm64						conformance-arm64
conformance-ppc64le						conformance-ppc64le
conformance-s390x						conformance-s390x
hyperkube							hyperkube
hyperkube-amd64							hyperkube-amd64
hyperkube-arm							hyperkube-arm
hyperkube-arm64							hyperkube-arm64
hyperkube-ppc64le						hyperkube-ppc64le
hyperkube-s390x							hyperkube-s390x
kube-aggregator						      <
kube-aggregator-amd64					      <
kube-aggregator-arm					      <
kube-aggregator-arm64					      <
kube-aggregator-ppc64le					      <
kube-aggregator-s390x					      <
kube-apiserver							kube-apiserver
kube-apiserver-amd64						kube-apiserver-amd64
kube-apiserver-arm						kube-apiserver-arm
kube-apiserver-arm64						kube-apiserver-arm64
kube-apiserver-ppc64le						kube-apiserver-ppc64le
kube-apiserver-s390x						kube-apiserver-s390x
kube-controller-manager						kube-controller-manager
kube-controller-manager-amd64					kube-controller-manager-amd64
kube-controller-manager-arm					kube-controller-manager-arm
kube-controller-manager-arm64					kube-controller-manager-arm64
kube-controller-manager-ppc64le					kube-controller-manager-ppc64le
kube-controller-manager-s390x					kube-controller-manager-s390x
kube-proxy							kube-proxy
kube-proxy-amd64						kube-proxy-amd64
kube-proxy-arm							kube-proxy-arm
kube-proxy-arm64						kube-proxy-arm64
kube-proxy-ppc64le						kube-proxy-ppc64le
kube-proxy-s390x						kube-proxy-s390x
kube-scheduler							kube-scheduler
kube-scheduler-amd64						kube-scheduler-amd64
kube-scheduler-arm						kube-scheduler-arm
kube-scheduler-arm64						kube-scheduler-arm64
kube-scheduler-ppc64le						kube-scheduler-ppc64le
kube-scheduler-s390x						kube-scheduler-s390x
```

also according to https://cs.k8s.io/?q=kubernetes-ci-images&i=nope&files=&excludeFiles=&repos=, the repos seeming to still be using them (ignoring documentation related) are:
- kubernetes-sigs / cluster-api-provider-azure
- kubernetes / test-infra (https://github.com/kubernetes/test-infra/pull/21548)
- kubernetes-sigs / cluster-api
- kubernetes-sigs / cluster-api-provider-openstack
- kubernetes / release

all of which only have minimal references.

**Comment by ameukam** [comment]
About the images :
- `kube-aggretator` has not been published since 1.12
- `cloud-controller-manager` has not been publish since 1.16 
So we don't really need to migrate them but we make sure they can be consumed. That's you find reference of kubernetes-ci-images in `k/release`.

IMO, we should announce a maintenance window before we made changes in other repos outside of `k/test-infra`.

**Comment by spiffxp** [comment]
/remove-lifecycle stale
This is being worked on in concert with gs://kubernetes-release-dev migration

**Comment by spiffxp** [comment]
Intend to call this done once deprecation window is announced for https://github.com/kubernetes/k8s.io/issues/2318, so keeping in v1.22

There are some repos that reference this? But it's mostly in docs, and most of them are historical docs that probably shouldn't be updated. https://cs.k8s.io/?q=kubernetes-ci-images&i=nope&files=&excludeFiles=&repos=

**Comment by spiffxp** [comment]
I've updated https://github.com/kubernetes/k8s.io/issues/2318 to track removing any remaining non necessary/historically-archived references to `kubernetes-ci-images` across the kubernetes project

I will close this once I've opened a followup issue to turn down this project post-deprecation-window

**Comment by spiffxp** [comment]
/close
Followup issue to close (milestoned to v1.25) is https://github.com/kubernetes/k8s.io/issues/2417
