### ISSUE TITLE
Migrate away from google.com gcp project kubernetes-tools

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/k8s.io#1466]
Part of umbrella issue to migrate away from google.com gcp projects: https://github.com/kubernetes/k8s.io/issues/1469

We used to host slack-infra on a cluster running in kubernetes-tools.  The cluster has since been turned down: https://github.com/kubernetes/k8s.io/issues/790

However there are still references to images in this project: https://cs.k8s.io/?q=kubernetes-tools&i=nope&files=&repos=

I'm pretty sure we have a staging repo, and can replace the remaining references

**Comment by spiffxp** [comment]
Here's what we have in the staging repository
```
$ gcloud container images list --repository gcr.io/k8s-staging-slack-infra
NAME
gcr.io/k8s-staging-slack-infra/slack-event-log
gcr.io/k8s-staging-slack-infra/slack-moderator
gcr.io/k8s-staging-slack-infra/slack-post-message
gcr.io/k8s-staging-slack-infra/slack-report-message
gcr.io/k8s-staging-slack-infra/slack-welcomer
gcr.io/k8s-staging-slack-infra/tempelis
```

**Comment by spiffxp** [comment]
We are missing slackin, which is referenced here: https://github.com/kubernetes/k8s.io/blob/54e8506f8404206eb15d619ac55324332a47985c/slack-infra/resources/slackin/deployment.yaml#L19

**Comment by ameukam** [comment]
@spiffxp Since the slackin image used is built from a fork (possibly https://github.com/Katharine/slackin), we could manually push the image to `gcr.io/k8s-staging-slack-infra/`.

**Comment by spiffxp** [comment]
Did the manual push as a workaround for now.
```
$ docker pull gcr.io/kubernetes-tools/slackin-kubernetes@sha256:d1a9b02239e690d5cbd78c76475a112aedf279dbd8ef401de1b8394f817a23b3
$ docker tag gcr.io/kubernetes-tools/slackin-kubernetes@sha256:d1a9b02239e690d5cbd78c76475a112aedf279dbd8ef401de1b8394f817a23b3 gcr.io/k8s-staging-slack-infra/slackin-kubernetes
$ docker push gcr.io/k8s-staging-slack-infra/slackin-kubernetes
# ...
latest: digest: sha256:d1a9b02239e690d5cbd78c76475a112aedf279dbd8ef401de1b8394f817a23b3 size: 1583
$ gcloud container images list-tags gcr.io/k8s-staging-slack-infra/slackin-kubernetes
DIGEST        TAGS    TIMESTAMP
d1a9b02239e6  latest  2019-03-11T18:50:49
```

**Comment by BobyMCbobs** [comment]
I made this PR to update the references away from _kubernetes-tools_
https://github.com/kubernetes-sigs/slack-infra/pull/44

**Comment by spiffxp** [comment]
/close
No more references to kubernetes-tools https://cs.k8s.io/?q=kubernetes-tools&i=nope&files=&excludeFiles=&repos=

**Comment by spiffxp** [comment]
/assign @spiffxp @BobyMCbobs @ameukam 
Keeping track of who's helped close out what
