### ISSUE TITLE
hook up build clusters to prow staging instance

### ISSUE THREAD

**Issue by ameukam** [kubernetes/k8s.io#1475]
Part of #1394 

* ensure `aaa` cluster has network access to `k8s-infra-prow-build` and `k8s-infra-prow-build-trusted` build clusters 
* Generate kubeconfig config (and credentials) for `k8s-infra-prow-build` and `k8s-infra-prow-build-trusted` and them as secrets in namespace `prow` (in `aaa` cluster). see prow [doc](https://github.com/kubernetes/test-infra/blob/master/prow/getting_started_deploy.md#run-test-pods-in-different-clusters)

/area prow
/sig testing
/wg k8s-infra

**Comment by spiffxp** [comment]
I would hold off on this until you've documented more of a transition plan.

To date, I'm not sure we have successfully had two prow service clusters pointed at the same build cluster.  There are a number of potentially-dueling prow components to consider.  @chaodaiG was looking into this recently for a different prow/build-cluster for a different project (ref: https://github.com/kubernetes/test-infra/issues/14343)

The issue I am aware of off the top of my head is that `sinker` consider pods that _do_ have prow-related labels, but are not in the service cluster's registry as orphans, and delete them.  This means if you point the prow staging instance at k8s-infra-prow-build, it will delete any pods it hasn't scheduled. See https://github.com/kubernetes/test-infra/blob/8f5082828ae02af9ae105119730f18ae0609678c/prow/cmd/sinker/main.go#L475-L493

**Comment by spiffxp** [comment]
cc @BenTheElder @amwat

**Comment by ameukam** [comment]
As discussed during SIG testing meeting on 02/23/2021, we can deploy the staging again `k8s-infra-prow-build` and `k8s-infra-prow-build-trusted` using a different namespace than `test-pods`. 
cc @BenTheElder

**Comment by ameukam** [comment]
This was blocked by https://github.com/kubernetes/k8s.io/issues/2559. 
I think we can it call done. 

/close
