### ISSUE TITLE
cert-manager cannot renew k8s-io-prod certificate due to second IPv6 ingress

### ISSUE THREAD

**Issue by munnerz** [kubernetes/k8s.io#1476]
As initially reported and discussed [on Slack](https://kubernetes.slack.com/archives/CCK68P2Q2/p1607546569252400), the `k8s-io-prod` certificate (used for the redirector service) is failing to renew.

After some debugging, there are two issues at play here:

* #1374 adding a second IPv6 only Ingress resource and the AAAA record configured to point to this - cert-manager only knows to update a _single_ Ingress (named via the `edit-in-place` annotation) to inject `path` entries for the HTTP01 challenge solvers. As per https://letsencrypt.org/docs/ipv6-support/, if an AAAA record is returned then Let's Encrypt will *prefer* that and utilise it first. If we update cert-manager to *only* update the IPv6 Ingress resource, Let's Encrypt will quite likely pass validation (as it won't check IPv4) *however*, because cert-manager performs a 'self check' to ensure all routes are serving traffic correctly, and because our *Pods* do not utilise IPv6, the self check performed by cert-manager will never pass either. Ultimately, we need to ensure *both* Ingress resources contain the challenge path entries (which is not something that cert-manager supports today).

* When running `kubectl describe` on our Ingress resources, the follow error is shown:

```
  Warning  Sync    6m38s (x29 over 85m)  loadbalancer-controller  Error during sync: error running backend syncing routine: googleapi: Error 403: Exceeded limit 'MAX_DISTINCT_NAMED_PORTS' on resource 'k8s-ig--ea949c440a044527'. Limit: 1000.0, limitExceeded
```

It appears that ingress-gce does *not* clean up 'unused named ports' - it _was_ originally added in https://github.com/kubernetes/ingress-gce/pull/430, but was later reverted in https://github.com/kubernetes/ingress-gce/pull/585.

We can see that there are a _lot_ of named ports associated with the 3 'unmanaged instance groups' that ingress-gce creates:

```
gcloud compute instance-groups get-named-ports k8s-ig--ea949c440a044527 --project kubernetes-public --zone us-central1-c | wc -l
1001
```

As you can see here, there are far fewer than 1000 nodePorts in our aaa cluster:

```
kubectl get services -A -o yaml | grep nodePort
      nodePort: 30062
      nodePort: 32044
      nodePort: 30404
      nodePort: 31694
      nodePort: 32072
      nodePort: 32212
      nodePort: 32382
      nodePort: 30980
      nodePort: 30566
      nodePort: 30633
      nodePort: 32142
      nodePort: 31365
      nodePort: 31558
      nodePort: 31752
      nodePort: 32464
      nodePort: 30414
      nodePort: 32125
      nodePort: 32392
      nodePort: 32046
      nodePort: 31204
      nodePort: 32185
      nodePort: 30887
      nodePort: 30923
      nodePort: 32006
      nodePort: 30046
      nodePort: 32489
      nodePort: 31023
    - nodePort: 31015
    - nodePort: 31614
    - nodePort: 30938
    - nodePort: 30242
    - nodePort: 32282
    - nodePort: 30382
```

(note that *some* of these nodePort entries are for the 'challenge solvers' for the currently on-going/blocked renewal, and so they are *not* present in the `get-named-ports` output).

## Short term solutions/moving forward

The current certificate expires on December 19th (so in ~9 days). We need to resolve *both* of these issues to get a renewal now.

For (1), I propose we take the simplest approach of manually copying the `path` entries that cert-manager injects into the second Ingress resource. We will then manually remove them again afterwards. This will allow both the v4 and v6 front end IPs to respond to HTTP01 challenge requests.

For (2), we need to manually clean up some of these named ports. We have a list of all the `nodePort` allocations from `kubectl get svc -A` above, so we can write a script to calculate which ports are not actually used and set the full list appropriately for each of the instance groups that ingress-gce manages. If we make a mistake here or miss a port, I am *not sure* whether GCP will actually just reject because it'd break a load balancer, or if it'll make the associated service be unavailable until that port is added back.

## Longer term solutions

For (1), I see a few avenues:

a) cert-manager is modified to be able to update multiple Ingress resources to inject routes for solving. This is a little out of the ordinary, but isn't the _worst_ thing, especially given how many other awkward hoops we have to jump through to make HTTP01 solving work with that wide variety of ingress controller implementations.

b) write a controller that can be used by ingress-gce users to 'sync' the `path` entries on Ingress resources, treating one as authoritative. This would mean we could configure either the v4 or v6 Ingress to mirror the routes specified on the other one (that cert-manager updates). This feels cleaner than cert-manager updating multiple resources, but it'd be good to get feedback here

c) improve cert-manager's extensibility story to allow for "out of tree" HTTP01 solvers, which would in turn mean we could have a standalone 'ingress-gce-solver' which would understand ingress-gce's nuances. (this would also allow for e.g. an out of tree IngressRoute/VirtualService/Ingress v2 solver too). This is certainly something that the cert-manager project should do anyway, though may be a bit more involved as a resolution given the scope of the issue here.

d) not use IPv6, or use something like ingress-nginx running in-cluster (exposed with a TCP load balancer) to handle ingresses

For (2), we are likely to not be affected for a while again, but:

a) patching ingress-gce to allow it to clean up unused ports (may take a while to have this change in effect)

b) write automation to make it easy for *us* to clean up unused ports (after learning how to do this safely whilst resolving the issue we face today)

---

I'm going to mark this as `priority/critical-urgent` as we have a count-down timer on this before it becomes very visible/public 😅 - if people are available for a call today/over the coming days, we should try and move swiftly to get agreement on the short term solution so we can all go home for the holidays 🎅 🎄

/priority critical-urgent
/area cert-manager
/cc @thockin @dims @aojea @BenTheElder @bartsmykla

**Comment by ameukam** [comment]
@munnerz A possible short-term workaround for (2) : https://github.com/kubernetes/ingress-gce/issues/43#issue-264678302/

**Comment by munnerz** [comment]
Nice find 😄 here is a list of in-use ports after running `ports=$(gcloud compute backend-services list --global --format='value(port,port)' |  xargs printf 'port%s:%s,')`:

```
port30046:30046,port30062:30062,port30242:30242,port30382:30382,port30938:30938,port31015:31015,port31023:31023,port31614:31614,port32282:32282,port32489:32489,port32044:32044,port30923:30923,
```

I can go ahead and update the named ports for each instance group to this list. What is the best way to coordinate running a potentially risky command like this? :)

**Comment by bowei** [comment]
@spencerhance @rramkumar1

**Comment by cblecker** [comment]
@munnerz What services would be potentially impacted (documenting a list would be great)? That way we can determine risk and who we'd have to notify.

**Comment by cblecker** [comment]
awesome! thank you!

**Comment by dims** [comment]
Thanks a ton @munnerz @thockin

**Comment by thockin** [comment]
GCP folks are looking at (3) and then (2) longer term

**Comment by munnerz** [comment]
/assign

I'm going to work on 1(c) above today (controller to sync `rules` portion of Ingress resources). In the meantime, as we are nearing March 11th and this has not been resolved yet, I am applying the same workaround as in December to get us over the hump.

**Comment by munnerz** [comment]
Update - certificate has been renewed:

```
  status:
    conditions:
    - lastTransitionTime: "2020-03-06T11:15:52Z"
      message: Certificate is up to date and has not expired
      reason: Ready
      status: "True"
      type: Ready
    notAfter: "2021-05-31T10:22:27Z"
```

**Comment by DaveWelling** [comment]
It seems like the workaround for this is to move the orphaned ports to another region?  Is that right?  I'm guessing that means there is no way to directly remove the ports?  I cannot see any obvious method via the `gcloud compute instance-groups` cli.  Did anybody find a better solution?  I'm worried I will just have to jump from region to region.
Obviously, I'm also going to avoid recreating ingresses unnecessarily, but that also doesn't seem like  permanent solution when we are in heavy development and have frequent deployments.

**Comment by thockin** [comment]
Do we need this now?

**Comment by ameukam** [comment]
@thockin I don't think we need this again. I just don't want to close it until cert-manager is fully removed.

**Comment by Riaankl** [comment]
@ameukam should this be on the radar for 2023?

**Comment by BenTheElder** [comment]
Yes we should be removing cert-manager #4160

**Comment by ameukam** [comment]
Issue addressed and GKE Networking now offers `HTTP Route` and support dual-stack. 

/close
