### ISSUE TITLE
[Question] Road Map for the Kubernetes component Images under kubeimage DockerHub profile

### ISSUE THREAD

**Issue by chirangaalwis** [kubernetes/k8s.io#1502]
**Description:**
Is the [`kubeimage`](https://hub.docker.com/u/kubeimage) DockerHub profile officially maintained by the Kubernetes Community?

If so, what is the road map for maintaining images under this profile?

**Note:**
Encountered the details regarding the [vanity domain flip](https://github.com/kubernetes/k8s.io/blob/master/k8s.gcr.io/Vanity-Domain-Flip.md#the-solution) and the latest images maintained at a public [Google Container Registry](https://console.cloud.google.com/gcr/images/k8s-artifacts-prod/US).

IMO, having images in two different, public registries (i.e. [DockerHub](https://hub.docker.com/u/kubeimage) and [GCR](https://console.cloud.google.com/gcr/images/k8s-artifacts-prod/US)) seem to be somewhat confusing.

**Comment by spiffxp** [comment]
No, kubeimage is not part of the kubernetes project.  Not sure who owns or maintains that.

The source of truth for Kubernetes images is k8s.gcr.io.

Our DockerHub account is https://hub.docker.com/u/kubernetes, and the intent is for it to be explicitly empty (deleting the pause image keeps falling off my priority list, ref: https://github.com/kubernetes/k8s.io/issues/237#issuecomment-673586373)

/close
