### ISSUE TITLE
Update the cluster cert-manager

### ISSUE THREAD

**Issue by rikatz** [kubernetes/k8s.io#1508]
Cluster cert-manager needs to be updated. 

Per manifests, the installed version is v0.13 while the last version is v1.1

Some steps needs to be taken before updating (this playbook must be run somewhere else before submitting a PR to the repo to validate those steps)

* verify which gke version is running (and which kubectl version to be used) per cert-manager docs
* Update to the last v0.x (v0.16) before updating to v1.1
* Create the proper Roles and Role Bindings to newer API versions
* Update to v1.1 - can this be done with a new apply over new cert-manager manifest?
* Convert the manifests of cluster issuer to v1
* check if the remaining manifests needs to be converted in the repo

**Comment by ameukam** [comment]
Exploring the possibility to GKE ManagedCertificates : #1943

/remove-lifecycle stale
/milestone clear

**Comment by rikatz** [comment]
@ameukam @spiffxp I guess we can close this one as we are moving to Google Managed SSL Certs :)

I'll close (issue cleanup sunday here) but we can reopen if needed 

/close

**Comment by ameukam** [comment]
@rikatz Thank you so much for the time and effort. 🙇🏾‍♂️
