### ISSUE TITLE
pull-k8sio-cip should fail on manifest changes that mutate tags

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/k8s.io#1520]
https://github.com/kubernetes/k8s.io/pull/1509 should not have been allowed to merge

It did, and broke:
- the image promoter CI job: https://testgrid.k8s.io/wg-k8s-infra-k8sio#ci-k8sio-image-promo&width=20
- future instances of pull-k8sio-cip, eg: https://github.com/kubernetes/k8s.io/pull/1515 was blocked

pull-k8sio-cip appeared to skip, but not fail, attempted tag moves in dry-run mode: (ref: https://github.com/kubernetes/k8s.io/pull/1519#issuecomment-759031889)

FYI @kubernetes/release-engineering

**Comment by xmudrii** [comment]
Is this eventually relevant/related to https://github.com/kubernetes-sigs/k8s-container-image-promoter/issues/277?

**Comment by spiffxp** [comment]
/remove-lifecycle stale
FYI @listx if @tylerferrara is looking for other stuff to do

**Comment by spiffxp** [comment]
/assign @listx 
ref: https://github.com/kubernetes-sigs/k8s-container-image-promoter/issues/375

**Comment by spiffxp** [comment]
We hit this again with https://github.com/kubernetes/k8s.io/pull/2052 (subsequently reverted via https://github.com/kubernetes/k8s.io/pull/2421)

**Comment by listx** [comment]
I've begun work on this now.

**Comment by listx** [comment]
https://github.com/kubernetes-sigs/k8s-container-image-promoter/pull/385 has been merged, so this is fixed now. I just need to deploy it to the various Prow jobs that use the promoter.

**Comment by listx** [comment]
Waiting on https://github.com/kubernetes/test-infra/pull/23148 to get merged.

**Comment by listx** [comment]
This should be fixed now, but just for good measure let me try to perform a tag move in a fake promotion PR.

**Comment by spiffxp** [comment]
@listx have you verified this is fixed?

**Comment by listx** [comment]
> @listx have you verified this is fixed?

@justaugustus Have we deployed a new version of the promoter that includes the fix from https://github.com/kubernetes-sigs/k8s-container-image-promoter/pull/385 ?

**Comment by justaugustus** [comment]
> @listx have you verified this is fixed?

@listx -- This is still dependent on getting tests passing on the default dry-run PR: https://github.com/kubernetes-sigs/k8s-container-image-promoter/pull/285
If you can assist in debugging the test failures, we can try and push this along.

**Comment by spiffxp** [comment]
@justaugustus I see https://github.com/kubernetes-sigs/promo-tools/pull/285 has merged, are we running a version of the promoter that includes this fix now?

**Comment by justaugustus** [comment]
> @justaugustus I see [kubernetes-sigs/promo-tools#285](https://github.com/kubernetes-sigs/promo-tools/pull/285) has merged, are we running a version of the promoter that includes this fix now?

We do indeed! It was rolled out as part of https://github.com/kubernetes/test-infra/pull/23591 (and https://github.com/kubernetes/test-infra/pull/23593).
Testing here: https://github.com/kubernetes/k8s.io/pull/2738

/assign

**Comment by justaugustus** [comment]
From https://github.com/kubernetes/k8s.io/pull/2738#issuecomment-920472873:

> Confirmed failure on https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/k8s.io/2738/pull-k8sio-cip/1438291342051512320:
> 
> ```
> level=error msg="edge {{gcr.io/k8s-staging-artifact-promoter   true} {cip 20200222-v2.3.1-109-gb6af319} sha256:1e6fa1a97fcd3a3142aa51516552c16cfbeba58d16bd202365484d35def433d6 {us.gcr.io/k8s-artifacts-prod/artifact-promoter k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com  false} {cip 20200222-v2.3.1-109-gb6af319}}: tag 20200222-v2.3.1-109-gb6af319: ERROR: tag move detected from sha256:1e6fa1a97fcd3a3142aa51516552c16cfbeba58d16bd202365484d35def433d6 to sha256:1a36d74b30052783c986326f522e3b5688ea17c0cad851f9b1f265a67b67785b" 
> 
> <snip...>
> 
> level=error msg="edge {{gcr.io/k8s-staging-artifact-promoter   true} {cip 20200222-v2.3.1-109-gb6af319} sha256:1e6fa1a97fcd3a3142aa51516552c16cfbeba58d16bd202365484d35def433d6 {eu.gcr.io/k8s-artifacts-prod/artifact-promoter k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com  false} {cip 20200222-v2.3.1-109-gb6af319}}: tag 20200222-v2.3.1-109-gb6af319: ERROR: tag move detected from sha256:1e6fa1a97fcd3a3142aa51516552c16cfbeba58d16bd202365484d35def433d6 to sha256:5c9a73a90fdfd08adaf3d53ae863144922958911952dfa67cbf9a0d33dedde63" 
> ```

Thanks for the fix, @listx!

/close
