### ISSUE TITLE
Migrate away from google.com gcp project kubernetes-jenkins-pull

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/k8s.io#1526]
Part of umbrella issue to migrate away from google.com gcp projects: https://github.com/kubernetes/k8s.io/issues/1469

Umbrella issue for migrating or removing dependence on all of the kubernetes project infra that lives under kubernetes-jenkins-pull:
- gs://kubernetes-release-pull (or stop using this bucket entirely, ref: https://github.com/kubernetes/test-infra/issues/18789)
- pr-kubekins@kubernetes-jenkins-pull.iam.gserviceaccount.com service account
- kubernetes-jenkins-pull@appspot.gserviceaccount.com service account?
- compute instances?

/wg k8s-infra
/sig testing
/sig release
/area release-eng

**Comment by BenTheElder** [comment]
This project also had a number of defunct GCS buckets that I'm deleting, aside from `kubernetes-release-pull` which still needs a plan.

**Comment by BenTheElder** [comment]
The bucket is deleted. That leaves the service accounts, which I hope we'll phase out as part of migrating the control plane next week?

**Comment by BenTheElder** [comment]
Yes
