### ISSUE TITLE
[Umbrella Issue] Setup a GCS Bucket for projects to use

### ISSUE THREAD

**Issue by dims** [kubernetes/k8s.io#153]
Please see
- https://docs.google.com/document/d/1cQUAU3AeRahL8Y4R6BDiMiMV44ESPDFNyZQIlgSA5eQ/edit#heading=h.oa3xwm42jn26
- https://github.com/kubernetes/community/pull/2695

**Comment by dims** [comment]
cc @thockin @mkumatag  @javier-b-perez @listx

**Comment by javier-b-perez** [comment]
Added some comments in the doc, LGTM

**Comment by dims** [comment]
cc @mkumatag @thockin

**Comment by dims** [comment]
- Separate out GCS buckets for say kops binaries.
- Need separate GCR as well for images

**Comment by dims** [comment]
Let's use this for GCS buckets. will create another issue for GCR container images repo

**Comment by ixdy** [comment]
I think @spiffxp meant to 
/assign @thockin @dims
here

**Comment by BenTheElder** [comment]
cc

**Comment by spiffxp** [comment]
/remove-lifecycle stale
Its not clear to me that breaking out issues for GCS, GCR, etc. really maps well to the work that is ongoing.  Will revisit this

**Comment by spiffxp** [comment]
Via the scripts: anyone who creates a "staging repo" gets both a GCS bucket and GCR repo now

**Comment by spiffxp** [comment]
/close
we have a set of scripts that work well for staging repos, everything else is ad-hoc (eg: release team asked for one and it was handled ad-hoc)

no individual access (other than via group)
