### ISSUE TITLE
Update k8s-infra prow build clusters from v1.16 to release channels

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/k8s.io#1541]
Upgrading cluster versions is currently done at a time of our choosing, but we've let our clusters fall out of supported versions.  Using GKE release channels means cluster version will get upgraded as versions fall out of support.  

For more info on channels/schedule, see https://cloud.google.com/kubernetes-engine/docs/concepts/release-channels#channels

We're now on v1.16.  If we move to release channels, we may bump versions again
- stable: 1.16
- regular: 1.17
- rapid: 1.18

Due to lack of skip-level upgrades, if we want to move to rapid, we'll have to move to regular first.

Hopefully terraform supports doing this in-place.

**Comment by ameukam** [comment]
#1402 give the possibility to change the release channel in the terraform gke module `gke-cluster`. Once the change is applied, Terraform will register the cluster to the release channel defined.

**Comment by spiffxp** [comment]
https://github.com/kubernetes/k8s.io/pull/1402 - added release channel support to modules
https://github.com/kubernetes/k8s.io/pull/1631 - enroll clusters in stable channel

Just applied the changes https://github.com/kubernetes/k8s.io/pull/1631#issuecomment-777219336

**Comment by spiffxp** [comment]
So it looks like we'll be upgrading to 1.17.15-gke.800 sometime over the next few days https://cloud.google.com/kubernetes-engine/docs/release-notes#february_9_2021_2021-r5

**Comment by spiffxp** [comment]
We still remain at v1.16
```
$ for s in build build-trusted; do gcloud container clusters list --project=k8s-infra-prow-$s; done
NAME        LOCATION     MASTER_VERSION    MASTER_IP      MACHINE_TYPE    NODE_VERSION      NUM_NODES  STATUS
prow-build  us-central1  1.16.15-gke.6000  34.69.231.159  n1-standard-32  1.16.15-gke.6000  106        RUNNING
NAME                LOCATION     MASTER_VERSION    MASTER_IP    MACHINE_TYPE   NODE_VERSION      NUM_NODES  STATUS
prow-build-trusted  us-central1  1.16.15-gke.6000  34.66.53.94  n1-standard-8  1.16.15-gke.6000  3          RUNNING
```

**Comment by spiffxp** [comment]
Going to force an upgrade to v1.17, we've added node local dns, and that requires node recreation to take effect.  Since upgrading to v1.17 requires the same, let's batch the changes before updating node pools.

To be safe, I did _not_ batch for k8s-infra-prow-trusted, node-local dns change is here: https://github.com/kubernetes/k8s.io/pull/1680.  Will start with upgrading this cluster + nodes to v1.17

I will be batching for k8s-infra-prow-build, node-local dns change is here: https://github.com/kubernetes/k8s.io/pull/1686.  After trusted cluster, will upgrade this cluster to 1.17.  Then nodes.

**Comment by spiffxp** [comment]
Both `k8s-infra-prow-build` and `k8s-infra-prow-build-trusted` control planes are now at `v1.17.15`
```
START_TIME                      END_TIME                        TYPE            NAME                              STATUS  TARGET
2021-02-19T19:00:57.59724087Z   2021-02-19T19:38:31.006471249Z  UPGRADE_MASTER  operation-1613761257597-c6cb69f5  DONE    prow-build-trusted
2021-02-19T19:15:24.751520239Z  2021-02-19T19:40:21.455113807Z  UPGRADE_MASTER  operation-1613762124751-ed77e6e2  DONE    prow-build
```
Done via
```
gcloud container clusters upgrade --async --project=k8s-infra-prow-build-trusted --region=us-central1 prow-build-trusted --cluster-version=1.17.15-gke.800 --master
gcloud container clusters upgrade --async --project=k8s-infra-prow-build --region=us-central1 prow-build --cluster-version=1.17.15-gke.800 --master
```

**Comment by spiffxp** [comment]
Upgrading `k8s-infra-prow-build-trusted` node pool, and `k8s-infra-prow-build` greenhouse node pool
```
gcloud container clusters upgrade --project=k8s-infra-prow-build-trusted --region=us-central1 prow-build-trusted --node-pool=trusted-pool1-20200430235251092500000001 --cluster-version=1.17.15-gke.800 --async
gcloud container clusters upgrade --project=k8s-infra-prow-build --region=us-central1 prow-build --node-pool=greenhouse-20200518173345958100000001 --cluster-version=1.17.15-gke.800 --async
```

**Comment by spiffxp** [comment]
`k8s-infra-prow-build-trusted` nodes  and `k8s-infra-prow-build` greenhouse nodes are now at `v1.17.15`
```
START_TIME                      END_TIME                        TYPE            NAME                              STATUS  TARGET
2021-02-19T20:17:07.97637054Z   2021-02-19T20:31:35.308929386Z  UPGRADE_NODES   operation-1613765827976-6180ca23  DONE    greenhouse-20200518173345958100000001
2021-02-19T20:15:11.565741936Z  2021-02-19T20:30:16.2910463Z    UPGRADE_NODES   operation-1613765711565-9d660269  DONE    trusted-pool1-20200430235251092500000001
```

**Comment by spiffxp** [comment]
Upgrading `k8s-infra-prow-build` main node pool
```
gcloud container clusters upgrade --project=k8s-infra-prow-build --region=us-central1 prow-build --node-pool=pool4-20200828175901156000000001 --cluster-version=1.17.15-gke.800 --async
```

**Comment by spiffxp** [comment]
`k8s-infra-prow-build` node pool upgraded successfully
```
START_TIME                      END_TIME                        TYPE            NAME                              STATUS  TARGET
2021-02-19T21:06:44.363477969Z  2021-02-20T01:33:36.657559348Z  UPGRADE_NODES   operation-1613768804363-e36aa207  DONE    pool4-20200828175901156000000001
2021-02-21T11:07:07.408007405Z  2021-02-21T11:31:54.803856606Z  UPDATE_CLUSTER  operation-1613905627408-4fb00f88  DONE    prow-build
```

**Comment by spiffxp** [comment]
So here's where we now stand.  We're in STABLE.  I saw REGULAR had 1.17 and 1.18 last week, but no more.
```yaml
# $ gcloud container get-server-config --format='yaml(channels)' --project=k8s-infra-prow-build
channels:
- channel: RAPID
  defaultVersion: 1.19.7-gke.1302
  validVersions:
  - 1.19.7-gke.1500
  - 1.19.7-gke.1302
- channel: REGULAR
  defaultVersion: 1.18.12-gke.1210
  validVersions:
  - 1.18.12-gke.1210
  - 1.18.12-gke.1206
- channel: STABLE
  defaultVersion: 1.17.15-gke.800
  validVersions:
  - 1.17.15-gke.800
  - 1.16.15-gke.7800
  - 1.15.12-gke.6002
```

IMO we either close this as-is and followup with move to REGULAR, or decide we want moving to REGULAR be the exit criteria for this.

**Comment by spiffxp** [comment]
Reasons to move to v1.18:
- v1.17 has left its upstream support window
- https://github.com/kubernetes/k8s.io/issues/1187#issuecomment-763762981 - gke added support for local-ssd node pools

**Comment by spiffxp** [comment]
https://github.com/kubernetes/k8s.io/pull/1721 - upgraded k8s-infra-prow-build-trusted to regular channel and then initiated an upgrade
```
START_TIME                      END_TIME                        TYPE            NAME                              STATUS
2021-02-25T03:03:19.944933211Z  2021-02-25T03:03:20.182820122Z  UPDATE_CLUSTER  operation-1614222199944-39e46c5e  DONE
2021-02-25T03:03:30.274238748Z  2021-02-25T03:03:30.492961302Z  UPGRADE_MASTER  operation-1614222210274-d6330ac9  DONE
2021-02-25T03:07:29.935682765Z  2021-02-25T03:32:30.453088739Z  UPGRADE_MASTER  operation-1614222449935-6283e4aa  DONE
2021-02-25T04:10:32.66787437Z   2021-02-25T04:23:56.808001318Z  UPGRADE_NODES   operation-1614226232667-36817155  DONE
```

**Comment by spiffxp** [comment]
Upgrading `k8s-infra-prow-build` control plane
```
gcloud container clusters upgrade   --project=k8s-infra-prow-build   --region=us-central1   prow-build   --master   --async
```

**Comment by spiffxp** [comment]
https://github.com/kubernetes/k8s.io/pull/1723 - moved k8s-infra-prow-build to regular channel

Initiating upgrade of control plane
```
$ gcloud container clusters upgrade   --project=k8s-infra-prow-build   --region=us-central1   prow-build   --master   --async
```

**Comment by spiffxp** [comment]
k8s-infra-prow-build control plane has been upgraded to v1.18
```
START_TIME                      END_TIME                        TYPE            NAME                              STATUS
2021-02-25T21:04:08.850463077Z  2021-02-25T21:04:09.18301018Z   UPDATE_CLUSTER  operation-1614287048850-50f48605  DONE
2021-02-25T21:05:57.988208925Z  2021-02-25T21:05:58.184285011Z  UPDATE_CLUSTER  operation-1614287157988-6099ea19  DONE
```
```
NAME        LOCATION     MASTER_VERSION    MASTER_IP      MACHINE_TYPE    NODE_VERSION       NUM_NODES  STATUS
prow-build  us-central1  1.18.12-gke.1210  34.69.231.159  n1-standard-32  1.17.15-gke.800 *  87         RUNNING
```
Initiating upgrade of greenhouse node pool
```
gcloud container clusters upgrade --project=k8s-infra-prow-build --region=us-central1 prow-build --node-pool=greenhouse-20200518173345958100000001 --async
```

**Comment by spiffxp** [comment]
Initiating upgrade of k8s-infra-prow-build's main node pool
```
gcloud container clusters upgrade --project=k8s-infra-prow-build --region=us-central1 prow-build --node-pool=pool4-20200828175901156000000001 --async
```

**Comment by spiffxp** [comment]
/close
I'm going to call use done here.  Both k8s-infra prow build clusters and all of their node pools are at `v1.18.12`

Both clusters are now in the REGULAR channel, so they should continue to get regularly bumped,

https://cloud.google.com/kubernetes-engine/docs/release-notes-regular shows roughly what the cadence looks like.
