### ISSUE TITLE
cloudbuild job failed to access k8s-artifacts-csi

### ISSUE THREAD

**Issue by jingxu97** [kubernetes/k8s.io#1544]
I have a clouldbuild job https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/post-csi-proxy-push-images/1305641389169577989 failed due to permission.

ResumableUploadAbortException: 403 272675062337@cloudbuild.gserviceaccount.com does not have storage.objects.create access to k8s-artifacts-csi/csi-proxy/dev/csi-proxy-master.exe.
CommandException: 1 file/object could not be transferred.
ERROR
ERROR: could not upload bin/csi-proxy-master.exe to gs://k8s-artifacts-csi/csi-proxy/dev/; err = gsutil exited with non-zero status: 1

The cloudbuild file in csi-proxy is here https://github.com/kubernetes-csi/csi-proxy/blob/master/cloudbuild.yaml

**Comment by ameukam** [comment]
The priority may have shifted over time. 

/remove-priority critical-urgent
/priority backlog

Feel free to revert if emergency is still relevant

**Comment by spiffxp** [comment]
/milestone v1.23
Need to re-examine what should be allowed to push to what.  This is attempting to push directly to a "prod" bucket, when ideally we should be doing a staging->promote->prod process

**Comment by ameukam** [comment]
@jingxu97 Do you encounter the same issue ? I see the job have been successful for some time now: https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/post-csi-proxy-push-images. 

Also the binaries are pushed: 

```shell
gsutil stat gs://k8s-staging-sig-storage/csi-proxy/master/csi-proxy.exe
gs://k8s-staging-sig-storage/csi-proxy/master/csi-proxy.exe:
    Creation time:          Thu, 17 Feb 2022 04:14:35 GMT
    Update time:            Thu, 17 Feb 2022 04:14:35 GMT
    Storage class:          STANDARD
    Content-Length:         14402560
    Content-Type:           application/x-msdos-program
    Hash (crc32c):          1C2e9Q==
    Hash (md5):             J9wj1haFHDsRux34YghDfA==
    ETag:                   CKfJg4jwhfYCEAE=
    Generation:             1645071275451559
    Metageneration:         1
```

**Comment by ameukam** [comment]
No report for the original author. Let's close this. Please reopen with more details if the issue still exists

/close
