### ISSUE TITLE
[Umbrella Issue] Setup Billing/Reporting for all k8s-infra assets

### ISSUE THREAD

**Issue by dims** [kubernetes/k8s.io#156]
We are starting with a GKE cluster for a few jobs. Once that is setup, we will need to make sure we account for the $'s spent with appropriate billing and make sure we have enough reports going back to Google / CNCF.

/assign @idvoretskyi

**Comment by idvoretskyi** [comment]
I made brief research and figured out that the most efficient way for us to have the historical billing usage data is BigQuery export (https://cloud.google.com/billing/docs/how-to/export-data-bigquery); it also allows us to visualize the data with Data Studio - https://cloud.google.com/billing/docs/how-to/visualize-data.

An alternative method is exporting to CSV/JSON file, which is easier, but less-feature-rich (https://cloud.google.com/billing/docs/how-to/export-data-file).

PS. BigQuery export requires a specific `bigquery.datasets.create` permission on GCP.

**Comment by idvoretskyi** [comment]
cc @hh who is going to work on the Bigquery + DataStudio utilization.

**Comment by hh** [comment]
Brought #193 under this umbrella so we know where our storage costs are going.

Thank you @justinsb for bringing this up! (and for keeps kops infra up until the transition) :100: :1st_place_medal:

**Comment by hh** [comment]
Tracking implementation of per-namespace billing at https://github.com/kubernetes/k8s.io/issues/194

**Comment by spiffxp** [comment]
My ideal outcome for this:
- at the start of each wg-k8s-infra meeting we can look at generated reports
- for cluster-based infra, we can see per-namespace billing info (#194)... ie: if we added the "gcsweb" service, would we know how much extra that is costing us
- for artifact storage, we can see how much a given subproject / sig is costing us (#193)
- for non-cluster based infra, we can see per-project billing info... ie: how much is dns costing us, how much is bigquery costing us, etc.

**Comment by spiffxp** [comment]
In the most recent wg-k8s-infra meeting, Tim was able to read out "the default GCP billing report."  This allowed him to break down costs over the past two weeks as follows:
- vm (compute, ram, ssd pv)
- dns (queries)
- load balancing
- dns-zone
- inter-zone egress
- (no storage bills as of yet)

Data is in BigQuery, ready to be analyzed in Data Studio.  Need to produce a dashboard to see what we want, or understand what is possible, and figure out what questions we want to answer

**Comment by spiffxp** [comment]
- Want parity of number between tim's readout and justin's readout
- Answer on billing-per-bucket
- Find more info on billing-per-namespace
- Possibly send daily reports to google group

**Comment by spiffxp** [comment]
Justin is getting a daily e-mail, will send to cluster admins google group, still have questions about parity

**Comment by spiffxp** [comment]
Justin to look at sharing Data Studio report with other users, possibly use another group as defined in groups.yaml

TBD whether we can export / import Data Studio reports to use some kind of gitops driven model

**Comment by spiffxp** [comment]
/assign @justinsb 
Now sending billing report out to a google group, still not sure how to allow others to edit the report

**Comment by spiffxp** [comment]
Would like to continue to cross check this billing report against tim's billing report

**Comment by spiffxp** [comment]
Send report weekly to public google group https://groups.google.com/forum/#!forum/kubernetes-wg-k8s-infra

Send report daily to existing google group of k8s-infra-gcp-accounting

**Comment by spiffxp** [comment]
Backing up / sharing the work:
- lets open up the Data Studio project to the k8s-infra-gcp-account group
- may want to consider dumping sql query out, or finding a way to make the data studio report public read-only, etc.

**Comment by spiffxp** [comment]
@thockin unable to see report since july 1st

**Comment by spiffxp** [comment]
Latest report august 5th: https://groups.google.com/d/msg/kubernetes-wg-k8s-infra/uW7dEBaBWDY/-zXJc0QEBQAJ

**Comment by spiffxp** [comment]
would like to share edit access of the report to a group... k8s-infra-gcp-accounting can already edit it

would like some kind of README in an accounting directory

nice to have: other people provide other data studio addons

**Comment by spiffxp** [comment]
will continue to spot check as a recurring agenda item but we are ready to call this done

**Comment by thockin** [comment]
@justinsb update on this?

**Comment by thockin** [comment]
This is done.  The billing report should be accessible to anyone in the k8s-infra group.  To make it truly world-readable we'd need to recreate it on a non google-com email.  Maybe a kubernetes.io gsuite account for publish docs like this?  Will open an issue
