### ISSUE TITLE
Upgrade cluster terraform files to be compatible with terraform >= 0.13

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/k8s.io#1572]
Part of issue to upgrade the version of terraform used by our modules: https://github.com/kubernetes/k8s.io/issues/2020

Currently our terraform files require some version of terraform 0.12
```
$ ag required_version
projects/k8s-infra-prow-build-trusted/prow-build-trusted/00-provider.tf
9:  required_version = "~> 0.12.20"

projects/kubernetes-public/aaa/00-inputs.tf
10:  required_version = ">= 0.12.8"

_example/test-us/00-inputs.tf
10:  required_version = ">= 0.12.8"

projects/k8s-infra-prow-build/prow-build/00-provider.tf
9:  required_version = "~> 0.12.20"

_example/test-eu/00-inputs.tf
10:  required_version = ">= 0.12.8"

modules/gke-nodepool/versions.tf
18:  required_version = "~> 0.12.20"

modules/gke-project/versions.tf
18:  required_version = "~> 0.12.20"

modules/gke-cluster/versions.tf
18:  required_version = "~> 0.12.20"
```

We should upgrade, ideally to 0.14.  If it's too much effort, we should try for at least 0.13. Relevant guides:
- https://www.terraform.io/upgrade-guides/0-13.html
- https://www.terraform.io/upgrade-guides/0-14.html

The aaa cluster still uses the google 2.x terraform providers, we may need to upgrade to 3.x as part of this (ref: https://github.com/kubernetes/k8s.io/issues/1403)

/wg k8s-infra
/area cluster-mgmt
/sig testing
since this is how prow clusters are managed
/sig release
/sig contributor-experience
since these sigs have apps on the aaa cluster
/milestone v1.21
/priority important-longterm

/assign @ameukam @spiffxp 
I'm assigning us since we've been doing the most work with our existing terraform lately
/assign @justinsb 
Assigning as FYI since this is one of the things precluding your PR from merging (ref: https://github.com/kubernetes/k8s.io/pull/1016#pullrequestreview-566665404)

**Comment by ameukam** [comment]
Build clusters have been upgraded to Terraform 0.13 : https://github.com/kubernetes/k8s.io/pull/1693

**Comment by ameukam** [comment]
Next step will be :
- upgrade aaa to 0.13 and 0.14
- upgrade the build clusters to 0.14 

/milestone v1.22

**Comment by ameukam** [comment]
All the clusters use now `0.14`

```shell
grep 'required_version'
./tmp.bbGJik: Permission denied (os error 13)
infra/gcp/terraform/projects/kubernetes-public/registry.k8s.io/versions.tf
2:  required_version = ">= 0.14"

infra/gcp/clusters/projects/k8s-infra-public-pii/versions.tf
7:  required_version = "~> 0.14.0"

infra/gcp/clusters/projects/k8s-infra-ii-sandbox/versions.tf
7:  required_version = "~> 0.13"

infra/gcp/clusters/projects/kubernetes-public/aaa-tf-v3/versions.tf
2:  required_version = "~> 0.12"

infra/gcp/clusters/projects/k8s-infra-prow-build-trusted/prow-build-trusted/versions.tf
7:  required_version = "~> 0.14.0"

infra/gcp/clusters/modules/gke-project/versions.tf
18:  required_version = "~> 0.14.0"

infra/gcp/clusters/projects/kubernetes-public/aaa/00-inputs.tf
10:  required_version = "~> 0.14.0"

infra/gcp/clusters/modules/gke-nodepool/versions.tf
18:  required_version = "~> 0.14.0"

infra/gcp/clusters/projects/k8s-infra-prow-build/prow-build/versions.tf
7:  required_version = "~> 0.14.0"

infra/gcp/clusters/modules/gke-cluster/versions.tf
18:  required_version = "~> 0.14.0"
```

Done via #2019
