### ISSUE TITLE
Donate Azure subscription to CNCF

### ISSUE THREAD

**Issue by chewong** [kubernetes/k8s.io#1637]
We have an Azure subscription dedicated to testing for various Kubernetes-related projects. It's been running well until we have to rotate [this specific secret](https://github.com/kubernetes/test-infra/blob/master/config/prow/config.yaml#L702-L705), which includes sharing with the test-infra on-call folks our credential (i.e. username, password, subscription ID, storage account key, etc all in plain text) used to authenticate test instances to create Kubernetes clusters on our Azure subscription. It's definitely not ideal and we would like to eliminate this process. 

After having a [conversation on Slack](https://kubernetes.slack.com/archives/C09QZ4DQB/p1612909014117600), it seems that the first step would be donating our Azure subscription/resources to the CNCF, which we would like to get some help with.

Our goals:
- Manage and rotate secrets by core maintainers instead of sharing them in plain text with test-infra on-call folks
- Schedule all Azure-related ProwJobs to an Azure cluster instead of a GKE cluster via the [`cluster`](https://github.com/kubernetes/test-infra/blob/master/prow/getting_started_deploy.md#run-test-pods-in-different-clusters) field in prow job config to reduce the chance of secrets being leaked
- Allow the Kubernetes community to run tests on Azure infrastructure

Here is a list of projects that use the Azure subscription, and their core maintainers:

| Project | Maintainers |
| - | - |
| https://github.com/kubernetes/kubernetes | @feiskyer, @andyzhangx, @nilo19 |
| https://github.com/kubernetes-sigs/cloud-provider-azure | @feiskyer, @nilo19 |
| https://github.com/kubernetes-sigs/azuredisk-csi-driver | @andyzhangx |
| https://github.com/kubernetes-sigs/azurefile-csi-driver | @andyzhangx |
| https://github.com/kubernetes-sigs/blob-csi-driver | @andyzhangx |
| https://github.com/kubernetes-sigs/secrets-store-csi-driver | @aramase, @ritazh |
| https://github.com/kubernetes-csi/csi-driver-smb | @andyzhangx |
| https://github.com/kubernetes-csi/csi-driver-nfs | @andyzhangx | 
| https://github.com/kubernetes-sigs/cluster-api-provider-azure | @CecileRobertMichon, @devigned |
| https://github.com/kubernetes-sigs/image-builder | @CecileRobertMichon |
| [sig-windows testing](https://testgrid.k8s.io/sig-windows-releases) | @chewong, @marosset, @jsturtevant |
| [dualstack and IPv6 testing](https://testgrid.k8s.io/provider-azure-dualstack) | @aramase |

Thanks!

/cc @dims

**Comment by justaugustus** [comment]
cc: @kubernetes/k8s-infra-team @caniszczyk 

FYI @kubernetes/release-engineering

**Comment by dims** [comment]
@caniszczyk @idvoretskyi - will this fit into the new program around cloud credits at CNCF?

**Comment by idvoretskyi** [comment]
@dims can we kick-off the email thread please (with me and @caniszczyk)?

**Comment by hh** [comment]
Might be useful to bring me into the thread as well.

I’ve been working on both the Cloud Credits program and some earlier
conversations with Microsoft.

**Comment by hh** [comment]
Looping in Lachie.

/cc @lachie83
