### ISSUE TITLE
Remove scripts related to k8s-artifacts-prod-vuln-dashboard

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/k8s.io#1642]
This bucket has been manually removed, but we're in a state where if someone re-runs `infra/gcp` scripts, it will get re-provisioned.  Please open a PR to remove from the scripts

/milestone v1.21
/priority critical-urgent
We're blocked from running scripts to roll out any further changes until this is done
/wg k8s-infra
/sig release
/area release-eng
/assign @justaugustus 
or please find a @kubernetes/release-engineering member capable of making the PR

**Comment by spiffxp** [comment]
/assign @dims @thockin
FYI, please hold off on merging PRs that touch scripts infra/gcp until this is addressed

**Comment by dims** [comment]
@spiffxp ACK!

**Comment by spiffxp** [comment]
/unassign @dims @thockin @justaugustus
/assign @hasheddan @spiffxp 
We're unblocked, see https://github.com/kubernetes/k8s.io/pull/1643 for manual changes made

**Comment by cpanato** [comment]
I'm confused, we have this job: https://github.com/cpanato/test-infra/blob/master/config/jobs/kubernetes/wg-k8s-infra/trusted/releng/releng-trusted.yaml#L93

that uses the service account, should we create a new one? or how we proceed?

@spiffxp @hasheddan @dims @justaugustus

**Comment by justaugustus** [comment]
@cpanato -- Please see the discussion here: https://kubernetes.slack.com/archives/GKEA5EL67/p1613162193026700?thread_ts=1613162193.026700&cid=GKEA5EL67
