### ISSUE TITLE
renaming k8s-infra-team to wg-k8s-infra

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/k8s.io#166]
Now that our charter has landed (ref: https://github.com/kubernetes/community/pull/2830), and we're still in early days, let's rename assets from k8s-infra-team to wg-k8s-infra:

**slack channel**
- #k8s-infra-team - > wg-k8s-infra

This is a transparent rename, need to ask #slack-admins

**public google group**
- https://groups.google.com/forum/#!newtopic/k8s-infra-team -> wg-k8s-infra

This is a hard break, suggest e-mailing list to let them know of the move, and then doing the move.

**k/community docs**

update references in here once the slack channel and public google group is renamed

**admin groups**
- k8s-infra-cluster-admins@googlegroups.com -> wg-k8s-infra-cluster-admins@googlegroups.com
- k8s-infra-dns-admins@googlegroups.com -> wg-k8s-infra-cluster-admins@googlegroups.com

>@thockin we only have a few references in the extant GCP project.  If you create new google groups for k8s-infra-cluster-admins@googlegroups.com and k8s-infra-dns-admins@googlegroups.com I can replicate the config then remove the old groups.  We have some docs to update too in DNS

Honestly I'm torn on this, part of me says do it so everything is the same. Part of me says k8s-infra is good enough since there are questions of whether this stays as a wg or may one day become a sig (or a committee, or who knows)

/assign @spiffxp
I'm willing to take on all but admin groups

/assign @dims @thockin 
WDYT about the admin groups?

/wg k8s-infra
/kind cleanup

**Comment by cblecker** [comment]
I'd like to consider if we're moving anyways, to use our gsuite instead of public google groups. The auditing of permissions, the administrator recovery, etc are way stronger there as opposed to the public groups (especially with these really high level trusted permissions).

**Comment by dims** [comment]
@cblecker i am cool with waiting for/using the gsuite. 
@spiffxp looks good other than that!

**Comment by cblecker** [comment]
It's my understanding that *groups* don't cost anything, so we'd just need to request of one of the steering committee admin account holders to set up the groups themselves for us.

**Comment by spiffxp** [comment]
I'm fine with the idea of holding on our groups for ACLs etc, to see if gsuite makes more sense

But I would still like to rename our public discussion group / mailing list

**Comment by thockin** [comment]
In general, the feeling was NOT to use the gsuite account very much.  Because this will be potentially a lot of small groups, in particular.  But I don't hold those keys any more.  If steering wants to use gsuite ggroups for this, I am fine.

If we stay with public ggroups, I think we should leave the admin groups (which means the GCP project needs no changes).

If we move to gsuite, I will need new admin groups created and give me owner on them.  Then I can set it up in GCP

**Comment by cblecker** [comment]
The problem is I don't want to lose access or control over any of the google groups that give infrastructure control. I would like to see those extremely tightly held.

**Comment by thockin** [comment]
Christoph, are you arguing FOR or AGAINST gsuite? :)

**Comment by cblecker** [comment]
FOR :)

Sure, we'd need to bug one of the admins for new groups being created, but we have way better control/visibility/auditing too.

**Comment by bartsmykla** [comment]
Hi guys. I've found one more place where where was an old url to the wg google group, and created a PR: https://github.com/kubernetes/community/pull/3334

I'm in the process of adding my email to the list of CNCF's approved CLA, but after that is there anything else I can help here with? :-)

**Comment by dims** [comment]
that should be it.

/close
