### ISSUE TITLE
audit follow: some boskos-scale projects have lower quotas

### ISSUE THREAD

**Issue by thockin** [kubernetes/k8s.io#1660]
k8s-infra-e2e-boskos-scale-01 thru 05 have lower quotas than all the rest.

Sample:
```
@@ -26,99 +26,99 @@
   "name": "k8s-infra-e2e-boskos-scale-NN",
   "quotas": [
     {
-      "limit": 10000,
+      "limit": 5000,
       "metric": "SNAPSHOTS"
     },
     {
-      "limit": 30,
+      "limit": 15,
       "metric": "NETWORKS"
     },
     {
-      "limit": 500,
+      "limit": 200,
       "metric": "FIREWALLS"
     },
     {
-      "limit": 5000,
+      "limit": 2000,
       "metric": "IMAGES"
     },
     {
-      "limit": 175,
+      "limit": 21,
       "metric": "STATIC_ADDRESSES"
     },
     {
-      "limit": 300,
+      "limit": 250,
       "metric": "ROUTES"
     },
```

**Comment by spiffxp** [comment]
quota changes were due to what the org defaults were at when the project was created

this isn't going to be fun to reconcile unless we can somehow script quota changes (I have always had to manually fill out requests on GCP console)

**Comment by thockin** [comment]
It may be OK - it just came out as a delta in my quick comparisons.  Maybe
no action needed

**Comment by spiffxp** [comment]
/retitle audit follow: some boskos-scale projects have lower quotas

**Comment by spiffxp** [comment]
/priority backlog
I'm going to push down priority and keep out of current milestone until it's clear there's an issue, but it would be good to reconcile this eventually

**Comment by spiffxp** [comment]
/remove-lifecycle stale
/assign
I don't plan on reconciling this. But I feel like it should be documented as a known issue or quirk somewhere instead of an issue that will age out.

I'm taking a pass at prow related docs so I'll take care of this along the way
