### ISSUE TITLE
audit followup: inconsistent role bindings for k8s-infra-prow-viewers on e2e projects

### ISSUE THREAD

**Issue by thockin** [kubernetes/k8s.io#1661]
k8s-infra-e2e-boskos-scale-06 thru 30 do not have the following IAM binding (or maybe the issue is that 01-05 do have it)

```
    {
      "members": [
        "group:k8s-infra-prow-viewers@kubernetes.io"
      ],
      "role": "roles/viewer"
    }
```

**Comment by spiffxp** [comment]
/sig testing
/area prow
/priority important-soon
/milestone v1.21
/assign
this requires a re-run of `infra/gcp/prow/ensure-e2e-projects.sh`

**Comment by spiffxp** [comment]
/retitle audit followup: some boskos-scale projects missing IAM

**Comment by spiffxp** [comment]
https://github.com/kubernetes/k8s.io/pull/1061 switched from using `role/viewer` to the custom role `prow.viewer`, so have `role/viewer` is the detritus that should be cleaned up

**Comment by spiffxp** [comment]
Confirmed consistent in https://github.com/kubernetes/k8s.io/pull/1748

Removing old role cleanup code in https://github.com/kubernetes/k8s.io/pull/1737

Then can call this done

**Comment by spiffxp** [comment]
/close
Per the comment above, this is done.  Think I was waiting for #1737 to merge.
