### ISSUE TITLE
k8s-infra-e2e-scale-project has unmanaged bucket

### ISSUE THREAD

**Issue by thockin** [kubernetes/k8s.io#1664]
gs://kubernetes-staging-8cf5cbdf30/ exists with no auto-removal.  Last changed May of 2020 - maybe we can just remove this bucket entirely?

@wojtek-t

**Comment by wojtek-t** [comment]
I'm not aware of it being used for anything, but I will ask around.

**Comment by wojtek-t** [comment]
It seems people around are not aware of it too. So I think we can probably remove it.

**Comment by jkaniuk** [comment]
+1, let's remove it

**Comment by thockin** [comment]
I will nuke it

**Comment by spiffxp** [comment]
/assign @thockin 
FWIW these `kubernetes-staging` buckets are expected detritus from kube-up: https://github.com/kubernetes/k8s.io/pull/1710/files#r582417235

The bucket's last updated date doesn't change if objects inside are updated more recently (e.g. https://github.com/kubernetes/k8s.io/pull/1714#discussion_r582436252)

I don't think they're worth our attention from a cost perspective.

They are noise though:
- kube-up will recreate these buckets if they don't exist
- kube-up doesn't remove these on teardown
- boskos doesn't clean GCS buckets (solely uses `gcloud`) https://github.com/kubernetes-sigs/boskos/blob/master/cmd/janitor/gcp_janitor.py#L32

**Comment by thockin** [comment]
Will these buckets accumulate files and grow to unbounded size?    Should we pre-create them and add deletion policies?

**Comment by spiffxp** [comment]
> Will these buckets accumulate files and grow to unbounded size?    Should we pre-create them and add deletion policies?

SGTM will open issue for followup
