### ISSUE TITLE
audit followup: some k8s-staging-* projects have differing IAM

### ISSUE THREAD

**Issue by thockin** [kubernetes/k8s.io#1665]
Example:

```
k8s-staging-addon-manager
--- /dev/fd/63  2021-02-16 16:28:00.085969274 -0800
+++ /dev/fd/62  2021-02-16 16:28:00.089969238 -0800
@@ -177,19 +177,19 @@
     },
     {
       "members": [
-        "serviceAccount:service-NNN@gcp-sa-containerscanning.iam.gserviceaccount.com"
+        "serviceAccount:service-NNN@containerregistry.iam.gserviceaccount.com"
       ],
-      "role": "roles/containerscanning.ServiceAgent"
+      "role": "roles/containerregistry.ServiceAgent"
     },
     {
       "members": [
-        "serviceAccount:service-NNN@containerregistry.iam.gserviceaccount.com"
+        "serviceAccount:service-NNN@gcp-sa-containerscanning.iam.gserviceaccount.com"
       ],
-      "role": "roles/editor"
+      "role": "roles/containerscanning.ServiceAgent"
     },
```

**Comment by spiffxp** [comment]
/sig release
/area release-eng
/priority important-soon
/milestone v1.21
this may be reconcilable via a full run of `infra/gcp/ensure-staging-storage.sh` but I suspect there may be some case-by-case manual changes needed

**Comment by spiffxp** [comment]
FYI @kubernetes/release-engineering

**Comment by spiffxp** [comment]
/retitle audit followup: some k8s-staging-* projects have differing IAM

**Comment by spiffxp** [comment]
/priority backlog
/milestone v1.23
Needs another pass.  The diff in the description is likely an artifact of when GCR was setup for a given staging project.  It used to need roles/editor, it doesn't anymore.  We should reconcile to the service agent role
