### ISSUE TITLE
audit followup: some k8s-staging-* buckets give "roles/storage.legacyBucketReader" and some do not

### ISSUE THREAD

**Issue by thockin** [kubernetes/k8s.io#1666]
I don't know which is right, but some have:

```
     {
       "members": [
+        "group:k8s-infra-staging-XYZ@kubernetes.io",
         "projectViewer:k8s-staging-XYZ
       ],
       "role": "roles/storage.legacyBucketReader"
     },
```

and some don't

**Comment by spiffxp** [comment]
/sig release
/area release-eng
/priority important-soon
/milestone v1.21
this may be reconcilable via a full run of infra/gcp/ensure-staging-storage.sh but I suspect there may be some case-by-case manual changes needed

**Comment by spiffxp** [comment]
/milestone v1.23
/priority important-longterm
Also needs another pass. I've run ensure-staging-storage.sh for everything a number of times at this point.  If there are additional bindings beyond the standard set, we should remove them
