### ISSUE TITLE
some k8s-staging-* projects have other services enabled

### ISSUE THREAD

**Issue by thockin** [kubernetes/k8s.io#1667]
k8s-staging-addon-manager has compute.googleapis.com and oslogin.googleapis.com

k8s-staging-capi-docker has dns.googleapis.com

k8s-staging-capi-openstack has compute.googleapis.com and oslogin.googleapis.com

There are more...

**Comment by spiffxp** [comment]
/close
Going to close this in favor of https://github.com/kubernetes/k8s.io/issues/1675 to address this for multiple projects, multiple services
