### ISSUE TITLE
audit followup: remove k8s-prow iam bindings for jobs that no longer run in k8s-prow

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/k8s.io#1674]
Followup to https://github.com/kubernetes/k8s.io/pull/1534#discussion_r577999661

https://github.com/kubernetes/test-infra/pull/19810 migrated some container image promoter jobs to k8s-infra-prow-build-trusted, we don't need k8s-prow to have workload identity bindings for these anymore

This is not intended to outright remove all k8s-prow bindings, some are likely still required for prow.k8s.io to schedule to the k8s-infra prow build clusters

/kind cleanup
/wg k8s-infra
/sig testing
/sig release
/area release-eng
/priority important-longterm
/milestone v1.21

**Comment by spiffxp** [comment]
/remove-lifecycle stale
Still relevant. Not going to freeze this though

**Comment by ameukam** [comment]
prow.k8s.io is now migrated. 
We no longer need this

cc @BenTheElder 

/close
