### ISSUE TITLE
k8s-infra-prow-oncall unable to navigate to k8s-infra-prow-build via GCP console UI

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/k8s.io#1678]
The "kubernetes.io" org does not appear in the "Select from" box, it should

I'm guessing this is either org view, folder view, or some other resourcemanager permission

/kind bug
/area prow
/area access
/sig testing
/priority important-soon
/assign
/milestone v1.21

**Comment by ameukam** [comment]
@spiffxp Forgive me if I misunderstand this issue but I don't have this issue (as member of k8s-infra-prow-oncall and k8s-infra-prow-viewers):  

![image](https://user-images.githubusercontent.com/2343515/108428208-7fa52400-723e-11eb-8f52-3833e99033be.png)

**Comment by spiffxp** [comment]
@ameukam that would be because you're a member of `gke-security-groups@`
```
$ gcloud organizations get-iam-policy 758905017065
# ...
- members:
  - group:gke-security-groups@kubernetes.io
  role: roles/browser
# ...
$ gcloud iam roles describe roles/browser
description: Access to browse GCP resources.
etag: AA==
includedPermissions:
- resourcemanager.folders.get
- resourcemanager.folders.list
- resourcemanager.organizations.get
- resourcemanager.projects.get
- resourcemanager.projects.getIamPolicy
- resourcemanager.projects.list
name: roles/browser
stage: GA
title: Browser
```

That seems a little too broad for a group that's supposed to be about access to `aaa` in `kubernetes-public`, but I'm not going to change for now

I think that role does make sense for k8s-infra-prow-oncall though, since prow interacts with many projects, and viewing iam policies would help troubleshooting.

**Comment by spiffxp** [comment]
https://github.com/kubernetes/k8s.io/pull/1679 should fix

**Comment by spiffxp** [comment]
ref: https://github.com/kubernetes/k8s.io/issues/1743
