### ISSUE TITLE
increase prow build/test cluster capacity

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/k8s.io#1703]
the wg k8s infra cluster is periodically hitting the capacity limit AFAICT, we should probably increase it as we've added more workloads

/assign @spiffxp 

https://console.cloud.google.com/monitoring/dashboards/custom/10925237040785467832?timeDomain=1m&project=k8s-infra-prow-build

https://github.com/kubernetes/k8s.io/blob/main/infra/gcp/clusters/projects/k8s-infra-prow-build/prow-build/main.tf#L120

**Comment by spiffxp** [comment]
/assign @BenTheElder 
who opened https://github.com/kubernetes/k8s.io/pull/1706 for the non-quota part of this

**Comment by spiffxp** [comment]
https://github.com/kubernetes/k8s.io/pull/1706 bumped node pool max size from 50 to 80

Quotas this would need for us-central1:
- 3 * 80 * 8 = 5760 CPUs
- 3 * 80 * 500 = 120,000 Gi pd-ssd capacity
- 3 * 80 * 1 = 240 in-use IP addresses
- (3 * 80 * 375 = 90,000 Gi local-ssd if we wanted to go this route with the minimum local-ssd size)

Quotas for us-central1 at present:
- 2,500 CPUs (raised by https://github.com/kubernetes/k8s.io/issues/1231)
- 130,000 Gi pd-ssd capacity (raised by https://github.com/kubernetes/k8s.io/issues/1231)
- 320 in-use IP addresses (raised by https://github.com/kubernetes/k8s.io/issues/1616)
- 6,000 Gi local-ssd capacity (default)

**Comment by spiffxp** [comment]
Requested the following quota changes:
>Change CPUs - us-central1 from 2,500 to 3,840
>Change Persistent Disk SSD (GB) - us-central1 from 130,000 GB (130 TB) to 140,000 GB (140 TB)
>Change Local SSD (GB) - us-central1 from 20,000 GB (20 TB) to 100,000 GB (100 TB)

**Comment by spiffxp** [comment]
/close
Request has been approved
