### ISSUE TITLE
We need a GSuite for sharing SIG/WG documents

### ISSUE THREAD

**Issue by dims** [kubernetes/k8s.io#175]
Context : https://github.com/kubernetes/community/issues/3159

Some docs are in personal google accounts, we need to move them somewhere better. 

Example of a problem from a slack discussion:
```
lavalamp [12:58 PM]
yeah if you can make a gsuite available I'll be super happy, I'm constantly spammed by access requests from people who don't realize they just have to join a group
```

Also see https://groups.google.com/a/kubernetes.io/forum/?utm_medium=email&utm_source=footer#!msg/steering/my_roZIKuXo/I-pjrrvrDwAJ

**Comment by dims** [comment]
cc @parispittman @idvoretskyi

**Comment by thockin** [comment]
We don't want to make "member of the gsuite" a new "achievement unlocked"
thing.  I try to remember to publish docs from my personal gmail.  That is
obnoxious but at least it doesn't mean "myname@k8s.io" becomes a merit
badge.

**Comment by dims** [comment]
discussion here : https://groups.google.com/a/kubernetes.io/d/msg/steering/my_roZIKuXo/I-pjrrvrDwAJ
