### ISSUE TITLE
audit-followup: deal with project ssh-keys growing 

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/k8s.io#1751]
Followup from https://github.com/kubernetes/k8s.io/pull/1748

over time k8s-infra-e2e-* projects are accumulating entries in `project.commonInstanceMetadata["ssh-keys"]` (eg: https://github.com/kubernetes/k8s.io/pull/1748/files#diff-358508c57e9216cf9e24c719a001712286b35054ea2618b4c7904db2290e8337R6)

briefly:
- first entry ends in `prow\nprow:prow:ssh-rsa` (this is intended, same across all projects and managed by scripts in this repo)
- second entry ends in `prow\nkubetest2:ssh-rsa` (not sure if this is actively used / the same key everywhere)
- a lot of the entries end in something like `root@6e6f003c-7933-11eb-a603-2218f636630c\nkubetest2:ssh-rsa`

concerns:
- are these growing unbounded?
- what happens if we hit a max entries limit? 
- do we want to pre-create these keys ourselves vs. trusting CI to be allowed to do this?
- if we preserve status quo of ever-changing, can we make audit of these expected changes less noisy?

/kind bug
/wg k8s-infra
/sig testing
/area prow
/area infra-mgmt
/area access
/area infra/auditing
/priority important-longerm

**Comment by spiffxp** [comment]
/assign @amwat 
To answer questions re: kubetest2

**Comment by amwat** [comment]
so i think both of those are generated by kube-up for the same reasons, except they have a different $USER
kubetest just inherits from https://github.com/kubernetes/test-infra/blob/master/config/prow/config.yaml#L614-L615 kubetest2 overrides it to use `kubetest2`

**Comment by spiffxp** [comment]
if that's the case I guess I would expect to see a lot more spurious keys with not-kubetest2 at the end of them

wonder what it is that kube-up is doing differently on its own?  regardless, I'm feeling like some possible paths forward could be:
- make kube-up clean after itself
- make boskos clean up _some_ of this stuff (I don't think wiping all common metadata is what we want, and not even all keys in this one field)
- have some other custom janitor sweep through and clean these up ~daily/weekly

**Comment by amwat** [comment]
I think `kube-down` cleaning after itself and janitor both make sense.

Just to elaborate on the "why they are all the same":

we add `preset-k8s-ssh` keys to all the jobs 

https://github.com/kubernetes/test-infra/blob/92cd24353f22a1d9be918983bb7330d4a317ea55/config/prow/config.yaml#L611-L628

which mounts a pair of existing keys (as secrets in the prow cluster) to each job.

which `scenarios/kubernetes_e2e.py` copies into `/workspace/.ssh/google_compute_engine`
which gcloud ends up reusing. 

https://github.com/kubernetes/test-infra/blob/92cd24353f22a1d9be918983bb7330d4a317ea55/scenarios/kubernetes_e2e.py#L192-L205

This will propagate once for every time it encounters a new project, after that the keys will already exist (so makes it faster).

Whereas by default, gcloud will just create a new pair of keys (currently what's happening for kubetest2)

Depending on what's more important (time saving with static keys/ clean runs)
we can (port over all this logic to kubetest2/go the should be cleaned up in kube-down/janitor route)

**Comment by spiffxp** [comment]
That assumed key the preset adds is already prepopulated in all projects by ensure-e2e-projects.sh 

We should figure out why it's not being detected

**Comment by spiffxp** [comment]
New key per run and cleaning up afterward would be a good followup and reduce impact of the assumed key needing to be rotated, but let's cut the noise down first

**Comment by spiffxp** [comment]
https://github.com/kubernetes-sigs/kubetest2/issues/109 - support for reusing ssh keys
https://github.com/kubernetes/test-infra/pull/21561 - enable for our kubetest2 jobs

At this point I'm inclined to try a one-shot that nukes the ssh-keys and resets to known default.  I will try to take a look at currently running jobs (look at boskos resources on relevant build clusters) to see if it's worth avoiding potential disruption caused by wiping keys.

**Comment by spiffxp** [comment]
Latest audit PR's don't show keys randomly getting added anymore.

Opened https://github.com/kubernetes/k8s.io/pull/1894 to stage a manual edit so I can edit keys more quickly, will run `K8S_INFRA_ENSURE_E2E_PROJECTS_RESETS_SSH_KEYS=true ./infra/gcp/prow/ensure-e2e-projects.sh` to purge all the random ssh-keys, and then look for results to be reflected in latest audit PR

**Comment by spiffxp** [comment]
Latest audit PR (https://github.com/kubernetes/k8s.io/pull/1897) shows the results of https://github.com/kubernetes/k8s.io/pull/1894

I sorta want to wait one more round and see if any more keys come back
