### ISSUE TITLE
Growth in the consumption cost of Compute Engine service

### ISSUE THREAD

**Issue by ameukam** [kubernetes/k8s.io#1762]
During the billing review of 03-03-2021 meeting, @spiffxp noticed a increase of the total spent on Compute Engin for project `k8s-infra-prow-build`. This may need further investigation. 

![image](https://user-images.githubusercontent.com/2343515/110170823-0dfed580-7dfb-11eb-9122-f05188461240.png)

Source: https://datastudio.google.com/s/k4qozcHEZrk. 

/assign @spiffxp 
/priority backlog
/area cluster-infra
/area billing

**Comment by ameukam** [comment]
Maybe the recent efforts to reduce build maintenance : https://github.com/kubernetes/enhancements/issues/2420#issuecomment-791024902 ?

**Comment by BenTheElder** [comment]
I don't think so, more likely code freeze => lots of PRs being tested, bigger node pool?
We also had some issues with bad unit tests and bad partial go 1.16 upgrade leading to lots of spurious failures (that had nothing to do with bazel or not).

**Comment by ameukam** [comment]
Over the time, resources consumption grew significantly. I don't think we should investigate this. 
We can re-open it if needed. 

/close
