### ISSUE TITLE
Move slack inviter to CNCF infrastructure.

### ISSUE THREAD

**Issue by dims** [kubernetes/k8s.io#177]
http://slack.k8s.io/ is running in a cluster which very few people have access to. We need to move this to the CNCF's GKE cluster.

**Comment by dims** [comment]
Don't know where our yaml file is or how it's installed. Though looks like @luxas has a setup for another instance here: https://github.com/luxas/cloud-native-finland/blob/master/setup/blog/slackin.yaml

**Comment by thockin** [comment]
I can extract the running YAML for this, when we are ready.

**Comment by thockin** [comment]
https://github.com/kubernetes/k8s.io/pull/192

**Comment by dims** [comment]
/close

please see https://github.com/kubernetes/k8s.io/pull/226
