### ISSUE TITLE
Donating clusterapi.io domain to CNCF

### ISSUE THREAD

**Issue by vincepri** [kubernetes/k8s.io#1815]
Hi everyone,

A while ago I registered `clusterapi.io` domain given that it was available. I would like to donate this domain to the CNCF and use it for the [Cluster API](https://github.com/kubernetes-sigs/cluster-api) project.

/cc @dims

**Comment by dims** [comment]
@caniszczyk Can you please help with the transfer of this domain to our use?

**Comment by caniszczyk** [comment]
yes, can you file a ticket @dims ? we can potentially do this via a self service fashion: https://jira.linuxfoundation.org/plugins/servlet/theme/portal/2/create/63

whoever can unlock the domain + send the auth code over should do it

if that doesn't work, we will do the domain transfer dance over email like usual :)

**Comment by dims** [comment]
Excellent. on it (filing a ticket)

**Comment by dims** [comment]
@vincepri Do you want to try that portal url method please?

**Comment by dims** [comment]
@caniszczyk here it is! CNCFSD-734

**Comment by dims** [comment]
@vincepri @caniszczyk is this wrapped up?

**Comment by vincepri** [comment]
Folks, how do we go about managing the dns zone within this repository?

**Comment by ameukam** [comment]
@vincepri we manage the DNS zones here : https://github.com/kubernetes/k8s.io/tree/main/dns.

Also `cluster-api.io`is free to acquisition.

**Comment by idvoretskyi** [comment]
@vincepri a quick check on the current status of this

**Comment by vincepri** [comment]
This can probably be closed, everything was done and the domain transfer was completed.

/close

**Comment by spiffxp** [comment]
/remove-lifecycle rotten
Given that the domain transfer happened
