### ISSUE TITLE
Request premissions to create and manage Projects on Kubernetes/k8.io

### ISSUE THREAD

**Issue by Riaankl** [kubernetes/k8s.io#1817]
To help track and focus on the **Umbrella issue: migrate away from google.com gcp projects #1469** I would like to request permissions to be able to create and manage [Projects](https://github.com/kubernetes/k8s.io/projects) in this repo.

**Comment by spiffxp** [comment]
Why not use issues on https://github.com/orgs/kubernetes/projects/6 ?

**Comment by Riaankl** [comment]
We want to put a lot of focus on the topics related to your Umbrella issue and other issue supporting that work.
I saw I have access to that https://github.com/orgs/kubernetes/projects/6.
Would it make sense to create a new project board for tracking the work and filter out some noise? 
Or would you prefer if we stick with Project board 6?

**Comment by spiffxp** [comment]
What GitHub search syntax could adequately filter down to the relevant work?

eg milestone, priority label, area label, sig label, lifecycle label, etc

Our label taxonomy needs work and we could use some suggestions

**Comment by Riaankl** [comment]
Good, I will work with that. 
Thank you @spiffxp 
/close

**Comment by spiffxp** [comment]
https://github.com/kubernetes/k8s.io/issues/508#issuecomment-804388064 per taxonomy

I'm not completely opposed to the idea of smaller boards I just worry about fragmentation. I already have a tough time keeping track of what's going on. Thinking in terms of GitHub search queries is most effective for me. It could be that "is on this other project board" is useful in that sense. But I guess I'm asking for some exploration first

**Comment by Riaankl** [comment]
@spiffxp I do not know how you manage to keep track of all the things. - Respect.
I am very new to K8s.io repo and it is still a little unclear to me. I would like to simplify and not further complicate it for you.
You are probably correct that a label could be a good way to filter on the current protect board. Maybe something like `Infra-Migration` + assigning the issue to Hippie / Caleb.
