### ISSUE TITLE
Run publisher-bot in CNCF infra

### ISSUE THREAD

**Issue by dims** [kubernetes/k8s.io#183]
https://github.com/kubernetes/publishing-bot is currently running in a OpenShift based cluster inside RedHat. We should move it to a CNCF sponsored GKE cluster.

To try the bot out, we can use the kubernetes-nightly github org. To populate the repos in this org, we can use:
```
hack/fetch-all-latest-and-push.sh kubernetes-nightly
```

To run the bot you can use:
```
make build-image push-image deploy CONFIG=configs/kubernetes-nightly
```

Note that you will need to be added to get access to the github token (we use `git crypt`): 
```
https://github.com/kubernetes/publishing-bot/pull/147
```
You will also need to be added as admin in the [kubernetes-nightly github org](https://github.com/kubernetes-nightly) by @sttts. Once you are able to run the bot against `kubernetes-nightly` and the job is stable, we can promote to running the bot against `kubernetes` target-org

**Comment by dims** [comment]
@sttts any other tips we can record here? (eventually we need to write these up somewhere)

**Comment by sttts** [comment]
Publishing-bot for the main kubernetes org is now running in CNCF cluster in k8s-publishing-bot namespace. It is deployed manually as it had been before in Openshift:

```shell
$ make validate build-image push-image deploy CONFIG=configs/kubernetes
```

**Comment by nikhita** [comment]
cc @hoegaarden

**Comment by nikhita** [comment]
What's remaining here?

**Comment by dims** [comment]
we are good! i think :)

/close

**Comment by nikhita** [comment]
> (eventually we need to write these up somewhere)

Missed this before, do we need to document some stuff too :)

**Comment by dims** [comment]
lol ok. reopening

/reopen
