### ISSUE TITLE
audit followup: give k8s-conform serviceaccounts objectAdmin privileges for their respective gcs buckets

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/k8s.io#1850]
Followup for https://github.com/kubernetes/k8s.io/pull/1800/files#r597514009

Currently we give humans (`group:k8s-infra-conform-foo`) `roles/storage.objectAdmin` for the gcs bucket `k8s-conform-foo`, but the corresponding service account only gets `roles/storage.objectCreator`

I believe this was chosen at the time to ensure rogue automation couldn't go delete a bunch of results.  But I'm fine giving it the more elevated privileges we extend to humans.  The use case motivating this is allowing CI using that serviceaccount to update well-known files within the bucket (version-marker, latest build, etc.)

**Comment by dims** [comment]
+1 to this idea.

**Comment by saschagrunert** [comment]
I would be also in favor of this :+1:

**Comment by spiffxp** [comment]
Opened https://github.com/kubernetes/k8s.io/pull/1890 to fix this, PTAL
