### ISSUE TITLE
Request for sig-cluster-lifecycle-cluster-api-alerts@kubernetes.io Google Group

### ISSUE THREAD

**Issue by randomvariable** [kubernetes/k8s.io#1863]
We were using kubernetes-sig-cluster-lifecycle-cluster-api-alerts@googlegroups.com for Testgrid/Prow alerts for Cluster API. Unfortunately, after a Google Workspace migration, all the owners were removed and the group has disappeared into the ether.

Would it be possible to create a Google Group within the kubernetes.io domain, so we can manage it via this repository, e.g. in this example PR https://github.com/kubernetes/k8s.io/pull/1862 where I attempted to do it using a normal googlegroups.com email address?

Thanks.

**Comment by dims** [comment]
cc @spiffxp @thockin @ameukam

**Comment by ameukam** [comment]
@randomvariable Looking at #1862, we need to validate 2 requirements: 
* group name (including the domain) can be up to 73 characters long.
* domain need to `kubernetes.io`.

Feel free to open a new PR (or reopen #1862) and assign it to me.

**Comment by randomvariable** [comment]
@ameukam , great, thanks. will do.
