### ISSUE TITLE
CRI-O artifact staging

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes/k8s.io#1882]
We require a staging location for image and binary artifacts, which is modifiable by us (without a retention policy).

I'll request a staging project for that purpose.

cc @haircommander @mrunalp

**Comment by spiffxp** [comment]
... so actually, cri-o is not actually part of kubernetes anymore (as of kubernetes/community#3668).

It's now a CNCF incubating project: https://cri-o.io/

If it's not part of kubernetes, I don't think k8s-infra is the right place to host its artifacts.

https://github.com/kubernetes/k8s.io/issues/915 - we still need to document our policies on what is/not fair game for a staging project

**Comment by saschagrunert** [comment]
Thank you for the clarification, I'll check if I can request a project directly from the CNCF
/close
