### ISSUE TITLE
cannot find sippy deployment

### ISSUE THREAD

**Issue by deads2k** [kubernetes/k8s.io#1889]
After merging https://github.com/kubernetes/k8s.io/pull/1615 I expected to see the manifests get applied to the cluster, but I don't see that. 

```
deads@cloudshell:~$ kubectl --context=prod-aaa -nsippy get pod
No resources found in sippy namespace.
deads@cloudshell:~$ kubectl --context=prod-aaa -nsippy get deployment
No resources found in sippy namespace.
deads@cloudshell:~$ kubectl --context=prod-aaa -nsippy get all
Error from server (Forbidden): replicationcontrollers is forbidden: User "deads@redhat.com" cannot list resource "replicationcontrollers" in API group "" in the namespace "sippy": r
equires one of ["container.replicationControllers.list"] permission(s).
Error from server (Forbidden): daemonsets.apps is forbidden: User "deads@redhat.com" cannot list resource "daemonsets" in API group "apps" in the namespace "sippy": requires one of 
["container.daemonSets.list"] permission(s).
deads@cloudshell:~$ kubectl --context=prod-aaa -nsippy get ingress
No resources found in sippy namespace.
```

Is there a spot for logs showing failures to create certain manifests if we have trouble?  Is there a slack channel I should be asking in?

**Comment by ameukam** [comment]
@deads2k Sorry for the confusion. See https://github.com/kubernetes/k8s.io/pull/1615#issuecomment-816098149

**Comment by deads2k** [comment]
> @deads2k Sorry for the confusion. See [#1615 (comment)](https://github.com/kubernetes/k8s.io/pull/1615#issuecomment-816098149)

ah ha!

> @deads2k 👋🏾 , resources deployment is still a manual action in aaa. You will need to connect and deploy them yourself.

Thanks!

/close
