### ISSUE TITLE
Provide firebase accounts for subproject docs

### ISSUE THREAD

**Issue by justinsb** [kubernetes/k8s.io#189]
In the cluster-api meeting today we discussed how best to do docs for subprojects, and there was a general preference for using firebase - except that it isn't free.  Is this something we can do under the CNCF wg-infra umbrella?

cc @neolit123 and @davidewatson for visibility and possibly to provide some background context.

**Comment by neolit123** [comment]
thanks for logging this @justinsb !

**Comment by hh** [comment]
Justin and @dims discussed this on the #k8s-wg-infra call toady.
@idvoretskyi recommended the request come from you or @spiffxp

**Comment by idvoretskyi** [comment]
Before submitting, can someone please update this issue with more details on the purpose of using Firebase?

Specifically, in Firebase vs Netlify comparison.

**Comment by neolit123** [comment]
thanks @idvoretskyi 
^ @davidewatson could you please comment.

**Comment by dims** [comment]
@davidewatson please write up what we need and why, and ping me back?

**Comment by davidewatson** [comment]
After talking to @BenTheElder I learned that kind and kubebuilder recently switched to using netlify so I don't think there is any reason for us to use firebase anymore. Thanks for everyone's help on this.

/close

**Comment by BenTheElder** [comment]
See this thread for some more details until we get it written up properly: https://kubernetes.slack.com/archives/C1J0BPD2M/p1550730421025400

----

I've been working to solve subproject docs, we have a netlify experiment here: https://kind.sigs.k8s.io/

I think we can do this repeatably at scale and at no additional cost to the main website, which already uses it.

In particular nearly all details of netlify can be managed via a [config file](https://www.netlify.com/docs/netlify-toml-reference/) in the repo, and the cost for paid netlify as we use it is just based on the number of team-members. 

For DNS verification reasons these have to be the same team anyhow (unless every site also gets a domain), so we can have an overall Netlify team (which I'm volunteering to help with) do initial setup for each site and then do ongoing site configuration via the `netlify.toml` in each repo.

Doing this means each site doesn't cost additional $, and we're unlikely to move the main https://kubernetes.io site off of it anytime soon.

Aligning with SIG Docs on the stack is additionally helpful for shared expertise, though any static site generator can be used.

I am syncing back with @zacharysarah about this next week when they're back from vacation.
