### ISSUE TITLE
Requesting access to GCP & GCS for ii.coop

### ISSUE THREAD

**Issue by Riaankl** [kubernetes/k8s.io#1945]
# Reason for the issue:

We created the PR's
- Create group for access to gcs logs #1871
- Add ii.coop to k8s-infra-gcp-{auditors,accounting} #1913

We are still unable to access the logs.
In K8s Infra meeting on 14 April 2021 Arnaud Meukam offered to help unblock.

## The purpose of the access is to determine:
1. artifacts logs per artifact and location
2. Originating IP for artifact requests.

 With local testing we found the user need these permissions to access these logs
- storage.buckets.get
- storage.objects.get
- storage.objects.list
- logging.viewer

## Questions:
- What else needs to be done from ii's side to successfully get access to the logs?
- What is the best practice for the analysis of these logs? (BigQuery, DataStudio, SQL)

**Comment by ameukam** [comment]
@Riiankl For better transparency, can you mention why you need access to those logs ? Thanks!

**Comment by Riaankl** [comment]
As part of the K8s Infra WG's mandate to move K8s Infra to community own infra, ii will investigate the use of artifacts by volume of traffic and ASN data related to the traffic.
CNCF & Google legal agreed on the terms and the ii team agreed to all the legalities around it.

**Comment by Riaankl** [comment]
Access seems to work as expected.
Thank you @ameukam
