### ISSUE TITLE
Update netlify configuration for cluster-api-aws.sigs.k8s.io for default branch rename

### ISSUE THREAD

**Issue by randomvariable** [kubernetes/k8s.io#1946]
Default branch for https://github.com/kubernetes-sigs/cluster-api-provider-aws is now `main` and needs its netlify configuration updated accordingly.

Part of https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/1782 

Thanks in advance!

**Comment by mrbobbytables** [comment]
updated it in netlify's settings 👍

**Comment by randomvariable** [comment]
thanks @mrbobbytables !

/close
