### ISSUE TITLE
Document Requirements for spending CNCF money on sigs

### ISSUE THREAD

**Issue by hh** [kubernetes/k8s.io#195]
I think the general guideline we discussed was, "are the artifacts produced publicly consumed"

/assign @dims

**Comment by dims** [comment]
"Various projects in the kubernetes and kubernetes-sigs github organizations produce artifacts including release binaries, container images etc. The wg-k8s-infra will help figure out choices/options for supporting the creation and dissemination of these artifacts."

Is this enough? where do we add this language?

**Comment by spiffxp** [comment]
I think we should add this to the wg-k8s-infra charter.

We also discussed escalation: checking with a CNCF representative first, then going to steering
