### ISSUE TITLE
Set up Organizational ID with IANA for X.509 Attributes

### ISSUE THREAD

**Issue by randomvariable** [kubernetes/k8s.io#1959]
The Kubernetes GCP Cloud Provider uses [Google owned IANA ASN.1 OIDs](https://github.com/kubernetes/cloud-provider-gcp/blob/0e9c8d0151f46b5a6c0beea7778c034c6984d5d0/pkg/nodeidentity/id.go#L14) for extension attributes in CSRs for the Kubelet. We would like to genericise this mechanism in Kubernetes Cluster API but feel that it would be more appropriate to use CNCF / Kubernetes Project owned OIDs instead of using something from Google's block.

Would it therefore be possible to register for a OID at https://pen.iana.org/pen/PenApplication.page , and then we can maintain a list of attributes and definitions within this repository.

/assign @dims 
Who I had chatted with previously about this.

**Comment by dims** [comment]
@randomvariable i've submitted the application, will report back when we have the OID (used the sc1 - steering email id)

**Comment by randomvariable** [comment]
Thanks!

**Comment by dims** [comment]
```
Dear Davanum Srinivas,

Your application [REQUEST-96856] has been completed and a PEN has been assigned.

Your Private Enterprise Number is: 57683

Below is a copy of your PEN record. This record will be visible in the PEN registry within an hour.

The PEN registry is available at the following address:

http://www.iana.org/assignments/enterprise-numbers

If there is any change in the contact information, please submit a modification template via the following link:

http://pen.iana.org/pen/PenModification.page

Best regards,

IANA Services, PTI
iana-pen@iana.org

********************************************

Private Enterprise Number: 57683
Organization Name: Cloud Native Computing Foundation
Organization Address: 548 Market St
PMB 57274
San Francisco, CA 94104-5401
Organization Phone: x-xxx-xxx-xxxxx
Contact Name: Davanum Srinivas
Contact Address:
Contact Phone:
Contact Fax:
Contact Email: xxxxxxxxxxxxxxxxx
```

**Comment by dims** [comment]
@randomvariable sorry just caught up with this again.

**Comment by randomvariable** [comment]
Great, thanks for this!

**Comment by randomvariable** [comment]
cc @ykakarap and @yastij

**Comment by BenTheElder** [comment]
Should we update the contact info to someone at the CNCF?

**Comment by liggitt** [comment]
> Would it therefore be possible to register for a OID at https://pen.iana.org/pen/PenApplication.page , and then we can maintain a list of attributes and definitions within this repository.

Did that list / standardization ever happen? There are two proposed usages underneath the issued PEN and I want to make sure we maintain an accurate canonical list
