### ISSUE TITLE
Moving k8s-artifacts-gcslogs bucket to its own project 

### ISSUE THREAD

**Issue by Riaankl** [kubernetes/k8s.io#1968]
ii.coop request access to the k8s-artifacts-gcslogs to work on K8s Infra WG projects
Granting access with the correct level of permission proof to be difficult.

If the bucket is in its own project it need not pick up `projectOwners` 
Bindings is a cleaner solution to accomplish

Fixes issue: #1945 
Refers to PR: 
Read access to read access k8s-artifacts-gcslogs #1966
Enable GCS logs [#904](https://github.com/kubernetes/k8s.io/issues/904#issuecomment-816484483)

**Comment by Riaankl** [comment]
k8s-artifacts-gcslogs bucket access available to ii
Thank you @spiffxp @ameukam

**Comment by ameukam** [comment]
/reopen
I'll consider this done when #2031 is merged. I plan to do the transition to the dedicated project next week.

**Comment by spiffxp** [comment]
/assign @hh 
I'm assigning @hh for awareness, but I think this is something that @ameukam and I can handle.  We just might someone from ii to confirm that they are capable of polling/regenerating their reports at the end of this.

My sketch of a plan:
- switch all access log settings to point to the new bucket
- copy the old access logs to the proper location in the new bucket
- ask ii to ensure polling/reporting works with the new bucket location
- drop old data, IAM resources (service accounts and/or bindings)
- verify that all PII data goes solely into the one project, and that only members authorized to handle PII have access

**Comment by ameukam** [comment]
We will need to migrate the BigQuery datasets used for images pulling reports.
@Riaankl @bernokl Can you provide us the list of datasets that need to be migrated ?

**Comment by Riaankl** [comment]
@ameukam I cleaned up the `k8s-infra-ii-sandbox` with only 2 data sets remaining:
- `riaan_data_store`
- `etl_script_generated_set_prod`
These we need for reports

**Comment by ameukam** [comment]
@Riaankl Do you need those buckets to be migrated :

```shell
cloud alpha storage ls --project k8s-infra-ii-sandbox
gs://artifacts.k8s-infra-ii-sandbox.appspot.com/
gs://export-c2e4nmc5jmg9n5nacc60/
gs://ii_bq_scratch_dump/
gs://k8s-infra-ii-sandbox-bb-test/
```

Apart from all this, is there anything else that needs to be migrated ?
cc @bernokl

**Comment by Riaankl** [comment]
> @Riaankl Do you need those buckets to be migrated :
> 
> ```shell
> cloud alpha storage ls --project k8s-infra-ii-sandbox
> gs://artifacts.k8s-infra-ii-sandbox.appspot.com/
> gs://export-c2e4nmc5jmg9n5nacc60/
> gs://ii_bq_scratch_dump/
> gs://k8s-infra-ii-sandbox-bb-test/
> ```

@ameukam Yes, please.

**Comment by spiffxp** [comment]
Migrating files from the old bucket to the new bucket via
```
gsutil -m rsync gs://k8s-artifacts-gcslogs gs://k8s-infra-artifacts-gcslogs
```

**Comment by spiffxp** [comment]
Done migrating data over
```
[323.5k/323.5k files][  2.2 TiB/  2.2 TiB] 100% Done 671.9 MiB/s ETA 00:00:00
Operation completed over 323.5k objects/2.2 TiB.
```

**Comment by spiffxp** [comment]
@BobyMCbobs @Riaankl can you confirm you're reading from k8s-infra-artifacts-gcslogs and that it's safe to delete k8s-artifacts-gcslogs?

**Comment by BobyMCbobs** [comment]
> @BobyMCbobs @Riaankl can you confirm you're reading from `gs://k8s-infra-artifacts-gcslogs` 
Yes! Permissions are sorted, thank you :smiley: 

> and that it's safe to delete `gs://k8s-artifacts-gcslogs`?
I will have to defer back to @Riaankl for Monday (NZDT), to ensure things are all pulled across and referenced correctly.

Cheers!

**Comment by Riaankl** [comment]
@BobyMCbobs now that you have pipeline off log data establish we do not need any older data.

**Comment by spiffxp** [comment]
I don't follow if the above comment means we're OK to delete the old bucket, can you please clarify?

**Comment by Riaankl** [comment]
> I don't follow if the above comment means we're OK to delete the old bucket, can you please clarify?

From my side, yes you can delete, Thank you.

**Comment by spiffxp** [comment]
```
$ time gsutil -mq rm -r gs://k8s-artifacts-gcslogs

real	51m27.627s
user	28m47.162s
sys	12m52.428s
```

**Comment by spiffxp** [comment]
/close
Saw an audit PR confirm the bucket is gone.  Calling this done.
