### ISSUE TITLE
switching on compute api and other APIs in k8s-staging-cluster-api-gcp

### ISSUE THREAD

**Issue by dims** [kubernetes/k8s.io#1993]
We are trying to enable building node images regularly for cluster API for GCP project:
https://github.com/kubernetes-sigs/image-builder/pull/445

Background : Currently some of the CI jobs build the image every time and THEN create the cluster using the node image which takes a long time. if we have prebuilt images when things change in image-builder then we can speed things up. this will help us build a viable alternative to kube-up scripts using CAPG.

the packer based image-build needs compute API (and may be other things ... but let's start with this), we had a hack job where we were trying this out which showed this issue:
https://storage.googleapis.com/kubernetes-jenkins/logs/cluster-api-provider-gcp-build-image-nightly/1388933164977623040/build-log.txt

Also note that this means will will have a bunch of images here over time and we will need a way to clean them up (or make sure we have retention policy)

cc @cpanato

**Comment by cpanato** [comment]
I tried on a personal project and it required only the compute api

**Comment by cpanato** [comment]
will work over the weekend or next week when kubecon is over :)
