### ISSUE TITLE
Change the image type of aaa

### ISSUE THREAD

**Issue by ameukam** [kubernetes/k8s.io#2013]
GKE 1.19 is now GA and the image type variant `cos` is now deprecated. 

https://cloud.google.com/kubernetes-engine/docs/release-notes#April_14_2021:

> With the release of GKE node version 1.19, the Container-Optimized OS with Docker (cos) variant is deprecated. Please migrate to the Container-Optimized OS with Containerd (cos_containerd) variant, which is now the default GKE node image. For instructions, see Containerd images.

```shell
gcloud container clusters describe aaa --format="table(name,currentMasterVersion,currentNodeVersion,nodeConfig.imageType)" --region=us-central1
NAME  CURRENT_MASTER_VERSION  CURRENT_NODE_VERSION  IMAGE_TYPE
aaa   1.17.17-gke.3000        1.17.17-gke.3000      COS

gcloud container node-pools describe pool1-20190918234853194900000001 --format="value(config.imageType)" --region=us-central1 --cluster=aaa
COS

gcloud container node-pools describe pool2-20200316195138785800000001 --format="value(config.imageType)" --region=us-central1 --cluster=aaa
COS
```

We should also subscribe to the regular channel.

**Comment by spiffxp** [comment]
Deploying the change to do this https://github.com/kubernetes/k8s.io/pull/2252#issuecomment-870920388

- [x] `terraform apply` started: ~ 2021-06-29 21:10:00 UTC
- [x] pool2 finished migrated
- [ ] pool1 finished migrating
- [ ] terraform apply finished:
- [ ] verified cluster / node pool configuration
- [ ] verified apps running
  - [ ] gcsweb.k8s.io
  - [ ] k8s.io
  - [ ] kubernetes-external-secrets
  - [ ] node-perf-dash.k8s.io
  - [ ] perf-dash.k8s.io
  - [ ] publishing-bot
  - [ ] sippy
  - [ ] slack-infra

**Comment by spiffxp** [comment]
Fixing slack-infra notes

Why is the pod crashing:
```
$ k logs -n slack-infra slack-moderator-words-69d6867cb6-7n757
2021/06/30 16:54:40 Failed to load config from /etc/slack-moderator-words/config.json: couldn't parse config: invalid character '}' looking for beginning of object key string
```

What does config.json look like:
```
$ k --context=aaa get secrets -n slack-infra slack-moderator-words-config -o=yaml | yq -r '.data["config.json"]' | base64 -d
{
  "signingSecret": "REDACTED",
  "accessToken": "REDACTED",
}
```

I bet it's the trailing comma.  Edit to remove, push new k8s secret yaml to GSM, run deploy.sh, see pods running
```
$ k --context=aaa get secrets -n slack-infra slack-moderator-words-config -o=yaml | yq -r '.data["config.json"]' | base64 -d > config.json
$ vi config.json
$ kubectl create secret generic slack-moderator-words-config --from-file config.json --dry-run=client -o=yaml | gcloud secrets --project=kubernetes-public versions add slack-moderator-words-config --data-file=-
$ cd slack-infra
$ ./deploy.sh
# ...
secret/slack-moderator-words-config configured
$ k delete pod -n slack-infra -l app=slack-moderator-words
pod "slack-moderator-words-69d6867cb6-7n757" deleted
pod "slack-moderator-words-69d6867cb6-prv9m" deleted
$ k get pods -n slack-infra -l app=slack-moderator-words
NAME                                     READY   STATUS    RESTARTS   AGE
slack-moderator-words-69d6867cb6-d8wwk   1/1     Running   0          89s
slack-moderator-words-69d6867cb6-xzq4v   1/1     Running   0          89s
```
