### ISSUE TITLE
Take inventory of the google groups we created

### ISSUE THREAD

**Issue by dims** [kubernetes/k8s.io#206]
- we need to document who is in which group, what is the group used for. 
- also add a template for creating new groups

**Comment by thockin** [comment]
Also need a way to programmatically get a list of members

**Comment by spiffxp** [comment]
Look for everything that starts with "k8s-infra"

**Comment by spiffxp** [comment]
@thockin is in the process of converting over most of the public googlegroups.com groups that we're using, migrating over to the kubernetes.io google groups that are managed by https://github.com/kubernetes/k8s.io/issues/228

**Comment by spiffxp** [comment]
Unclear whether we can automatically find dangling references or delete and wait for those people to yell

**Comment by spiffxp** [comment]
/assign @thockin 
remove people from everything, use groups for everything

**Comment by thockin** [comment]
I *think* this is done.  Once the audit-script is done and merged we will have confidence.

**Comment by thockin** [comment]
Audit found exactly ONE place where we had an old googlegroups - k8s-infra-sig-release-prototype@googlegroups.com was storage admin on gs://k8s-sig-release-prototype

No longer - now  k8s-infra-sig-release-prototype@kubernetes.io which should be the same ppl.

@justaugustus
