### ISSUE TITLE
Reorganize apps running on aaa under /apps

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/k8s.io#2150]
This will make it easier to setup a prowjob that auto-deploys these apps on postsubmit

We can also auto-label PRs against these apps and enforce ownership conventions:
- group: `k8s-infra-rbac-{app}@kubernetes.io`
- namespace on aaa: `{app}`
- label on k8s resources: `app: {app}`
- label on gcloud secrets: `app: {app}`
- OWNERS: `approvers: {app}-approvers`
- etc...

Going off of the list of namespaces in `infra/gcp/namespaces/ensure-namespaces.sh` and some manual inspection
- [x] cert-manager (@jimdaga, https://github.com/kubernetes/k8s.io/pull/2374)
- [x] gcsweb (@jimdaga, https://github.com/kubernetes/k8s.io/pull/2284)
- [x] k8s.io (@spiffxp, https://github.com/kubernetes/k8s.io/pull/2383)
- [X] kubernetes-external-secrets (@spiffxp, https://github.com/kubernetes/k8s.io/pull/2290)
- [x] node-perf-dash (@spiffxp, https://github.com/kubernetes/k8s.io/pull/2290)
- [x] perfdash (@jimdaga, https://github.com/kubernetes/k8s.io/pull/2317)
- [X] prow (@ameukam, https://github.com/kubernetes/k8s.io/pull/2330)
- [X] publishing-bot (@jimdaga, https://github.com/kubernetes/k8s.io/pull/2315)
- [x] sippy (@jimdaga, https://github.com/kubernetes/k8s.io/pull/2261)
- [x] slack-infra (@jimdaga, https://github.com/kubernetes/k8s.io/pull/2304)
- [x] triageparty-release (@jimdaga, https://github.com/kubernetes/k8s.io/pull/2303)

/priority important-longterm
/kind cleanup
/wg k8s-infra
/area cluster-infra

**Comment by jimdaga** [comment]
@spiffxp I could maybe give this a try; 

Just to make sure I follow; you're looking to re-org this `k8s.io` repo so that the folders containing app code get moved under `/apps` - and the various labels, OWNER files, etc get updated to match the `{app}` name - correct?

Also; since you mentioned prow - I take it there is no existing deploy automation I'd have to consider, right?

**Comment by jimdaga** [comment]
Sorry things have been slow, I'm hoping to find some time soon to sit down and finish a bunch of PRs at once.

**Comment by spiffxp** [comment]
It's all good, I've been pretty slow myself.  Updated description with what I think are the remaining apps, along with notes about which ones might be special cases.  I am doing a few straightforward apps to get a feel for it, but will leave the rest open.  

If I have time, I'll look at answering my questions on the tougher ones, but it's likely I won't have time, so could use help on those.

**Comment by spiffxp** [comment]
https://github.com/kubernetes/k8s.io/pull/2290 for kubernetes-external-secrets and node-perf-dash

**Comment by jimdaga** [comment]
One more PR- but I have a question in the NOTES about directory names.
https://github.com/kubernetes/k8s.io/pull/2317

**Comment by ameukam** [comment]
kettle : the presence of this namespace is for [kettle migration](https://github.com/kubernetes/k8s.io/issues/787). We should remove it if we consider host kettle on a different GKE cluster during the migration.

**Comment by spiffxp** [comment]
I've opened https://github.com/kubernetes/k8s.io/issues/2386 to address fleshing out "what is an app" and generally anything else listed as a known issue in https://github.com/kubernetes/k8s.io/tree/main/apps#proposed-format

Thanks to all of this, I was able to move forward on https://github.com/kubernetes/k8s.io/issues/2151

**Comment by spiffxp** [comment]
/assign @spiffxp @ameukam 
since we did a few of the apps, but mostly this was @jimdaga 

/close
Calling this done!
