### ISSUE TITLE
Setup postsubmit deploy job(s) for apps running under aaa

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/k8s.io#2151]
Allow k8s-infra-prow-build-trusted to automatically deploy apps to aaa

Preferably using a service-account per app that grants it the same privileges that humans would have? I would rather avoid giving k8s-infra-prow-build-trusted cluster-admin access to `aaa`

If we're comfortable doing this in a pinch, we can consider it

/wg k8s-infra
/kind feature
/area access
/area prow
/area cluster-infra
/priority important-longterm

**Comment by spiffxp** [comment]
ref: https://github.com/kubernetes/k8s.io/pull/988 where I tried to grant per-namespace access to secrets, need to unpack whether this is feasible or we're still concerned about exfiltration of cert secrets

**Comment by ameukam** [comment]
Related to https://github.com/kubernetes/k8s.io/issues/2150.

**Comment by spiffxp** [comment]
/milestone v1.23
There's a chance I may implement this before close of v1.22 but let's plan on v1.23

**Comment by spiffxp** [comment]
Opened https://github.com/kubernetes/test-infra/pull/22970

**Comment by spiffxp** [comment]
Opened https://github.com/kubernetes/test-infra/pull/23040 to have the postsubmits report to #k8s-infra-alerts in slack

**Comment by spiffxp** [comment]
I've been holding this open to see successful deploys of all the apps

https://github.com/kubernetes/k8s.io/pull/2425 touches quite a few, so if all the resulting jobs are successful I'll call this done

**Comment by spiffxp** [comment]
Promising...
<img width="619" alt="Screen Shot 2021-07-30 at 7 23 10 AM" src="https://user-images.githubusercontent.com/49258/127667352-73975635-1281-4526-b99d-e8f7992f9353.png">

**Comment by spiffxp** [comment]
One mildly annoying thing I guess, I scanned right past the "failure" text the first time.  Making the template auto-bold or capitalize that might help? Or notify vs. just a regular message?

Apps that have yet to be exercised:
- kubernetes-external-secrets
- prow
- publishing-bot

**Comment by spiffxp** [comment]
https://github.com/kubernetes/k8s.io/pull/2431 - PR to bump kubernetes-external-secrets

**Comment by spiffxp** [comment]
/close
kubernetes-external-secrets fails to deploy automatically right now due to https://github.com/kubernetes/k8s.io/issues/2218

I'm going to call this done and followup on kubernetes-external secrets in that issue
