### ISSUE TITLE
DNS REQUEST: add CAA record

### ISSUE THREAD

**Issue by jimangel** [kubernetes/k8s.io#2216]
It was requested to create CAA DNS records for k/website as a security best practices and, well, it's good to know what CAs can issue "official" certificates for public facing Kubernetes things.

More info in this PR: https://github.com/kubernetes/k8s.io/pull/1849. The PR covers kubernetes.io, not k8s.io, which we should also lock down in a similar manor.

/priority important-soon
/milestone v1.22
/cc @dims @ameukam @spiffxp @thockin

**Comment by sftim** [comment]
/sig security
perhaps?

**Comment by spiffxp** [comment]
Bumping for recency because I'd like to see the PR merged in the next week

**Comment by jimangel** [comment]
@spiffxp sorry I missed this, yep, I'll get a PR in for k8s.io soon (probably after 1.23 settles down).

/assign

**Comment by ameukam** [comment]
@jimangel I think we can close this. It's been exactly 30 days since we added the CAA record for `k8s.io`. WDYT ?

**Comment by jimangel** [comment]
LGTM! Thanks!
/close
