### ISSUE TITLE
Migrate all Opaque kubernetes Secrets on k8s-infra clusters to ExternalSecrets

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/k8s.io#2220]
- Clusters that need kubernetes-external-secrets installed:
  - [x] k8s-infra-prow-build/prow-build: https://github.com/kubernetes/k8s.io/pull/2827, https://github.com/kubernetes/k8s.io/pull/2830

- Secrets that need to be migrated over for k8s-infra-prow-build/prow-build:
```$ k --context=prow-build get secrets -A | grep Opaque | awk '{print "- [ ] "$1"/"$2}';```
  - [x] test-pods/service-account: https://github.com/kubernetes/k8s.io/pull/2845, https://github.com/kubernetes/k8s.io/pull/2858
  - [x] test-pods/ssh-key-secret: https://github.com/kubernetes/k8s.io/pull/2845, https://github.com/kubernetes/k8s.io/pull/2858

- Secrets that need to be migrated over for k8s-infra-prow-build-trusted/prow-build-trusted:
```$ k --context=prow-build-trusted get secrets -A | grep Opaque | awk '{print "- [ ] "$1"/"$2}'```
  - [x] test-pods/cncf-ci-github-token (https://github.com/kubernetes/k8s.io/pull/2219)
  - [x] test-pods/k8s-cip-test-prod-service-account: https://github.com/kubernetes/k8s.io/pull/2859
  - [x] test-pods/k8s-gcr-audit-test-prod-service-account: https://github.com/kubernetes/k8s.io/pull/2859
  - [x] test-pods/k8s-infra-ci-robot-github-token: https://github.com/kubernetes/k8s.io/pull/2859
  - [x] test-pods/k8s-triage-robot-github-token: https://github.com/kubernetes/k8s.io/pull/2859
  - [x] test-pods/service-account: https://github.com/kubernetes/k8s.io/pull/2859
  - [x] test-pods/slack-tempelis-auth: https://github.com/kubernetes/k8s.io/pull/2859
  - [x] test-pods/snyk-token* (https://github.com/kubernetes/k8s.io/pull/2222)

- Secrets that need to be migrated over for kubernetes-public/aaa
``` $ k --context=aaa get secrets -A | grep Opaque | awk '{print "- [ ] "$1"/"$2}' ```
  - [x] ~cert-manager/letencrypt-prod-account-key~ (generated by cert-manager)
  - [x] cert-manager/letencrypt-staging-account-key (generated by cert-manager. still used)
  - [x] elekto/elekto-secret
  - [x] prow/k8s-infra-build-clusters-kubeconfig
  - [x] prow/k8s-infra-ci-robot-github-token
  - [x] prow/k8s-infra-prow-cookie
  - [x] prow/k8s-infra-prow-github-oauth-config
  - [x] prow/k8s-infra-prow-hmac-token
  - [x] prow/k8s-infra-prow-sa-key
  - [x] publishing-bot/github-token (https://github.com/kubernetes/k8s.io/pull/2825, https://github.com/kubernetes/k8s.io/pull/2829)
  - [x] slack-infra/recaptcha: https://github.com/kubernetes/k8s.io/pull/2828
  - [x] slack-infra/slack-event-log-config: https://github.com/kubernetes/k8s.io/pull/2828
  - [x] slack-infra/slack-moderator-config: https://github.com/kubernetes/k8s.io/pull/2828
  - [x] slack-infra/slack-moderator-words-config: https://github.com/kubernetes/k8s.io/pull/2828
  - [x] slack-infra/slack-post-message-config: https://github.com/kubernetes/k8s.io/pull/2828
  - [x] slack-infra/slack-welcomer-config: https://github.com/kubernetes/k8s.io/pull/2828
  - [x] slack-infra/slackin-token: https://github.com/kubernetes/k8s.io/pull/2828
  - [X] triageparty-release/triage-party-github-token: https://github.com/kubernetes/k8s.io/pull/2754
  - [x] prow/k8s-infra-ci-robot-github-token* (https://github.com/kubernetes/k8s.io/pull/2224)

\* new secret, not a migration, but tracking here anyway

**Comment by spiffxp** [comment]
https://github.com/kubernetes/k8s.io/pull/2219 is a first attempt at migrating a secret for k8s-infra-prow-build-trusted

**Comment by ameukam** [comment]
cc @chaodaiG

**Comment by spiffxp** [comment]
/close
All secrets in our kubernetes clusters now come from Google Secret Manager (or could come from other secret systems).  This is great for DR, since if a cluster disappears, we can re-provision it with the existing secrets.  Also nice for safe rotation, since new secret values can be added without implicitly deleting old values.

We could use some docs updates here, and kubernetes-public is still managed via bash instead of terraform.  Will continue to track that work under https://github.com/kubernetes/k8s.io/issues/1731
