### ISSUE TITLE
Increase quotas for k8s-infra-e2e-scale-5k-project

### ISSUE THREAD

**Issue by ameukam** [kubernetes/k8s.io#2225]
Part of : https://github.com/kubernetes/k8s.io/issues/1469

Tracking issue for the list of quotas that need to be increased for GCP project `k8s-infra-e2e-scale-5k-project`. 
Project created here: https://github.com/kubernetes/k8s.io/pull/2195

[List of quotas](https://docs.google.com/spreadsheets/d/1v9ynsUx3pcMJKVaHViuVqxVtRP1OmGIadvw2uro7D7Y/edit#gid=0) 

/assign @spiffxp @dims 
cc @thockin 

/assign @mm4tt @wojtek-t @shyamjvs 
cc @jkaniuk @marseel

**Comment by ameukam** [comment]
I raised the quotas for `k8s-infra-e2e-scale-5k-project` in us-east1. Quotas are now https://console.cloud.google.com/iam-admin/quotas?project=k8s-infra-e2e-scale-5k-project : 

CPU: 6000
Persistent Disk Standard (GB): 501,800 GB

**Comment by spiffxp** [comment]
I think this can be closed but I don't have all of the issue links handy.  AFAIK we've migrated over the jobs that use this project and they're not having quota issues anymore.

**Comment by ameukam** [comment]
> I think this can be closed but I don't have all of the issue links handy. AFAIK we've migrated over the jobs that use this project and they're not having quota issues anymore.

@spiffxp Migration is still in progress : https://github.com/kubernetes/test-infra/pull/23844. 

I'll update the issue with the links concerned.

**Comment by spiffxp** [comment]
It looks like https://github.com/kubernetes/test-infra/pull/23844 has been merged, are we good to call this done?

**Comment by ameukam** [comment]
I'll close this when https://github.com/kubernetes/test-infra/pull/24080 is merged

**Comment by spiffxp** [comment]
/close
https://github.com/kubernetes/test-infra/pull/24080 has merged

nicely done @ameukam !
