### ISSUE TITLE
audit followup: add ensure_project_oslogin function

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/k8s.io#2278]
Followup issue for: https://github.com/kubernetes/k8s.io/pull/2234/files#r659954289

>This is required by the canary prowjobs for sig-scalability. This ensure the SA `prow->build@k8s-infra-prow-build.iam.gserviceaccount.com` can login in the instances created in >the project. I need to add a `ensure_project_oslogin` bash function.

_Originally posted by @ameukam in https://github.com/kubernetes/k8s.io/pull/2234#r659954289_

Agreed

Should we ensure `enable-oslogin` is set for any project that has `oslogin` enabled?

/wg k8s-infra
/sig testing
/sig scalability
/area prow

**Comment by ameukam** [comment]
> Should we ensure enable-oslogin is set for any project that has oslogin enabled?
How can we identify those who need it? Or just enable it for all the k8s-infra-e2e-boskos-* projects  ?

**Comment by ameukam** [comment]
> > Should we ensure enable-oslogin is set for any project that has oslogin enabled?
> 
> How can we identify those who need it? Or just enable it for all the k8s-infra-e2e-boskos-* projects ?

We enabled this in #2296 but it breaks the scalability jobs. Reverted in #2312.

**Comment by spiffxp** [comment]
/milestone clear
Is this actually needed then? Or should we drop the dead code?

**Comment by ameukam** [comment]
Function is removed. #2466 
/close
