### ISSUE TITLE
audit followup: update list of services enabled for k8s-infra-ii-sandbox

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/k8s.io#2279]
Followup issue for https://github.com/kubernetes/k8s.io/pull/2234/files#r659949688

>@bernokl @hh I would be better to do this with the existing Terraform code we use for this project.

_Originally posted by @ameukam in https://github.com/kubernetes/k8s.io/pull/2234#r659949688_

Yup, this is the list of what's currently explicitly enabled:
https://github.com/kubernetes/k8s.io/blob/f7d1b639aade0faa9b2c1ed4e7b09600cf14f09a/infra/gcp/clusters/projects/k8s-infra-ii-sandbox/main.tf#L42-L48

Compare with the list of what's actually enabled: https://github.com/kubernetes/k8s.io/blob/f7d1b639aade0faa9b2c1ed4e7b09600cf14f09a/audit/projects/k8s-infra-ii-sandbox/services/enabled.txt#L2-L22

Not all of these need to be explicitly enabled; many of them are probably dependencies that automatically get enabled by other services.  But I would suggest at least adding:
- `bigquery.googleapis.com`
- `cloudasset.googleapis.com`
- `secretmanager.googleapis.com`
- `storage-api.googleapis.com`

/wg k8s-infra
/area infra/auditing
/priority important-longterm
/assign @bernokl @Riaankl @hh

**Comment by spiffxp** [comment]
/remove-lifecycle stale
Is this something y'all can get to sometime soon?

**Comment by ameukam** [comment]
/milestone clear.
At this point there is no need to update the services enabled. the project is actually for experimental purposes.
/close
