### ISSUE TITLE
Manage Google Group memberships via API

### ISSUE THREAD

**Issue by cblecker** [kubernetes/k8s.io#228]
If we use the kubernetes.io gsuite, we should be able to manage group creation and membership via an API.

We should be able to create a service account, and then delegate it the following scopes via domain-wide delegation:
- `https://www.googleapis.com/auth/admin.directory.group`: https://developers.google.com/admin-sdk/directory/v1/guides/delegation
- `https://www.googleapis.com/auth/apps.groups.settings`: https://developers.google.com/admin-sdk/groups-settings/auth

With these, we should be able to script creation of groups, administer their settings, and modify membership of them. It appears that we should be able to do this just with Gsuite Basic, without adding on any extra options/services/cost.

It appears there are also SDK libraries to get started:
https://godoc.org/google.golang.org/api/admin/directory/v1
https://godoc.org/google.golang.org/api/groupssettings/v1

**Comment by spiffxp** [comment]
I know Christoph ended up starting [a steering@ thread](https://groups.google.com/a/kubernetes.io/forum/#!topic/steering/ZR40uoFT9VI), my main question is what are next steps

**Comment by spiffxp** [comment]
/assign @dims 
investigate how to recreate all of the groups we want from command line

**Comment by spiffxp** [comment]
I have created a wg-k8s-infra-api-test@kubernetes.io account, assigned to a "Group Admin" role, and given credentials to @dims

The intent is for this to be temporary / exploratory to prove we can do what we want via API.  We should follow up with a more constrained account that has exactly what we need.

/assign
@dims and @cblecker can tap me if more is needed

**Comment by dims** [comment]
@cblecker in the API that creates new groups, there is no support for switching on `Allow members outside your organization` toggle that is available in the UI. 
https://developers.google.com/admin-sdk/directory/v1/reference/groups/insert

**Comment by dims** [comment]
So we will have to create the groups by hand (with that option on) and then script the add/delete of members.

**Comment by cblecker** [comment]
@dims: that's because that setting is in the OTHER API I mentioned at the top: https://developers.google.com/admin-sdk/groups-settings/manage 🤦‍♂ 

I don't know WHY Google had to split it up into two different API schemes, but yeah.

**Comment by dims** [comment]
ah! thanks @cblecker

**Comment by spiffxp** [comment]
I walked through https://developers.google.com/admin-sdk/directory/v1/guides/delegation#delegate_domain-wide_authority_to_your_service_account for a client_id @dims provided to me

**Comment by dims** [comment]
WIP is here https://github.com/kubernetes/k8s.io/pull/248 it uses the service account @spiffxp minted. all the APIs i need (so far!) are working. will hammer out a yaml structure and turn the WIP into something we can use.

Anyone else wants to be able to run the commands, please send me your GPG key, i used `git-crypt` to encrypt the json for the service account (see the PR above), at the moment it's me and @cblecker who can decrypt the file.

**Comment by dims** [comment]
The scoped needed so far for the service account are

```
https://www.googleapis.com/auth/admin.directory.user.readonly
https://www.googleapis.com/auth/admin.directory.group
https://www.googleapis.com/auth/admin.directory.group.member
https://www.googleapis.com/auth/apps.groups.settings
```

in english ..

![Sign_in_-_Google_Accounts](https://user-images.githubusercontent.com/23304/57101620-9e47cd00-6cef-11e9-95e3-e43a20c0f41c.png)

**Comment by dims** [comment]
- add new group
- delete old group
- add folks to group
- delete folks from group

all works!

**Comment by spiffxp** [comment]
wg-k8s-infra-api-test@ renamed to wg-k8s-infra-api@

![Screen Shot 2019-05-09 at 1 31 14 PM](https://user-images.githubusercontent.com/49258/57484822-e40c1480-725e-11e9-9ff8-0f42a2885378.png)
![Screen Shot 2019-05-09 at 1 31 28 PM](https://user-images.githubusercontent.com/49258/57484823-e5d5d800-725e-11e9-8fee-232813ba3457.png)

**Comment by spiffxp** [comment]
I once again walked through https://developers.google.com/admin-sdk/directory/v1/guides/delegation#delegate_domain-wide_authority_to_your_service_account for a client_id @dims provided to me, granting the following scopes
```
https://www.googleapis.com/auth/admin.directory.user.readonly
https://www.googleapis.com/auth/admin.directory.group
https://www.googleapis.com/auth/admin.directory.group.member
https://www.googleapis.com/auth/apps.groups.settings
```

**Comment by spiffxp** [comment]
Script is now runnable, two of us can run it: @dims and @cblecker (list of people who have gpg keys in repo)
