### ISSUE TITLE
Document how to find the URL for gcsweb

### ISSUE THREAD

**Issue by techtonik** [kubernetes/k8s.io#23]
I think that the question is rather lame, but if [guidelines](https://github.com/kubernetes/k8s.io/blob/master/CONTRIBUTING.md) are true in:

> We'd like this repo to demonstrate the best practices for running sites on Kubernetes.

then I'd really like to know how to find URL for the `gcsweb` site, which config is located here:
https://github.com/kubernetes/k8s.io/tree/master/gcsweb

**Comment by thockin** [comment]
I answered this in the other PR, but 2 things.

1) gcsweb is just a tool, anyone can run it at any URL with any allowed buckets they want.
2) everything in this repo is ...k8s.io - so gcsweb.k8s.io is this instance, but it's not designed for initial browsing (it doesn't list which GCS buckets are available, for instance), but once you are in, through a documented link, you can browse.

**Comment by techtonik** [comment]
The question is still bothering me - where is the missing link from https://github.com/kubernetes/k8s.io/tree/master/gcsweb config and http://gcsweb.k8s.io/gcs/kubernetes-release/release/v0.4.1/ URL?

**Comment by thockin** [comment]
if I understand correctly - look at deployment.yaml - it has a list of which buckets are being served.
