### ISSUE TITLE
Convert Ingresses and services on k8s-infra cluster aaa

### ISSUE THREAD

**Issue by ameukam** [kubernetes/k8s.io#2316]
The GKE `aaa` cluster have been [upgraded](https://github.com/kubernetes/k8s.io/pull/2294/files) to GKE 1.19. We should move the existing ingresses to the GA version `networking.k8s.io/v1`. 

We currently use the  `networking.k8s.io/v1beta1`:

```shell:
$grep 'networking.k8s.io/v1beta1'

perf-dash.k8s.io/ingress.yaml
1:apiVersion: networking.k8s.io/v1beta1

k8s.io/ingress-canary.yaml
1:apiVersion: networking.k8s.io/v1beta1

k8s.io/ingress-canary-v6.yaml
1:apiVersion: networking.k8s.io/v1beta1

k8s.io/ingress-prod-v6.yaml
1:apiVersion: networking.k8s.io/v1beta1

k8s.io/ingress-prod.yaml
1:apiVersion: networking.k8s.io/v1beta1

apps/triageparty-release/ingress.yaml
1:apiVersion: networking.k8s.io/v1beta1

apps/slack-infra/resources/ingress.yaml
1:apiVersion: networking.k8s.io/v1beta1

apps/node-perf-dash/ingress.yaml
1:apiVersion: networking.k8s.io/v1beta1

apps/gcsweb/ingress.yaml
1:apiVersion: networking.k8s.io/v1beta1

apps/sippy/ingress.yaml
1:apiVersion: networking.k8s.io/v1beta1
```

And possibly convert Kubernetes services of type NodePort to the ClusterIP type with [GCP Networking Endpoint](https://cloud.google.com/kubernetes-engine/docs/how-to/standalone-neg).

References: 
https://cloud.google.com/kubernetes-engine/docs/concepts/ingress
https://kubernetes.io/docs/concepts/services-networking/ingress/
https://cloud.google.com/kubernetes-engine/docs/how-to/container-native-load-balancing

**Comment by jimdaga** [comment]
First PR submitted: https://github.com/kubernetes/k8s.io/pull/2375

**Comment by spiffxp** [comment]
/close
Closed out by:
- https://github.com/kubernetes/k8s.io/pull/2397 (@spiffxp)
- https://github.com/kubernetes/k8s.io/pull/2425 (@jimdaga)

```
$ ./hack/verify-conftest.sh | grep networking || echo all migrated
all migrated
```

**Comment by ameukam** [comment]
Still want to do : 

> And possibly convert Kubernetes services of type NodePort to the ClusterIP type with GCP Networking Endpoint.

I'll open a separate issue.
