### ISSUE TITLE
Add a filter for http://k8s.io/good-first-issue and https://go.k8s.io/help-wanted to not show assigned issues

### ISSUE THREAD

**Issue by marianabocoi** [kubernetes/k8s.io#2323]
When searching for a good first issue or wanting to help, it was hard for me to find not-assigned issues. 

Initially, I opened issues and looked around, and I got de-motivated to start helping. 😞 
I then found the `no:assignee` filter in GitHub, and it made it easier to find an issue to contribute to.

If the short link is for the contributors, I would like to add the `no:assignee` filter in the link. 🎈 

I think it is fixed by changing these two lines to add `+no%3Aassignee`: 
https://github.com/kubernetes/k8s.io/blob/e3d8230ec9727d086d26de3aa9f648eb3d3b8801/k8s.io/configmap-nginx.yaml#L238
https://github.com/kubernetes/k8s.io/blob/e3d8230ec9727d086d26de3aa9f648eb3d3b8801/k8s.io/configmap-nginx.yaml#L239

**Comment by marianabocoi** [comment]
also, tests need to be updated 😄

**Comment by dims** [comment]
@marianabocoi please open a PR!

**Comment by marianabocoi** [comment]
Fixing the pr 🍿

**Comment by marianabocoi** [comment]
Was working on figuring out how to run the tests, but found the makefile in the folder 🎉  and the dance with forking etc.  
I Will ping on it soon ❤️ 

Not sure if there are many contributors to this that are not in the wg so maybe documenting how to test changes in [CONTRIBUTING.md](https://github.com/kubernetes/k8s.io/blob/main/CONTRIBUTING.md) does not make sense.

**Comment by marianabocoi** [comment]
@dims I was wrong; I have not figured out how to run tests 😿  

I would love to run the tests locally, and I noticed if I do not provide a TARGET_IP, it runs the tests towards the actual host (`socket.gethostbyname('k8s.io')`). I am curious how I can spin things up locally to test towards `localhost` or similar.
