### ISSUE TITLE
Update slack welcome message

### ISSUE THREAD

**Issue by marianabocoi** [kubernetes/k8s.io#2335]
Update the welcome messages according to suggestions by @mrbobbytables 
> we do need to update the msg to say kubernetes-contributors instead of kubernetes-dev and point folks to k8s.dev for slack guidelines instead of github

This is the file to change 
https://github.com/kubernetes/k8s.io/blob/15fa575622776da06e11c0d95243b47e34961c22/apps/slack-infra/resources/slack-welcomer/message.yaml#L6

/cc @mrbobbytables

**Comment by spiffxp** [comment]
/close
https://github.com/kubernetes/k8s.io/pull/2336 was deployed

Thanks @marianabocoi !
