### ISSUE TITLE
Google groups description limit < 300 chars not checked in tests

### ISSUE THREAD

**Issue by PushkarJ** [kubernetes/k8s.io#2345]
Google groups description max. limit is 300 characters: https://developers.google.com/admin-sdk/groups-settings/v1/reference/groups#:~:text=entry/-,apps%3Adescription,-object

This should be tested in `groups_test.go` otherwise it can lead to failed jobs like this: https://storage.googleapis.com/kubernetes-jenkins/logs/post-k8sio-groups/1415792053220020224/build-log.txt 

Will open a PR to fix this shortly. There is also an existing group: `k8s-infra-staging-cip-test` that seem to have gone through with a higher description character length (maybe because it was created before this limit was imposed). Can add the test to ignore the check for this group. 

/kind bug
/sig security
/area access

**Comment by spiffxp** [comment]
/priority critical-urgent
Since this is breaking group sync right now
/milestone v1.22
