### ISSUE TITLE
GCS Bucket for sig-release prototype for apt and rpm repos

### ISSUE THREAD

**Issue by dims** [kubernetes/k8s.io#235]
Some @kubernetes/sig-release members are looking at prototyping a new repository layout for k/k release artifacts. As part of this effort https://github.com/kubernetes/kubernetes/issues/76738

Can we please create a CNCF owned temporary GCS bucket for this experiment? They would try a job that pushes daily artifacts to start with once they figure out the directory tree layout. This would not be permanent until the KEP is baked (at which point we can remove it and start fresh, would also script everything along the way so we can start fresh in a new bucket)

cc @tpepper

**Comment by thockin** [comment]
I'm a little uncomfortable making one-off experiments without a clean way to track it, but I can do this one.

Do we consider this a "staging" repo that needs a PR to "promote" artifacts or is it a real thing that people push to and store forever?

I'll need emails for people to add to a googlegroup to grant access to anything.  I created "k8s-infra-sig-release-prototype@googlegroups.com" .   I create a project "k8s-sig-release-prototype" and a public-readable bucket of the same name.  I gave that group "Storage admin" privs to that bucket.

I did all of this by hand.

**Comment by tpepper** [comment]
There's a few options depending on how we structure this and how distro-like we might become, but my vision at this point is focused on core packages not broader:
* automated builds (eg: nightly) go here, in a specific clearly "nightly" part of a folder hierarchy
* testing happens
* PR to promote an indicated set of those built artifacts to a "testing" place, perhaps with an alpha/beta/rc designation added in the file name?
* testing happens
* PR to promote an indicated set of those built artifacts to a "release" place

I also want to see reaping of existing artifacts as a part of promotion so nightly's age out to archive, testing's age out to archive, and release section holds the current set of preferred/supported packages with prior ones moved out to archive.

I want all of this to happen from automation driven by auditable PRs.  No parallel, slightly different builds.  No rebuild for publication.  No building from any non-committed code (today all packages are built using non-committed package spec files with manual edits made before building).   I want to see a set of makefiles with "bump" target commands that increment build metadata, commit it, and then build/promote the next 1.13.N, or the next 1.13.1-R packaging, from that committed code.

This bucket would be use to prototype all of that.

(emails coming via DM)

**Comment by thockin** [comment]
The vision is grand.  We are establishing "staging" repos (GCR and GCS) for
various sub-projects.  This sounds similar but a little different.  We'll
need to rationalize the differences and see how we want to set this up in
the end.  For now, you have your playground (once you join the group)

**Comment by tpepper** [comment]
Forgot to update the issue here.  We have this (k8s-sig-release-prototype) as a playground.

/close
