### ISSUE TITLE
Retire dockerhub kubernetes org and delete all associated images

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/k8s.io#237]
In response to the [recent Docker Hub breach](https://success.docker.com/article/docker-hub-user-notification) we have rotated credentials on https://hub.docker.com/u/kubernetes, and removed all repositories contained therein.

None of the kubernetes GitHub orgs use Docker Hub for building images.  We do not host official build artifacts at Docker Hub.  The repositories that lived at https://hub.docker.com/u/kubernetes had not been updated in anywhere from 2-3 years.  Whether these images have migrated on to better homes, what they were built from, and how they are used is a mystery.  They are effectively ownerless and their continued existence is a liability.

|image|last updated|
|---|---|
|kubernetes/cassandra|2015-11-14|
|kubernetes/cauldron|2015-11-14|
|kubernetes/cluster-insight|2015-08-28|
|kubernetes/elasticsearch|2015-11-14|
|kubernetes/eptest|2015-11-14|
|kubernetes/etcd|2015-11-14|
|kubernetes/example-guestbook-php-redis|2015-11-13|
|kubernetes/flake|2015-11-14|
|kubernetes/fluentd-elasticsearch|2015-11-14|
|kubernetes/fluentd-gcp|2015-11-14|
|kubernetes/guestbook|2015-11-13|
|kubernetes/heapster_grafana|2016-01-14|
|kubernetes/heapster_influxdb|2015-12-11|
|kubernetes/heapster|2017-01-10|
|kubernetes/kibana4|2015-11-14|
|kubernetes/kibana|2015-11-13|
|kubernetes/kube2sky|2015-11-12|
|kubernetes/liveness|2015-11-13|
|kubernetes/mariadb|2015-11-14|
|kubernetes/mounttest|2015-11-14|
|kubernetes/nettest|2015-11-13|
|kubernetes/pause|2015-11-13|
|kubernetes/php-redis|2015-11-14|
|kubernetes/phpmyadmin|2015-11-13|
|kubernetes/redis-proxy|2015-11-14|
|kubernetes/redis-slave|2015-11-13|
|kubernetes/redis|2015-11-14|
|kubernetes/serve_hostname|2015-11-13|
|kubernetes/skydns|2015-11-13|
|kubernetes/sleepy|2015-11-14|
|kubernetes/test-webserver|2015-11-14|
|kubernetes/update-demo|2015-11-14|
|kubernetes/zookeeper|2015-11-14|

(source: https://gist.github.com/spiffxp/26a14e1fe284814bbf290d7b47fb7e0c)

If this turns out to have badly broken someone's workflow, please contact our mailing list [kubernetes-wg-k8s-infra@](https://groups.google.com/forum/#!forum/kubernetes-wg-k8s-infra) or slack channel [#wg-k8s-infra](https://kubernetes.slack.com/messages/CCK68P2Q2), and we will work to resolve the issue.

If we hear nothing within a week, we will retire https://hub.docker.com/u/kubernetes.  It will remain owned by the project to ensure nobody else snags it, but we won't be using it.

/wg k8s-infra
/kind cleanup
/priority important-soon

**Comment by thecrudge** [comment]
Redis image not found See PR #14106

**Comment by cblecker** [comment]
@thecrudge which repo?

**Comment by thecrudge** [comment]
@cblecker kubernetes/redis

**Comment by cblecker** [comment]
You mentioned a PR number.. where is that PR? Could you link to it directly? github.com/kubernetes/redis doesn't exist.

**Comment by thecrudge** [comment]
https://github.com/kubernetes/website/pull/14106

**Comment by cblecker** [comment]
@thecrudge replied requesting changes on that PR. thanks for the catch!

**Comment by spiffxp** [comment]
I have restored `kubernetes/pause` as a stopgap for https://github.com/kata-containers/tests/issues/1522

```
$ docker load -i dockerhub-kubernetes-pause.tar.gz
Loaded image: kubernetes/pause:asm
Loaded image: kubernetes/pause:go
Loaded image: kubernetes/pause:latest
$ docker push kubernetes/pause:asm
The push refers to repository [docker.io/kubernetes/pause]
5f70bf18a086: Pushed
03b40935cf58: Pushed
asm: digest: sha256:74a98f0e4d750c9052f092a7f7a72de7b20f94f176a490088f7a744c76c53ea5 size: 936
$ docker push kubernetes/pause:go
The push refers to repository [docker.io/kubernetes/pause]
5f70bf18a086: Layer already exists
e16a89738269: Pushed
go: digest: sha256:b31bfb4d0213f254d361e0079deaaebefa4f82ba7aa76ef82e90b4935ad5b105 size: 938
$ docker push kubernetes/pause:latest
The push refers to repository [docker.io/kubernetes/pause]
5f70bf18a086: Layer already exists
e16a89738269: Layer already exists
latest: digest: sha256:b31bfb4d0213f254d361e0079deaaebefa4f82ba7aa76ef82e90b4935ad5b105 size: 938
```

**Comment by cblecker** [comment]
To document things further, looks like this image was still referenced as recently as October 2018: https://github.com/kubernetes/kubernetes/pull/69631

**Comment by chavafg** [comment]
@spiffxp we have changed our configuration to now use `k8s.gcr.io/pause` image. From kata side, the `kubernetes/pause` image can now be deleted.
Thanks

**Comment by spiffxp** [comment]
/remove-lifecycle stale
I suggest we plan to remove `kubernetes/pause` once v1.16 goes out the door, per our 3 version support policy (ref: https://kubernetes.io/docs/setup/release/version-skew-policy/)

**Comment by dims** [comment]
@spiffxp +1 to `remove kubernetes/pause after v1.16 goes out the door`

**Comment by justaugustus** [comment]
/remove-lifecycle rotten
/lifecycle frozen

What's the status of this?

**Comment by dims** [comment]
Looks like they have fixed it https://github.com/kata-containers/tests/pull/1526 so we should be able to clean things up now.

**Comment by stp-ip** [comment]
We have 1.17 out so we should be able to finish this in 2020 I guess.

**Comment by bartsmykla** [comment]
@spiffxp do you think we can delete the `pause` image now?

**Comment by spiffxp** [comment]
/remove-priority important-soon
/priority backlog
It's really low on my priority list at this point; it would feel great to finally get this done, but I'm juggling too much right now

**Comment by stp-ip** [comment]
Docker is changing their ToS especially important is this part about retention:
```
Docker is introducing a container image retention policy which will be enforced starting November 1, 2020. The container image retention policy will apply to the following plans:
Free plans will have a 6 month image retention limit
Pro and Team plans will have unlimited image retention
```

Assuming we are on a free plan the last images will go away on November 1. Might be a good time to tackle the full retirement of the org once all images are removed by us or docker.

**Comment by spiffxp** [comment]
I am very tempted to delete the pause image now and be done with it, since we're well past v1.16.

OTOH, we could give one last final warning and say once v1.19 is released, we're removing `kubernetes/pause`.

What do folks think?

**Comment by gjtempleton** [comment]
I think the comms around this are a bit confusing as it seems from [their FAQ](https://www.docker.com/pricing/retentionfaq) that the retention period only applies for images that have been neither pushed nor pulled within that retention window:

From the FAQ:

> What is a container image retention limit and how does it affect my account?
Image retention is based on the activity of each individual image stored within a user account. If an image has not either been pulled or pushed in the amount of time specified in your subscription plan, the image will be tagged “inactive.” Any images that are tagged as “inactive” will be scheduled for deletion.

**Comment by BenTheElder** [comment]
This only applies to "inactive" images if you read the FAQ, odd that it wasn't in the email.

**Comment by stp-ip** [comment]
Thanks for the clarification. Would have expected that detail to be worth putting next to the retention notice ^^
Anyway happy to have this cleaned up nonetheless.

**Comment by dims** [comment]
+1 let's please clean it up!

**Comment by sftim** [comment]
Also I think:
/sig security

**Comment by sftim** [comment]
Cleaning up these unmaintained images has helped avoid security concerns.

**Comment by dims** [comment]
backed up the pause image in dockerhub

```
$ docker images | sort
REPOSITORY           TAG       IMAGE ID       CREATED       SIZE
ghcr.io/dims/pause   asm       7b57aeefc2c0   8 years ago   129B
ghcr.io/dims/pause   go        f9d5de079539   8 years ago   240kB
ghcr.io/dims/pause   latest    f9d5de079539   8 years ago   240kB
kubernetes/pause     asm       7b57aeefc2c0   8 years ago   129B
kubernetes/pause     go        f9d5de079539   8 years ago   240kB
kubernetes/pause     latest    f9d5de079539   8 years ago   240kB
```

**Comment by dims** [comment]
and they are gone! https://hub.docker.com/r/kubernetes/pause/tags

![image](https://github.com/kubernetes/k8s.io/assets/23304/26ef5536-919d-428a-9480-4f0a7a2ffc92)
