### ISSUE TITLE
[Umbrella] Implement self-service DNS updates

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/k8s.io#239]
Followup from https://github.com/kubernetes/k8s.io/issues/151

At the moment, updating DNS still requires humans to run commands.  The ideal state is PR-driven:
- DNS requests are made via PR
- OWNERS files dictate who has authority to approve a given DNS request
- When then PR merges, something deploys the change

https://github.com/kubernetes/k8s.io/tree/master/dns#todo outlines some potential tasks

The model we've used elsewhere is:
- Build an image and store it somewhere in gcr.io
- Use prow jobs that run in a "trusted" cluster (has credentials to do things, so don't let untrusted code run in it)
- Use postsubmits to deploy immediately
- Use periodics to reconcile state

Which would mean this may be blocked on:
- community owned gcr.io repo for k8s-infra
- community owned prow
- community owned trusted prow cluster

**Comment by thockin** [comment]
De-duping with #507
