### ISSUE TITLE
Take inventory of Google-owned cluster-based k8s-infra

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/k8s.io#240]
Google has a number of clusters floating around running different pieces of infra for the project.  What's running on them

**Comment by spiffxp** [comment]
First pass.  Based on a survey of internal clusters, with some educated guesses about which services/deployments/statefulsets are still relevant.  I can provide something that's more raw if desired, but it will take time to scrub out potentially sensitive info.

k8s-gubernator/g8r
- kettle

k8s-mungegithub/mungegithub
- perfdash

k8s-prow/prow
- prow (many microservices)

k8s-prow-builds/prow
- boskos
- grandmatriarch
- greenhouse

kubernetes-site/utilicluster
- cert-manager
- gcsweb: https://github.com/kubernetes/k8s.io/issues/204
- k8s-io
- node-perf-dash
- velodrome (many microservices)

kubernetes-tools/tools-cluster
- slack-event-log
- slack-moderator
- slackin

non-google:
- [publishing-bot](https://github.com/kubernetes/publishing-bot)
- [oncall-issue-filer](https://github.com/philips/oncall-issue-filer)

**Comment by ameukam** [comment]
I noticed `velodrome` use very old versions of prometheus and grafana. Do we plan to upgrade those tools during the migration ?

**Comment by philips** [comment]
Is there an estimate on when services will be ready to migrate? I need to decide whether to stand up a new cluster for the oncall-issue-filer or do something else. Thanks!

**Comment by thockin** [comment]
The new cluster is up and is viable for migrations.  A small number of things, including k8s.io, have moved.

@philips do you have docs or info on your thing?

**Comment by philips** [comment]
@thockin I just decommissioned my thing on Tuesday because it has been replaced by HackerOne 😂

**Comment by spiffxp** [comment]
To close this out I'd like to create or link a corresponding issue for each piece of cluster infra https://github.com/kubernetes/k8s.io/issues/240#issuecomment-488210434

**Comment by bartsmykla** [comment]
As perfdash is currently running at the `aaa` and the last bits are updating the docs (kubernetes/perf-tests#1184 and #778) I'm happy to write we can destroy the `k8s-mungegithub/mungegithub` cluster and mark perfdash as done. :-)

**Comment by spiffxp** [comment]
/close
OK, I've stopped short of creating "turn down" issues for the k8s-prow and k8s-prow-build clusters because those may stick around for other purposes.  I've created issues for everything else here.

Next is _non_-cluster infra, such as BigQuery, App Engine, etc. which can lead to turn down of GCP projects, not just clusters.  That's https://github.com/kubernetes/k8s.io/issues/241
