### ISSUE TITLE
Take inventory of Google-owned GCP projects for k8s-infra

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/k8s.io#241]
Google has GCP projects for k8s-infra that hold more than just Kubernetes clusters and the pods/services therein.  To better identify which services need to be migrated over, let's inventory which projects are currently used to run k8s-infra (or tests for k8s) and the services that they use

eg:
- k8s-prow
- k8s-prow-builds
- k8s-mungegithub
- k8s-gubernator
- kubernetes-jenkins
- kubernetes-jenkins-pull
- kubernetes-site
- (the sundry projects used by boskos)
- etc.

**Comment by ameukam** [comment]
How can give some help on this one ?

**Comment by parispittman** [comment]
wanted to document google analytics somewhere for kubernetes.io - unsure if this has been transferred or status but now we have it documented to check :)

**Comment by dims** [comment]
@parispittman Thanks! good one. Who uses the analytics most? (sig-docs?)

**Comment by parispittman** [comment]
@dims - correct. i believe all major players on the team have access (including non-googlers) but it may be still a google owned account.

**Comment by spiffxp** [comment]
/close
Closing this in favor of #1469
