### ISSUE TITLE
post-deprecation-window: turn down kubernetes-ci-images GCP project

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/k8s.io#2417]
Related:
- Part of umbrella issue to migrate away from google.com gcp projects: https://github.com/kubernetes/k8s.io/issues/1469
- Part of umbrella to migrate kubernetes e2e test images/registries to community-owned infrastructure: kubernetes/k8s.io#1458
- Followup to: https://github.com/kubernetes/k8s.io/issues/1460

We've stopped writing new data to this project.

This project can be turned down either:
- 1 year after the release of v1.22 (which should ideally be after the release of v1.25 based on the project's new 3 releases/year cadence), ref: https://kubernetes.io/releases/version-skew-policy/#supported-versions
- when there is negligible traffic to gcr.io/kubernetes-ci-images

/wg k8s-infra

/sig release
/area artifacts
/area release-eng
FYI @kubernetes/release-engineering

/kind cleanup
/kind deprecation
/priority backlog
/milestone v1.25

**Comment by spiffxp** [comment]
/triage accepted
/lifecycle frozen
This is going to need to stay open for a while, but I've bumped its priority down and put in a milestone to signify it's a thing we care about

**Comment by Riaankl** [comment]
@ameukam should this be added to /milestone v1.27 ?

**Comment by ameukam** [comment]
No. Let's extend the deprecation period.

/milestone clear

**Comment by BenTheElder** [comment]
We should do this now.

**Comment by BenTheElder** [comment]
I can see data for the storage amount but the graphs for traffic have none after 2022, though it is abrupt and it was very little at the end.

We're way past the planned turn down.

**Comment by BenTheElder** [comment]
I have changed visibility to private, we will revisit after some time to see if there's a reason to revert that, if not then I'll actually delete everything.

Let's say
/milestone v1.31

And come back by the next release

**Comment by BenTheElder** [comment]
I'm going to delete the content now, since no issues have cropped up with the registry set to private for months now.

**Comment by BenTheElder** [comment]
done
