### ISSUE TITLE
Burn down and recreate k8s-infra cluster

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/k8s.io#243]
Last we talked, the original manually created cluster had not yet been burned down.  We want to burn it down, and use a script to stand up a cluster.

umbrella ref: https://github.com/kubernetes/k8s.io/issues/152

/assign @thockin @justinsb @hh 
/wg k8s-infra

TBD: what... is actually being stood back up?
- accounts / iam policies?
- nodes
- RBAC roles/policies
- infra running on the cluster

**Comment by spiffxp** [comment]
also certificates

**Comment by spiffxp** [comment]
Fair to start with cluster singular before figuring out how to manage N clusters

First place to start is the script itself.  There are many knobs in the UI, how do we set them up in the script.  Interested folks may use a test project and we'll iterate on turning up cluster there

**Comment by cblecker** [comment]
When we talked about this 6 months ago, I had thought we could use terraform for this: https://github.com/cblecker/k8s-tf-cluster

Don't know if we want to go that way, or if we want bash+gcloud, or something else.

**Comment by spiffxp** [comment]
We may try to get together to hack on this at KubeCon EU (contributor summit?)

**Comment by ameukam** [comment]
+100 to do this. I'll need someone that access to the GCP project that owns `kubernetes.io`.

**Comment by spiffxp** [comment]
relevant PR's:
- https://github.com/kubernetes/k8s.io/pull/276
- https://github.com/kubernetes/k8s.io/pull/266
- https://github.com/kubernetes/k8s.io/pull/279

**Comment by spiffxp** [comment]
Use results of https://github.com/kubernetes/k8s.io/pull/250 to create a new cluster

Burn down / migrate contents of `development` and `development2` clusters to this new cluster

Use this cluster to confirm per-namespace billing

**Comment by spiffxp** [comment]
Our goal is to move away from bash toward terraform.

Does terraform support everything we need? Ran into a beta GKE feature that wasn't yet supported by the terraform provider.  We could probably tap the right people on the shoulder to motivate which features get prioritized.

Would we be able to drop down to gcloud if we _had_ to? Yes, this is something we can do if necessary.

Opting to just go straight to terraform

**Comment by spiffxp** [comment]
Awaiting a directory in k8s.io from @cblecker that contains terraform prototype

**Comment by cblecker** [comment]
Opened https://github.com/kubernetes/k8s.io/pull/306

**Comment by thockin** [comment]
We now have a cluster that is born of terraform.  Mission accomplished (enough to close this)
