### ISSUE TITLE
Enumerate RBAC roles that are based off of same groups as IAM roles

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/k8s.io#246]
/area access
/area cluster-mgmt

**Comment by thockin** [comment]
Trying to clean up - is this the same as https://github.com/kubernetes/k8s.io/issues/275 ?  If not, what does this mean?

**Comment by spiffxp** [comment]
/milestone ready-to-migrate
I think this is the same, let's discuss during meeting

**Comment by spiffxp** [comment]
This is about access to things within the GKE cluster.  IAM roles are about access to everything in a given project (or set of projects).  Do we need granularity or can we use a straight 1:1 mapping?

What are the roles on the cluster and what should they have access to

**Comment by thockin** [comment]
Dup of #275
