### ISSUE TITLE
Migrate sig-cli triage party instance

### ISSUE THREAD

**Issue by eddiezane** [kubernetes/k8s.io#2460]
sig-cli currently uses https://tp.kuberneddies.dev/s/kustomize-daily as our triage party instance.

- [X] Google groups and GKE namespace on aaa : https://github.com/kubernetes/k8s.io/pull/2467
- [x] GCP External Global IP address and DNS : https://github.com/kubernetes/k8s.io/issues/2621
- [x] Kubernetes resource deployment : https://github.com/kubernetes/k8s.io/pull/2617
- [x] TLS certificate : https://github.com/kubernetes/k8s.io/pull/2617
- [x] postsubmit auto-deploy : https://github.com/kubernetes/k8s.io/pull/2617

We want to migrate this to Kubernetes infra and domain.

**Comment by ameukam** [comment]
Feel free to follow instructions documented in : https://github.com/kubernetes/k8s.io/blob/main/running-in-community-clusters.md.

**Comment by ameukam** [comment]
The instance is up : https://cli.triage.k8s.io/. 

@eddiezane I think we can call it. Leave the honor to `/close`. :-)

**Comment by eddiezane** [comment]
Thanks for the help!!

/close
