### ISSUE TITLE
k8s-infra-prow: allow deck to access to gs://k8s-testgrid

### ISSUE THREAD

**Issue by ameukam** [kubernetes/k8s.io#2497]
Followup issue of #2235 

deck (component of prow) need access (Read-Only ?) to `gs://k8s-tesgrid` so it can display Testgrid links in the SpyGlass.

```
{"component":"deck","error":"Get \"https://storage.googleapis.com/k8s-testgrid/config\": compute: Received 403 `Unable to generate access token; IAM returned 403 Forbidden: The caller does not have permission\nThis error could be caused by a missing IAM policy binding on the target IAM service account.\nFor more information, refer to the Workload Identity documentation:\n\thttps://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity#authenticating_to\n\n`","file":"prow/spyglass/testgrid.go:45","func":"k8s.io/test-infra/prow/spyglass.(*TestGrid).Start","level":"error","msg":"Couldn't fetch TestGrid config.","severity":"error","time":"2021-08-09T17:19:55Z"}
{"component":"deck","file":"prow/kube/config.go:55","func":"k8s.io/test-infra/prow/kube.kubeConfigs","level":"info","msg":"Parsed kubeconfig context: prow-build-trusted","severity":"info","time":"2021-08-09T17:20:49Z"}
```

I believe this bucket in a Google GCP organization. 

/assign @spiffxp 
cc @BenTheElder 
/area prow
/area apps/prow
/sig testing
/priority important-soon
/milestone v1.23

**Comment by fejta** [comment]
Who is this job trying to authenticate as? Google rejecting deck's attempt to authenticate as whatever identity it is trying to use.

```
Unable to generate access token; IAM returned 403 Forbidden: The caller does not have permission\
```

**Comment by ameukam** [comment]
> Who is this job trying to authenticate as? Google rejecting deck's attempt to authenticate as whatever identity it is trying to use.
> 
> ```
> Unable to generate access token; IAM returned 403 Forbidden: The caller does not have permission\
> ```

This a deck instance running on a public GKE cluster (see #1394). The attempt is triggered by the configuration of this instance : https://github.com/kubernetes/k8s.io/blob/main/apps/prow/config.yaml#L74-L75.

**Comment by spiffxp** [comment]
https://github.com/kubernetes/k8s.io/blob/main/audit/projects/kubernetes-public/service-accounts/k8s-infra-prow%40kubernetes-public.iam.gserviceaccount.com/iam.json - I think the deck service account needs to be authorized to bind to k8s-infra-prow too...

**Comment by ameukam** [comment]
> [https://github.com/kubernetes/k8s.io/blob/main/audit/projects/kubernetes-public/service-accounts/k8s-infra-prow%40kubernetes-public.iam.gserviceaccount.com/iam.json](https://github.com/kubernetes/k8s.io/blob/main/audit/projects/kubernetes-public/service-accounts/k8s-infra-prow%40kubernetes-public.iam.gserviceaccount.com/iam.json?rgh-link-date=2021-08-10T20%3A59%3A07Z) - I think the deck service account needs to be authorized to bind to k8s-infra-prow too...

I think it's already done : https://github.com/kubernetes/k8s.io/blob/main/apps/prow/cluster/deck_rbac.yaml#L2-L7

**Comment by spiffxp** [comment]
I would expect to see a `serviceAccount:kubernetes-public.svc.id.goog[prow/deck]` for the `deck` service account in the `prow` namespace in a cluster in `kubernetes-public` to be able to use this service account

**Comment by fejta** [comment]
https://github.com/kubernetes/k8s.io/blob/main/apps/prow/cluster/deck_rbac.yaml#L2-L7 is configuring the deck service account to request to act as a GCP service account, and the feedback from Google in the description is "No, you (deck service account) are not allowed to do this (act as the GCP service account)."

**Comment by ameukam** [comment]
Thanks for the feedback both of you! I got the initial issue addressed : https://github.com/kubernetes/k8s.io/pull/2512.

I still get in the deck logs :

```shell
Message\u003e\u003cDetails\u003ek8s-infra-prow@kubernetes-public.iam.gserviceaccount.com does not have storage.objects.get access to the Google Cloud Storage object.\u003c/Details\u003e\u003c/Error\u003e","file":"prow/spyglass/testgrid.go:45","func":"k8s.io/test-infra/prow/spyglass.(*TestGrid).Start","level":"error","msg":"Couldn't fetch TestGrid config.","severity":"error","time":"2021-08-10T22:35:34Z"}
```

I guess we need to bind the role `storage/objectViewer` (or more permissions) to `k8s-infra-prow@kubernetes-public.iam.gserviceaccount.com` for the bucket.

**Comment by fejta** [comment]
> need to bind the role storage/objectViewer (or more permissions) to k8s-infra-prow@kubernetes-public.iam.gserviceaccount.com for the bucket.

Done

**Comment by ameukam** [comment]
@fejta Tanks for the help!

I don't think there is anything else to be done here.
/close
