### ISSUE TITLE
k8s-infra-prow: GKE ssl certificate failed to get provisioned

### ISSUE THREAD

**Issue by ameukam** [kubernetes/k8s.io#2505]
k8s-infra-prow.k8s.io requested a SSL certificate through a `ManagedCertificate` : 

https://github.com/kubernetes/k8s.io/blob/dfae9968ee9b3f342797285d0f97c08778bbe83a/apps/prow/cluster/prow_managedcertificate.yaml#L1-L8

The certificate requested ended up with a `FAILED_NOT_VISIBLE` :

```shell
gcloud compute ssl-certificates list --project kubernetes-public --format='table(name,managed.status,managed.domainStatus)' --filter='name ~ mcrt-c0e5fe27-188f-4dc4-b010-3256ef2d1221'
NAME                                       MANAGED_STATUS
mcrt-c0e5fe27-188f-4dc4-b010-3256ef2d1221  PROVISIONING
    k8s-infra-prow.k8s.io: FAILED_NOT_VISIBLE
```

Ref: #1394 
/area dns
/assign @ameukam

**Comment by ameukam** [comment]
Checking the DNS entries are propaged : 

```shell
dig @1.1.1.1 AAAA k8s-infra-prow.k8s.io +short
2600:1901:0:b267::

dig @1.1.1.1 A k8s-infra-prow.k8s.io +short
34.117.224.94
```

This matches what was added in #2404

**Comment by ameukam** [comment]
I can confirm that dropping the AAAA DNS record for `k8s-infra-prow.k8s.io`. Fixed the problem. 

```shell
kubectl get managedcertificates -n prow
NAME                    AGE   STATUS
k8s-infra-prow-k8s-io   44m   Active
```

**Comment by sftim** [comment]
Is this OK to close?

**Comment by ameukam** [comment]
@sftim 👋🏾  co-chair of WG-k8s-Infra here. Thank you for checking this issue. I'll close the issue next week. 
Still want to drop some explanation about what happened.
