### ISSUE TITLE
The link in the README is broken.

### ISSUE THREAD

**Issue by ryuichi1208** [kubernetes/k8s.io#2542]
https://github.com/kubernetes/k8s.io/blob/main/README.md

"https://gcsweb.k8s.io" is 404

```
gcsweb: instance of gcsweb at https://gcsweb.k8s.io - owned by sig-testing
```

**Comment by ameukam** [comment]
gcsweb don't have a default page but it's used to have a web overview of GCS buckets. For example:
https://gcsweb.k8s.io/gcs/k8s-infra-prow-results/. 

I don't this is a technical issue. Feel free to look at gcsweb code and maybe add a default web page: https://github.com/kubernetes/test-infra/tree/master/gcsweb.
