### ISSUE TITLE
Follow up to PR 248 for automation of google groups

### ISSUE THREAD

**Issue by dims** [kubernetes/k8s.io#255]
- [ ] Extract k8s-infra- prefix requested by @spiffxp
- [ ] Search for a way to constrain this to groups created solely by this service account instead of or in addition to blacklisting by name requested by @spiffxp
- [ ] Pick Authoritative model vs Opportunistic model requested by @cblecker 
- [ ] Make lists settings for security customizable
- [ ] Ability to specify "owner"/"manager"/"member" for a google group

**Comment by dims** [comment]
cc @spiffxp @thockin @cblecker

**Comment by spiffxp** [comment]
ref: https://github.com/kubernetes/k8s.io/issues/228

**Comment by thockin** [comment]
This is now totally unassigned.  Is it important?  Can we throw a prio tag on it?

**Comment by cblecker** [comment]
/remove-lifecycle rotten
/close

Everything in here is done already.
