### ISSUE TITLE
Setting up Elekto on Kubernetes infra

### ISSUE THREAD

**Issue by jberkus** [kubernetes/k8s.io#2575]
For the 2021 Steering Committee election, we need to set up [Elekto](https://elekto.dev) running on the Kubernetes infra cluster.  Note that, once running, Elekto will keep running indefinitely, to host any elections within the community that we need to run.

I'm currently setting up container image auto-build according to feedback I got from @ameukam and will update this issue when that image is ready.  One question regarding the image, though: are there specific requirements for what base images I should use for Python applications?  Currently we're using Python:3.7.11-stretch.

Beyond that, we will need the following:

- one running pod hosting the application
- route/ingress to HTTPS
- DBAAS for the database for Elekto, either PostgreSQL or MySQL (could be self-hosted but I've been told we prefer dbaas)
- one configmap OR just hand-coded YAML
- a couple of secrets
- a GitHub token we can use for Oauth and repository checkout

Getting this started now so that we can assemble the requirements.  Thanks!

/sig contributor-experience
/commitee steering

**Comment by ameukam** [comment]
cc @spiffxp @dims

**Comment by ameukam** [comment]
> DBAAS for the database for Elekto, either PostgreSQL or MySQL (could be self-hosted but I've been told we prefer dbaas)

The current GCP DBaaS offer is [Cloud SQL](cloud.google.com/sql/). Can you give us more details about what's the needed configuration for elekto based of the existing features :  https://cloud.google.com/sql/docs/features ?
More detailed list : https://cloud.google.com/sql/docs/feature_support. 

> a GitHub token we can use for Oauth and repository checkout

Github tokens are responsibility of SIG Contribex (Github Administration Team). You can request it here : https://github.com/kubernetes/org/issues/new/choose

**Comment by jberkus** [comment]
CloudSQL requirements are pretty simple: just a Cloud SQL instance, current MySQL or PostgreSQL, configured with name/password login from our cluster.  One database.  Storage requirement: 5GB max.

**Comment by ameukam** [comment]
Opened https://github.com/kubernetes/k8s.io/pull/2587. cc @jberkus

**Comment by jberkus** [comment]
Here's what we need for secrets and config for Elekto.  All of these need to be translated into the same-name ENV variables in the container (please remove {comments})

```
configmap:
  APP_NAME=k8s.elections
  APP_ENV=production
  APP_KEY=
  APP_DEBUG=False
  APP_URL=http://localhost
  APP_PORT=5000 {or whatever you want ingress to connect to}
  APP_HOST=localhost
  APP_CONNECT=http
  DB_CONNECTION=mysql {or postgresql}
  DB_HOST={CloudSQL address}
  DB_PORT={CloudSQL port}
  DB_DATABASE={CloudSQL database}
  META_REPO=https://github.com/kubernetes/community.git
  ELECTION_DIR=events/elections
  META_DEPLOYMENT=local
  META_PATH=meta
  META_BRANCH=main
  GITHUB_REDIRECT=/oauth/github/callback
  
secret:
  GITHUB_CLIENT_ID={clientID from Oauth App}
  GITHUB_CLIENT_SECRET={secret from Oauth app}
  DB_USERNAME={CloudSQL user}
  DB_PASSWORD={CloudSQL pwd}
  META_SECRET={Webhook Secret Here}
```

**Comment by ameukam** [comment]
@jberkus You can add the kubernetes resources(except the secret) for elekto in https://github.com/kubernetes/k8s.io/tree/main/apps.

**Comment by spiffxp** [comment]
As a github admin, I've made a kubernetes org-owned OAuth app for elekto

**Comment by spiffxp** [comment]
We now have elekto deploying successfully... as to whether it's functioning as expected, TBD

**Comment by jberkus** [comment]
So according to logs, Elekto is running, but I'm still getting a 404 when I try to reach it via elections.k8s.io.

**Comment by ameukam** [comment]
> So according to logs, Elekto is running, but I'm still getting a 404 when I try to reach it via elections.k8s.io.
> 
> ```
> [pid: 47|app: 0|req: 99/156] 35.191.10.98 () {28 vars in 315 bytes} [Thu Sep 23 22:37:13 2021] GET / => generated 214 bytes in 1 msecs (HTTP/1.1 302) 5 headers in 269 bytes (1 switches on core 0)
> [pid: 47|app: 0|req: 100/157] 35.191.2.12 () {28 vars in 312 bytes} [Thu Sep 23 22:37:13 2021] GET / => generated 214 bytes in 1 msecs (HTTP/1.1 302) 5 headers in 269 bytes (1 switches on core 0)
> [pid: 47|app: 0|req: 101/158] 35.191.10.104 () {28 vars in 315 bytes} [Thu Sep 23 22:37:13 2021] GET / => generated 214 bytes in 1 msecs (HTTP/1.1 302) 5 headers in 269 bytes (1 switches on core 0)
> ```

GKE have the health checks for applications before the Ingress is available: https://cloud.google.com/kubernetes-engine/docs/concepts/ingress#health_checks and expect a HTTP 200 code. 

Currently Elekto returns instead a HTTP 301. Another endpoint can be defined to check the readiness of the pod ?

**Comment by jberkus** [comment]
Yeah, lemme see about adding that.

**Comment by jberkus** [comment]
So I've added a /health endpoint and configured it in the deployment.  Does anything need to go into the ingress.yaml to have it check /health instead of /?

**Comment by jberkus** [comment]
Added the custom health check, Ingress still doesn't want to forward connections.  Help?

**Comment by jberkus** [comment]
Problem appears to be resolved.  Elekto is live.  Closing!

**Comment by ameukam** [comment]
> Problem appears to be resolved. Elekto is live. Closing!

I manually recreated the ingress.
