### ISSUE TITLE
Resources for PRR survey analysis

### ISSUE THREAD

**Issue by johnbelamaric** [kubernetes/k8s.io#2619]
The PRR team does an annual survey to help track the effectiveness of prod readiness reviews. The 2020 survey was the first one, and I just did the analysis using BigQuery and a report with Data Studio (another Google product) in one of my Google projects. But as we went to do the analysis this year, I found I wasn't able to share the data set with other PRR members, and David Eads is the one working on it this year.

Can we get a project or at least a data set where we can share queries / data sets / data studio reports?

The team is here: https://github.com/kubernetes/enhancements/blob/master/OWNERS_ALIASES#L191

**Comment by spiffxp** [comment]
/sig architecture
For PRR

**Comment by spiffxp** [comment]
Bigquery should be easily shareable

We're still trying to figure out what is needed for Data Studio, ref: https://github.com/kubernetes/k8s.io/issues/1590

**Comment by johnbelamaric** [comment]
thanks. for data studio we can share individually for now, I was able to share a report created with my google.com account with David's redhat.com account. so if we can get the project / bigquery access that will unblock us

**Comment by spiffxp** [comment]
/close
Dataset created.  Members of `k8s-infra-prod-readiness@kubernetes.io` have `roles/bigquery.dataOwner` on `kubernetes-public:k8s_prod_readiness`.

Please /reopen if you're having issues with access etc.
