### ISSUE TITLE
Setup k8s.io subdomain for E2E testing in DigitalOcean

### ISSUE THREAD

**Issue by rifelpet** [kubernetes/k8s.io#2651]
There currently exists a test-cncf-aws.k8s.io DNS zone that lives in an AWS account and is used by kOps e2e testing. The records in this zone are ephemeral, with a lifecycle matching an associated prow job. kOps e2e testing uses this zone to validate its management of DNS records.

kOps also uses the CNCF-owned DigitalOcean (DO) account setup by @timoreimann for e2e testing of kOps' DigitalOcean support. Currently these jobs do not use any DNS records and rely on DO-provided IP addresses for access from the prow job.

It would be great if we could create a `test-cncf-do.k8s.io` (or similar) DNS zone in the DO account so that kOps could validate its management of DNS records in DO as well. This would involve having @timoreimann or someone else with access creating the zone in the account, and setting up the necessary records in the k8s.io zone to delegate the subzone to the DO account.

/cc @srikiz @justinsb

**Comment by spiffxp** [comment]
/priority important-longterm
/milestone v1.23
I'm not familiar with whether we manage the AWS domain mentioned here, but I'd be happy to see an equivalent for DO happen

**Comment by srikiz** [comment]
FYI - @timoreimann

**Comment by timoreimann** [comment]
I have created the zone on the DO test account. We should be good to delete to it from k8s.io.

**Comment by srikiz** [comment]
> delete to it fro

@timoreimann - wondering if you mean "delegate" here?

**Comment by timoreimann** [comment]
Oh yeah good catch, I did mean delegate. Blaming it on auto complete. 😅

**Comment by srikiz** [comment]
@rifelpet - Please let me know in case there is something that needs to be done from my end on this. Please suggest whom to reach out to get the needed changes here. 
FYI - @timoreimann @spiffxp

**Comment by ameukam** [comment]
/priority blacklog
/milestone clear

@rifelpet Can we call this done ?

**Comment by rifelpet** [comment]
yes this has been completed
/close
