### ISSUE TITLE
assign ownership of k8s-infra-staging-coredns and k8s-infra-staging-etcd

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/k8s.io#2726]
Broken out from https://github.com/kubernetes/k8s.io/issues/460

These two staging projects are currently special cases.  They do not correspond to artifacts that are directly built from a kubernetes subproject.  Instead, they are staged and released as part of a kubernetes/kubernetes release.

We need to decide which SIG "owns" these groups for the purposes of delegated group approval.

There are a few options:
1. Assign ownership to sig-release, since these groups related to cutting a release of kubernetes/kubernetes
2. Assign ownership to sig-architecture, since they own "what is kubernetes" and these components are shipped as part of it
3. Assign ownership of coredns to sig-network (since they own DNS-related subprojects), and etcd to sig-apimachinery (since they own etcd as the persistence layer of kubernetes)

/sig architecture
/sig api-machinery
/sig release
/sig network
/wg k8s-infra
/area artifacts
/area groups

**Comment by stp-ip** [comment]
For context: For now I mainly check and push the upstream images manually to staging and the promotion to prod is being reviewed by other CoreDNS and Kubernetes Maintainers.

CoreDNS releases are separate from K8s releases and which release/version is being used in a K8s release is handled separately in select sigs.

There is a rough idea on building CoreDNS within a wrapper repo. Currently on (my personal) backlog as I am buried.

**Comment by dims** [comment]
for the longest time, sig-network helped with coredns and sig-apimachinery helped with etcd images. I'd like to keep it that way. (so my choice would be #3)

**Comment by justaugustus** [comment]
cc: @kubernetes/release-engineering

**Comment by justaugustus** [comment]
> for the longest time, sig-network helped with coredns and sig-apimachinery helped with etcd images. I'd like to keep it that way. (so my choice would be #3)

Agreed, primary control should yield to the SIG that the subprojects/external most closely align with.
That said, I would like SIG Release (Release Engineering specifically) to have access to break glass/unblock releases.

There are two other such special cases that immediately come to mind:
- CRI tools
- CNI plugins

**Comment by spiffxp** [comment]
https://github.com/kubernetes/k8s.io/pull/2811 implements option 3
