### ISSUE TITLE
need bigquery.jobs.create permission  in kubernetes-public

### ISSUE THREAD

**Issue by deads2k** [kubernetes/k8s.io#2729]
While working with the PRR survey results (thanks for handling https://github.com/kubernetes/k8s.io/issues/2619), I tried to run come queries and got back an error that says

> Access Denied: Project kubernetes-public: User does not have bigquery.jobs.create permission in project kubernetes-public.

The query I attempted to run is 

```
select 
  concat("select ", string_agg(concat(raw_column_name, " as ", staged_column_name) order by question_number)) 
from 
  kubernetes-public.k8s_prod_readiness.survey_2021Q2_questions
```

This particular on is to use the output to create a new query with better column names, but I'll have others as well.

**Comment by ameukam** [comment]
@deads2k Can you check if the BQ table `survey_2021Q2_questions` is present ? We created the dataset `k8s_prod_readinesss` without tables.

**Comment by deads2k** [comment]
Yes, I created the table by importing a google sheet.  See screenshot.

![Screenshot from 2021-09-16 08-42-14](https://user-images.githubusercontent.com/8225098/133614006-c63bcacd-5e0e-488f-949c-3b1f3a03c225.png)

**Comment by spiffxp** [comment]
/assign
I'll take a look

**Comment by spiffxp** [comment]
Opened https://github.com/kubernetes/k8s.io/pull/2744
