### ISSUE TITLE
Use Googlegroups for fine-grained GKE cluster authz

### ISSUE THREAD

**Issue by ameukam** [kubernetes/k8s.io#275]
We can use the _Google Groups for GKE_ feature to organize accesses to the new GKE clusters. 
As mentioned in the [documenntation](https://cloud.google.com/kubernetes-engine/docs/how-to/role-based-access-control#google-groups-for-gke), we will need a G Suite Google Group named `gke-security-groups@kubernetes.io` and add the necessary groups. 

/assign @spiffxp @thockin 

/wg k8s-infra
/area access

**Comment by dims** [comment]
@ameukam we are using "k8s-infra" prefix for all the mailing lists, Can you please submit a PR against https://github.com/kubernetes/k8s.io/blob/master/groups/groups.yaml ?

**Comment by ameukam** [comment]
@dims I made a PR (#276) with a test mailing list. A requirement mentioned in the doc to consider :

> The group must be named exactly gke-security-groups.

The test group need to be added to `gke-security-groups@kubernetes.io`.

**Comment by dims** [comment]
I believe the main reason for the exact string "gke-security-groups" is for the gcloud command documented there. So we should be ok. Right @thockin ?

```
gcloud beta container clusters create my-cluster \
  --security-group="gke-security-groups@[yourdomain.com]"
```

**Comment by thockin** [comment]
Is this still an open question?  I have not played with this feature (since I don't have a personal gsuite), so I can't say, but honestly "gke-security-groups" sounds better than "k8s-infra-cluster-operators" (as pr #276) to me.  It's a group of groups, not of ops people.

**Comment by spiffxp** [comment]
Opinion fro @cblekcer could we prefer assigning scopes to a user / group at the project level, rather than the use of groups at the cluster level

@thockin is thinking that prevents us from attempting multi-tenancy on a cluster, using rbac and namespaces.

@cblecker unsure if that level of granularity is worth it.. either we trust someone or we don't

Let's start without the granularity, and look at adding granularity as a followup effort

**Comment by thockin** [comment]
I'm OK to start with less granularity, but I'd like to still try it and make sure our clusters are capable of it.

**Comment by dims** [comment]
table this for now while we are looking at terraform

**Comment by thockin** [comment]
This is active now, at least for gcsweb.
