### ISSUE TITLE
Investigate usage of terraform for GCP quotas increase

### ISSUE THREAD

**Issue by ameukam** [kubernetes/k8s.io#2861]
We currently manage GCP services quotas with ClickOps. E.g.:

https://github.com/kubernetes/k8s.io/issues/2225
https://github.com/kubernetes/k8s.io/issues/1703#issuecomment-785427415

We could use the Terraform resource https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/service_usage_consumer_quota_override

/area infra
/area billing
/priority important-longterm

**Comment by spiffxp** [comment]
/close
These are only usable to restrict quotas, not request increases from GCP itself.

These would be used for example if we wanted to request an org-level quota for some resource, and then divide up into quota for children folders/projects.  At the moment I don't see a strict need to do this.
