### ISSUE TITLE
[sig-release] GCS + GCR repos for mocking release workflow

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/k8s.io#292]
In support of this [Releng brainstorm](https://docs.google.com/document/d/1Js_36K51Q6AjEsVUjRBMISTA4D7cnjZmoSkn43_Jmxo/edit), which will soon become KEPs or updates to existing KEPs, I'd like to request a playground so Release Engineering can start to mock the release process end-to-end.

We know we produce:
- binaries
- tarballs
- container images
- rpms
- debs

so it sounds like at the very least, we'd need a GCS bucket and GCR repo.

- SIG Release Chairs would have ownership (hopefully) via IAM
- [Release Engineering personnel](https://github.com/kubernetes/release/blob/master/OWNERS_ALIASES#L8-L24) would have write access (this can happen as a follow-up)
- Service account with write access that we can wire into test-infra for jobs

Naming: `k8s-staging-release`?

I think that covers first steps, but I'm new to GCP, so please steer me in the right direction :)

/cc @kubernetes/sig-release-admins @kubernetes/release-managers @dims @thockin 
/sig release
/area release-eng
/milestone v1.16
/priority important-soon

**Comment by thockin** [comment]
Do you want a staging repo (with associated policies like retention), or do you want something else?  We're in early days, so we could define new concepts if needed.  E.g. a storage playground could be a thing...
