### ISSUE TITLE
Create a prow job that update APISnoop website

### ISSUE THREAD

**Issue by Riaankl** [kubernetes/k8s.io#2920]
#### Why is this needed?
The website apisnoop.cncf.io aims to show the latest test coverage data for kubernetes.  The site displays data from json files stored at https://github.com/cncf/apisnoop/tree/main/resources/coverage.    Currently, these files are generated by manually running a shell script.

We would like to move this operation into a prow job so that the site can be always current without requiring human intervention."

**Comment by Riaankl** [comment]
Added the topic SIG Architecture Agenda for 7 Ocktober 2021 for further discussion

**Comment by johnbelamaric** [comment]
+1 from me. This is used only for conformance so it makes sense for us to own that.

@dims @derekwaynecarr

**Comment by dims** [comment]
+1 from me.

**Comment by Riaankl** [comment]
/remove-lifecycle stale
This is still important. Should get attention soon.

**Comment by Riaankl** [comment]
This have been completed. 
And run @ Scheduler updater on 12:00 Saturdays [#565](https://github.com/cncf/apisnoop/pull/565)

https://github.com/cncf/apisnoop/runs/6925855983?check_suite_focus=true
