### ISSUE TITLE
failure when re-casting a ballot in the 2021 Steering election

### ISSUE THREAD

**Issue by bridgetkromhout** [kubernetes/k8s.io#2955]
I noticed an issue with elekto. (I originally opened it in test-infra but am moving it upon discussion with @jberkus.)

**What happened**:

I noticed a typo "Only the 4 favorite `chocies` will win the election." on https://elections.k8s.io/app/elections/2021/vote so I attempted to re-vote so I could copy/paste the exact typo and report it.

It seems like attempting to re-vote not only fails but it is also is wiping out my first vote without warning me that happens.

**What you expected to happen**:

I expected to be able to re-vote. I also expected my original vote to be saved if a re-vote attempt didn't complete.

**How to reproduce it (as minimally and precisely as possible)**:

First I go to https://elections.k8s.io/app/elections/2021. I have a "Vote" button at the bottom of the page.

![image](https://user-images.githubusercontent.com/2104453/137818075-e6f9795e-1828-49da-a284-61c7d993a050.png)

After saving my vote with a passphrase, I get success.
![image](https://user-images.githubusercontent.com/2104453/137818862-564837fe-b587-4dc0-b601-afc6fdb977e3.png)

I return to https://elections.k8s.io/app/elections/2021, enter that passphrase, and attempt to re-cast ballot.

![image](https://user-images.githubusercontent.com/2104453/137818951-d1f2dbb7-816b-4d7c-8756-fafd7891bd56.png)

It takes a while to load and finally I get a 502.

![image](https://user-images.githubusercontent.com/2104453/137818967-b38a7244-3fa4-4374-a15c-a41dc4f06714.png)

When I return to https://elections.k8s.io/app/elections/2021, I have a "Vote" button at the bottom of the page as if I have not yet voted.

**Please provide links to example occurrences, if any**:

Screenshots provided above.

**Anything else we need to know?**:

Might want to adjust the re-vote button in the short term so that people are warned that even attempting and failing to re-vote will wipe out their original vote. That doesn't seem to be an expected behavior.

**Comment by jberkus** [comment]
@ameukam @spiffxp 

This is happening consistently whenever anyone attempts to re-vote.

It does not happen in elekto when I run the tests on a test server, nor does it happen on the Knative election server.  Thus it's something that's happening only in the instance deployed on k8s.io.

Further, the pod shows no errors for the event, of any kind.

Notably the code does a Redirect as part of the re-casting:

```
    F.flash('The old ballot is sucessfully deleted, please re-cast the ballot.')
    return F.redirect(F.url_for('elections_voting_page', eid=eid))
```

I'm wondering if that redirect being blocked by Ingress somehow? That would be consistent with the error, which is a 502 error in the browser, but no corresponding error in the pod.

**Comment by jberkus** [comment]
Oh, sorry that was unclear.  The 502 happens when entering a *correct* password.  The original ballot gets deleted, and the next step is the redirect to voting again.  That's where the 502 happens.

I don't see how that would take over 30s

**Comment by jberkus** [comment]
Issue cause diagnosed:  https://github.com/elekto-io/elekto/issues/49
