### ISSUE TITLE
Create issue template for staging repo request

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/k8s.io#298]
/assign @cblecker 

ref: https://groups.google.com/forum/#!topic/kubernetes-dev/ZqdjjDIAISY

**Comment by nikhita** [comment]
Is this still needed? Looks like folks are successfully creating PRs directly using https://github.com/kubernetes/k8s.io/tree/master/k8s.gcr.io#creating-staging-repos? :woman_shrugging:
