### ISSUE TITLE
Infra turnup:  Whoever creates the project is listed as Owner

### ISSUE THREAD

**Issue by thockin** [kubernetes/k8s.io#299]
E.g. @dims created k8s-release-test-prod and is now an owner as his individual ID.

We should probably require (automatically via the scripts) that individuals remove themselves unless they are org-inherited.

**Comment by spiffxp** [comment]
Going to remove myself from all of the e2e projects via: https://github.com/kubernetes/k8s.io/pull/1722

A longer term fix would be to have `ensure_project` be smart about this.  And maybe find a blanket way of enforcing that `user:foo` bindings should not exist at the project level or below

**Comment by spiffxp** [comment]
- https://github.com/kubernetes/k8s.io/pull/1859#issuecomment-814364589 - took care of all k8s-infra-e2e-* projects
- https://github.com/kubernetes/k8s.io/pull/1859#issuecomment-814430035 - took care of all k8s-staging-* projects
