### ISSUE TITLE
Pilot container-image-promoter promotion process with cluster-api

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/k8s.io#300]
/assign @detiber 
/cc @dims @listx @amy 

refs:
- https://kubernetes.slack.com/archives/CCK68P2Q2/p1562778773325500?thread_ts=1562776843.324300&cid=CCK68P2Q2
- https://github.com/kubernetes/k8s.io/issues/157#issuecomment-510131578

/area artifacts

**Comment by listx** [comment]
@detiber I think you can just add a new entry in https://github.com/kubernetes/k8s.io/blob/master/k8s.gcr.io/k8s-staging-cluster-api/manifest.yaml once you push up your first image to gcr.io/k8s-staging-cluster-api.

**Comment by detiber** [comment]
@listx I believe I'm currently blocked on https://github.com/kubernetes-sigs/k8s-container-image-promoter/issues/71

**Comment by detiber** [comment]
/reopen

hit an issue with the promotion process during the `post-k8sio-cip` job: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/post-k8sio-cip/1149377755071123456

**Comment by listx** [comment]
It succeeded upon a simple rerun: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/post-k8sio-cip/1149395751097339904. Pasting my slack comments:

```
listx  [13 minutes ago]
ok so rerunning it made it succeed. so either (1) there is a race condition in the ReadRepository code (probably not likely) or (2) there was an error with the stdout stream from GCR which made the json decoder choke (because that's what the trace said). i wonder if we can log the stdout if possible before we send it off to the json decoder (it's a library function). will add as an issue

listx  [12 minutes ago]
at least if we log the stdout before processing it, we'll be able to debug it better in the future
```

**Comment by detiber** [comment]
Closing, since the promotion process has been successfully run.
/close
