### ISSUE TITLE
elections.k8s.io needs an http -> https redirect.

### ISSUE THREAD

**Issue by mauilion** [kubernetes/k8s.io#3005]
When reminding folks to vote on elections.k8s.io I noticed that following an http link gets me a google 404 page while https://elections.k8s.io works fine. 

/cc @jberkus

**Comment by jberkus** [comment]
@ameukam any idea what's going on here?

**Comment by ameukam** [comment]
I don't currently allow HTTP traffic for elections.k8s.io. I'll add the needed configuration to redirect from HTTP to HTTPS.

**Comment by ameukam** [comment]
Confirms the redirection is working: 

```shell
http -h http://elections.k8s.io
HTTP/1.1 301 Moved Permanently
Cache-Control: private
Content-Length: 222
Content-Type: text/html; charset=UTF-8
Date: Tue, 02 Nov 2021 13:45:15 GMT
Location: https://elections.k8s.io/
Referrer-Policy: no-referrer
```

**Comment by jberkus** [comment]
Confirmed from this end.  Thanks!
