### ISSUE TITLE
k8s.io: deployment nginx image is 5 years old

### ISSUE THREAD

**Issue by imjasonh** [kubernetes/k8s.io#3131]
https://github.com/kubernetes/k8s.io/blob/931f2c727215c77523170d97d5aa0d1551f1d8bc/apps/k8s-io/deployment.yaml#L37

It seems fairly easy to update -- `nginx:1.20-alpine` is the current `:stable-alpine` as of today -- but I wanted to file an issue first in case there was a better/slower way to roll it out, if it's load-bearing.

**Comment by ameukam** [comment]
I planned to do this after 1.23 is out.

/assign

/milestone v1.24
/priority important-longterm
/area infra
/area apps/k8s.io

**Comment by imjasonh** [comment]
I'd be happy to help with this if there's anything I can do. I don't know about how the website is deployed from these configs, but I can send a PR to update the image in the config to latest nginx stable ([`1.22-alpine`](https://hub.docker.com/_/nginx)) at least.

Trivy says `1.10-alpine` has 8 critical vulns and 14 high, compared to `1.22-alpine` which has 0/0.

**Comment by ameukam** [comment]
> I'd be happy to help with this if there's anything I can do. I don't know about how the website is deployed from these configs, but I can send a PR to update the image in the config to latest nginx stable ([`1.22-alpine`](https://hub.docker.com/_/nginx)) at least.
> 
> Trivy says `1.10-alpine` has 8 critical vulns and 14 high, compared to `1.22-alpine` which has 0/0.

I prepared the rollout for this but never merged it: https://github.com/kubernetes/k8s.io/pull/3258. I'll update to match the 1.22 version

**Comment by ameukam** [comment]
I think we can close this. 
/close
