### ISSUE TITLE
GCP Org Admin

### ISSUE THREAD

**Issue by cblecker** [kubernetes/k8s.io#314]
I know we have @thockin and some CNCF folks as GCP org admins for kubernetes.io. We should ensure have at least one or two more.

@dims and/or @spiffxp may already be one. We should confirm and document. If we need additional (based on who we have and the coverage we have), I would be happy to volunteer to be a key holder too.

**Comment by cblecker** [comment]
It looks like @idvoretskyi is one too :)

**Comment by justaugustus** [comment]
Would be happy to be a keyholder as well. :)

**Comment by spiffxp** [comment]
I know as far as GSuite goes `kubernetes.io` is solely under the purview of the steering committee: https://github.com/kubernetes/steering#top-level-accounts

We have three members with access (I am one), in addition to @idvoretskyi  as a CNCF representative.

**Comment by cblecker** [comment]
This is being controlled here:
https://github.com/kubernetes/k8s.io/blob/51503ac970a5be71d446e80ffe8d36c817bb387b/groups/groups.yaml#L64-L71
