### ISSUE TITLE
k8s.io redirector should document itself

### ISSUE THREAD

**Issue by verb** [kubernetes/k8s.io#340]
I can never remember the short links. There should be a short link for listing the short links, something like https://go.k8s.io/help or a bare https://go.k8s.io/.

It would probably be easiest to just link to https://github.com/kubernetes/k8s.io/tree/master/k8s.io

I'm willing to do this work, just opening this issue for coordination and feedback.

**Comment by bartsmykla** [comment]
Hi @verb. I like the idea, do you still want to do it? :-)

**Comment by verb** [comment]
Hi @bartsmykla, I've had trouble finding time to do this, so a few days ago I resolved to add this to the list of good first issues... which I've also had trouble finding time to do. 😀 

Are you interested in taking this over?

**Comment by bartsmykla** [comment]
I'm doing some research for issues which we can quickly implement and close. I'm gonna create PR soon :-)

**Comment by bartsmykla** [comment]
Done
