### ISSUE TITLE
GKE clusters are not updating

### ISSUE THREAD

**Issue by ameukam** [kubernetes/k8s.io#3459]
According to GKE release notes: https://cloud.google.com/kubernetes-engine/docs/release-notes#December_14_2021, Automatic node upgrades were halted from GKE 1.20 to GKE 1.21. It's suggested to add a `Pod Disruption Budget(PDB)` for kube-system pods: https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#how-to-set-pdbs-to-enable-ca-to-move-kube-system-pods.
Main impact is the loss of metrics from metrics-server.

/sig testing
/kind bug
/area infra
/area prow
/milestone v1.24
priority important-soon

**Comment by ameukam** [comment]
cc @BenTheElder @chaodaiG
For sig-testing part

**Comment by BenTheElder** [comment]
huh? I don't think a PDB is related??

From the link:

https://cloud.google.com/kubernetes-engine/docs/release-notes#December_14_2021

> File capability CAP_NET_BIND_SERVICE required by metrics-server to bind privileged port 443 is dropped in clusters that enable PodSecurityPolicy and use the Ubuntu with Docker container runtime in node pools. As a result, metrics-server fails to bootstrap and autoscaling functionality fails to function. All 1.21 and 1.22 node versions are impacted. This issue will be fixed in a future release. Automatic node upgrades from GKE version 1.20 to 1.21 will be halted until this issue is fixed.


And then a more recent update:

https://cloud.google.com/kubernetes-engine/docs/release-notes#March_09_2022

> The following GKE versions fix a [known issue](https://cloud.google.com/kubernetes-engine/docs/release-notes#December_14_2021) in which the CAP_NET_BIND_SERVICE file capability was dropped from the metrics-server. To fix the issue, upgrade your control plane to any of these versions:
> 
> 1.21.9-gke.1002 and later
> 1.21.10-gke.400 and later
> 1.22.6-gke.300 and later
> 1.22.7-gke.300 and later
> 1.22.7-gke.900 and later
> 1.23.4-gke.300 and later


I think this is fixed.

**Comment by ameukam** [comment]
I triggered a manual update for GKE cluster `prow-build-trusted`: 

```shell
ameukam@cloudshell:~ (kubernetes-public)$ gcloud container operations list --project k8s-infra-prow-build-trusted
NAME: operation-1647283668313-93a18bdf
TYPE: UPGRADE_MASTER
LOCATION: us-central1
TARGET: prow-build-trusted
STATUS_MESSAGE:
STATUS: DONE
START_TIME: 2022-03-14T18:47:48.313385145Z
END_TIME: 2022-03-14T19:12:48.279304652Z
```

We got automated upgrades for GKE cluster `aaa` :

```shell
ameukam@cloudshell:~ (kubernetes-public)$ gcloud container operations list --project kubernetes-public
NAME: operation-1647345543500-a5a8859b
TYPE: UPGRADE_MASTER
LOCATION: us-central1
TARGET: aaa
STATUS_MESSAGE:
STATUS: DONE
START_TIME: 2022-03-15T11:59:03.500541309Z
END_TIME: 2022-03-15T12:23:25.327067625Z
```

and GKE cluster `prow-build`

```shell
ameukam@cloudshell:~ (kubernetes-public)$ gcloud container operations list --project k8s-infra-prow-build
NAME: operation-1647345634813-983015c3
TYPE: UPGRADE_MASTER
LOCATION: us-central1
TARGET: prow-build
STATUS_MESSAGE:
STATUS: DONE
START_TIME: 2022-03-15T12:00:34.813324005Z
END_TIME: 2022-03-15T12:25:40.579061649Z
```

**Comment by dims** [comment]
thanks @ameukam

**Comment by ameukam** [comment]
The clusters stopped to auto-upgrade again. I will take a look
/milestone v1.25
