### ISSUE TITLE
Project Creation Request:  k8s-trust

### ISSUE THREAD

**Issue by puerco** [kubernetes/k8s.io#3461]
## Project Data

<table>
<tr>
<td> Name</td><td>k8s-trust</td>
</tr>
<tr>
  <td>Viewer Access</td>
  <td>k8s-infra-release-viewers@kubernetes.io</td>
</tr>
</table>

/sig release
/sig k8s-infra
/sig security

/assign @ameukam 
/cc @kubernetes/sig-release-leads @kubernetes/release-engineering  

## Purpose of the New Project

As part of [KEP-3031 - Signing Release Artifacts](https://github.com/kubernetes/enhancements/tree/master/keps/sig-release/3031-signing-release-artifacts), SIG Release needs a project to host the cloud resources related to image and file signing.  The resources hosted in the new project will be used during the Kubernetes release process, image promotion, and later during the release processes of the more projects under the Kubernetes org.

The immediate need for the project arises from the image signing flow described in https://github.com/kubernetes/release/issues/2445 (see _Impersonation Flow During Image Promotion_). The promoter service account needs access to the identity service account to issue OIDC tokens to sign the images and later files.

## Cloud Resources

As the TUF delegation of trust for the Kubernetes org is still under development, the final list of resources to be hosted is still changing, but there are some resources that the project needs to create now in order to finish the KEP. Most importantly the project itself and the service accounts required provide identity.

* Service Accounts to provide the identity for image/artifact signing 
* KMS for near-future key storage

## Justification

After some discussions in the recent RelEng meetings, we have determined that hosting the identity service accounts and keys in their own project is the best way to isolate them and also for access control to both to the project and also to the resources themselves.  Protecting access to the service accounts is the most immediate need. The service accounts hosted in the project will provide the identity tied to the signatures of images and artifacts. Our goal is to gate access via IAM policies to the identity service accounts.

Another important factor for having a separate project is that we need that the service accounts allow cross-project impersonation. This involves removing the `iam.disableCrossProjectServiceAccountUsage` constraint to allow principals from other projects to impersonate the new service accounts. Removing the constraint in the dedicated project allows us to scope the change only to it.

**Comment by justaugustus** [comment]
Could we use `k8s-releng-prod` and add the requisite permissions to it instead?

ref: https://github.com/kubernetes/sig-release/blob/master/release-engineering/gcp.md#kms

https://github.com/kubernetes/k8s.io/blob/ab42d92ce9acc9ba18ec33cea7c0c1ee6e6d6587/infra/gcp/bash/ensure-releng.sh#L17-L22

**Comment by puerco** [comment]
Repurposed the signer accounts PR to fit the new plan:  https://github.com/kubernetes/k8s.io/pull/3456

**Comment by puerco** [comment]
Closing now as we will build resources in k8s-releng-prod. Thanks all!
/close
