### ISSUE TITLE
apiVersion: certificates.k8s.io/v1 approving cert but never issuing it.

### ISSUE THREAD

**Issue by nickekstest** [kubernetes/k8s.io#3467]
Result:
`myuser    39m    kubernetes.io/kube-apiserver-client   kubernetes-admin   Approved`

Expected Result:
`myuser    39m    kubernetes.io/kube-apiserver-client   kubernetes-admin   Approved,Issued`

I've tried making the csr a few different ways including:
`cat <<EOF | cfssl genkey - | cfssljson -bare server
{
  "hosts": [
    "my-svc.example.com",
    "my-pod.example.com",
    "192.0.2.24",
    "10.0.34.2"
  ],
  "CN": "system:node:example.com",
  "key": {
    "algo": "ecdsa",
    "size": 256
  },
  "names": [
      {
          "O": "system:nodes"
      }
  ]
}
EOF`

**Comment by ameukam** [comment]
I don't think the issue you described is related to this repo. You'll fine better support in https://github.com/kubernetes/kubernetes.

/close
