### ISSUE TITLE
Request: GCS bucket to store official CVE list

### ISSUE THREAD

**Issue by PushkarJ** [kubernetes/k8s.io#3494]
In support of KEP-3203: https://github.com/kubernetes/enhancements/pull/3204

We need GCS bucket to store generated JSON blob of official CVE list, which needs to be public readable (http get should work)
- The google group this can be linked to for membership is [security-tooling-private@kubernetes.io](https://github.com/kubernetes/k8s.io/blob/931fb0523b0d64b7e04c4ae019d961e139eec44d/groups/sig-security/groups.yaml#L2)
- We will also need a service account with credentials that we can use to write to bucket

Reference PR I have seen that does something very similar is https://github.com/kubernetes/k8s.io/pull/2570

/sig security k8s-infra docs testing

**Comment by ameukam** [comment]
Sorry for not taking care of this now. The main effort is focused on 1.24 out in 2 weeks. I'll get back when 1.25 start.

/milestone v1.25

**Comment by ameukam** [comment]
> @ameukam Any updates on this issue ?

@nehaLohia27 Sorry. I didn't have the bandwidth to take care of this. Should be take care before end of the milestone.

**Comment by PushkarJ** [comment]
@ameukam (when you are back) This is part of https://github.com/kubernetes/enhancements/issues/3203 tracked for v1.25. 

Much of our implementation depends on having this GCS bucket created. What's the best way we can help you get this created?

**Comment by PushkarJ** [comment]
Just confirmed a few things post merge of https://github.com/kubernetes/k8s.io/pull/4009

- A user(me) from security-tooling-private is able to write to the bucket
- View access is public for all
- Anonymous users are not able to write to the bucket and get this error `ServiceException: 401 Anonymous caller does not have storage.objects.create access to the Google Cloud Storage object.`

So I think it is safe to close this one!!

Thank you for your help in implementing this @ameukam 
/close
