### ISSUE TITLE
Setting up storage space under CNCF/AWS account for pushing K8s Artifacts from registry.k8s.io to

### ISSUE THREAD

**Issue by Riaankl** [kubernetes/k8s.io#3541]
We need input on best way to regionalize this storage cost-effectively so we can know where to implement the 302
Is there an agreed upon naming scheme?
For copies of container images we always use immutable tags (we only redirect blob requests… by design immutable)
We are just substituting the host currently
Do we have a bucket per region?
OR do we hand off to AWS at top level?
Should Cloudfront used? Ted can come in and advise

**Comment by hh** [comment]
Closing in favour of https://github.com/kubernetes/k8s.io/issues/3568
/close
