### ISSUE TITLE
Auto deploy for archeo in staging to registry-sandbox.k8s.io

### ISSUE THREAD

**Issue by BobyMCbobs** [kubernetes/k8s.io#3577]
The image for archeo is already being built with CloudBuild, [here](https://github.com/kubernetes-sigs/oci-proxy/blob/main/cloudbuild.yaml). Next an auto deployment needs to be set up for any changes that take place in the repo

Ref: https://www.youtube.com/watch?v=Lrui9QURMys&t=2406s

**Comment by BobyMCbobs** [comment]
registry-sandbox was brought up using Terrafrom in k8s.io
https://github.com/kubernetes/k8s.io/blob/4df04a7cc54ed3b25eeae53e2f2a7d5fd7defb38/infra/gcp/terraform/k8s-infra-oci-proxy/oci-proxy-sandbox.tf

**Comment by BobyMCbobs** [comment]
A CloudBuild trigger might need to be set up
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloudbuild_trigger

**Comment by BobyMCbobs** [comment]
Manual builds, very nice
https://cloud.google.com/build/docs/deploying-builds/deploy-cloud-run

**Comment by hh** [comment]
Caleb is iterating on https://github.com/kubernetes/k8s.io/issues/3577

**Comment by BobyMCbobs** [comment]
Created the PR https://github.com/kubernetes-sigs/oci-proxy/pull/40

It is possible that CloudBuild service account doesn't have sufficient role/run.admin perms

**Comment by BobyMCbobs** [comment]
It appears that a postsubmit might be needed to initiate the deploy

**Comment by hh** [comment]
During the #sig-k8s-infra meeting on 14th of April we noted some corrections we need to take.

Caleb made a comment.

**Comment by BobyMCbobs** [comment]
The service account related requirements are located over here
https://github.com/kubernetes-sigs/oci-proxy/issues/41

These updates I'm not sure if they're done in k/k8s.io or if I'm able to perform them.

**Comment by BenTheElder** [comment]
done in https://github.com/kubernetes/k8s.io/pull/3663
/close
