### ISSUE TITLE
BOSKOS sometimes fails to be recreated

### ISSUE THREAD

**Issue by ameukam** [kubernetes/k8s.io#3600]
# Description

The Boskos instance running inside the community-owned GKE build clusters sometimes fails to get recreated after rescheduling.

This is seems to be related to a `containerd` bug present in the current version we are currently using.

```shell
ameukam@cloudshell:~ (k8s-infra-prow-build)$ kubectl --context gke_k8s-infra-prow-build_us-central1_prow-build get nodes gke-prow-build-pool5-2021092812495606-3a8095df-5p77 -o jsonpath='{.status.nodeInfo.containerRuntimeVersion}'
containerd://1.4.3
```

Initial finding: https://github.com/kubernetes/kubernetes/issues/107561
`containerd` issue: https://github.com/containerd/containerd/issues/4604

Fix merged in `containerd` 1.6: https://github.com/containerd/containerd/pull/6478 and backported in 1.5.

# Possible solutions

## Long term

- Upgrade the GKE clusters to match the version of `containerd` containing the fix.
The fix seems be in `1.22-x.gke-.y`. (still looking for the exact version)
- Add a new nodepool either with bigger disks or boot disks with SSD

## Short term
- add a restart policy at the podSpec for boskos

# Rapid Mitigation 
In case the incident occurs again, delete the boskos pod

- Requirements
Access to the build clusters only accessible to:

https://github.com/kubernetes/k8s.io/blob/b4fed55b4fdffb0077903f548fceb0e31d06d024/groups/sig-testing/groups.yaml#L208-L224

- open Cloud Shell https://shell.cloud.google.com
- get the credentials for the build cluster:

```shell
gcloud container clusters get-credentials prow-build --region us-central1 --project k8s-infra-prow-build
```

Locate the boskos pod:

```shell
kubectl --context gke_k8s-infra-prow-build_us-central1_prow-build get pods -n test-pods -l app=boskos
NAME                      READY   STATUS    RESTARTS   AGE
boskos-54b6b94f76-z26ml   1/1     Running   0          45m
```

Delete the pod:

```shell
kubectl --context gke_k8s-infra-prow-build_us-central1_prow-build delete pod boskos-54b6b94f76-7v4xw -n test-pods
```

/area prow
/area infra
/priority important-soon
/milestone v1.24

**Comment by dims** [comment]
```
kubectl --context gke_k8s-infra-prow-build_us-central1_prow-build -n test-pods -l app=boskos get pods 
kubectl --context gke_k8s-infra-prow-build_us-central1_prow-build  -n test-pods get pods -o yaml
watch -n 1 kubectl --context gke_k8s-infra-prow-build_us-central1_prow-build get pods -n test-pods -l app=boskos

PODID=boskos-FILL_ME_XYZ

kubectl --context gke_k8s-infra-prow-build_us-central1_prow-build -n test-pods describe pods/$PODID
kubectl --context gke_k8s-infra-prow-build_us-central1_prow-build -n test-pods logs -f $PODID
kubectl --context gke_k8s-infra-prow-build_us-central1_prow-build -n test-pods delete pods/$PODID
```

**Comment by ameukam** [comment]
`boskos-reaper` was also affected by the bug. The `boskos-reaper` pod was stuck in `ContainerCreating`. 

<img width="1483" alt="image" src="https://user-images.githubusercontent.com/2343515/162417935-be26c1de-603d-4482-a0fa-22dd82968cc9.png">

Direct consequence is the lack of cleaning of GCP resources by boskos.

<img width="1708" alt="image" src="https://user-images.githubusercontent.com/2343515/162418223-126df3de-b490-4937-85d2-788f67c4d646.png">

The resources accumulating over time, it was not possible for the tests to pick up resources.

> W0408 03:21:44.813] 2022/04/08 03:21:44 main.go:331: Something went wrong: failed to prepare test environment: --provider=gce boskos failed to acquire project: resources not found

I recreated the `boskos-reaper` pod. 

```shell
ameukam@cloudshell:~ (k8s-infra-oci-proxy-prod)$ kubectl --context gke_k8s-infra-prow-build_us-central1_prow-build get pods -l app=boskos-reaper -n test-pods
NAME                             READY   STATUS    RESTARTS   AGE
boskos-reaper-7b54fdbb8d-8jzb2   1/1     Running   0          86m
```

Cleanup as be done:

<img width="1647" alt="image" src="https://user-images.githubusercontent.com/2343515/162419372-6bcb5025-2ca3-438c-861a-af001d6fd80b.png">

I'll try to monitor this over the incoming week-end.

**Comment by ameukam** [comment]
No incidents until now. Let's keep it under the radar. Long term solution is impactful for the build clusters

/milestone v1.25
/priority important-longterm

**Comment by ameukam** [comment]
No incidents reported until now. The GKE clusters have upgrade to a 1.5 containerd version.

I'll considered this as solved.
/close
