### ISSUE TITLE
build sandbox infrastructure for images-layers

### ISSUE THREAD

**Issue by ameukam** [kubernetes/k8s.io#3620]
Part of:
  - https://github.com/kubernetes/k8s.io/issues/3568
  
# Context

Build a development environment to explore AWS S3 capabilities in order to achieve goals defined in the [design doc](https://docs.google.com/document/d/1yNQ7DaDE5LbDJf9ku82YtlKZK0tcg5Wpk9L72-x2S2k/)

See: https://github.com/kubernetes/k8s.io/wiki/New-Registry-url-for-Kubernetes-(registry.k8s.io)

## Implementation
  
 Reuse the account created in https://github.com/cncf/credits/issues/1 as a sandbox environment image layers promotion to AWS.

Required:

- [X] Create a S3 bucket for testing
   - [X] The bucket already exists and a full sync was already done. I need to recreate the bucket to respect naming convention and do a full copy again.
   - [X] Ensure the bucket is world-readable
   - [X] Allow only HTTPs connections to the bucket
- ~[X] Give access to @jaypipes and @kubernetes/release-engineering and associate them `AWSS3FullAccess` policy.~

Non-Required:
- ~Enable [AWS Config](https://docs.aws.amazon.com/config/latest/developerguide/WhatIsConfig.html)  (experimental purpose)~
- ~Enable [AWS Cloudtrail](https://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-user-guide.html)  (experimental purpose)~
- ~Enable [AWS GuardDuty](https://docs.aws.amazon.com/guardduty/latest/ug/what-is-guardduty.html)  (experimental purpose)~
- ~Ensure access logs is enabled for the bucket (experimental purpose)~
- ~Ensure versioning is enabled (experimental purpose)~
- ~Ensure a notification is send when a object is deleted (experimental purpose)~

Update:

This AWS account is for this infrastructure is temporary and will be replaced. In the meantime. The HCL code for it will be in https://github.com/kubernetes/k8s.io/tree/main/infra/aws/terraform. 

/assign @ameukam
/sig release
/sig k8s-infra
/kind feature
/area artifacts
/priority important-soon
/milestone v1.24

**Comment by ameukam** [comment]
cc @jhoblitt @BobyMCbobs

**Comment by ameukam** [comment]
cc @sftim

**Comment by sftim** [comment]
What information can we add to this issue to make it easier for a newcomer to help?

**Comment by ameukam** [comment]
> What information can we add to this issue to make it easier for a newcomer to help?

I think we need to provide more context about what we are trying achieve. I updated the description. But this issue is targeted for individuals with good knowledge of AWS.

**Comment by sftim** [comment]
To clarify: can we help someone who is confident in AWS, but new to the infrastructure SIG?

**Comment by ameukam** [comment]
> To clarify: can we help someone who is confident in AWS, but new to the infrastructure SIG?

@sftim short answer: Yes. How to onboard can be defined over time. For AWS, I would say the only requirement is knowledge of the [HCL](https://www.terraform.io/language/syntax/configuration) but it's not a strong requirement.

**Comment by ameukam** [comment]
> > Give access to @jaypipes and https://github.com/orgs/kubernetes/teams/release-engineering and associate them `AWSS3FullAccess` policy.
> 
> Is `AWSS3FullAccess` the right policy to grant? I'd expect to have a role that is allowed to run Terraform to deploy buckets, and another role that is allowed to add and remove objects.

The main intent is to provide an environment with some autonomy for the contributors to implement the tooling needed to achieve the goal defined in https://github.com/kubernetes-sigs/promo-tools/issues/533. I'm open to different propositions.

**Comment by BobyMCbobs** [comment]
@ameukam, I believe we've got an account for the buckets for registry.k8s.io; can this issue be closed?

**Comment by ameukam** [comment]
> @ameukam, I believe we've got an account for the buckets for registry.k8s.io; can this issue be closed?

Yes. The AWS account provided for this issue is still used for `registry-sandbox.k8s.io`.

/close
