### ISSUE TITLE
sync blobs from k8s.gcr.io to AWS S3 buckets

### ISSUE THREAD

**Issue by hh** [kubernetes/k8s.io#3623]
Production buckets have been created in https://github.com/kubernetes/k8s.io/issues/3595.

Ideally ensure the blobs from k8s.gcr.io are replicated to those buckets.

**Comment by ameukam** [comment]
/retitle sync blobs from k8s.gcr.io to AWS S3 buckets

**Comment by BenTheElder** [comment]
see also https://github.com/kubernetes/k8s.io/issues/3666 "bulk sync existing image layers to these s3 layers as a starting point (from GCS/GCR)"

**Comment by BobyMCbobs** [comment]
Depends on https://github.com/cncf-infra/aws-infra/issues/4

**Comment by ameukam** [comment]
> From the sig-k8s-infra meeting from 6th/7th:
> 
> @ameukam asks: how will the registry.k8s.io S3 buckets stay synced back up?
> 
>     * differential sync?
> 
>     * full sync?
> 
>     * promo-tools does it?
> 
> 
> is it necessary?

@BobyMCbobs I think we need that until proper tooling is built to handle what I'm suggesting properly. We want to be sure the buckets are fully synced before we start to use the image promotion process to push container blobs from GCR/AR to the S3 buckets. I suggest a full sync for the S3 buckets if we don't find a smart and better approach to this. According to https://rclone.org/commands/rclone_sync/ `rclone sync` should be able to handle this scenario. 
I also want to add that the current GCS buckets have over 105300 (small?) objects so we may encounter possible issues (timeouts, etc...) during the initial sync.

**Comment by Riaankl** [comment]
Update on the bucket sync!
After a day of syncing and adding some looping to stop it from timing out the bucket s3://prod-registry-k8s-io-us-east-2 is now pulled across.
Currently trying to bring in the rest of the buckets
https://kubernetes.slack.com/archives/CCK68P2Q2/p1657169494211579

**Comment by BobyMCbobs** [comment]
> @BobyMCbobs Can we get the credentials(access key, secret key) for the user created in [cncf-infra/aws-infra#12](https://github.com/cncf-infra/aws-infra/pull/12) ?

@ameukam, sure. How may I best provide the creds?

**Comment by ameukam** [comment]
@BobyMCbobs you can PM the AWS credentials on slack.

**Comment by Riaankl** [comment]
Bucket created and synced
/close
