### ISSUE TITLE
bulk sync existing image layers to these s3 layers as a starting point (from GCS/GCR)

### ISSUE THREAD

**Issue by Riaankl** [kubernetes/k8s.io#3666]
Creating this draft based on https://github.com/kubernetes/k8s.io/wiki/New-Registry-url-for-Kubernetes-(registry.k8s.io)#what-exactly-are-you-doing

We will bulk sync existing image layers to these s3 layers as a starting point (from GCS/GCR)

Also from our April 13th meeting: https://github.com/kubernetes/k8s.io/issues/3595#issuecomment-1098462663

We should do a one sync copy from GCS to S3... 10 buckets is going to take a while.

If we do the one sync, then later use the mirror to push these options. It's going to be easier, as we already have a copy of the source of truth over s3 so we don't waste time.
@dims >

We already have one is a single s3 bucket, we just need to copy to one.
We need to create one bucket and copy to the s3 bucket.

@arnaud > There is one permission to be added to do the once off sync

**Comment by Riaankl** [comment]
/assign @jaypipes 
Converted draft into an issue.

**Comment by ameukam** [comment]
/sig k8s-infra
/priority backlog
/milestone v1.25

Ref: https://github.com/kubernetes/k8s.io/issues/3595

**Comment by Riaankl** [comment]
data sync complete
Thank you @jaypipes @BobyMCbobs
