### ISSUE TITLE
GCP project for testing cluster-api-provider-gcp 

### ISSUE THREAD

**Issue by dims** [kubernetes/k8s.io#374]
We recently added:
https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/174

and follow up work is in:
https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/175/files

We basically need a GCP project for running this e2e/conformance test that stands up a k8s cluster using cluster-api-provider-gcp. We need a service account with Editor access as well for this to work. We have the basics ready in those PR(s) above, already tested by hand against personal GCP project.

cc @vincepri @detiber

**Comment by BenTheElder** [comment]
is there a reason this won't work with one of the existing boskos GCP project pools?

**Comment by vincepri** [comment]
@dims correct me if I'm wrong, but I think during testing we used one of the boskos GCP projects and we were lacking some permissions to run Cluster API

**Comment by BenTheElder** [comment]
hmm well not having boskos (or something comparable) manage the project(s) is an anti-pattern for CI in any case ...

**Comment by cblecker** [comment]
I agree, relying on a single project for this sounds like the wrong approach compared to checking out a boskos project.

**Comment by dims** [comment]
@BenTheElder @cblecker i am already using script to pull a boskos project :) (copied stuff from the AWS folks). problem is that the service account i am getting does not have enough permissions

please see the ci job run in:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/sigs.k8s.io_cluster-api-provider-gcp/175/pull-cluster-api-provider-gcp-make-conformance/1176520341170688005/

**Comment by dims** [comment]
see checkin/checkout python scripts in https://github.com/kubernetes-sigs/cluster-api-provider-gcp/tree/master/hack (adapted from the AWS use case)

**Comment by dims** [comment]
the boskos currently gives me just the name of the project to use when i check out ... it does not have a provision to give me a new service account with the permissions i need

**Comment by cblecker** [comment]
from those logs, it looks like gcloud is pointing at the wrong project? it's targetting `k8s-prow-builds` rather than a boskos project

**Comment by dims** [comment]
@cblecker ignore the gcloud commands at the tail end ... search for `kubernetes-jenkins-pull` that's the one we are using for running the cluster. will fix the gcloud cleanup lines shortly

**Comment by cblecker** [comment]
I don't see where you're actually checking out a boskos project there.

From a pull-kubernetes-e2e-gce log:
```
W0925 18:43:02.640] Run: ('kubetest', '--dump=/workspace/_artifacts', '--gcp-service-account=/etc/service-account/service-account.json', '--build=bazel', '--stage=gs://kubernetes-release-pull/ci/pull-kubernetes-e2e-gce', '--up', '--down', '--test', '--provider=gce', '--cluster=e2e-0f69e818d8-674b9', '--gcp-network=e2e-0f69e818d8-674b9', '--extract=local', '--gcp-node-image=gci', '--gcp-zone=us-west1-b', '--ginkgo-parallel=30', '--runtime-config=batch/v2alpha1=true', '--test_args=--ginkgo.skip=\\[Slow\\]|\\[Serial\\]|\\[Disruptive\\]|\\[Flaky\\]|\\[Feature:.+\\] --minStartupPods=8', '--timeout=80m')
W0925 18:43:02.651] 2019/09/25 18:43:02 main.go:332: Limiting testing to 1h20m0s
W0925 18:43:02.652] 2019/09/25 18:43:02 main.go:725: --gcp-project is missing, trying to fetch a project from boskos.
W0925 18:43:02.652] (for local runs please set --gcp-project to your dev project)
W0925 18:43:02.653] 2019/09/25 18:43:02 main.go:737: provider gce, will acquire project type gce-project from boskos
W0925 18:46:37.279] 2019/09/25 18:46:37 process.go:153: Running: gcloud config set project k8s-gce-gci-1-6-mstr-ctl-skew
W0925 18:46:38.194] Updated property [core/project].
W0925 18:46:38.690] 2019/09/25 18:46:38 process.go:155: Step 'gcloud config set project k8s-gce-gci-1-6-mstr-ctl-skew' finished in 1.412122746s
W0925 18:46:38.691] 2019/09/25 18:46:38 process.go:153: Running: gcloud auth activate-service-account --key-file=/etc/service-account/service-account.json
W0925 18:46:39.552] Activated service account credentials for: [pr-kubekins@kubernetes-jenkins-pull.iam.gserviceaccount.com]
W0925 18:46:39.622] 2019/09/25 18:46:39 process.go:155: Step 'gcloud auth activate-service-account --key-file=/etc/service-account/service-account.json' finished in 931.198559ms
W0925 18:46:39.622] 2019/09/25 18:46:39 main.go:781: Checking existing of GCP ssh keys...
W0925 18:46:39.623] 2019/09/25 18:46:39 main.go:791: Checking presence of public key in k8s-gce-gci-1-6-mstr-ctl-skew
W0925 18:46:39.623] 2019/09/25 18:46:39 process.go:153: Running: gcloud compute --project=k8s-gce-gci-1-6-mstr-ctl-skew project-info describe
W0925 18:46:41.431] 2019/09/25 18:46:41 process.go:155: Step 'gcloud compute --project=k8s-gce-gci-1-6-mstr-ctl-skew project-info describe' finished in 1.8090441s
W0925 18:46:41.432] 2019/09/25 18:46:41 process.go:153: Running: make -C /go/src/k8s.io/kubernetes bazel-release
```

**Comment by dims** [comment]
looks like i missed a step (default the boskos host URL):
https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/175/commits/c5d085a8b818bfa81a871e18e2a4d615617a5678

trying again

**Comment by timothysc** [comment]
Looks like things moving, let me know if you need anything from me.

**Comment by BenTheElder** [comment]
> the boskos currently gives me just the name of the project to use when i check out ... it does not have a provision to give me a new service account with the permissions i need

the existing service account in the job pod should have access to the boskos projects :sweat_smile:

**Comment by dims** [comment]
looks like i had the resource type wrong ... setting resource-type to `gce-project` got me `k8s-jkns-e2e-gce-alpha` ... will kick the tires and reopen this if needed.

thanks @BenTheElder @Katharine @timothysc @cblecker

**Comment by BenTheElder** [comment]
Great, thanks all!

**Comment by BenTheElder** [comment]
FWIW the boskos projects should be moved to the CNCF / k8s-infra, but that's probably much more involved.

**Comment by dims** [comment]
@BenTheElder 💯
