### ISSUE TITLE
create backup GCR for gcr.io/k8s-artifacts-prod

### ISSUE THREAD

**Issue by listx** [kubernetes/k8s.io#375]
This backup GCR is necessary for copying images (as backups) from `gcr.io/k8s-artifacts-prod`. The name `gcr.io/k8s-artifacts-prod-backup` should be used as the `-backup` suffix is probably the simplest way to name it.

/assign @thockin

**Comment by thockin** [comment]
Do we need a cip-test-prod-backup also for testing backup?

**Comment by thockin** [comment]
PTAL at #375

**Comment by listx** [comment]
So upon some more reflection, I have 2 thoughts on this:

(1) I don't think testing the backup is necessary (it's a lot of engineering effort for little gain). This is because in a real life situation the actual disaster recovery process would more or less be a 1-line `gcrane cp -r <backup_gcr> <prod_gcr>` by a human with write access.

(2) I can't deny that there is merit in testing if `gcrane` itself is actually viable as a backup tool, and so if we do want to test that, yes we do need a cip-test-prod-backup as well.

**Comment by thockin** [comment]
(1) LOL, disagree :)

If you don't test it, it is broken.

**Comment by listx** [comment]
Some more thoughts on disaster recovery/backups, regardless of the above discussion: I think it's much more important/interesting to have regular audits of what's in prod vs what's in the manifests (and probably what's in the backups too). This is independent of the backup tool we end up using (whether we use `gcrane` or the promoter itself to perform copies from prod to the backup repo).

> (1) LOL, disagree :)
> 
> If you don't test it, it is broken.

Well I mean assuming we have regular backups, which are audited (constantly checked for consistency), we essentially will have 2 GCRs full of an identical set of images. IOW most of the engineering value will be in the creation of the backups and how we check them for consistency. Actually doing the copy of all images from the backup to prod just isn't that interesting.

I am going to wager that you're insisting we test the backup tool (`gcrane` in this case) because it is nowhere near as well-tested as, for example, the `cp` command from GNU coreutils?

**Comment by thockin** [comment]
Test the backup tool.  Test the audit tool.  Set up known-bad situations
and ensure it fails, etc.  Standard unit test stuff, but e2e.

**Comment by listx** [comment]
ACK
