### ISSUE TITLE
Put gcsweb behind ingress and install a TLS cert for it

### ISSUE THREAD

**Issue by ixdy** [kubernetes/k8s.io#38]
Should be pretty straightforward. It seems like using ingress has the best Let's Encrypt automation support.

**Comment by ixdy** [comment]
The submit-queue has been using kube-lego for a while, and it seems to be working fine, even though it's not for "production use".

It seems like the simplest option, and is probably easily extensible to the rest of the k8s.io services.

**Comment by thockin** [comment]
ACK

**Comment by ixdy** [comment]
kube-lego is deprecated; cert-manager is the endorsed replacement.

**Comment by munnerz** [comment]
If someone wants to point me to where the definitions for gcsweb live, and if this is still something that needs doing, I'd be happy to open a PR!

**Comment by munnerz** [comment]
d'oh. just spotted `/gcsweb.k8s.io`...

Presumably the cluster that's being deployed into is not already running cert-manager, and presumably we want to use GCLB ingress (i.e. `ingress-gce`) for this? 😄

**Comment by thockin** [comment]
James,

Presumably true, so far. :)

**Comment by ixdy** [comment]
cc @hh @justinsb 

This is probably a good first step - if we get TLS automation working for gcsweb, then the k8s.io redirector site should be an easy extension from there.

**Comment by ixdy** [comment]
Neither gcsweb nor the k8s.io redirector is running behind ingress, so that's the 0th step.

After that we can set up TLS automation.

**Comment by thockin** [comment]
GCSweb should be easy since it has only one hostname.  The redirector is
the fugly one.

**Comment by ixdy** [comment]
We should also put slack.k8s.io behind TLS.

**Comment by thockin** [comment]
Also true.

**Comment by thockin** [comment]
https://github.com/kubernetes/k8s.io/pull/180 - put gcsweb behind ingress

**Comment by thockin** [comment]
As far as I can tell the ingress part of gcsweb is done.  Simple recipe to follow for slack (when ready).

Now for the TLS part :)

**Comment by ixdy** [comment]
I played around with cert-manager a bit this evening, got it working on my own deployment: https://gcsweb.ixdyland.net/gcs/kubernetes-jenkins/

Should be pretty easy to deploy this for the "real" gcsweb as well as the k8s.io redirector.

Only issue with putting the k8s.io redirector behind a GCLB Ingress is that I'm not sure we can do http -> https upgrades.

**Comment by ixdy** [comment]
OK, it's possible to force http -> https upgrades by inspecting the `X-Forwarded-Proto` header.

Example of its use in gcsweb: https://github.com/kubernetes/test-infra/pull/11176

**Comment by ixdy** [comment]
not yet deployed

**Comment by ixdy** [comment]
This is now deployed; gcsweb is running behind an ingress with https, and it auto-upgrades itself from http -> https.
