### ISSUE TITLE
Need a new hack/ verify script that validates project name length

### ISSUE THREAD

**Issue by dims** [kubernetes/k8s.io#3836]
From https://cloud.google.com/resource-manager/docs/creating-managing-projects we have the following restrictions:
```
Project ID requirements:

Must be 6 to 30 characters in length.
Can only contain lowercase letters, numbers, and hyphens.
Must start with a letter.
Cannot end with a hyphen.
Cannot be in use or previously used; this includes deleted projects.
Cannot contain restricted strings, such as google and ssl.
```

For example the following project name is invalid `k8s-staging-cloud-provider-openstack`:
https://github.com/kubernetes/k8s.io/blob/343320108a89136fd4cad92b1dda6765d251dffe/infra/gcp/infra.yaml#L274

So we need a shellscript that uses `yq` to enumerate the projects in the `/infra/gcp/infra.yaml` file and ensures that each project is between `6 to 30 characters in length`.

**Comment by ameukam** [comment]
@Priyankasaggu11929 are we consider this as done ?

**Comment by Priyankasaggu11929** [comment]
yes @ameukam :)

**Comment by ameukam** [comment]
@Priyankasaggu11929 Thanks!

/sig k8s-infra
/milestone v1.25
/close
