### ISSUE TITLE
continuous promotion to k8s.gcr.io

### ISSUE THREAD

**Issue by listx** [kubernetes/k8s.io#387]
Today the promoter promotes new images in the k8s.gcr.io folder on a postsubmit job (right when an image promotion PR is merged).

I propose an alternate model (more expensive in terms of network churn, but more robust/secure):

1. continuously promote what's in master HEAD to prod (make the promoter run periodically every 5 minutes)
2. delete postsubmit job

Advantages:
- If a postsubmit fails for network reasons (maybe Prow is down or something), we don't have to poke Prow admins to restart the failed job for us, because the periodic will kick in quickly enough.
- The continuous promotion can act as a sort of "self-healing" process, as it will run as often as possible (every X minutes, not hours, like the ci-k8sio-cip which currently runs daily). This is arguably more secure than only running the promoter on new PR merges, because for example if some external process mutates tags, the next (continuous) promotion run would reinstate the intent of the promoter manifests.
- Because there is now only 1 Prow job that performs the promotion, there are no race conditions for things like running an audit check (an independent job that performs an audit can race against a PR merge postsubmit that starts during the audit job itself). We would simply make the continuous promotion process additionally perform an audit check afterwards (because auditing is important for security posture).

Disadvantages:
- We might saturate GCR API call quotas. So it should run in a separate IP (just a guess, not sure how GCR detects needy clients). Maybe this means needing to have a dedicated Prow cluster for this to not affect other jobs already on it.

/cc @thockin @justinsb

**Comment by cblecker** [comment]
How long does the promoter job take?

**Comment by listx** [comment]
The last promotion took around 2 minutes (https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/post-k8sio-cip/1179452108047388672 --- Prow says it took over 3 minutes but if you look at the timestamp of our logs it took less time, because I guess Prow counts total job length). Yesterday's CI run (nothing to promote) took 28s (https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-k8sio-cip/1179842936750215168). With thousands of images, the logic to read all images will take longer, but assuming there are no throttling issues, it would take just a few minutes (for comparison, running the `-snapshot` flag against gcr.io/google-containers takes maybe 10 seconds or so from my local desktop).

**Comment by cblecker** [comment]
What about moving the CI job to every 30 or 60 minutes, but maintain the "on PR merge" job?

The CI job itself is the self heal, but I like changes happening instantly~ when PRs merge, and not have to wait for a job to trigger.

**Comment by listx** [comment]
That is certainly possible, but I think waiting 2 extra minutes (or whatever) for the merge to take effect is not a big cost at all (it's going to take longer and longer anyway with the increasing number of images). I'd rather have to maintain just 1 job rather than 2 separate ones, as it also reduces complications around running audit logic (added this as a 3rd bullet point for "Advantages" in my original post). The solace of knowing that there can only be 1 Prow job in the world at a time (guaranteed) to be writing into prod at any given time makes auditing much saner (auditing = just checking that all images in prod are accounted for in the promoter manifests --- i.e., NO spooky actions happening!).

Also, keep in mind that it's not like if we have a dedicated postsubmit for PR merges, the promotion is guaranteed to take <5 minutes or something like that --- it all depends on GCR throttling anyway.

Another thing: it would be much better to just have a continuous promotion run also send Slack notifications for newly-promoted images, so that as a developer you don't have to hit F5 refresh on a Prow job or GCR web UI to see if your image has been promoted. (Er, actually it appears this can be done with Cloud Functions in GCP, because you would make GCR's Pub/Sub events just trigger a Cloud Function written in Go, hmm).

**Comment by listx** [comment]
On further discussion with @thockin offline, I will hold off on making the change suggested in this issue, mainly because there is "bigger fish to fry" so to speak, with the bigger fish being: detection of changes to GCR based on Pub/Sub events #394.
