### ISSUE TITLE
Add list support to registry.k8s.io S3 buckets

### ISSUE THREAD

**Issue by BobyMCbobs** [kubernetes/k8s.io#3935]
From the July 6th/7th k8s-infra meeting.

It might be useful to support listing of the blobs for these buckets.

/assign

**Comment by ameukam** [comment]
The main intent is to replicate the existing behavior from the GCS buckets. e.g. 

```bash
❯ gsutil ls gs://us.artifacts.k8s-artifacts-prod.appspot.com
gs://us.artifacts.k8s-artifacts-prod.appspot.com/containers/
❯ gsutil ls gs://us.artifacts.k8s-artifacts-prod.appspot.com/containers
gs://us.artifacts.k8s-artifacts-prod.appspot.com/containers/images/
```

**Comment by BobyMCbobs** [comment]
Depends on https://github.com/cncf-infra/aws-infra/pull/10
