### ISSUE TITLE
event-based GCR auditing on inventory content changes

### ISSUE THREAD

**Issue by listx** [kubernetes/k8s.io#394]
Even if there is a continuous promotion job as described in https://github.com/kubernetes/k8s.io/issues/387, it could be the case that between the start of such a job and the end of it, a nefarious image could be uploaded there and then deleted. Such sneaky behaviors are hard to detect with plain promotions. Instead we need an event-based trigger on changes to GCR as they happen.

At the very least we could have a GCP Cloud Function that runs an audit every time an image is modified (created/uploaded/deleted). It would be better if we could course-correct (e.g., re-promote) offending images if they don't line up with the intent in the Promoter manifests in this GIt repository.

I will investigate a minimal implementation of this idea (let's call it the event-based auditing system) and update this issue.

**Comment by thockin** [comment]
A cloud function or even just a job that runs in our GKE clusters that examines the state of the world and sends an alert if needed.

**Comment by listx** [comment]
I think I will go with the first option, but I listed out pros/cons of each option below. The further you go down, the more "service-oriented" it gets.

*Please* chime in if my understanding of what the Cloud Function implementation would look like is inaccurate.

# Cloud Function
## Pros
- serverless (no infra needed)
- easy to consume GCR pub/sub events
## Cons
- can't re-run promoter easily (execution environment is not that flexible); a hacky way to run the promoter from a Cloud Function is to use the Cloud Build API to invoke a build that has a promoter image as a stage
- code would probably live in a separate (new) Go project

# Cloud Run
## Pros
- serverless (no infra needed)
- the auditing logic could be added already to the existing promoter source code
## Cons
- extra HTTP baggage needs to be added because Cloud Run only runs HTTP-servicing applications

# Louhi Microservice
*NOTE: [Louhi](https://www.youtube.com/watch?v=_azoxefUs_Y&t=7s) is a release orchestration tool that runs on Kubernetes as a set of microservices. There could be a promoter microservice that handles promotions in a service-oriented manner (e.g., there are REST endpoints for authenticated/authorized users to trigger for performing promotions). This same service could listen to GCR pub/sub events and run audits. Essentially this is taking the Cloud Run approach but instead of putting in a thin (almost place-holder-like) HTTP service layer, it would enrich it with more meaningful endpoints.
## Pros
- more development flexibility (easier for contributors to use the REST endpoints as a base for further abstractions)
- can keep track the state of multiple GCRs simultaneously
- as it is a service, we can always query about the "state" of GCR(s) in real-time (no need to kick off a Prow job, etc.)
## Cons
- not serverless
- hardest option to implement (need a *lot* more code)
- Louhi is not open-source yet, so the implementation would have to run inside a private Kubernetes cluster

# Cloud Function (alerting only, no course-correcting)
We could as another alternative only have alerting and defer the "fix" (re-running the promoter) to a human or other thing. Then the Cloud Function only has to check if the added/deleted image fits with the intent of the promoter manifests, and complain to Slack if there is a mismatch/surprise.

**Comment by listx** [comment]
I moved most of the content of my last comment into this public doc: https://docs.google.com/document/d/1LElgTfYB8ZdTsbmESk7Q1lhLaiHVXENwoEL-MHaFwNQ/edit?usp=sharing

**Comment by listx** [comment]
There is a wip branch here https://github.com/listx/k8s-container-image-promoter/blob/cloudrun/lib/auditserver/server.go#L54. The overall idea is:

(1) make the promoter run as an HTTP server (as a flag)
(2) using Cloud Run, intercept PubSub events from GCR and push them over HTTP using https://cloud.google.com/run/docs/events/pubsub-push
(3) for every event, update the known state of HEAD of master branch of https://github.com/kubernetes/k8s.io/tree/master/k8s.gcr.io using https://github.com/listx/k8s-container-image-promoter/blob/cloudrun/lib/auditserver/server.go#L54 and do a delta between the known state of these manifests vs what the pubsub event json payload is telling us about GCR's state change.

At that point, we know whether the event is good or bad (we can audit!) and send a slack message or something (run some business logic) to perform the alerting.

**Comment by listx** [comment]
Here's another summary of the flow:

1. GCR changes state (e.g., image is pushed)
2. GCR sends Pub/Sub notification to a TOPIC
3. A CloudRun-compatible version of the promoter (acting as a service) gets sent an HTTP request with the contents of the Pub/Sub message
4. The promoter-service pulls contents of the latest GitHub master branch of the official promoter manifests
5. The promoter-service compares the contents of the Pub/Sub message against the promoter manifests
6.  If OK, nothing happens (or maybe an OK message is sent)
7. If not OK, a new Pub/Sub message is sent to an "ERRORS" pub/sub topic
8. a Google Cloud Function consumes messages from "ERRORS" topic and posts them to slack

I am working on implementing parts 1-7. @bartsmykla can help with step 8.

**Comment by listx** [comment]
I've got steps 1-7 working in my own project, using a new feature of the promoter to run as an "auditor". I need to now add an e2e test that will run on every change to the auditing code to:

1. build/push a new image of the auditor
2. deploy the auditor to a test project (this has already been created as `k8s-gcr-audit-test-prod`) as a Cloud Run instance (it will use the default creds as per https://cloud.google.com/run/docs/securing/service-identity)
3. create/delete some images in the test project
4. check that the auditor created new pubsub messages in the "cip-auditor-rejected" and "cip-auditor-verified" topics (the auditor will essentially act as a filter for all GCR state changes, and qualify them as either passing or not passing muster, by republishing them to the topics mentioned above)
5. clean up the resources used by the test environment

Step 0 is creating the PR that adds the auditor logic itself, which I plan to do today.

**Comment by listx** [comment]
@bartsmykla On further thinking --- I believe re-publishing to "rejected" and "verified" topics might not be necessary at all. Stackdriver on GCP can be configured to consume log messages (which we already "publish" in a sense to Stackdriver) from the Cloud Run application directly. https://cloud.google.com/monitoring/alerts/

@thockin I think step #4 could possibly be simplified by just using the Stackdriver stuff natively (since it already has visibility of application logs). It would arguably be more robust as well because we don't have to worry about re-publishing messages to custom topics. Wdyt?

**Comment by listx** [comment]
Update: apparently you can make GCP auto-create new pubsub messages from existing logs by setting up what's called a logging "sink". However, I am still leaning against re-publishing pubsub messages because it feels like unnecessary complexity at this early stage.

**Comment by listx** [comment]
I just learned about https://cloud.google.com/error-reporting/docs/setup/go. It looks like adding a tiny bit of code will get us error reporting (alerting!) a lot more easily. As a recap, here are the alternative options for the auditor to report errors:

(1) republish a new pubsub message to a "rejected" topic that houses rejected GCR transactions (state changes GCR that could not be verified) by using the pubsub Go client in our code
(2) republish a new pubsub message to a "rejected" topic, but use a logging [sink](https://cloud.google.com/logging/docs/reference/tools/gcloud-logging) to do it (instead of using the pubsub Go client ourselves)
(3) do not republish pubsub messages --- instead just (a) set up log-based metrics and (b) set up alerting from within Stackdriver Monitoring
(4) (new) use https://cloud.google.com/error-reporting/docs/setup/go to report errors directly to Stackdriver Error Reporting and send alerts

I am leaning more toward the last option number (4), because it seems to be the most tightly-integrated and easy to set up with minimal fuss. (1) and (2) seem like they add unnecessary complexity (more pubsub topics to deal with). I was leaning more toward (3) up until today, but the main issue I have with it is that because it requires converting error logs into a *metric*, the alerting (while it works and I can get an email, etc) automatically goes away as "healthy" after the statistical "count" decreases back to 0. Contrast this with (4), which gives a very nice overview of all the existing alerts and also lets the human user choose whether alerts have been taken care of/dealt with (instead of auto-going away as "OK" or "healthy" as in the case of (3)).

**Comment by spiffxp** [comment]
/area infra/auditing
/area infra/monitoring
/area artifacts
It's unclear to me what our definition of done is here.  Is this still necessary? Do we think we shouldn't call artifact promotion done until we have this?

**Comment by listx** [comment]
This is actually done (we have event-based GCR auditing on inventory changes running now as I type this). OTOH we can open a separate issue about making the alerts get pushed to a slack channel.

**Comment by spiffxp** [comment]
/close
I'm fine deferring alerting to another issue
