### ISSUE TITLE
TODO: delete k8s-nodes SA when "old" dev cluster is finally deleted

### ISSUE THREAD

**Issue by nikhita** [kubernetes/k8s.io#395]
/kind bug

The godeps publishing-bot runs in the `k8s-publishing-bot-godeps` namespace in the `development2` cluster. While trying to redeploy the bot, @sttts and I got the following error after describing the pod in `k8s-publishing-bot-godeps` namespace:

```
Events:
  Type     Reason              Age   From                                             Message
  ----     ------              ----  ----                                             -------
  Normal   Scheduled           2m    default-scheduler                                Successfully assigned k8s-publishing-bot-godeps/publisher-n6jgr to gke-development2-workers-03baa44e-7lvz
  Warning  FailedAttachVolume  1m    attachdetach-controller                          AttachVolume.Attach failed for volume "pvc-b2be4071-e756-11e9-b6d4-42010a8001d3" : googleapi: Error 400: EXTERNAL_RESOURCE_NOT_FOUND - The resource 'k8s-nodes@kubernetes-public.iam.gserviceaccount.com' of type 'serviceAccount' was not found.
  Warning  FailedMount         22s   kubelet, gke-development2-workers-03baa44e-7lvz  Unable to mount volumes for pod "publisher-n6jgr_k8s-publishing-bot-godeps(965b717b-ea93-11e9-b6d4-42010a8001d3)": timeout expired waiting for volumes to attach or mount for pod "k8s-publishing-bot-godeps"/"publisher-n6jgr". list of unmounted volumes=[publisher-gopath]. list of unattached volumes=[munge-config publisher-rules secret-volume repo cache netrc publisher-gopath default-token-vmggj]
```

This error occurred because the `k8s-nodes@kubernetes-public.iam.gserviceaccount.com` service account didn't exist anymore.

Looking at the list of service accounts, it looks like the `k8s-nodes@...` one was deleted and `gke-nodes-aaa@kubernetes-public.iam.gserviceaccount.com` was supposed to be used instead?

This also made sense comparing the current output of `gcloud projects get-iam-policy kubernetes-public` (thanks to @dims!) and the one in https://github.com/kubernetes/k8s.io/issues/207#issuecomment-471018520 - `k8s-nodes@...` was replaced by `gke-nodes-aaa@...`.

To unblock the publishing-bot, @dims restored the old service account. This fixed the issue, but we should look into fixing it the right way instead. :)

/cc @dims @thockin @sttts

**Comment by dims** [comment]
So we tried looking in kubernetes/k8s.io and kubernetes/publishing-bot on where this old service account `k8s-node` was being set and could not find it. So next idea was to see if we could resurrect this account.

- Found this tip:
https://serverfault.com/questions/969289/google-cloud-service-account-not-found
- Found instructions here:
https://cloud.google.com/iam/docs/creating-managing-service-accounts#undeleting_a_service_account
- Look in activity (Search by "Resource Type" set to "Service Account") to find when @thockin deleted the account:
https://console.cloud.google.com/home/activity?project=kubernetes-public&supportedpurview=project
- Picked up the unique id for the service account `projects/-/serviceAccounts/102906005417360612620`
- Ran the following curl command:
`curl -X POST -H "Authorization: Bearer $(gcloud auth print-access-token)" "https://iam.googleapis.com/v1/projects/-/serviceAccounts/102906005417360612620:undelete"`
- Confirmed that the service account was reinstated:
https://console.cloud.google.com/iam-admin/serviceaccounts?project=kubernetes-public&supportedpurview=project

Then requested @nikhita to restart the publishing-bot and it worked fine.

So the question now is : where is this `k8s-node` specified? we should track that down and then delete this service account.

cc @cblecker @thockin (as this service account change happened when we switched to the new TF based cluster)

**Comment by nikhita** [comment]
Fwiw the `gke-nodes-aaa` value is defined here:

https://github.com/kubernetes/k8s.io/blob/295d621ed0f34048037c7ac3133100987442fc0c/infra/gcp/clusters/kubernetes-public/aaa/10-cluster-configuration.tf#L19

**Comment by nikhita** [comment]
> So the question now is : where is this k8s-node specified? we should track that down and then delete this service account.

Found it! :female_detective: 

The `development2` cluster is configured using the `k8s-node` one - can be seen [here](https://console.cloud.google.com/kubernetes/clusters/details/us-central1-b/development2?project=kubernetes-public&tab=details&node_pool_tablesize=10&persistent_volumes_tablesize=50&storage_class_tablesize=50&nodes_tablesize=50) in the `Permissions` section, for those with access.

And `aaa` is configured with `gke-nodes-aaa` - can be seen [here](https://console.cloud.google.com/kubernetes/clusters/details/us-central1/aaa?project=kubernetes-public&tab=details&node_pool_tablesize=10&persistent_volumes_tablesize=50&storage_class_tablesize=50&nodes_tablesize=50).

**Comment by cblecker** [comment]
This sounds like it won't be a problem after we move workloads over

**Comment by thockin** [comment]
Whew!  Thanks for finding that.

**Comment by thockin** [comment]
I will re-title this as a TODO for after dev2 is turned off.

**Comment by spiffxp** [comment]
/remove-lifecycle stale
/assign @thockin @spiffxp 
I think we can do this now

**Comment by spiffxp** [comment]
Should be done when we do https://github.com/kubernetes/k8s.io/issues/785

**Comment by thockin** [comment]
Done
