### ISSUE TITLE
improve security posture of the image promotion process

### ISSUE THREAD

**Issue by listx** [kubernetes/k8s.io#398]
There are several things happening concurrently in this space and I am creating this issue to track them all.

- [x] separate promoter credentials/metadata content from images data [PR](https://github.com/kubernetes-sigs/k8s-container-image-promoter/pull/141)
- [x] event-based GCR auditing of all changes to prod GCR (most likely using Pub/Sub and Cloud Functions) [issue](https://github.com/kubernetes/k8s.io/issues/394), [design doc](https://docs.google.com/document/d/1LElgTfYB8ZdTsbmESk7Q1lhLaiHVXENwoEL-MHaFwNQ/edit?usp=sharing)
  - [ ] write runbook
  - [ ] set up human escalation path (oncall process/paging rules, etc) for alerting against suspicious changes during audits

**Comment by spiffxp** [comment]
What remains to be done here?

**Comment by listx** [comment]
The runbook and formal escalation paths are not defined yet.
