### ISSUE TITLE
Request for help of organizing information for newcommers

### ISSUE THREAD

**Issue by bartsmykla** [kubernetes/k8s.io#403]
Hi everyone!

I have something to confess. I'm lost a little bit. I joined efforts of our working group (k8s-infra) almost a year ago and I don't know at which stage we currently are, and what we want to do next.

I realized that when I decided to put to our incoming on-boarding meeting segment where we will explain what is the state of the world, and what actually is the next thing we plan to do.

I would like to suggest to create one place (some document), which will be our single source of truth, where we'll put every link related to our work, every repository, project or document where new person can find any information or get help. I would also put there information about what we want to achieve, how it will happen, what is the current state of these efforts and what will be the next step.

We have invited new people to join our efforts and we have the responsibility to properly on-board them and give them any help they'll need to become happy, and valuable contributors.

If you agree I'm gonna ask you for a huge favor because I won't be able to do it by myself, and will be very grateful for any help related this.

Initial deadline: Wednesday 23 October 2019

cc. (I'm putting here all regular attendees of our bi-weekly zoom meetings) @BenTheElder @cblecker @dims @hh @idvoretskyi @detiber @justinsb @listx @munnerz @nikhita @spiffxp @stp-ip @thockin @tpepper

**Comment by nikhita** [comment]
> I would like to suggest to create one place (some document)

Should we start with a google doc so that all the folks listed here can add notes about what they work on or are familiar with? We can polish it later and eventually move it to this repo as a markdown file.

**Comment by nikhita** [comment]
And I've mentioned this before, but thank you soooo much for spearheading this and making sure all newcomers have a wonderful onboarding experience!! :raised_hands: :smile: :sparkling_heart:

**Comment by idvoretskyi** [comment]
> Should we start with a google doc so that all the folks listed here can add notes about what they work on or are familiar with? We can polish it later and eventually move it to this repo as a markdown file.

@nikhita big +1 to gdoc!

**Comment by thockin** [comment]
+1.  I have some context, I'll look at and update or file some issues today.
