### ISSUE TITLE
Good first-time-issues

### ISSUE THREAD

**Issue by bartsmykla** [kubernetes/k8s.io#404]
Hi everyone!

We plan to do on-boarding session next week for our newcomers and I think it would be good to prepare some issues/tasks which will be good for people, who joined our wg recently.

Please everyone, think about 1-2 issues which will be good for that purposes, and write if you'll be able to potentially mentor some people who will be interested in picking it up.

Thank you all in advance! :-)

cc. (I'm putting here all regular attendees of our bi-weekly zoom meetings) @BenTheElder @cblecker @dims @hh @idvoretskyi @detiber @justinsb @listx @munnerz @nikhita @spiffxp @stp-ip @thockin @tpepper

**Comment by stretchcloud** [comment]
Brilliant idea. Super pumped up to help and contribute.

**Comment by jakirpatel** [comment]
> Hi everyone!
> 
> We plan to do on-boarding session next week for our newcomers and I think it would be good to prepare some issues/tasks which will be good for people, who joined our wg recently.
> 
> Please everyone, think about 1-2 issues which will be good for that purposes, and write if you'll be able to potentially mentor some people who will be interested in picking it up.
> 
> Thank you all in advance! :-)
> 
> cc. (I'm putting here all regular attendees of our bi-weekly zoom meetings) @BenTheElder @cblecker @dims @hh @idvoretskyi @detiber @justinsb @listx @munnerz @nikhita @spiffxp @stp-ip @thockin @tpepper

Will it be Zoom meeting ? Is there any mailing list to subscribe for this updates or github watching will be okay ?

**Comment by nikhita** [comment]
> Will it be Zoom meeting ? 

Yes, this will be a zoom meeting.

> Is there any mailing list to subscribe for this updates

Yes, you can subscribe to https://groups.google.com/forum/#!forum/kubernetes-wg-k8s-infra.

**Comment by bartsmykla** [comment]
Unfortunately after many discussions with other members of the working group I think it's not possible to simply create that kind of tasks, so I want to propose something else. Because of that I'm gonna close that issue and point everyone who is interested in this topic here: https://github.com/kubernetes/k8s.io/issues/437
