### ISSUE TITLE
Transfer control of `kompose.io`

### ISSUE THREAD

**Issue by tabbysable** [kubernetes/k8s.io#4056]
`kompose.io` is used as a vanity domain for the Kompose documentation. It is hosted via GitHub Pages, and @cdrage maintains the registration and DNS.

For continuity, and to ensure Charlie doesn't have to worry about it personally anymore, let's transfer it to be under control of the project like the other domains are.

**Comment by ameukam** [comment]
@dims Do we need to forward this to CNCF ?

**Comment by dims** [comment]
@ameukam sounds like a service desk ticket is needed. ( cc @mrbobbytables or @cblecker )

**Comment by mrbobbytables** [comment]
@cdrage do you have a preferred email to loop into the CNCF to help coordinate? (will put it in the ticket)
Can also pm me on slack if you'd prefer not to share it on a public GH issue.

**Comment by cdrage** [comment]
@mrbobbytables (sorry, was on PTO for 6 days).

You can find my email on my personal site on my github profile! :)

**Comment by cdrage** [comment]
@mrbobbytables Just waiting on an email to transfer ownership (unsure who to ask?)

**Comment by cdrage** [comment]
@tabbysable ping

**Comment by cblecker** [comment]
Is this still required?

**Comment by cdrage** [comment]
> @tabbysable

Have yet to receive any email 🤷 but happy to transfer the domain whenever!
