### ISSUE TITLE
Continuously sync GCS to S3

### ISSUE THREAD

**Issue by ameukam** [kubernetes/k8s.io#4094]
Follow-up of https://github.com/kubernetes/k8s.io/issues/3666:

We should ensure we Continuously sync the container images blobs for GCS to the AWS S3 buckets used by oci-proxy

**Comment by BobyMCbobs** [comment]
My current progress

https://github.com/kubernetes/k8s.io/pull/3955

**Comment by BobyMCbobs** [comment]
From GCS to one of the S3 buckets may require a ProwJob and/or some GCS bucket specific configuration, if supported.

**Comment by BobyMCbobs** [comment]
Pairing with @upodroid on this tomorrow.

**Comment by Riaankl** [comment]
This have been resolved in :tada: 
https://github.com/kubernetes/k8s.io/pull/4118
https://github.com/kubernetes/k8s.io/pull/4170
https://github.com/kubernetes/k8s.io/pull/4171

/close
