### ISSUE TITLE
Replace slack.k8s.io with redirect

### ISSUE THREAD

**Issue by jberkus** [kubernetes/k8s.io#4099]
Infra,

We need to shut down the app (slackin) currently running at slack.k8s.io, and replace it with a redirect to https://communityinviter.com/apps/kubernetes/community.  It's not clear to me how to do this, particularly with TLS.

Alternately, if that's going to be very painful, we can embed an inviter widget into a simple web page, and run that in the place of Slackin as an app.

What's the best course?

@ameukam @mrbobbytables @cblecker @nikhita

**Comment by BenTheElder** [comment]
we have a redirector service at go.k8s.io (it's an nginx instance + GKE managed TLS certs / loadbalancer, config is in this repo), we could do the same thing here.

**Comment by ameukam** [comment]
To be more specific to what Ben said:

- Ensure `slack.k8s.io` go to `redirect.k8s.io` in the DNS config
- Ensure the nginx instance has the configuration to handle the redirection
- Ensure `slack.k8s.io` is an entry in the k8s.io wildcard certificate instead of a dedicated TLS certificate

**Comment by dims** [comment]
@ameukam one thing i was not sure about was - what to do with https://github.com/kubernetes/k8s.io/blob/c1f58df5705ea21fa55022e9ccf8ba6960116eb2/apps/slack-infra/resources/certificate.yaml#L7-L8

**Comment by dims** [comment]
Also i am not very sure about the steps for deploying https://github.com/kubernetes/k8s.io/pull/4105 - does one of you (@ameukam or @cblecker) want to please deploy?

**Comment by ameukam** [comment]
This is done.

```
❯ http -h https://slack.k8s.io
HTTP/1.1 301 Moved Permanently
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
Content-Length: 162
Content-Type: text/html
Date: Fri, 19 Aug 2022 13:11:35 GMT
Location: https://communityinviter.com/apps/kubernetes/community
Server: nginx
Via: 1.1 google
```

@jberkus can we consider this done ?

**Comment by dims** [comment]
@jberkus here's the set of urls we tested.

```
http://slack.kubernetes.io/  - WORKS
https://slack.kubernetes.io/ - WORKS
http://slack.k8s.io/         - WORKS
https://slack.k8s.io/        - WORKS
```

**Comment by jberkus** [comment]
This looks done.  I'll add removing the slackin app as a follow-up for me.

/close

**Comment by jberkus** [comment]
Follow-up: https://github.com/kubernetes/k8s.io/pull/4112
