### ISSUE TITLE
`registry.k8s.io` Production Readiness/Timelines

### ISSUE THREAD

**Issue by upodroid** [kubernetes/k8s.io#4119]
`registry.k8s.io` is the community owned and managed image registry for the Kubernetes project and it has been running for sometime. 

We need to do the following for it to be ready for production and wider rollout:

1. https://github.com/kubernetes/kubernetes/pull/109938
1. We need to manage the configuration of oci-proxy via Terraform and GitOps. 
1. Upgrade oci-proxy to serve images from AWS. @BobyMCbobs 
    ```
    cy@cloudshell:~ (k8s-infra-oci-proxy-prod)$ gcloud run services list
    ✔
    SERVICE: k8s-infra-oci-proxy-prod-asia-east1
    REGION: asia-east1
    URL: REDACTED
    LAST DEPLOYED BY: ameukam@gmail.com
    LAST DEPLOYED AT: 2022-03-28T07:58:25.682843Z
    ```
1. https://github.com/kubernetes/k8s.io/issues/3976 Configure oci-proxy to serve images from Artifact Registry. From sig-k8s-infra's perspective, AR has all the images from GCR and is autosynced from GCR every 2 hours. Direct Promotion is still being worked on and not a hard requirement for image serving.
1. Work with Google on redirecting `k8s.gcr.io` to `registry.k8s.io`. @BenTheElder 
1. https://github.com/kubernetes-sigs/oci-proxy/issues/97
1. Write a blog post on kubernetes.io, send emails to mailing list, etc

Optional Activities:
- https://github.com/kubernetes-sigs/oci-proxy/issues/94

**Tentative Prod Launch Date: 01/10/2022** I'm looking to get all of this resolved by this date excluding the `k8s.gcr.io` redirect

@ameukam @dims

/sig k8s-infra
/area artifacts

**Comment by BobyMCbobs** [comment]
Putting step two into it's own issue to track it
https://github.com/kubernetes/k8s.io/issues/4123

**Comment by BobyMCbobs** [comment]
registry.k8s.io's code was enabled for S3 serving
https://github.com/kubernetes-sigs/oci-proxy/pull/82
i'm unsure if production has yet been deployed

cc @bentheelder @ameukam

**Comment by ameukam** [comment]
I'm not sure about the intent of the issue but we went in production with the release of 1.25. 
Only Step 5 need some coordination since we don't have clear informations about when It's gonna be done

**Comment by upodroid** [comment]
> I'm not sure about the intent of the issue but we went in production with the release of 1.25.

I see it as more of a soft launch. We are missing everything I listed above that need to be sorted out very soon. prod isn't even serving anything from AWS yet.

**Comment by BenTheElder** [comment]
We're serving from S3 and we're redirecting a small portion of k8s.gcr.io to this with no issues
/close
