### ISSUE TITLE
registry.k8s.io autodeploy

### ISSUE THREAD

**Issue by BobyMCbobs** [kubernetes/k8s.io#4123]
registry.k8s.io (currently at https://github.com/kubernetes-sigs/oci-proxy) production and staging should both be managed in a GitOps way.

Related: https://github.com/kubernetes/k8s.io/issues/4119

**Comment by hh** [comment]
Existing prow jobs:
- https://github.com/kubernetes/test-infra/tree/master/config/jobs/kubernetes/sig-k8s-infra/oci-proxy
- https://github.com/kubernetes/test-infra/blob/master/config/jobs/image-pushing/k8s-staging-infra-tools.yaml#L2

**Comment by BobyMCbobs** [comment]
This must wait until there's the kubernetes/registry.k8s.io repo, for not repeating migration.

**Comment by Riaankl** [comment]
> I guess [kubernetes/registry.k8s.io#76](https://github.com/kubernetes/registry.k8s.io/issues/76) is a dupe.

/remove-lifecycle stale

@BobyMCbobs should we keep this open or can it be closed in favour of [#76](https://github.com/kubernetes/registry.k8s.io/issues/76) ?

**Comment by ameukam** [comment]
/close

As duplicate of https://github.com/kubernetes/registry.k8s.io/issues/76.
