### ISSUE TITLE
registry.k8s.io: S3 buckets metrics  

### ISSUE THREAD

**Issue by ameukam** [kubernetes/k8s.io#4141]
registry.k8s.io will use S3 buckets to distribute container blobs. we should be to get metrics generated by the network. AWS provides those metrics with AWS Cloudwatch.

https://docs.aws.amazon.com/AmazonS3/latest/userguide/metrics-dimensions.html#s3-cloudwatch-metrics

We should focus the scope of the metrics to the production buckets.

/milestone v1.26
/area artifacts
/priority important-longterm

**Comment by ameukam** [comment]
@BobyMCbobs is there a way to access to those metrics outside of the AWS account of the production buckets ?
cc @Riaankl

**Comment by ameukam** [comment]
@sftim pssible to do it using cross-account replication ?

**Comment by BobyMCbobs** [comment]
> @BobyMCbobs is there a way to access to those metrics outside of the AWS account of the production buckets ? cc @Riaankl

@ameukam, I believe some job may need to be set up to scrape the metrics out and places them else where. Otherwise it might be the case for bucket replication through _rclone_. Looking more into it

**Comment by sftim** [comment]
S3 has continuous, managed replication - can we use that?

**Comment by BenTheElder** [comment]
Does the community have *any* visibility into:
- AWS Budget and spend rate
- Which things are costing the most
- Traffic served by s3

I know we privately got traffic data for the GCR stuff, and we have the public data studio billing report that breaks down the usage in GCP, but AFAICT we have nothing for AWS.

**Comment by ameukam** [comment]
> AWS Budget and spend rate
> Which things are costing the most

They should be treated in separated issues since it's about overall cost of the AWS organization (including other projects) vs metrics of a specific service.

**Comment by BobyMCbobs** [comment]
I've tried approaching this several times, currently having a hard time with CloudWatch metrics.

**Comment by josh-ferrell** [comment]
I'm not sure what we're using for metrics scraping and handling now but perhaps the cloudwatch_exporter for prometheus is an option. Here's an example for S3 https://github.com/prometheus/cloudwatch_exporter/blob/master/examples/S3.yml

**Comment by sftim** [comment]
Have a look at https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/Counting404Responses.html

We can do the almost the same thing for 2xx responses, using mostly managed APIs. If we want to copy the counter data into Prometheus we can do that too.

To generate those logs: https://docs.aws.amazon.com/AmazonS3/latest/userguide/ServerLogs.html
Log delivery is best effort and is _not_ real time. There are ways to make sure to log every single request to a bucket, but folks I think wouldn't like 'em.

**Comment by sftim** [comment]
https://docs.aws.amazon.com/AmazonS3/latest/userguide/configure-request-metrics-bucket.html covers turning on CloudWatch metrics for a bucket

**Comment by BenTheElder** [comment]
With the built in dashboards we have some limited visibility into e.g. bandwidth usage and number of objects, but so far we can't tell things like egress vs in-region other than by correlating with the bills.

The bills are the thing we ultimately care about, but there's room for more insight here still
/remove-lifecycle stale
