### ISSUE TITLE
groups: needs unit tests

### ISSUE THREAD

**Issue by cblecker** [kubernetes/k8s.io#420]
The groups management scripts in `groups/` need unit tests.

**Comment by sgmac** [comment]
I was looking into this, but I don't know how to mock the calls to Admin Directory, do you have any suggestion? For instance, I wanted to work on the one below. 

```Go
func removeMembersFromGroup(service *admin.Service, groupEmailId string, members []string) error ```

**Comment by cblecker** [comment]
It probably needs a refactoring of the code to make this viable. Things like the client services refactored into an interface, so a fake client can be mocked.

**Comment by sgmac** [comment]
I would like to work on this, do I require some sort of access to Admin API? At least to test I don't break anything while refactoring. Let me know what you think.

**Comment by cblecker** [comment]
@sgmac I'd love the help! Unfortunately, access to the Admin API is highly privileged. If you open a PR I can work to test any changes with you and confirm they work as expected.

**Comment by sgmac** [comment]
blind coding such a challenge !! The only issue I see here is that 

```Go
srv *admin.Service
```
I'm not very experienced in Go but I took a look  *admin.Service, and has not single method definition but concrete types. 

https://github.com/googleapis/google-api-go-client/blob/master/admin/directory/v1/admin-gen.go#L249

**Comment by mayankkapoor** [comment]
@sgmac  I'm starting to give the refactoring a shot. Let me know if you want to collaborate on this.
@cblecker Any advice is appreciated.

**Comment by sgmac** [comment]
@mayankkapoor looking forward to help, please go ahead and share your branch so I can take a look how you are approaching this.

**Comment by mayankkapoor** [comment]
@sgmac I've opened a PR here: https://github.com/kubernetes/k8s.io/pull/466, and branch is https://github.com/mayankkapoor/k8s.io/tree/refactor-client-services.

**Comment by mayankkapoor** [comment]
@cblecker I'm having trouble creating a fake client for admin.Service. In order to mock/stub admin.Service, I need to create an interface with a function that admin.Service implements. However, there are no exported functions that admin.Service implements. Only `userAgent()` which is not exported. 

E.g. In order to test `func printGroupMembersAndSettings(srv *admin.Service, srv2 *groupssettings.Service)`, I did:

```
type IService interface {
	userAgent() string
}
...
func printGroupMembersAndSettings(srv IService, srv2 *groupssettings.Service) error {
```

I get following error:
```
# k8s.io/k8s.io/groups [k8s.io/k8s.io/groups.test]
./reconcile.go:135: cannot use srv (type *admin.Service) as type IService in argument to printGroupMembersAndSettings:
	*admin.Service does not implement IService (missing userAgent method)
		have admin.userAgent() string
		want userAgent() string
```

I can try and mock the entire admin sdk, with mock structs for Service and Groups, if you think that is the way to go. Let me know what you think.

**Comment by spiffxp** [comment]
/remove-lifecycle rotten

Unit tests would still be nice.  However we're leaning on this enough now that I'm getting concerned about config sprawl.

To help reduce review burden, I think we should encode our conventions / rules as tests.  I got started with https://github.com/kubernetes/k8s.io/pull/925

**Comment by spiffxp** [comment]
/remove-lifecycle stale
/milestone v1.22
Could also try conftest for these

**Comment by spiffxp** [comment]
I re-realized how little test coverage there is here over in https://github.com/kubernetes/k8s.io/issues/460#issuecomment-889337833

I tried to add the tiniest bit of coverage for a new addition to the groups reconciler in https://github.com/kubernetes/k8s.io/pull/2414

**Comment by spiffxp** [comment]
/milestone v1.23
We are looking at shifting a much larger volume of groups management to this tool during the v1.23 release cycle, I would feel a lot better about that if we had test coverage

Loosely I think it involves breaking up into mockable components and testing each piece

**Comment by spiffxp** [comment]
/remove-help
Since @MadhavJivrajani is working on this
