### ISSUE TITLE
GCP UI is clunky for cluster-admins because they can't use the project selector

### ISSUE THREAD

**Issue by thockin** [kubernetes/k8s.io#425]
Crafting a URL that goes straight to a project is OK, but we should probably just give every role ability to use the UI (list projects)

**Comment by thockin** [comment]
Users should be able to list projects now, but I think they still can't list orgs :(

**Comment by bartsmykla** [comment]
Hi @thockin what is the status of it? As I'm part of `k8s-infra-gcp-auditors` group I can lsit projects without problem so I can't check if users can list projects. What is the role for listing organisations?

/assign @thockin

**Comment by thockin** [comment]
at least for people in multiple organizations, you have to somehow list which org you want to list projects from.  Maybe it got better, but it was broken when I filed this.  If it works for you, I am happy to close this :)

**Comment by bartsmykla** [comment]
@thockin sorry, maybe I was not clear asking about role. I meant what IAM Role can it be to list organizations. Do you know maybe?
