### ISSUE TITLE
Create a prow job that scans proposed images against vulnerabilities

### ISSUE THREAD

**Issue by rikatz** [kubernetes/k8s.io#436]
As talked with @listx on Slack:

It would be interesting to have some sort of Prow job that verifies staging images against vulnerabilities, using GCR Container Analysis or some other tool.

Any image trying a 'promotion' might need to be scanned and only promoted if its vulnerability score is lower than some defined threshold.

Also it would be interesting to have some sort of "Allowed CVE List" to bypass well-known false positives.

Edit: maybe related: https://github.com/kubernetes-sigs/k8s-container-image-promoter/issues/144

**Comment by rajibmitra** [comment]
design doc : https://docs.google.com/document/d/1ps_rgQoK9wsRlFUMKBbAsBNzu5rIqZByDuf3P7KpX7s/edit?ts=5e417965

**Comment by listx** [comment]
/remove-lifecycle stale

@yodahekinsew is working on this.

**Comment by rikatz** [comment]
/close

I'm closing this, if this became a problem again I'll open a new discussion

**Comment by rikatz** [comment]
Damn sorry!

I read the wrong issue

/reopen

**Comment by spiffxp** [comment]
/sig release
/area release-eng
/area artifacts
/milestone v1.21
/assign @cpanato @hasheddan 
I think we basically have this now, I will defer to @kubernetes/release-engineering whether this can be closed.  I would consider gating promotion based on vulns to be a followup issue.

**Comment by cpanato** [comment]
We now have this initial page that shows the vulns for the images we published 

https://storage.googleapis.com/k8s-artifacts-prod-vuln-dashboard/dashboard.html

it is not beautiful, but I'm working to make it more "nice" and will open some discussion in RelEng to define the next steps.

/note-myself to add this topic in the RelEng agenda

**Comment by spiffxp** [comment]
@ameukam asked if we still want this service enabled for staging repos during today's k8s infra meeting

**Comment by rikatz** [comment]
I'm not sure. IMO it's really important for us to make sure the images we serve (at least the kubernetes one) does not contain any vulnerable package, but I guess it's worth to discuss with sig-security about this.

For other images, this should be an opt-in.

Maybe we should close this, and think from another perspective: does sig-release wants to scan the generated images? If so, instead of relying on GCP costs, maybe add a prow job that downloads the image and runs trivy or some other image scanner for problems, and break the CI if this happens, triggering an alert to update the image.

@IanColdwater @tabbysable I guess it would be good to have some point of view from security here

**Comment by spiffxp** [comment]
@kubernetes/release-engineering is this part of your v1.22 plans?

**Comment by spiffxp** [comment]
/remove-lifecycle stale
/close
We've disabled vulnerability scanning for now.  Can reopen or recreate this issue when we've been able to give this more thought
