### ISSUE TITLE
Verify new AR repositories match existing GCR Paths

### ISSUE THREAD

**Issue by upodroid** [kubernetes/k8s.io#4367]
We recently started serving images from Artifact Registry and that means that we are adding new registries as Google launches new regions. We should write a test that ensures that as we add new regions, there are no typos in the subproject. We have had a few that snuck in when we migrated to AR and one wasn't caught in time.

Promotions are taking too long today and I don't think there is much appetite in going from 20 to 35 regions. 

/sig k8s-infra
/sig release
/area artifacts
/area release-eng
/priority important-soon

**Comment by BenTheElder** [comment]
xref: #4366 #4298

**Comment by BenTheElder** [comment]
regression test: https://github.com/kubernetes/k8s.io/pull/4368
