### ISSUE TITLE
Place for discussions about sub-groups

### ISSUE THREAD

**Issue by bartsmykla** [kubernetes/k8s.io#437]
During the last week at the on-boarding session for newcomers, there was introduced idea, which can be new for some people. This idea is `sub-groups`.

**So, sub-group?**
About 80 people shown at the on-boarding, I also received a lot of messages from people who couldn't attend the session so we can assume there is at least 100 people, who want to help with efforts of our working group.

Currently it's impossible to create, delegate and oversee issues which we can assign for that amount of people. I think the best idea to solve the problem is to divide our work into sub-groups. Every sub-group will have one mentor (regular attendee from our wg), who will be responsible for coordinating work.

My suggestion is that every two weeks every sub-group would pick one of the newcomers from this group to be the person who will give feedback about the progress of the work, what are the next steps, blocking points etc. at our bi-weekly meetings.

What to expect from the mentor of a sub-group?
You will have to be responsible for a communication inside your group. You can work as you like but my suggestion would be to create a zoom call every week to have everybody in the loop. You can do pair-programming, delegate tasks or something else, it doesn't matter if there will be a good communication with the group.

I want to propose myself as a person who would make sure the things are going forward by poking mentors every week, and also who would be point of contact for our newcomers if they will need any help. I will also ask them for feedback (work, progress etc.) about sub-groups they are working at. If you think I'm not the right person just write here and propose someone else (I won't be offended! :-)!

I would like to set a deadline for the discussions for November 13, 2019 (we have a lot of people eager to start!), and I would expect the result of this discussions to be a document with the list of sub-groups and descriptions for these sub-groups about their responsibility.

I created a document: https://docs.google.com/document/d/1IWxWCMccx2OX6EJWcjD_RVhRjU0qdoNOJ2HM9C5qVFk/ and there are already some propositions from @thockin - let's work with that document.

I also think the best idea will be for every sub-group as a first task to create a document with the state of work, where will be information what actually needs to be done in relations to the sub-group and what's the progress of that efforts.

cc. @BenTheElder @cblecker @detiber @dims @hh @ihor.dvorestkyi @justinsb @listx @munnerz @nikhita @stp @spiffxp @tpepper @thockin

**Comment by thockin** [comment]
Historical context on a more detailed list of efforts.  Somewhat stale, but some good stuff in there:

https://docs.google.com/document/d/1r0nydnBoU7o_L7Hnjdc9SZrWe9zosbz64ZUUPn0XwXk/edit#

**Comment by nielsvbrecht** [comment]
My 2 cents;
My suggestion would be to put 3 and 10 together as migration effort subgroup. 
Also suggest to change 7 to security & auditing, to monitor any issues on that part. 
I'd suggest to put the DNS and redirect subgroup together as they're so closely tied together.
And 10 and 12 seem to be the same?
I think there should be something that covers life cycle management, like at what times do we switch to a new or other version. E.g. the redirector runs on nginx 1.10.3 or something while newer versions are available. It doesn't contain any vulnerabilities afaik, but just to serve as an example when and why would you want to update/upgrade.

**Comment by andrealmar** [comment]
Hi everyone any progress on sub-groups ?

**Comment by listx** [comment]
@bartsmykla Should there be a separate doc that describes the "state of work" and tasks/progress that needs to be completed for each subgroup?

**Comment by bartsmykla** [comment]
These are groups which we want to propose:

- Cluster management (mentor: @thockin)
- Monitoring/alerting/observability (mentor: ?)
- Moving “easy” apps from old clusters to new (thockin)
- Container image serving and management (listx)
- Staging and move towards automation (mentor: ?)
- Non-container artifacts (mentor: @justinsb)
- Auditing (mentor: @hh)
- Billing (mentor: @justinsb)
- Changing shortlink-redirect mechanism (mentor: @stp)
- Moving “harder” apps into community space (mentor: ?)
- DNS (mentor: @thockin)
- Moving CI testing (mentor: ?)
- Moving scale testing (wojtekt)
- Governance (mentor: ?)
- Infrastructure turnup tools (e.g. the scripts) (mentor: ?)

As you can see, not all sub-groups have mentors assigned, so this is a great opportunity for people who have knowledge about this efforts and project, and experience to step up and help us. If you want to be a mentor or suggest anybody as a mentor, please write here!

**Comment by bartsmykla** [comment]
@listx my idea is to give this as a first task for each of subgroups (this kind of document)

**Comment by RiRa12621** [comment]
@bartsmykla What's the idea for a mentor to be doing?

**Comment by bartsmykla** [comment]
@RiRa12621 moving things forwards in relation to sub-groups efforts. I mean deciding how to divide work which sub-group needs to do into smaller chunks and assign it to mentees, or organizing some weekly calls with mentees and doing pair programming, and finding 15 minutes of time every week to give me some report about the progress of work during the week. :-)

**Comment by RiRa12621** [comment]
@bartsmykla Ok cool, happy to do that for the monitoring/alerting/observability subgroup if someone else could assist that knows the current infra a bit better.

**Comment by bartsmykla** [comment]
@RiRa12621 we can discuss it. @thockin @dims @listx @cblecker @tpepper @stp-ip what do you think about it?

**Comment by bartsmykla** [comment]
As a reminder, if you want to join as a mentee to one of the sub-groups, please put your username in table at the bottom of the document: https://docs.google.com/document/d/1IWxWCMccx2OX6EJWcjD_RVhRjU0qdoNOJ2HM9C5qVFk

**Comment by listx** [comment]
> @RiRa12621 we can discuss it. @thockin @dims @listx @cblecker @tpepper @stp-ip what do you think about it?

Maybe it's worth just moving along with the existing subgroups with mentors instead of waiting for the list to get fully populated. /shrug

**Comment by RiRa12621** [comment]
The lists seem pretty full for the most part now already.
Just need to fill up the missing mentors and then we should be good to go except for one or two.
But maybe "let's be agile" and start with the ones that have members and try to fill the missing ones over time.

**Comment by bartsmykla** [comment]
@listx @RiRa12621 just as a reminder from my message here: https://groups.google.com/forum/#!topic/kubernetes-wg-k8s-infra/jv7Ye7GqDoU the idea is to start with efforts of 3 subgroups:

1. Container image serving and management (mentor: @listx)
2. Moving “easy” apps from old clusters to new (mentor: @thockin)
3. Auditing (mentor: @hh)

As a mentors, is it ok for you @listx @thockin @hh?

**Comment by hh** [comment]
Count me in.

**Comment by listx** [comment]
> @listx @RiRa12621 just as a reminder from my message here: https://groups.google.com/forum/#!topic/kubernetes-wg-k8s-infra/jv7Ye7GqDoU the idea is to start with efforts of 3 subgroups:
> 
> 1. Container image serving and management (mentor: @listx)
> 2. Moving “easy” apps from old clusters to new (mentor: @thockin)
> 3. Auditing (mentor: @hh)
> 
> As a mentors, is it ok for you @listx @thockin @hh?

SGTM
