### ISSUE TITLE
Speed up image promotion process

### ISSUE THREAD

**Issue by sbueringer** [kubernetes/k8s.io#4374]
First of all, thank you very much for all the work on the registry and the image promotion process!!

If I understood it correctly, recently the image promotion jobs were changed to sync to additional registries.
This slowed down the `pull-k8sio-cip` and the `post-k8sio-image-promo` and both now take roughly an hour.

Unfortunately, this has the side effect that the release process in projects like Cluster API now takes > 2 hours, while previously it took 10-15 minutes.

I don't really know much about the jobs, but it looks to me like both jobs are scanning the entire registry / all images in the repo which is the reason why it takes over an hour.

Would it be possible to adapt the jobs to only sync the images that were promoted in the current PR / commit?

If necessary, we could still do a periodic full sync with a periodic job.

**Comment by upodroid** [comment]
More details are available at https://github.com/kubernetes-sigs/promo-tools/issues/637

**Comment by saschagrunert** [comment]
We could solve this via https://github.com/kubernetes-sigs/promo-tools/pull/657

**Comment by saschagrunert** [comment]
We still have to cut a new promo tools release and get the new flag being used.

**Comment by spiffxp** [comment]
/reopen
Let's leave this open until we've confirmed the speed up in prod

**Comment by BenTheElder** [comment]
https://github.com/kubernetes-sigs/promo-tools/pull/657 + https://github.com/kubernetes/test-infra/pull/27855 has had lovely results, thank you!

**Comment by saschagrunert** [comment]
I have one more optimization in my mind which I will try out today. Let's leave this issue open until then.

**Comment by sbueringer** [comment]
Thank you very much, this really helps a lot!

Just for my understanding. Did I see correctly that the presubmit job is now very quick but the postsubmit takes ~ the same time?

**Comment by saschagrunert** [comment]
The postsubmit is expeted to take a bit longer, yes. But I think we can still improve both sides by diffing more focused on what needs to be pushed/signed.

**Comment by sbueringer** [comment]
Just took another look. There was one run with 5m and the others >1h. This probably depends on which images are promoted? (https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/post-k8sio-image-promo)

**Comment by saschagrunert** [comment]
> This probably depends on which images are promoted?

Exactly. The official Kubernetes manifest is already huge, so filtering based on the file is not enough. With https://github.com/kubernetes-sigs/promo-tools/pull/661 we now additionally filter based on the digests which should be a significant performance improvement.

**Comment by saschagrunert** [comment]
With https://github.com/kubernetes-sigs/promo-tools/issues/662 we can now close this.

**Comment by spiffxp** [comment]
For reference:

[postsubmit improvement](https://testgrid.k8s.io/sig-k8s-infra-k8sio#post-k8sio-image-promo&graph-metrics=test-duration-minutes&width=20) 
<img width="598" alt="Screen Shot 2022-11-02 at 10 48 07 AM
" src="https://user-images.githubusercontent.com/49258/199563811-b76bb0bb-dd37-4bfb-b97b-996a64f69acf.png">

[presubmit improvement](https://testgrid.k8s.io/sig-k8s-infra-k8sio#pull-k8sio-cip&graph-metrics=test-duration-minutes&width=20)
<img width="868" alt="Screen Shot 2022-11-02 at 10 49 20 AM" src="https://user-images.githubusercontent.com/49258/199564022-39be86cc-8b5d-4cfb-b439-bb42f349c769.png">

**Comment by CecileRobertMichon** [comment]
Thank you!! ❤️ 🎉 👏

**Comment by spiffxp** [comment]
/reopen
ref: https://github.com/kubernetes/k8s.io/pull/4441#issuecomment-1309107480
