### ISSUE TITLE
cs.k8s.io is 502

### ISSUE THREAD

**Issue by jberkus** [kubernetes/k8s.io#4392]
Just noticed that cs.k8s.io is returning Bad Gateway.  Not sure what's wrong there, filing an issue so that we look into it after Kubecon.

**Comment by ameukam** [comment]
We had an issue with the instance hosting it. I think everything is back to normal:

```bash
curl -I https://cs.k8s.io/
HTTP/1.1 200 OK
Server: nginx
Date: Tue, 25 Oct 2022 11:54:05 GMT
Content-Type: text/html; charset=utf-8
Connection: keep-alive
```

**Comment by dims** [comment]
when you see this, you can use `cs-canary.k8s.io`

**Comment by josh-ferrell** [comment]
This is just me being curious, is codesearch availability a priority or something worth having a backlog issue for?

**Comment by ameukam** [comment]
It's a priority for GitHub Admin Team since they have search snippets based on `cs.k8s.io`. e.g. `go.k8s.io/owners/dims`.

**Comment by BenTheElder** [comment]
https://cs.k8s.io/?q=foo&i=nope&files=&excludeFiles=&repos= seems to be working

**Comment by ameukam** [comment]
No issue until now. I'm gonna close this.

/close
