### ISSUE TITLE
give others access to the promoter test projects (for backups, auditing work)

### ISSUE THREAD

**Issue by listx** [kubernetes/k8s.io#444]
See https://github.com/kubernetes-sigs/k8s-container-image-promoter/wiki/Container-Image-Promoter:-The-State-of-Things--Today for a description of the backups and auditing work that needs to be completed.

We need a way to give people access to GCP resources to be able to test things.

I don't fully understand what needs to be done other than editing https://github.com/kubernetes/k8s.io/tree/master/groups. We should start from there.

**Comment by listx** [comment]
At a minimum the people working on the promoter should have `roles/viewer` access for the projects used for backups/auditing.

**Comment by listx** [comment]
The test projects are defined here: https://github.com/kubernetes/k8s.io/blob/6a8b73dde2fe08c2be9f5f512254fb5158a00633/infra/gcp/ensure-prod-storage.sh#L66-L75

**Comment by rajibmitra** [comment]
are we going to create any service account for this ?  @listx

**Comment by thockin** [comment]
@listx is this done now?

**Comment by listx** [comment]
> @listx is this done now?

Yes, because the already-existing group `k8s-infra-artifact-admins` got access to administrate the auditor in https://github.com/kubernetes/k8s.io/pull/571 (this group already had storage admin access to `k8s-artifacts-prod-bak`).

**Comment by listx** [comment]
Oops, sorry, misread this issue. Currently the `k8s-infra-artifact-admins` group has access to administrate both the production instance of the auditor as well as to view/administer the backups in `k8s-artifacts-prod-bak`. However this issue is for the *test* projects. I can create a PR for this now that I understand how groups work in the `infra/gcp` folder of this repo.

**Comment by listx** [comment]
It appears that the existing `ensure-prod-storage.sh` script already empowers everyone in the `k8s-infra-staging-cip-test@kubernetes.io` group to at least Project Viewer access. So it's just a matter of expanding this group.

To start, @rajibmitra can you add yourself to https://github.com/kubernetes/k8s.io/blob/26cd0c9a4f21f2bfe7a60a8582adafe02243116b/groups/groups.yaml#L509-L513 ?

**Comment by rajibmitra** [comment]
Done, thanks @listx  
Here is the PR #576  , let me know if I need to anything else.

**Comment by listx** [comment]
> Done, thanks @listx
> Here is the PR #576 , let me know if I need to do anything else.

Can you now try to see if you can see e.g. the `k8s-staging-cip-test` GCP project on the web console?

**Comment by justaugustus** [comment]
@listx -- It'd be great to get @kubernetes/release-managers at least view access as well.

**Comment by rajibmitra** [comment]
> > Done, thanks @listx
> > Here is the PR #576 , let me know if I need to do anything else.
> 
> Can you now try to see if you can see e.g. the `k8s-staging-cip-test` GCP project on the web console?

Yes , I can see now @listx  
![image](https://user-images.githubusercontent.com/1690251/74898259-65ccc900-53bf-11ea-95a0-dcd0e2a8dcd4.png)

**Comment by spiffxp** [comment]
What needs to be done to close this out?

**Comment by listx** [comment]
> What needs to be done to close this out?

Not much else AFAICS. New access grants should be done in separate PRs/issues.

/close
