### ISSUE TITLE
Running ppc64le arch tests for Kubernetes in CNCF infra

### ISSUE THREAD

**Issue by Pensu** [kubernetes/k8s.io#448]
Hi,

Since k8s infra is now moving from Google owned to CNCF owned, would it be possible to run the tests on other archs than amd64 as well? I am not sure about status of hardware at CNCF, or what hardware we are going to use (would it still be GCP but owned by CNCF or CNCF has their own data center?), but I would like to know if it's possible to provide hardware (talking about ppc64le here), and then run k8s tests there. We have been running the tests for ppc64le internally and posting the results to testgrid, but if it's possible I would like to volunteer for any help/resources to get this done. Thanks.

CC: @bartsmykla

**Comment by dims** [comment]
@Pensu Peeyush, "CNCF owned" currently means credits in various clouds paid for by CNCF. So if we can find a public cloud with support for the architecture then we can do something. No we don't have a data center where we can have any machines, we don't currently have sysadmins either to take care of such needs.

**Comment by Pensu** [comment]
Thanks for the response @dims. So, to understand correctly, if any public cloud has ppc64le machines (not necessarily GCP), we can try to run the k8s test suit for ppc64le there? Just want to clarify that having machines in GCP is not a hard requirement.

**Comment by dims** [comment]
if you can find it, we can try to get credits to run there. it's a long process just so we are clear. for GCP, we are funded for sure right now [1].

[1] https://cloud.google.com/blog/products/gcp/google-cloud-grants-9m-in-credits-for-the-operation-of-the-kubernetes-project

**Comment by Pensu** [comment]
Great, thanks for the inputs @dims. I will check and get back on this.

**Comment by manojnkumar** [comment]
@dims : Do you know whether the GCP credits apply to Power: https://cloud.google.com/blog/products/gcp/ibm-power-systems-now-available-on-google-cloud?

**Comment by dims** [comment]
@manojnkumar these dont seem to be available via the GCP API itself ... so won't work with our CI systems

**Comment by mkumatag** [comment]
> @manojnkumar these dont seem to be available via the GCP API itself ... so won't work with our CI systems

@dims I was thinking of writing a provider for kubetest to create a cluster in the ibm cloud where we already powervm and run the tests. We can discuss more on this when meet, I also see kubetest2 is also created but not sure if we need to choose kubetest vs kubetest2! @cblecker ???

**Comment by mkumatag** [comment]
oops, sorry I tagged cblecker instead of @BenTheElder ^^^

**Comment by dims** [comment]
@mkumatag another pattern we use with AWS is using boskos. We register cloud information with boskos and acquire/release stuff as needed. Example see how we use it in CAPA
- https://github.com/kubernetes/test-infra/tree/master/boskos
- https://cs.k8s.io/?q=boskos&i=nope&files=&repos=kubernetes-sigs/cluster-api-provider-aws

The above stuff works as we just feed the credentials to cluster api and cluster api talks to AWS natively. there are a bunch of scripts there that use AWS credentials too for settings things up and cleaning things.

Another option, Don't do kubetest2, just kubetest is fine for now. kubetest does checkout projects from boskos, but only for GCP. kubetest though has support for other clouds (see eks/azure/kops in https://github.com/kubernetes/test-infra/tree/master/kubetest), so you could add that with support for boskos and that would be another way of integrating

**Comment by mkumatag** [comment]
> @mkumatag another pattern we use with AWS is using boskos. We register cloud information with boskos and acquire/release stuff as needed. Example see how we use it in CAPA
> 
> * https://github.com/kubernetes/test-infra/tree/master/boskos
> * https://cs.k8s.io/?q=boskos&i=nope&files=&repos=kubernetes-sigs/cluster-api-provider-aws
> 
> The above stuff works as we just feed the credentials to cluster api and cluster api talks to AWS natively. there are a bunch of scripts there that use AWS credentials too for settings things up and cleaning things.
> 
> Another option, Don't do kubetest2, just kubetest is fine for now. kubetest does checkout projects from boskos, but only for GCP. kubetest though has support for other clouds (see eks/azure/kops in https://github.com/kubernetes/test-infra/tree/master/kubetest), so you could add that with support for boskos and that would be another way of integrating

@dims Thanks for the information, will explore more on this.

**Comment by BenTheElder** [comment]
kubetest & kubetest2 are both skippable if you want, but you will probably want some sort of program if you plan to use boskos. KIND CI doesn't use either since the resources are local and we can avoid some of the complexity..

If you're going to use one, kubetest is the widely used one, kubetest2 is not in any CI atm and is pretty much a dead effort, I've had to refocus on KIND & some other things...

I will warn that kubetest is a bit of spaghetti code :+)

**Comment by mkumatag** [comment]
> kubetest & kubetest2 are both skippable if you want, but you will probably want some sort of program if you plan to use boskos. KIND CI doesn't use either since the resources are local and we can avoid some of the complexity..
> 
> If you're going to use one, kubetest is the widely used one, kubetest2 is not in any CI atm and is pretty much a dead effort, I've had to refocus on KIND & some other things...
> 
> I will warn that kubetest is a bit of spaghetti code :+)

Thanks for the information, you are right kubetest looks spaghetti. :)

**Comment by bartsmykla** [comment]
@mkumatag what is the progress and your expectations in regards to this issue now? :-)

**Comment by mkumatag** [comment]
> @mkumatag what is the progress and your expectations in regards to this issue now? :-)

so far we haven't started working on this task, the expectation of this task is to enable/add tests for ppc64le platform. Initially, we can run the jobs periodically and later can be included in PR testing.

**Comment by bartsmykla** [comment]
@mkumatag do you think I can help you with anything to move things forward? :-)

**Comment by mkumatag** [comment]
There are issues with the infrastructures atm, we won't be able to contain this work for the next few months.
