### ISSUE TITLE
Create a ServiceAccount for ingress-nginx image pushing

### ISSUE THREAD

**Issue by rikatz** [kubernetes/k8s.io#4587]
More like a discussion / analysis other than a request. On ingress-nginx we heavily rely on cloud-build to do all our 13 images  (yeah, I know, and we plan to reduce it) builds/pushing.

cloud-build is used by us mostly to build the multi architecture image, and then push it to staging repo. 

I have already verified that we can push images to staging repo directly using our own accounts (me, @strongjz , etc) as we are part of the k8s-staging-ingress-nginx group, and I wanted to discuss about moving away this process (which is part of our release process) from Prow to Github Actions.

BTW, we already use github actions a lot on ingress-nginx so there's no news here.

So let's go first for the discussions:
## Pros
* We can shift org expenses from GCP to Github (which we are not charged, as we are opensource project, etc)
* We will have some better control over the build process. I know we can have multiple branches, etc on prow jobs, but for us turned out to be too much "bureaucratic" (in a lack of finding a better word). We need to keep changing branches, build process, images on prow jobs to comply with tagging, variables, etc. I know this is not "that much" work, but still, we can make it easier if we control the whole process
* We can simplify a lot our image build and push process
* We are building some automation for our release process (that is today "complex") and having all the steps done on Github (but the image promotion, that will still be a PR on k8s.io and we don't plan on changing this!) will make stuff much easier

## Cons
* I'm not sure if the image signing will still work
* Is an image built/pushed outside our "trusted cluster" still considered trusted?

Please feel free to fill some more pros/cons above

Now, for the how: based on https://cloud.google.com/container-registry/docs/advanced-authentication we may have a ServiceAccount with the same permissions that our individual accounts have, and as soon as we have a key with this same permissions, we can turn this build/push process something like:
* Build the multiarch image on gh actions
* Log into service account with gcloud auth activate-service-account (key as part of cicd vars)
* Push the image
* logoff

I'm not sure how we can "protect" this key file, and still use it on github actions so this is also open to discussion on how and if we should do that.

**Comment by upodroid** [comment]
The image promotion process is relatively straight forward. The project owners publish an image in their designed staging project (k8s-staging-ingress-nginx) via Cloud Build. They then raise a PR to promote the image from staging to registry.k8s.io which is when the images are signed.

Now, you could have images built by Github Actions and pushed to the GCR Registry in the staging project and follow the existing process today. We would need to create a service account inside the staging project and allow workflows from kubernetes/ingress-nginx repository to assume and use the service account that has write access to GCR.

Google has a great blog on how it works. 

https://cloud.google.com/blog/products/identity-security/enabling-keyless-authentication-from-github-actions

For workflows that need access to GCP, you would add this step first.

```
steps:
- id: 'auth'
  name: 'Authenticate to Google Cloud'
  uses: 'google-github-actions/auth@v0.4.0'
  with:
    workload_identity_provider: 'projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
    service_account: 'my-service-account@my-project.iam.gserviceaccount.com'
```

**Comment by rikatz** [comment]
ok, I love it! So we could just create the serviceaccount but never have it, and use the github action to authenticate and push!

I have added to next sig-k8s-infra to verify how we can do this and if this can be automated.

**Comment by ameukam** [comment]
+1 on giving the capability to subprojects to use Github Actions for image pushing to the staging registry

**Comment by strongjz** [comment]
I believe the image signing is done with the production promotion process @puerco or @cpanato can correct me there. 

So we could build in GHA, push to the staging repo and open a PR to the k8s.io repo. That would be lovely from the release automation perspective.

**Comment by upodroid** [comment]
I'll propose the infra changes next week.

/assign
