### ISSUE TITLE
Cleanup manifests for subprojects that don't promote images to `registry.k8s.io`

### ISSUE THREAD

**Issue by upodroid** [kubernetes/k8s.io#4611]
There are alot of subprojects that have a staging repository but don't actually promote images to registry.k8s.io. It makes adding registries annoying as you have to add registries as we expand our Artifact Registry footprint.

For example, https://github.com/kubernetes/k8s.io/blob/main/k8s.gcr.io/manifests/k8s-staging-test-infra/promoter-manifest.yaml needs to be updated when a new AR mirror is deployed even though https://github.com/kubernetes/k8s.io/blob/main/k8s.gcr.io/images/k8s-staging-test-infra/images.yaml is empty and won't be updated at all.

**Comment by ameukam** [comment]
Some of those projects are only used to store container images that we use in CI and we don't intent to promote.
