### ISSUE TITLE
Add DNS setup to `ensure-main-project.sh`

### ISSUE THREAD

**Issue by thockin** [kubernetes/k8s.io#464]
I started this but have not had time to finish.

```
DNS_GROUP="k8s-infra-dns-admins@kubernetes.io"

color 6 "Enabling the DNS API"
enable_api "${PROJECT}" dns.googleapis.com

color 6 "Empowering ${DNS_GROUP}"
gcloud projects add-iam-policy-binding "${PROJECT}" \
    --member "group:${DNS_GROUP}" \
    --role roles/dns.admin

#FIXME: bootstrap DNS zones
```

**Comment by sgmac** [comment]
I would like to work on this. What are the zones we need to bootstrap?

**Comment by iftachk** [comment]
@sgmac
Let me know if you wanna work on it together
I would like to get some experience with it

**Comment by bartsmykla** [comment]
@sgmac @iftachk I think it would be good to create initial PR with some dummy zone, and ping @thockin in the PR, and also we can discuss the topic on the next community meeting. What do you think? :-)

**Comment by sgmac** [comment]
@bartsmykla  sounds good to me. Don't you think we should merge this first  [WIP: Add DNS setup #465](https://github.com/kubernetes/k8s.io/pull/465/files)?  I can work on that branch as well :)
