### ISSUE TITLE
[Umbrella Issue] AWS Infrastructure for Kubernetes

### ISSUE THREAD

**Issue by ameukam** [kubernetes/k8s.io#4654]
We got 3M of AWS credits for 2023.

We need to setup a new infrastructure that gonna be use for 

- serving artifacts produced by the project
- as part of the test infrastructure.

**Comment by ameukam** [comment]
To start:

-  Ensure we have a trail of activities for the entire organization
- Ensure we establish AWS monthly budgets
- Ensure billing payment informations are updated

**Comment by ameukam** [comment]
cc @sftim

**Comment by ameukam** [comment]
Support of the management account is upgraded to the `Business plan`. 
See https://aws.amazon.com/premiumsupport/plans/business/ for details

**Comment by devarsh10** [comment]
Hey @ameukam, I would like to contribute in this.
As I'm familiar with some of the concepts of aws cloud.

Regards.

**Comment by ameukam** [comment]
@devarsh10 Feel to look at the issues with the label `area/infra/aws`. 

We mainly use [Terraform](https://www.terraform.io/) for the moment to manage our AWS resources.

**Comment by devarsh10** [comment]
Okay.
I'm also little bit familiar with the terraform concepts too.
From terraform init to terraform apply and about its architecture.
So, please let me know if I can contribute.

Regards.

**Comment by RuchiDhal** [comment]
Hello @ameukam, 
I would like to contribute to this.

**Comment by dims** [comment]
/close

it's been a year! we have set up a whole bunch of things :)
