### ISSUE TITLE
Migrate first three AWS kubernetes.io accounts from CNCF to Kubernetes

### ISSUE THREAD

**Issue by hh** [kubernetes/k8s.io#4658]
Creating this issue for visibility for https://github.com/kubernetes/k8s.io/issues/4626#issuecomment-1387620492

> We need to move the AWS accounts under those emails:
### Done
- [x] [k8s-infra-aws-root-account@kubernetes.io](mailto:k8s-infra-aws-root-account@kubernetes.io)
### Needs Mailing list (or ability for catchall) for Password Reset Links to be sent
- [x] [k8s-infra-accounts@kubernetes.io](mailto:k8s-infra-accounts@kubernetes.io)
- [ ] [k8s-infra-aws-registry-k8s-io-admin@kubernetes.io](mailto:k8s-infra-aws-registry-k8s-io-admin@kubernetes.io)

Pulling in steps from https://github.com/kubernetes/k8s.io/issues/4626#issuecomment-1384814126

## Steps:
- [ ] Reset passwords for each account we migrate, or at least ensure Kubernetes access to the account without the CNCF Org (@hh / @ameukam)
  - We will need to authenticate directly without CNCF or Kubernetes Org access.
- [x] CNCF Provides credit card details in order to make account standalone (@hh)
- [ ] CNCF Must remove the k8s account from the CNCF Org**[aws organizations remove-account-from-organization --account-id](https://docs.aws.amazon.com/cli/latest/reference/organizations/remove-account-from-organization.html)** or via the Console (**ALTERNATIVES TO THIS WELCOME!!**)
- [ ] Kubernetes Org admin issues (@hh / @ameukam) **[aws organizations invite-account-to-organization](https://docs.aws.amazon.com/cli/latest/reference/organizations/invite-account-to-organization.html)** capturing the handshake id
- [ ] Migrating Account authenticates via password or console to (@ameukam) **[aws organizations accept-handshake](https://docs.aws.amazon.com/cli/latest/reference/organizations/accept-handshake.html)**

**Comment by hh** [comment]
@ameukam I believe you have the passwords for only two of these:
- [x] [k8s-infra-aws-root-account@kubernetes.io](mailto:k8s-infra-aws-root-account@kubernetes.io)
- [x] [k8s-infra-accounts@kubernetes.io](mailto:k8s-infra-accounts@kubernetes.io)
- [ ] [k8s-infra-aws-registry-k8s-io-admin@kubernetes.io](mailto:k8s-infra-aws-registry-k8s-io-admin@kubernetes.io)

**Comment by hh** [comment]
> Account Account #266690972299 could not be removed.
> k8s-infra-aws-root-account (#266690972299): ConstraintViolationException
> You cannot remove an account from the organization if the account owner has not completed phone pin verification.
> [Sign in into that account ](https://266690972299.signin.aws.amazon.com/console/organizations/complete-signup) to address this.
> Note that attempting to access this account in the same browser will end your current session.

Steps from https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_accounts_remove.html?icmpid=docs_orgs_console#leave-without-all-info

I’ved added the credit card info to make it easier, but I believe you will need to login with your password first to complete the following:
- [x] Provide a valid payment method (I did that)
- [ ] Provide contact information
- [ ] Verify the phone number
- [ ] Select a support plan option

**Comment by hh** [comment]
Thanks @ameukam. We've moved the one account over.

For the other two accounts, we need to create mailing list or similar to reset the passwords (is there a catchall for @kubernetes.io) for:
- [ ] [k8s-infra-accounts@kubernetes.io](mailto:k8s-infra-accounts@kubernetes.io)
- [ ] [k8s-infra-aws-registry-k8s-io-admin@kubernetes.io](mailto:k8s-infra-aws-registry-k8s-io-admin@kubernetes.io)

**Comment by jaypipes** [comment]
@hh in the future when creating member accounts, we need to remember to use an email naming strategy like `base+extension@kubernetes.io` in order to limit the impact of this poor AWS Organizations/Account management user experience.

Basically, we'd have a single email, associated with a list, like `sig-k8s-infra@kubernetes.io` and then have multiple AWS member accounts associated with "extension emails", like so:

* `sig-k8s-infra+registry-k8s-io@kubernetes.io`
* `sig-k8s-infra+ci@kubernetes.io`
* etc

**Comment by hh** [comment]
### k8s-infra-accounts@kubernetes.io -> k8s-infra-aws-admins+accounts@kubernetes.io
- [x] Reset password
- [x] Updated Email
- [x] Migrated from CNCF to Kubernetes

**Comment by hh** [comment]
### [k8s-infra-aws-registry-k8s-io-admin@kubernetes.io](mailto:k8s-infra-aws-registry-k8s-io-admin@kubernetes.io) -> k8s-infra-aws-admins+registry-k8s-io@kubernetes.io
- [x] Reset password
- [x] Updated Email
- [ ] Migrated from CNCF to Kubernetes

I'm about to migrate k8s-infra-aws-registry-k8s-io-admin@kubernetes.io, just confirming we are good to go.

**Comment by ameukam** [comment]
All the accounts have been migrated to a the new organization.
We can consider this done.

/close
