### ISSUE TITLE
Ensuring password reset link access for AWS CNCF->Kubernetes Migration

### ISSUE THREAD

**Issue by hh** [kubernetes/k8s.io#4659]
In order set passwords necessary for the migration (to authenticate while the accounts are unattached to CNCF or Kubernetes CNCF Orgs), AWS will send password reset links.

Some of the emails tied to AWS accounts are existing Kubernetes mailing lists, some are non existent.

I created some PRs for the mailing list, however we will need to create a list/forward or request the emails be retrieved from a `*@kubernetes.io` catchall if one exists.

```
aws organizations list-accounts --query 'sort_by(Accounts,&Email)[?contains(Email,`kubernetes.io`)==`true`].[Email]' | grep \"  | sed 's/+.*@/@/' | sort -u
        "k8s-infra-accounts@kubernetes.io"
        "k8s-infra-aws-admins@kubernetes.io"
        "k8s-infra-aws-registry-k8s-io-admin@kubernetes.io"
        "sig-release-leads@kubernetes.io"
```

- [ ] k8s-infra-aws-admins@kubernetes.io https://github.com/kubernetes/k8s.io/pull/4645
- [ ] sig-release-leads@kubernetes.io / https://github.com/kubernetes/k8s.io/pull/4646
- [ ] k8s-infra-accounts@kubernetes.io needs forward
- [ ] k8s-infra-aws-registry-k8s-io-admin@kubernetes.io needs forward

**Comment by hh** [comment]
[sig-release-leads@kubernetes.io](mailto:sig-release-leads@kubernetes.io) is a private mailing list. I've requested someone who has access to work with me on this. I don't see much usage there, might be fine just to close the account and have them create another one with #sig-k8s-infra directly.

**Comment by hh** [comment]
I'm not sure of the process for creating email lists or forwards within @kubernetes.io, but that is the next step for:
- [k8s-infra-accounts@kubernetes.io](mailto:k8s-infra-accounts@kubernetes.io) needs forward
- [k8s-infra-aws-registry-k8s-io-admin@kubernetes.io](mailto:k8s-infra-aws-registry-k8s-io-admin@kubernetes.io) needs forward

**Comment by ameukam** [comment]
@hh can we close this ?

**Comment by hh** [comment]
Thanks! We got this done!
/close
