### ISSUE TITLE
Create AWS Access for Kubermatic to create prow clusters

### ISSUE THREAD

**Issue by hh** [kubernetes/k8s.io#4748]
@xmudrii and the team at Kubermatic need AWS creds.

Would be good to document the process for either the AWS Account or IAM user creation process here:
https://github.com/kubernetes/k8s.io/blob/main/infra/aws/terraform/README.md#infraawsterraform

This is in support of https://github.com/kubernetes/k8s.io/issues/4686

**Comment by hh** [comment]
@ameukam I can create this manually now, or you can document approach you want.

**Comment by jeefy** [comment]
I think our default state for the next ~1.5mo is "move (reasonably) fast and do true best practices later" so yeah, I say @hh unblock @xmudrii and create them manually.

P-1 and P0 aren't "do the best thing first", and doing this sooner gives us breathing room to do it right later.

**Comment by hh** [comment]
I've created k8s-infra-aws-admins+prow@kubernetes.io and given the password to Kubermatic

**Comment by ameukam** [comment]
xRef: https://github.com/kubernetes/k8s.io/issues/4686
