### ISSUE TITLE
artifacts: set up prow authentication to S3

### ISSUE THREAD

**Issue by justinsb** [kubernetes/k8s.io#4763]
We need to set up some IAM roles / federation so that prow can authenticate to S3, so that it can copy artifacts to the mirror buckets.

/area artifacts

**Comment by justinsb** [comment]
We have a proposed PR here: https://github.com/cncf-infra/aws-infra/pull/21, which is a copy of the configuration for registry.k8s.io (the configurations should be pretty similar)

It's not clear whether we should be doing the configuration in this repo or in cncf-infra/aws-infra - anyone know?  I'm happy to submit a version of the above PR to this repo if that's easier.

**Comment by justinsb** [comment]
I also tried https://github.com/kubernetes/k8s.io/pull/4770, not sure whether that is the right place to do things now?

**Comment by justinsb** [comment]
/assign

I think #4770 is a good way to go

**Comment by justinsb** [comment]
The periodic job is running and prow is using identity federation to authenticate to AWS/S3

/close

**Comment by ameukam** [comment]
Part of:
  - https://github.com/kubernetes/k8s.io/issues/4401
