### ISSUE TITLE
artifacts: Create periodic jobs to copy to mirrors

### ISSUE THREAD

**Issue by justinsb** [kubernetes/k8s.io#4764]
We want to populate the AWS mirrors automatically, likely via a combination of a periodic job and a a postsubmit job.

**Comment by justinsb** [comment]
/area artifacts

PR is at https://github.com/kubernetes/test-infra/pull/28713

**Comment by justinsb** [comment]
Thanks to @BenTheElder for merging the PR.  This appears to now be working, the initial copy is serialized so will likely take many hours (and we'll hit our 2 hour limit a few times), but we expect it to be fast after that (and I have a WIP PR I can dust off to [copy files in parallel](https://github.com/kubernetes-sigs/promo-tools/pull/714) if we need it)

We can see the copy job runing here:
https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/ci-k8sio-file-promo-mirrors

**Comment by justinsb** [comment]
The job seems to be running pretty well.  The initial copy was about 6 hours, but I think that was actually CPU bound (because when we have to copy files we do a lot of hashing operations, I believe).  I sent a [PR to increase CPU allocation](https://github.com/kubernetes/test-infra/pull/28750) from 100m to 1 core :-)  But TBH even 100m is "good enough" until we add a lot more mirrors.

https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/ci-k8sio-file-promo-mirrors

The job is very fast when everything is in sync.

/close

**Comment by ameukam** [comment]
Part of:
  - https://github.com/kubernetes/k8s.io/issues/4401
