### ISSUE TITLE
artifacts: Need some test job that runs against against artifacts-sandbox.k8s.io

### ISSUE THREAD

**Issue by justinsb** [kubernetes/k8s.io#4765]
We need some form of community verification that artifacts-sandbox.k8s.io works with existing tooling e.g. kOps.

**Comment by justinsb** [comment]
/area artifacts

PR is https://github.com/kubernetes/test-infra/pull/28740

**Comment by ameukam** [comment]
We have now: https://testgrid.k8s.io/sig-cluster-lifecycle-kops#kops-artifacts-sandbox

/milestone v1.27

**Comment by justinsb** [comment]
We do!  Let's close

/close
