### ISSUE TITLE
artifacts: need to repoint artifacts.k8s.io to new setup

### ISSUE THREAD

**Issue by justinsb** [kubernetes/k8s.io#4766]
When all the other artifacts tasks are done, we need to repoint artifacts.k8s.io to the new porche instance.

Because the TLS certificate is generated on-demand, we think this might involve 15-30 minutes where artifacts.k8s.io is not serving over HTTPS, and possibly is not serving at all.  This might be a good reliability test for tooling, but we need to be mindful of this.  So far, the best way we know of to avoid this is to procure a TLS certificate manually, copy it to the new CloudRun configuration, cut over, then allow CloudRun to switch to automatic certificate management. 

/area artifacts

**Comment by ameukam** [comment]
We should probably plan a downtime of 30 min to ensure we can switch to a new auto-renewed TLS certificate.

/area infra
/priority important-soon
/milestone v1.27

**Comment by BenTheElder** [comment]
Progress: https://github.com/kubernetes/k8s.io/pull/4779 and https://github.com/kubernetes/k8s.io/pull/4781

**Comment by ameukam** [comment]
@justinsb can we close this ?

**Comment by justinsb** [comment]
Yes :tada: 

/close
