### ISSUE TITLE
artifacts: stand up production serving instances

### ISSUE THREAD

**Issue by justinsb** [kubernetes/k8s.io#4767]
We need to stand up our production instances of porche, using a configuration similar to the existing sandbox configuration.

/area artifacts

**Comment by justinsb** [comment]
PR is https://github.com/kubernetes/k8s.io/pull/4737

/assign

**Comment by justinsb** [comment]
Production instances are running (though not yet serving traffic until DNS is redirected #4766)

/close

**Comment by ameukam** [comment]
Part of:
  - https://github.com/kubernetes/k8s.io/issues/4401
