### ISSUE TITLE
artifacts: need to release kpromo

### ISSUE THREAD

**Issue by justinsb** [kubernetes/k8s.io#4768]
We are currently promoting artifacts using a CI version of kpromo (the release tools).  We needed some additional capabilities, particularly around copying to S3.

When artifact promotion is working, we should do a release that includes the commits we need.  If we're lucky, there may be one by that time anyway.

We should then ensure that all prow jobs are using a tagged release.

/area artifacts

**Comment by ameukam** [comment]
Opened:
  - https://github.com/kubernetes-sigs/promo-tools/issues/730

/priority important-soon
/milestone v1.27
/area release-eng

**Comment by BenTheElder** [comment]
Looks like the version was updated upstream, so we can update the prowjobs once the image is promoted to prod.

**Comment by BenTheElder** [comment]
kpromo was released https://github.com/kubernetes-sigs/promo-tools/issues/730

**Comment by BenTheElder** [comment]
/assign
updating CI jobs

**Comment by BenTheElder** [comment]
/unassign
already done in https://github.com/kubernetes/test-infra/pull/28773
/close

**Comment by ameukam** [comment]
Part of:
  - https://github.com/kubernetes/k8s.io/issues/4401
