### ISSUE TITLE
artifacts: add mirroring to postsubmit

### ISSUE THREAD

**Issue by justinsb** [kubernetes/k8s.io#4774]
Similar to #4764, we probably want to add mirroring to our postsubmits for artifacts.k8s.io artifacts.

It looks like it will not significantly impact the time required (particularly if we add logic to promote to the mirrors in parallel, and give it at least 1 cpu core).

/area artifacts

**Comment by hakman** [comment]
I see that there is a mirroring job now, which is failing after promoting `ecr-credential-provider` for `cloud-provider-aws`:
https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/ci-k8sio-file-promo-mirrors
```
********** FINISHED WITH ERRORS **********
error uploading "s3://test-artifacts-k8s-io-us-east-2/binaries/cloud-provider-aws/v1.26.1/linux/amd64/ecr-credential-provider-linux-amd64": AccessDenied: Access Denied
	status code: 403, request id: XNEQFB0VXK8XMFZ3, host id: 4/HTmTAVc2CPZ4YyWHOZsOtZmGJhbkW65oK/RGGqbbxTnMGIoegk0Fy+H59xMzK9bwBC/It2u+8=
```
