### ISSUE TITLE
Age Out Policy for container images in our registries

### ISSUE THREAD

**Issue by dims** [kubernetes/k8s.io#4889]
When we get out of our crisis mode, we should create a policy for how long our artifacts will be available in our registries. This will hopefully help drive folks to copy things over to their own registries as well.

The policy could be something like: Any container images from kubernetes releases will be available for at most a year after a specific version is out of support. possibly?

We'll need a way to also govern non-k8s-release artifacts. Give them a fixed span of say 2 years from when they got uploaded. perhaps?

**Comment by dims** [comment]
Capturing this to reflect the chat in #tag-chairs between @mrbobbytables and @TheFoxAtWork here: https://cloud-native.slack.com/archives/CSCPTLTPE/p1678219030800149

**Comment by TheFoxAtWork** [comment]
Thanks Dims!
