### ISSUE TITLE
gcr - k8s-staging-provider-os is private after creation?

### ISSUE THREAD

**Issue by zetaab** [kubernetes/k8s.io#4910]
We created new registry k8s-staging-provider-os to gcr. However, after creation it looks like

<img width="794" alt="Screenshot 2023-03-09 at 13 54 30" src="https://user-images.githubusercontent.com/22482503/224052632-990403f4-a205-4676-a757-d42193f78de3.png">

all repositories are private. If we compare for instance to AWS

```
docker pull gcr.io/k8s-staging-provider-aws/cloud-controller-manager:latest
```

it seems that the repos are open. Also, I tried to promote some images just for test the pipeline https://github.com/kubernetes/k8s.io/pull/4908 and it fails 

```
time="13:53:33.543" level=fatal msg="run `cip run`: promote images: filtering edges: filtering promotion edges: reading registries: getting tag list: GET https://gcr.io/v2/k8s-staging-provider-os/openstack-cloud-controller-manager/tags/list?n=1000: DENIED: Failed to read tags for host 'gcr.io', repository '/v2/k8s-staging-provider-os/openstack-cloud-controller-manager/tags/list?n=1000'" diff=311ms
```

because the registry is private? Or is this something else?

**Comment by dims** [comment]
it does say:
```
Ensuring gs://k8s-staging-provider-os exists and is world readable in project: k8s-staging-provider-os
```

**Comment by dims** [comment]
```
davanum@cloudshell:~/k8s.io (kubernetes-public)$ gsutil iam get gs://k8s-staging-provider-os
{
  "bindings": [
    {
      "members": [
        "group:k8s-infra-artifact-admins@kubernetes.io",
        "projectEditor:k8s-staging-provider-os",
        "projectOwner:k8s-staging-provider-os"
      ],
      "role": "roles/storage.legacyBucketOwner"
    },
    {
      "members": [
        "projectViewer:k8s-staging-provider-os"
      ],
      "role": "roles/storage.legacyBucketReader"
    },
    {
      "members": [
        "group:k8s-infra-staging-provider-os@kubernetes.io"
      ],
      "role": "roles/storage.legacyBucketWriter"
    },
    {
      "members": [
        "group:k8s-infra-artifact-admins@kubernetes.io",
        "group:k8s-infra-staging-provider-os@kubernetes.io"
      ],
      "role": "roles/storage.objectAdmin"
    },
    {
      "members": [
        "allUsers"
      ],
      "role": "roles/storage.objectViewer"
    }
  ],
  "etag": "CAs="
}
```

**Comment by zetaab** [comment]
@dims 

```
% curl https://gcr.io/v2/k8s-staging-provider-aws/tags/list
{"child":["aws-ebs-csi-driver","aws-iam-authenticator","cloud-controller-manager"],"manifest":{},"name":"k8s-staging-provider-aws","tags":[]}
```
vs

```
 % curl https://gcr.io/v2/k8s-staging-provider-os/tags/list
{"errors":[{"code":"DENIED","message":"Failed to read tags for host 'gcr.io', repository '/v2/k8s-staging-provider-os/tags/list'"}]}
```

**Comment by dims** [comment]
@zetaab yep, i can see the problem :) trying to figure out what i have to do to fix it :)

**Comment by dims** [comment]
@zetaab please try again. I toggled this via the UI for now:

![image](https://user-images.githubusercontent.com/23304/224064601-6340c7a2-e47b-4ec2-bccc-0c204e5992c7.png)

**Comment by dims** [comment]
and that flipped all the 3rd column entries to `Public`

![image](https://user-images.githubusercontent.com/23304/224064865-824a058a-3868-425a-b36c-bc059ba5dde0.png)

**Comment by dims** [comment]
tested with:
`curl https://gcr.io/v2/k8s-staging-provider-os/tags/list`

and:
`docker pull gcr.io/k8s-staging-provider-os/openstack-cloud-controller-manager@sha256:0d03ed5cecd52d94de5fbb13ca311c55e695db3cf65b063e4fbd45af02e3c605`

**Comment by zetaab** [comment]
yeah it do work now. Retest does not seems to work https://github.com/kubernetes/k8s.io/pull/4908 is that testing-ops issue or?
