### ISSUE TITLE
BUG: prow validation of image yaml 

### ISSUE THREAD

**Issue by strongjz** [kubernetes/k8s.io#4941]
I was able to get an incorrect yaml merged into main. The ingress-nginx web cert sha was missing a char and an " but prow bot merged the PR. 

File in question 
https://github.com/kubernetes/k8s.io/pull/4929/files#diff-177c8d0b37aa1ffb1cdbadfd7455d4922786090c8053452caa1da8a30da74f97R216

The verify job that I think should have failed? https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/k8s.io/4929/pull-k8sio-verify/1635604760147005440

**Comment by strongjz** [comment]
another image was a copy paste error missing one char on the sha https://github.com/kubernetes/k8s.io/blob/main/k8s.gcr.io/images/k8s-staging-ingress-nginx/images.yaml#L203

**Comment by TerryHowe** [comment]
Is this a bug or a feature request?

Is the expectation just to validate the sha?

**Comment by BenTheElder** [comment]
xref: https://github.com/kubernetes-sigs/promo-tools/issues/633

**Comment by T-Lakshmi** [comment]
/kind bug

**"** is missing here.

> "sha256:01d181618f270f2a96c04006f33b2699ad3ccb02da48d0f89b22abce084b292": [v20230312-helm-chart-4.5.2-28-g66a760794"]

**Comment by BenTheElder** [comment]
see also: https://github.com/kubernetes/k8s.io/issues/5221
