### ISSUE TITLE
Wind down godeps publishing-bot instance

### ISSUE THREAD

**Issue by nikhita** [kubernetes/k8s.io#500]
We run two instances of the publishing-bot today. The instance of the bot responsible for syncing releases <= `v1.14` runs in the `k8s-publishing-bot-godeps` namespace and the instance of the bot responsible for syncing the master branch and releases >= `v1.14` runs in the `k8s-publishing-bot` namespace.

The [final patch release](https://github.com/kubernetes/sig-release/blob/master/releases/patch-releases.md#114-and-older) for 1.14 is 1.14.10 which would be cut today (https://github.com/kubernetes/sig-release/issues/888). Once it is cut, we won't be supporting 1.14 anymore so we could technically wind down the godeps instance of the bot.

Having said this, we are in **no hurry** to wind down this instance and can keep running it until we are sure that we don't want it anymore. I just want to start the conversation around this so we have a roadmap in place of when to switch off the godeps instance.

Winding down the bot would mean:

- Deleting everything in the `k8s-publishing-bot-godeps` namespace (including the namespace itself)
- Removing https://github.com/kubernetes/kubernetes/blob/master/staging/publishing/rules-godeps.yaml file from k/k.

---

To decide when to switch the godeps instance off, I'd like confirmation/comments from the following folks/teams on when we could do it (and if doing this after 1.14.10 is cut is ok):

- other publishing bot owners - @sttts @dims 
- patch release team - @kubernetes/patch-release-team 
- product security committee - @kubernetes/product-security-committee 
- sig-release leads - @justaugustus @tpepper @calebamiles 
- wg-k8s-infra leads - @dims @spiffxp @bartsmykla  

Assigning myself to track this and do the actual switching off of the godeps instance
/assign

/wg k8s-infra
/sig release
/kind cleanup

**Comment by liggitt** [comment]
From my perspective, it makes sense to turn down the bot after the final 1.14.x release is cut, along with the rest of the 1.14 CI.

**Comment by thockin** [comment]
I don't mind letting it ride for a quarter "to be sure"

**Comment by liggitt** [comment]
Sure. It's basically 6 no-ops a day once we stop updating branches it cares about. Basically no impact to anything.

**Comment by bartsmykla** [comment]
@nikhita what is the state of this issue? If it's still the issue can I help somehow to move things forward? :-)

/remove-lifecycle stale

**Comment by nikhita** [comment]
> @nikhita what is the state of this issue? 

@bartsmykla We still need to wind down the godeps bot, I was thinking that we could do this after 1.18 is released. I'll circle back on this then -- will give a headsup here + on mailing lists and in a wg-k8s-infra meeting before actually implementing this. :+1:

**Comment by bartsmykla** [comment]
Thank you! :-)

**Comment by nikhita** [comment]
Discussed this with @dims @sttts and @liggitt  -- we will be winding down the godeps instance on Wednesday, April 1st. I have sent a [notice](https://groups.google.com/forum/#!topic/kubernetes-sig-release/HNj7y7D4Yz4) to the wg-k8s-infra and sig-release mailing lists.

I will also announce it in the wg-k8s-infra meeeting on April 1st before switching it off.

**Comment by bartsmykla** [comment]
Sounds good to me :-)

**Comment by nikhita** [comment]
This is done now! :tada:

**Comment by bartsmykla** [comment]
Great! Thank you @nikhita for the work! :-)
