### ISSUE TITLE
REQUEST: Need for AWS account for hosting CAPA generated AMIs

### ISSUE THREAD

**Issue by Ankitasw** [kubernetes/k8s.io#5010]
We need to host all of the new CAPA AMIs going forward in a CNCF account such that it's maintained upstream. 
Currently, the cost for running EC2 instances to generate AMIs is average of 5K USD in last 6 months. We also need small amount of budget for running a lambda function(costing around 20USD) and data transfer(costing around 36USD).

Would it be possible to provide a separate ACL to make this happen?

Refer slack thread [here](https://kubernetes.slack.com/archives/CCK68P2Q2/p1679325270740909) for more details.

**Comment by Ankitasw** [comment]
VMware owns the current account and hence we need a new one such that others also has access to the account

**Comment by hh** [comment]
I'm not sure if it's the amount we are looking for, but I did notice we migrated "cncf-k8s-infra-aws-capa-ami" account from the CNCF AWS Org to Kubernetes AWS AWS Org a while back: https://github.com/kubernetes/k8s.io/issues/4626#orgbead97b

The password for `arn:aws:organizations::348685125169:account/o-kz4vlkihvy/819546954734` is stored in the Kubernetes Community 1Password vault *AWS CI Accounts*.

```shell
export AWS_PROFILE=hh@kubernetes
aws organizations describe-account --account-id 819546954734
```

```
{
    "Account": {
        "Id": "819546954734",
        "Arn": "arn:aws:organizations::348685125169:account/o-kz4vlkihvy/819546954734",
        "Email": "cncf-k8s-infra-aws-capa-ami@lists.cncf.io",
        "Name": "cncf-k8s-infra-aws-capa-ami",
        "Status": "ACTIVE",
        "JoinedMethod": "INVITED",
        "JoinedTimestamp": "2023-02-07T01:11:07.090000+02:00"
    }
}
```

**Comment by hh** [comment]
@dims / @ameukam Here is the 1Password Kubernetes community Vault and entry for the account. Share as you see fit. I'd like to find a way to manage ongoing access to 1Password Vault entries so passwords can be updated and shared more easily.

- [Check Kubernetes Vaults](#orgb63a0dc)
- [Inspect &ldquo;AWI CI accounts&rdquo;](#orgb2aedcf)
- [Find capa-ami password item](#orgb7d18ed)
- [Retrieve capi-ami one password item](#orgba06307)
- [Share this link (good for 7 days)](#orgc092209)

<a id="orgb63a0dc"></a>
# Check Kubernetes Vaults

```shell
op vault list
```

```
ID                            NAME
5qq5hxaboazxl5p4e5dr6gypqi    Private
atxptplouln57mbc5kvt3tq6jm    AWS CI accounts
x5q2rsmkygy56vwmrgsccuoi2a    Shared
```


<a id="orgb2aedcf"></a>

# Inspect &ldquo;AWI CI accounts&rdquo;

```shell
op vault get "AWS CI accounts"
```

```
ID:                   atxptplouln57mbc5kvt3tq6jm
Name:                 AWS CI accounts
Type:                 USER_CREATED
Attribute version:    1
Content version:      125
Items:                87
Created:              4 months ago
Updated:              1 month ago
```


<a id="orgb7d18ed"></a>

# Find capa-ami password item

```shell
op items list | grep capa-ami
```

```
vatlttczb3iebcmf7t5hlartwq    Awazon (cncf-k8s-infra-aws-capa-ami)                           AWS CI accounts            3 months ago
```


<a id="orgba06307"></a>

# Retrieve capi-ami one password item

```shell
op items get vatlttczb3iebcmf7t5hlartwq | grep -v password:
```

```
ID:          vatlttczb3iebcmf7t5hlartwq
Title:       Awazon (cncf-k8s-infra-aws-capa-ami)
Vault:       AWS CI accounts (atxptplouln57mbc5kvt3tq6jm)
Created:     3 months ago
Updated:     3 months ago by Riaan
Favorite:    false
Tags:        aws,production,sig-k8s-infra
Version:     1
Category:    LOGIN
Fields:
  username:    cncf-k8s-infra-aws-capa-ami@lists.cncf.io
URLs:
  website:    https://signin.aws.amazon.com (primary)
```


<a id="orgc092209"></a>

# Share this link (good for 7 days)

We could do this, but it&rsquo;s only good for 7 days and then access to this is gone. I&rsquo;d like to find a process to share this longer term.

```shell
op items get vatlttczb3iebcmf7t5hlartwq --share-link
```

**Comment by dims** [comment]
@hh thank you I can confirm that i see it in my 1password

<img width="518" alt="image" src="https://github.com/kubernetes/k8s.io/assets/23304/afc96b30-7474-4f1b-935f-24d82ef7cba0">

**Comment by dims** [comment]
@Ankitasw please DM me, we'll work out what you need (looks like you want to install and run a lambda at least!)

**Comment by ameukam** [comment]
@hh Can we instead create an dedicated user for @Ankitasw with `AdministratorAccess` on the account `cncf-k8s-infra-aws-capa-ami` ? Thanks!

**Comment by richardcase** [comment]
@ameukam & @hh -  Would it also be possible to add me as well? So we have 2 maintainers of CAPA on the account.

**Comment by ameukam** [comment]
> @ameukam & @hh - Would it also be possible to add me as well? So we have 2 maintainers of CAPA on the account.

+1 from me.

**Comment by hh** [comment]
- [Our top level kubernetes-aws-admins@lists.cncf.io account + org](#orgae6a3cf)
- [List of current top level IAM Users](#orge3e90bd)
- [Inspect cncf-k8s-infra-aws-capa-ami@lists.cncf.io account](#org399a153)

The AWS account cncf-k8s-infra-aws-capa-ami@lists.cncf.io / arn:aws:organizations::348685125169:account/o-kz4vlkihvy/819546954734 is probably where we want to create the iam roles. Probably similar to the way we create them at the top level Kubernetes AWS account.

-   See <https://github.com/kubernetes/k8s.io/issues/5010#issuecomment-1580212057>

However I&rsquo;m not sure how we want to manage the terraform for AWS org member-accounts, and the resources (like IAM users) that are needed by them.

Should the CAPA team create their own terraform to create acccounts there? I can&rsquo;t imagine scaling this if we have to manage all-the-k8s sub/member-acccounts with terraform in the same repo managed by the same team.

Suggestions welcome.

If we decide to go with top level accounts, and a good read might be [Accessing member accounts in your organization](https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_accounts_access.html)


<a id="orgae6a3cf"></a>

# Our top level kubernetes-aws-admins@lists.cncf.io account + org

```shell
aws organizations describe-organization
```

```json
{
    "Organization": {
        "Id": "o-kz4vlkihvy",
        "Arn": "arn:aws:organizations::348685125169:organization/o-kz4vlkihvy",
        "FeatureSet": "ALL",
        "MasterAccountArn": "arn:aws:organizations::348685125169:account/o-kz4vlkihvy/348685125169",
        "MasterAccountId": "348685125169",
        "MasterAccountEmail": "kubernetes-aws-admins@lists.cncf.io",
        "AvailablePolicyTypes": [
            {
                "Type": "SERVICE_CONTROL_POLICY",
                "Status": "ENABLED"
            }
        ]
    }
}
```


<a id="orge3e90bd"></a>

# List of current top level IAM Users

```shell
aws iam list-users --output=table --query 'Users[*].[UserName,Arn]'
```

```
---------------------------------------------------------------
|                          ListUsers                          |
+-------------+-----------------------------------------------+
|  arnaud     |  arn:aws:iam::348685125169:user/arnaud        |
|  bentheelder|  arn:aws:iam::348685125169:user/bentheelder   |
|  dims       |  arn:aws:iam::348685125169:user/dims          |
|  hh         |  arn:aws:iam::348685125169:user/hh            |
|  jeefy      |  arn:aws:iam::348685125169:user/jeefy         |
+-------------+-----------------------------------------------+
```


<a id="org399a153"></a>

# Inspect cncf-k8s-infra-aws-capa-ami@lists.cncf.io account

```shell
aws organizations describe-account --account-id 819546954734
```

```
{
    "Account": {
        "Id": "819546954734",
        "Arn": "arn:aws:organizations::348685125169:account/o-kz4vlkihvy/819546954734",
        "Email": "cncf-k8s-infra-aws-capa-ami@lists.cncf.io",
        "Name": "cncf-k8s-infra-aws-capa-ami",
        "Status": "ACTIVE",
        "JoinedMethod": "INVITED",
        "JoinedTimestamp": "2023-02-07T00:11:07.090000+01:00"
    }
}
```

**Comment by richardcase** [comment]
> Should the CAPA team create their own terraform to create acccounts there? I can’t imagine scaling this if we have to manage all-the-k8s sub/member-acccounts with terraform in the same repo managed by the same team.

@hh (and @Ankitasw ) It would  be good if there was a way for the maintainers of CAPA to manage the access to the accounts. It would be more scalable as a principal.

I'd be happy maintaining terraform, or perhaps yaml for [ACK](https://aws-controllers-k8s.github.io/community/) for the CAPA specific account.

**Comment by richardcase** [comment]
Circling back to this. We need to build & publish some new AMIs to the AWS account for CAPA. How should we manage access to the account for the CAPA maintainers? 

@hh @dims - any thoughts on this?

**Comment by richardcase** [comment]
The current list of maintainers of CAPA who will ideally need to be able to publish new AMIs are:

- @richardcase
- @Ankitasw
- @dlipovetsky
- @vincepri

([source](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/OWNERS_ALIASES#L22-L25))

This changes over time so happy to contribute terraform or something else if needed.

**Comment by BobyMCbobs** [comment]
I think that the best path is to create terraform in _infra/aws/terraform/cncf-k8s-infra-aws-capa-ami_, where the Terraform provider for AWS is either expected to be run in the account or that it is accessing through assume role with the _OrganizationAccountAccessRole_ for full-permissions. 
In that terraform, specifying the IAM users stated above. 
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_user
https://github.com/kubernetes/k8s.io/pull/5044

cc @hh

**Comment by richardcase** [comment]
Thanks @BobyMCbobs .

I have started work on the terraform based on your suggestions and will have a PR for it soon.

**Comment by richardcase** [comment]
Finally got around to updating the PR for this.

**Comment by richardcase** [comment]
This is still needed:

/remove-lifecycle stale
