### ISSUE TITLE
Need RBAC for cert-manager in aaa

### ISSUE THREAD

**Issue by thockin** [kubernetes/k8s.io#502]
The "standard" RBAC is not going to be enough.  James agreed to think about the minimum permissions needed to run cert-manager.

**Comment by munnerz** [comment]
Are all the certificates needed by cert-manager only in one namespace? Is it likely we will want to use the Certificate resource type in other namespaces at some point in future?

cert-manager's namespace scoped mode only allows running in a *single* namespace, not in a list of namespaces. This means you'll need to run an instance of the `controller` component (the 'controller manager') for every namespace you want to process Certificate issuance for.

It is akin to running an instance of `kube-controller-manager` per namespace.

I've opened https://github.com/jetstack/cert-manager/issues/2454 to track us adding this in the project anyway, as it should be documented regardless 😄

**Comment by thockin** [comment]
On Wed, Dec 11, 2019 at 9:31 AM James Munnelly <notifications@github.com> wrote:
>
> Are all the certificates needed by cert-manager only in one namespace? Is it likely we will want to use the Certificate resource type in other namespaces at some point in future?

We will (do) use Certificates in multiple namespaces.

> cert-manager's namespace scoped mode only allows running in a single namespace, not in a list of namespaces. This means you'll need to run an instance of the controller component (the 'controller manager') for every namespace you want to process Certificate issuance for.
>
> It is akin to running an instance of kube-controller-manager per namespace.

That sounds awful :)

> I've opened jetstack/cert-manager#2454 to track us adding this in the project anyway, as it should be documented regardless

**Comment by munnerz** [comment]
I don't think there's anything specific to do here? cert-manager is running/set up properly, and uses RBAC 😄 I don't think we should deviate from the 'official' installation manifests (at least not without setting up some kind of e2e pipeline to run tests against it if we do, which seems out-of-scope).

/close

**Comment by thockin** [comment]
I meant RBAC for admins.  Someone should be able to be listed in a group
that is able to manage cert-manager (e.g. update it) without being able to
do other things in the cluster (e.g. the humans should not be able to make
namespaces or write to other namespace).
