### ISSUE TITLE
Move Publishing bot from development2 to aaa

### ISSUE THREAD

**Issue by thockin** [kubernetes/k8s.io#503]
figure out the correct config and yaml

document it and check it in to k8s.io

send a PR to make a group and namespace

deploy yaml to aaa

turn down dev2 cluster

**Comment by nikhita** [comment]
:wave: I can help with this! :)

Assigning to me since moving the configs would also involve moving the token, and only a few folks have access to it
/assign

**Comment by ameukam** [comment]
Happy to help with this as well. :-) 
From my understanding is about migrate those [manifests](https://github.com/kubernetes/publishing-bot/tree/master/artifacts/manifests) in this repo ?

**Comment by nikhita** [comment]
>  From my understanding is about migrate those manifests in this repo ?

Also configs: https://github.com/kubernetes/publishing-bot/tree/master/configs and adding a makefile to automatically deploy it

**Comment by nikhita** [comment]
xref https://github.com/kubernetes/k8s.io/issues/395

**Comment by spiffxp** [comment]
/assign @bartsmykla 
Was looking to get consensus on best approach to manage StorageClass.  Consensus was we're fine restricting to running inside Cloud Shell, and can use terraform to manage this for now since it straddles the line between infra and cluster resources.  Bart to create a pull request which he'll update

**Comment by spiffxp** [comment]
/remove-help
since this is actively being worked

**Comment by nikhita** [comment]
Had a quick chat with @bartsmykla about this. The current plan is to:

- Keep the publishing-bot configs and manifests in the publishing-bot repo
- Turn down the old bot instance in the `development2` cluster
- I will then create the secret (containing the GitHub token for the bot) in the `aaa` cluster
  - The token exists in the publishing-bot repo and is encrypted via git-crypt. @sttts @dims and I have access to it.
  - Once the secret has been created, it would be accessible to only cluster admins: https://github.com/kubernetes/k8s.io/blob/bc9ed63f5167bd71ffe852d0f937b9a962d4d87f/groups/groups.yaml#L221-L236
- I'll deploy the bot on a call with @ameukam 
- @ameukam / @bartsmykla will then help document steps (in the k8s.io repo) required to deploy the bot

----

The `1.19.0-alpha.2` tag is scheduled for today, so I can go ahead with switching off the old bot after that's published. I can wind down the old bot and deploy the new one tomorrow, there shouldn't be much downtime.

I'd like ack from the following folks before going ahead with this.

/cc @justaugustus 
from a sig-release perspective

/cc @sttts @dims 
from the publishing-bot perspective

**Comment by justaugustus** [comment]
SGTM!

**Comment by sttts** [comment]
sgtm

**Comment by dims** [comment]
Sounds like a good plan @nikhita !

**Comment by nikhita** [comment]
Bot has been migrated to the `aaa` cluster :tada: 

There weren't too many documentation updates, but I've created https://github.com/kubernetes/publishing-bot/pull/223 to reflect the migration.

/close

**Comment by thockin** [comment]
So it is safe for me to decom the old cluster now?

**Comment by nikhita** [comment]
> So it is safe for me to decom the old cluster now?

Yes :+1:

**Comment by thockin** [comment]
I'll scale it down to 0 nodes - how long do you want me to hold here, in
case we need to revert?

**Comment by nikhita** [comment]
> how long do you want me to hold here, in case we need to revert?

Until early next week (maybe until next week's wg-k8s-infra meeting) should be fine.

**Comment by thockin** [comment]
ACK

**Comment by spiffxp** [comment]
opened https://github.com/kubernetes/k8s.io/issues/785 to track the cluster turndown
