### ISSUE TITLE
Move k8s.io from old Google-only cluster to aaa

### ISSUE THREAD

**Issue by thockin** [kubernetes/k8s.io#504]
Other than the existing TLS secrets which will need to be manually copied, the YAML exists.

1) PR to make a group and namespace

2) Load YAML in aaa cluster, get new IP

3) figure out what tests we want to do to convince ourselves it is sane

4) Monitoring (at least up-checks)

5) Flip DNS to new IP

6) Turn down old

**Comment by ThomasWo** [comment]
I don't currently have access to either aaa or google clusters, but I'll do what I can on this one.

@thockin For `1. PR to make a group and namespace`, any idea on what the group name should be/who should be in it?  I have a first pass in #513 (just took a guess at a name and added usernames that I recognized).
/assign

**Comment by BenTheElder** [comment]
noting that 1. / https://github.com/kubernetes/k8s.io/issues/504#issuecomment-565773199 was done in https://github.com/kubernetes/k8s.io/pull/513

2\. seems pretty straightforward, 3/4 may need some thought still. 5.6 will be straightforward...

**Comment by BenTheElder** [comment]
GCP project for old cluster is `kubernetes-site`, I can access that and see the deployments etc.
The new `AAA` cluster is in `kubernetes-public`, which I think I actually can't.

Not sure what we want to name these for the new deployment.

**Comment by thockin** [comment]
Add thineself to k8s-infra-cluster-admins@kubernetes.io in groups.yaml and you will be able to drive all over aaa.
