### ISSUE TITLE
eks-prow-build-cluster: Setup boskos

### ISSUE THREAD

**Issue by ameukam** [kubernetes/k8s.io#5048]
Setup a [boskos](https://github.com/kubernetes-sigs/boskos) instance on AWS that will be used by prowjobs running e2e tests to acquire AWS accounts for execution.

We should probably also set a few AWS accounts as part of the boskos pool. 

/milestone v1.27
/priority important-soon
/area infra
/area infra/aws
cc @justinsb @pkprzekwas

**Comment by pkprzekwas** [comment]
I assume we want to deploy in on the EKS prow build cluster and we can base on https://github.com/kubernetes/k8s.io/tree/main/infra/gcp/terraform/k8s-infra-prow-build/prow-build/resources/test-pods

**Comment by xmudrii** [comment]
boskos is deployed on prod and configured with 10 AWS accounts
/close
