### ISSUE TITLE
Migrate remaining AWS accounts to K8s AWS credits

### ISSUE THREAD

**Issue by jeefy** [kubernetes/k8s.io#5111]
Context: https://kubernetes.slack.com/archives/CCK68P2Q2/p1680894907079219?thread_ts=1680893868.823139&cid=CCK68P2Q2

Looks like two K8s accounts didn't swap under the new K8s Infra AWS Org

```
13800559357 - CNCF K8s Minikube ($)
634972135556 - cncf-k8s-external-dns-aws ($)
```

/assign @Riaankl @hh

**Comment by Riaankl** [comment]
cncf-k8s-minikube-aws@lists.cncf.io
cncf-k8s-external-dns-aws@lists.cncf.io

No worries found the email addresses.
login credentials  would still help. Looking at resetting.

**Comment by Riaankl** [comment]
Account have been moved and login credentials added to K8s AWS 1Password account

**Comment by Riaankl** [comment]
@jeefy I think we can close this issue?
