### ISSUE TITLE
eks-prow-build-cluster: IAM refactoring and improvements

### ISSUE THREAD

**Issue by pkprzekwas** [kubernetes/k8s.io#5160]
- [ ]  create  IAM roles dedicated for running terraform scripts for provisioning EKS prow build cluster. This can be done with dedicated terraform script or simple bash script with aws cli.
- [ ] introduce [permission boundaries](https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_boundaries.html) to prevent access escalation in roles with assigned IAM actions. We can start small with positions like denying leaving org and removing permission boundary.

ref: https://github.com/kubernetes/k8s.io/pull/5113

/cc @xmudrii @sftim

**Comment by xmudrii** [comment]
/retitle eks-prow-build-cluster: IAM refactoring and improvements

**Comment by xmudrii** [comment]
This is done. :tada: Boundaries can be extended, but this can be done on demand.
/close
