### ISSUE TITLE
registry.k8s.io down?

### ISSUE THREAD

**Issue by Joseph94m** [kubernetes/k8s.io#5181]
### What happened?

Hey, I am not sure if that's a bug, a misconfig from my side or a temporary outage!

Attempts at upgrading my kubeadm cluster are timing out when pulling images from the registry.

sudo kubeadm upgrade apply v1.22.17 --yes
```
I0426 10:38:44.292075    8551 checks.go:838] using image pull policy: IfNotPresent
I0426 10:38:44.364022    8551 checks.go:855] pulling: registry.k8s.io/kube-apiserver:v1.22.17
I0426 10:39:19.746419    8551 checks.go:855] pulling: registry.k8s.io/kube-controller-manager:v1.22.17
I0426 10:40:17.199939    8551 checks.go:855] pulling: registry.k8s.io/kube-scheduler:v1.22.17
I0426 10:41:19.471083    8551 checks.go:855] pulling: registry.k8s.io/kube-proxy:v1.22.17
I0426 10:42:36.288870    8551 checks.go:855] pulling: registry.k8s.io/pause:3.5
I0426 10:44:16.331556    8551 checks.go:855] pulling: registry.k8s.io/coredns/coredns:v1.8.4
[preflight] Some fatal errors occurred:
	[ERROR ImagePull]: failed to pull image registry.k8s.io/kube-apiserver:v1.22.17: output: Error response from daemon: received unexpected HTTP status: 503 Service Unavailable
, error: exit status 1
	[ERROR ImagePull]: failed to pull image registry.k8s.io/kube-controller-manager:v1.22.17: output: Error response from daemon: Get https://registry.k8s.io/v2/: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
, error: exit status 1
	[ERROR ImagePull]: failed to pull image registry.k8s.io/kube-scheduler:v1.22.17: output: Error response from daemon: Get https://registry.k8s.io/v2/: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
, error: exit status 1
	[ERROR ImagePull]: failed to pull image registry.k8s.io/kube-proxy:v1.22.17: output: Error response from daemon: received unexpected HTTP status: 503 Service Unavailable
, error: exit status 1
	[ERROR ImagePull]: failed to pull image registry.k8s.io/pause:3.5: output: Error response from daemon: received unexpected HTTP status: 503 Service Unavailable
, error: exit status 1
	[ERROR ImagePull]: failed to pull image registry.k8s.io/coredns/coredns:v1.8.4: output: Error response from daemon: received unexpected HTTP status: 503 Service Unavailable
, error: exit status 1
```

I tried performing the requests from my machine locally with multiple releases:

docker pull registry.k8s.io/kube-apiserver:v1.22.17                                                                                                               
Error response from daemon: received unexpected HTTP status: 503 Service Unavailable

docker pull registry.k8s.io/kube-apiserver:v1.26.0                                                                                                            
Error response from daemon: received unexpected HTTP status: 503 Service Unavailable

docker pull registry.k8s.io/kube-apiserver:v1.26.3                                                                                                             
Error response from daemon: received unexpected HTTP status: 503 Service Unavailable

### What did you expect to happen?

I guess i was expecting the images to be pulled

### How can we reproduce it (as minimally and precisely as possible)?

Try pulling from the registry

### Kubernetes version

Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.14", GitCommit:"0f77da5bd4809927e15d1658fb4aa8f13ad890a5", GitTreeState:"clean", BuildDate:"2022-06-15T14:17:29Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}

### Cloud provider

Bare metal OVH

### OS version

NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

### Install tools

helm 3.5.1

### Container runtime (CRI) and version (if applicable)

Crio version 1.21.14

### Related plugins (CNI, CSI, ...) and versions (if applicable)

Calico v3.6.2

**Comment by dims** [comment]
folks, please look at the debugging steps here:
https://github.com/kubernetes/registry.k8s.io/blob/main/docs/debugging.md

this will help us with important details on what broke

**Comment by BenTheElder** [comment]
should be resolved https://github.com/kubernetes/registry.k8s.io/issues/234#issuecomment-1524456564
