### ISSUE TITLE
[aws] Need a new AWS account to replace 607362164682

### ISSUE THREAD

**Issue by dims** [kubernetes/k8s.io#5194]
Folks,

I've been wondering about account `607362164682` and finally tracked it down. Once upon a time @gyuho created this account for some of the AWS
related repositories that needed to run CI jobs.

<img width="462" alt="image" src="https://user-images.githubusercontent.com/23304/235199154-feb587c0-53ba-484c-bb7a-8fa390f047ae.png">

Let's please create a new account from our AWS credits to replace this account.

References:
- https://cs.k8s.io/?q=607362164682&i=nope&files=&excludeFiles=audit&repos=
- https://github.com/kubernetes/test-infra/pull/9811
- https://github.com/kubernetes/test-infra/pull/10868/files#diff-b6b7a809f492819b6087cd9c020844bcc1671c578abaa25f18cec5ff79c6ca28R3

Query to find instances to fix:
- https://cs.k8s.io/?q=preset-aws-credential-aws-(oss%7Cshared)&i=nope&files=&excludeFiles=&repos=

Repositories
- [x] aws-ebs-csi-driver ( https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/1745 needs to merge )
- [x] aws-efs-csi-driver ( https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/1137 needs to merge )
- [x] aws-fsx-csi-driver ( https://github.com/kubernetes-sigs/aws-fsx-csi-driver/pull/354 needs to merge )
- [x] aws-fsx-openzfs-csi-driver
- [x] aws-iam-authenticator
- [x] aws-load-balancer-controller
- [x] cloud-provider-aws
- [x] secrets-store-csi-driver

**Comment by dims** [comment]
@xmudrii @ameukam - how about `k8s_infra_eks_e2e_shared_001` as the name 

Since:
- We used  `k8s_infra_eks_e2e_boskos_XXX` pattern in https://github.com/kubernetes/k8s.io/pull/5185
- But this is not boskos
- And this goes into a shared credential file ( https://github.com/kubernetes/test-infra/blob/e4624a5858a436fb4d238e7580fa712537255c6f/config/jobs/kubernetes/sig-cloud-provider/aws/sig-aws-credentials.yaml#L18-L30 )

**Comment by BenTheElder** [comment]
Or else if not shared boskos, this should probably be N different accounts? so we can better track billing, since it's being used for different subprojects (storage, loadbalancer, etc).

**Comment by ameukam** [comment]
LGTM for the naming pattern. 

+1 on moving to a boskos pool.

**Comment by xmudrii** [comment]
+1 for the naming pattern and moving to a boskos pool if possible.

**Comment by dims** [comment]
+1 to boskos as follow ups (we can do it repo by repo with a follow up umbrella issue)

@nnmin-aws had offered to help

**Comment by nckturner** [comment]
Once we have the account we will need to determine what resources are missing in order to run the CI jobs (there may be IAM roles, S3 buckets, etc) and we also need a new injectable secret like we have now that prow jobs can add to their spec.  I'd be interested to know how that was set up actually, i.e. is it creds for an IAM user?  I suppose only @shyamjvs knows :)

**Comment by dims** [comment]
@xmudrii @ameukam @BenTheElder ... so the note from @nckturner precludes us to switch to boskos immediately. 

Let's create this account `k8s_infra_eks_e2e_shared_001` and get some experience with moving jobs one by one and during the process identify stuff we will need to automate to eventually switch to boskos accounts ... (E_DONT_KNOW_IF_WE_WILL_GET_THERE!)

**Comment by torredil** [comment]
We use `607362164682` over at [kubernetes-sigs/aws-ebs-csi-driver](https://github.com/torredil/aws-ebs-csi-driver).


Just a few things we need to take care of here, we'll need to create an [S3 bucket](https://github.com/torredil/aws-ebs-csi-driver/blob/cfe3673b921dd2f50e023371d54fdb2dd219c7a0/hack/e2e/run.sh#LL55C42-L55C57) `k8s-kops-csi-e2e` with write access in the new account and access to an [ECR repository](https://github.com/torredil/aws-ebs-csi-driver/blob/cfe3673b921dd2f50e023371d54fdb2dd219c7a0/hack/e2e/run.sh#L46) `aws-ebs-csi-driver` in `us-west-2` to push the images built for testing.

Lets ensure https://github.com/kubernetes-sigs/boskos/tree/master/aws-janitor runs against the new account to cleanup any leaked resources.

**Comment by ameukam** [comment]
@dims @xmudrii can we close this ? is there any follow-up to do ?

**Comment by xmudrii** [comment]
@ameukam I'm not really sure what's the status of this, @dims might know better

**Comment by dims** [comment]
we still need this. let's create a new one `k8s_infra_eks_e2e_shared_001` and replace usage of `607362164682` over time slowly

**Comment by dims** [comment]
new account is `209411653980`

**Comment by dims** [comment]
calling it! done!

![done-and-done-spongebob](https://github.com/kubernetes/k8s.io/assets/23304/e98bad05-129b-46c8-9ab2-d492a25faefe)

**Comment by dims** [comment]
thanks to everyone who helped with fixing things, reviews and approvals

/close
