### ISSUE TITLE
Hound (cs) Question

### ISSUE THREAD

**Issue by userbradley** [kubernetes/k8s.io#5197]
I have a question about how you're using Hound (cs.k8s.io)

I understand that Prow re-deploys the application when ever changes are made to the contents of the `apps/codesearch` directory

What I am asking is how do you re-deploy the deployment when a new repo is created? I feel like this question could be answered by being part of a SIG, but I have had a look around best I can, and I cant locate anything.

I have deployed it at work, but we are creating repos often on github, which requires we scale the deployment down and then up to get cs to re-find the repos and start indexing.

Any help would be appreciated 

TIA

Reference: 

- https://github.com/kubernetes/k8s.io/tree/main/apps/codesearch

**Comment by dims** [comment]
I use a python script that scrapes the list of repositories in our github orgs:
https://github.com/dims/k8s-code.appspot.com/blob/master/codesearch.k8s.io/fetch-repos.py

you can see a generated `config.json` here:
https://github.com/dims/k8s-code.appspot.com/blob/master/codesearch.k8s.io/config.json

I have a cron script that generates the config.json using the script and bounces `houndd` at a specific time every day.

**Comment by userbradley** [comment]
Sorry forgot to thank you for this, so Thank you!

Greatly appreciate it!
