### ISSUE TITLE
Failures in ci-k8sio-file-promo-mirrors

### ISSUE THREAD

**Issue by dims** [kubernetes/k8s.io#5358]
Seems like the CI job has been failing for a while:
https://testgrid.k8s.io/sig-k8s-infra-k8sio#ci-k8sio-file-promo-mirrors

Example log:
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-k8sio-file-promo-mirrors/1665487495040602112/promote-to-mirrors-staging-build-log.txt

Errors look like:
```
COPY "gs://k8s-artifacts-prod/binaries/kops/1.25.4/darwin/amd64/kops" to "s3://test-artifacts-k8s-io-ap-southeast-1/binaries/kops/1.25.4/darwin/amd64/kops"
level=info msg="uploading to s3://test-artifacts-k8s-io-ap-southeast-1/binaries/kops/1.25.4/darwin/amd64/kops"
level=warning msg="error copying file: error uploading \"s3://test-artifacts-k8s-io-ap-southeast-1/binaries/kops/1.25.4/darwin/amd64/kops\": AccessDenied: Access Denied\n\tstatus code: 403, request id: 34J8PYZQPGQ40S2S, host id: euAx/MgfT6ZvRnDe5PkBJaUeN4dkOhyZuqmOHxIwQ4VSpKJ6JcCgqEDO2WZkBiY8Sul6lP83vKur3aMPrdp04A=="
```

and:
```
error uploading "s3://test-artifacts-k8s-io-ap-southeast-1/binaries/cloud-provider-aws/v1.27.1/windows/amd64/ecr-credential-provider-windows-amd64.sha256": AccessDenied: Access Denied
	status code: 403, request id: A5WWNG0AJ4T7KWP7, host id: 0bdInExWCGynZe/00WYMKmewVaMvzFIptvW3xrec+mkwarDGb3hRQARI8IIxCH9FAaRSBmqg28k=
```

**Comment by dims** [comment]
there was an earlier report which we closed when the file copy worked, but we didn't fix this job :(
https://github.com/kubernetes/k8s.io/issues/4913

**Comment by dims** [comment]
cc @justinsb @ameukam

**Comment by pacoxu** [comment]
This still failed.

Ping @justinsb @ameukam 

@BenTheElder as this is mentioned in https://github.com/kubernetes/k8s.io/issues/4401

> level=warning msg="error copying file: error uploading \"s3://test-artifacts-k8s-io-us-east-2/binaries/kops/1.25.4/darwin/amd64/kops\": AccessDenied: Access Denied\n\tstatus code: 403, request id: N8J3C7G9CYJTBA5K, host id: ldYOWD7BxhCQtJq7f+rbSx304Z2jpCfn3nAHrWkIPXRm/TrDL3OV7FUXqH+h04gsd7XrhqhPqVA="
