### ISSUE TITLE
Link for https://gcsweb.k8s.io  broken in Readme.md

### ISSUE THREAD

**Issue by kundan2707** [kubernetes/k8s.io#5412]
Link for https://gcsweb.k8s.io  broken in Readme.md

**Comment by ameukam** [comment]
@kundan2707   It's not broken. `gcsweb.k8s.io` is not serving a default web page.

See: https://github.com/kubernetes/k8s.io/pull/5413#discussion_r1230231046

**Comment by kundan2707** [comment]
@ameukam thanks for clarifying

**Comment by kundan2707** [comment]
closing as not valid
