### ISSUE TITLE
Image promotion is not working for k8s.gcr.io/cpa/cluster-proportional-autoscaler:v1.8.8-rc.1

### ISSUE THREAD

**Issue by MrHohn** [kubernetes/k8s.io#5432]
We attempted to promote image `cluster-proportional-autoscaler:v1.8.8-rc.1` from staging to prod:
- existing staging image: `gcr.io/k8s-staging-cpa/cluster-proportional-autoscaler:v1.8.8-rc.1`
- expected prod image: `k8s.gcr.io/cpa/cluster-proportional-autoscaler:v1.8.8-rc.1`

https://github.com/kubernetes/k8s.io/pull/5411 was merged for this a few days back. As of now, the image still doesn't seem to be promoted.
```
$ docker pull k8s.gcr.io/cpa/cluster-proportional-autoscaler:v1.8.8-rc.1
Error response from daemon: manifest for k8s.gcr.io/cpa/cluster-proportional-autoscaler:v1.8.8-rc.1 not found: manifest unknown: Failed to fetch "v1.8.8-rc.1" from request "/v2/cpa/cluster-proportional-autoscaler/manifests/v1.8.8-rc.1".
```

We checked the corresponding postsubmit job and there doesn't seem to have obvious error:
- job link: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-k8sio-image-promo/1668691720755220480
- raw logs: https://storage.googleapis.com/kubernetes-jenkins/logs/post-k8sio-image-promo/1668691720755220480/build-log.txt

We are lacking the expertise on debugging this further - could someone help look into this? Thanks.

cc @vadasambar

**Comment by ameukam** [comment]
@MrHohn The images are now promoted to `registry.k8s.io`. 

Please see: https://kubernetes.io/blog/2023/02/06/k8s-gcr-io-freeze-announcement/

**Comment by MrHohn** [comment]
Thanks @ameukam! Yes, `registry.k8s.io/cpa/cluster-proportional-autoscaler:v1.8.8-rc.1` works for me. I certainly missed that announcement.
