### ISSUE TITLE
cluster addon-manager v9.1.7 is not built

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/k8s.io#5446]
https://github.com/kubernetes/kubernetes/blob/c0147ff5282c3aadcc10399ddc001aaeb173a596/cluster/addons/addon-manager/Makefile#L18

Not sure where can I find the post submit job.
```
[root@pacoall ~]# docker pull gcr.io/k8s-staging-addon-manager/kube-addon-manager:v9.1.6
Trying to pull repository gcr.io/k8s-staging-addon-manager/kube-addon-manager ...
v9.1.6: Pulling from gcr.io/k8s-staging-addon-manager/kube-addon-manager
Digest: sha256:49cc4e6e4a3745b427ce14b0141476ab339bb65c6bc05033019e046c8727dcb0
Status: Image is up to date for gcr.io/k8s-staging-addon-manager/kube-addon-manager:v9.1.6
[root@pacoall ~]#
[root@pacoall ~]# docker pull gcr.io/k8s-staging-addon-manager/kube-addon-manager:v9.1.7
Trying to pull repository gcr.io/k8s-staging-addon-manager/kube-addon-manager ...
Pulling repository gcr.io/k8s-staging-addon-manager/kube-addon-manager
unauthorized: authentication required
```

After https://github.com/kubernetes/kubernetes/pull/117573 was merged, there should be v9.1.7 staging image.
- Then I can promote it.

In https://github.com/kubernetes/kubernetes/pull/108313#issuecomment-1050117654, @MrHohn said this is a manual push, and would you help push the v9.1.7 image?

**Comment by MrHohn** [comment]
The staging images for 9.1.7 are now pushed:
- https://gcr.io/k8s-staging-addon-manager/kube-addon-manager:v9.1.7
- https://gcr.io/k8s-staging-addon-manager/kube-addon-manager-amd64:v9.1.7
- https://gcr.io/k8s-staging-addon-manager/kube-addon-manager-arm:v9.1.7
- https://gcr.io/k8s-staging-addon-manager/kube-addon-manager-arm64:v9.1.7
- https://gcr.io/k8s-staging-addon-manager/kube-addon-manager-ppc64le:v9.1.7
- https://gcr.io/k8s-staging-addon-manager/kube-addon-manager-s390x:v9.1.7

@pacoxu Would you help on promoting them? Feel free to add me to the promotion PR, thanks!
