### ISSUE TITLE
Wrong spf registry into kubernetes.io domain

### ISSUE THREAD

**Issue by rikatz** [kubernetes/k8s.io#554]
As stated by @tallclair at mailing list:

```
We've been getting a lot of reports through the Kubernetes bug bounty that kubernetes.io and k8s.io are missing valid SPF records. It looks like there may be a typo? "~all" should be "-all". Does anyone know if this is correct, and if not, how to fix it?

Here's the generic report:

SPF record lookup and validation for: kubernetes.io
SPF records are published in DNS as TXT records.

The TXT records found for your domain are:
v=spf1 include:_spf.google.com ~all
google-site-verification=oPORCoq9XU6CmaR7G_bV00CLmEz-wLGOL7SXpeEuTt8

Checking to see if there is a valid SPF record.

Found v=spf1 record for kubernetes.io:
v=spf1 include:_spf.google.com ~all

evaluating...
SPF record passed validation test with pySPF (Python SPF library)!

Use the back button on your browser to return to the SPF checking tool without clearing the form.

Remediation :

Replace ~all with -all to prevent fake email.
```

So this issue is to replace the ~all to -all into all kubernetes domains.

**Comment by puerco** [comment]
No, they are wrong. GSuite domains are supposed to have the ~ in the SPF. In the real world I think it would be better to have the `-all`. But, strictly speaking, [GSuite docs specify the SPF](https://support.google.com/a/answer/33786?hl=en) with ~:
```
 v=spf1 include:_spf.google.com ~all
```

**Comment by ixdy** [comment]
FYI `~` means soft fail. `-` is hard fail.

**Comment by rikatz** [comment]
IMO in this case hard is better than soft. ~all will let the message pass and rely on the server / user MTA side, -all will tell him to drop. Some might say ~all can be used only in servers transitioning to SPF.

As we're very aware of which are the authorized domains from kubernetes.io domain I think the best approach is to hard fail the SPF

**Comment by cblecker** [comment]
I'm inclined to go along with the current gsuite recommendations as @puerco noted.

**Comment by rikatz** [comment]
Some thoughts:

* Google and GSuite rely on ~all instead of -all trusting the MTA on the other side (receiving a fake kubernetes.io email) will have a threshold good enough to drop the message. 

An example:
- In case a user from Gmail or other good mail provider receives a mail from a non-authorized kubernetes.io IP it have the hability to receive and mark this as SPAM or phishing (softfail), so Google deals nicelly with soft fails

* A non GMail/Office365/whatever descent mail provider that deals with softfail - The email 'might' be flagged by SpamAssassin or whatever the user uses in its border but, still the email will pass. We can not assure that a soft failed validation will drop the fake message from users' Inbox

So, this is all about risks. Are we OK to pass an email from a kubernetes.io domain to users MTA (are they Gmail, Office 365 or the user's very own MTA in its DC) and rely that it will have the right treatment later, or we are not ok and prefer to drop the message if it cames from a non authorized IP not mapped in the domain registry.

IMO the second is the best, as it assures that if the destination MTA validates the SPF it will not have any more work than just dropping the message (and not flagging it as SPAM or whatever). But I might be a little paranoid with this security thing so need your thoughts :)

**Comment by cblecker** [comment]
> Are we OK to pass an email from a kubernetes.io domain to users MTA (are they Gmail, Office 365 or the user's very own MTA in its DC) and rely that it will have the right treatment later

Yes, I am okay with this. We don't send out sensitive things like passwords, and it is more detrimental in my opinion for us to get caught in spam filters than not.

@dims @BenTheElder @thockin: Unless any of you have any objections, I think this is a NOTABUG/WONTFIX.

**Comment by BenTheElder** [comment]
I am out of my depth here 🙃

**Comment by dims** [comment]
~no-objections

**Comment by stp-ip** [comment]
Not sure us changing `~` to `-` would change anything.
The SPF records afaik evaluate each rule in order. Meaning the mentioned `spf.google.com` link would get evaluated first, which uses `~all`. That would mean it most likely always passes as softfail and wouldn't normally jump into our own hard fail configured via `-all`.

SPF is definitely not my area of expertise so might be wrong on the above.
Couldn't find a definitive answer about it in the RFC: https://tools.ietf.org/html/rfc7208

**Comment by cblecker** [comment]
Thank you everyone for jumping on this and responding to the questions/concerns. We really do appreciate it.

At this time, we are going to hold off on any changes to this as we are currently following Gsuite's documentation on this.
