### ISSUE TITLE
Enable WAF for `prod-cdn.packages.k8s.io` CloudFront distribution

### ISSUE THREAD

**Issue by xmudrii** [kubernetes/k8s.io#5617]
We should enable WAF for CloudFront distribution used for serving packages (`prod-cdn.packages.k8s.io`). This is recommended by AWS folks (ref: https://kubernetes.slack.com/archives/CCK68P2Q2/p1688756337211689?thread_ts=1688752253.984129&cid=CCK68P2Q2) as a cheap way to block malicious requests and requests that doesn't make much sense (404s).

This should be doable with Terraform, but some additional resources are needed. We should try to do this before putting OBS in the production.

/assign
/sig release
/area release-eng
/priority important-soon

**Comment by remram44** [comment]
What are remediation steps when users are caught by this? Do you just give up on users hit by false-positives with no recourse?

This seems very community-hostile to be honest. Very disappointing to see this move right after launching this supposedly "community" repository.

**Comment by xmudrii** [comment]
@remram44 We try our best to accommodate all requests that we receive. For example, we did some adjustments in #5823 to enable `tdnf` users to use the new package repositories. If you experience any issues with pkgs.k8s.io, please create a new issue in this repository and we'll do our best to accommodate your request.
