### ISSUE TITLE
eks-prow-build-cluster: Configure EKS Node Group dedicated for KIND jobs

### ISSUE THREAD

**Issue by pkprzekwas** [kubernetes/k8s.io#5641]
While investigating [cluster instability issues](https://github.com/kubernetes/k8s.io/issues/5473), we noticed some correlation between failing nodes and types of jobs running on them. We suspect that kind jobs might be the reason for node problems. 

To proof our hypothesis we want to configure a dedicated node group with appropriate labels and taints so that we could schedule there kind jobs.

**Comment by BenTheElder** [comment]
Erm ... can we CC kind maintainers on issues like this in the future? cc @aojea
