### ISSUE TITLE
Some Hetzner Cloud IPs blocked for dl.k8s.io and apt.kubernetes.io

### ISSUE THREAD

**Issue by wiegelmann** [kubernetes/k8s.io#5655]
Since July, 24th we get 403 Forbidden for some IPs on Hetzner Cloud when using curl to download https://dl.k8s.io/apt/doc/apt-key.gpg and fetching packages from https://apt.kubernetes.io - is this a known issue by Fastly? Other IPs are working fine.

**Comment by tcurdt** [comment]
@wiegelmann I just ran into the same issue. How did you get this resolved?

**Comment by wiegelmann** [comment]
Hosting a mirror on another machine.
