### ISSUE TITLE
cdn.dl.k8s.io responding with `ERROR 503: Response object too large`

### ISSUE THREAD

**Issue by dims** [kubernetes/k8s.io#5659]
```
$ wget https://cdn.dl.k8s.io/gci-mounter/mounter.tar
--2023-07-29 00:14:06--  https://cdn.dl.k8s.io/gci-mounter/mounter.tar
Resolving cdn.dl.k8s.io (cdn.dl.k8s.io)... 151.101.1.55, 151.101.65.55, 151.101.129.55, ...
Connecting to cdn.dl.k8s.io (cdn.dl.k8s.io)|151.101.1.55|:443... connected.
HTTP request sent, awaiting response... 503 Response object too large
2023-07-29 00:14:07 ERROR 503: Response object too large.
```

**Comment by dims** [comment]
cc @ameukam @xmudrii

**Comment by dims** [comment]
Fixed one use here: https://github.com/kubernetes/kubernetes/pull/119663

**Comment by dims** [comment]
link to slack thread:
https://kubernetes.slack.com/archives/CCK68P2Q2/p1690596549284829

**Comment by xmudrii** [comment]
Let's use this issue to collect PRs where we switched to using the bucket directly instead of CDN, so that we can easily revert later:

- https://github.com/kubernetes/kubernetes/pull/119663
- https://github.com/kubernetes/kubernetes/pull/119671
- https://github.com/kubernetes/cloud-provider-gcp/pull/585

**Comment by BenTheElder** [comment]
xref https://github.com/kubernetes/k8s.io/issues/5726

I bet there are some knobs related to this. Been waiting for arnaud to be back to strike up discussion 😅

**Comment by dims** [comment]
cc @ameukam

**Comment by ameukam** [comment]
For gci-mounter, I think there is low value on trying to download trought the cdn. I think it's GCP specific (or only can be used with GCP-compatible APIs) and AFAIC unmaintained. We should probably copy it to a regional and community-owned GCS bucket.

**Comment by ameukam** [comment]
@dims Do we still need this ?

**Comment by dims** [comment]
/close

thanks for the reminder closing it
