### ISSUE TITLE
eks-prow-build-cluster: separate canary manifests from prod

### ISSUE THREAD

**Issue by pkprzekwas** [kubernetes/k8s.io#5689]
As we configure more services, differences between prod and canary configurations expands. In order to use Flux with different configs for prod and canary we need to create a dedicated set of manifests for canary. Previously we tries to use kustomize, but as explained in the [PR](https://github.com/kubernetes/k8s.io/pull/5539), we decided that introduced complexity is to high. In new approach we simply duplicate manifests so that each cluster has a dedicated folder.

/area infra/aws
/assign @pkprzekwas 
/cc @ameukam @dims @xmudrii

**Comment by xmudrii** [comment]
Canary will be decommissioned after some testing is done, this is no longer relevant
/close
