### ISSUE TITLE
k8s-infra-aws-boskos-accounts+scale-001 / aws-credential-boskos-scale-001-kops

### ISSUE THREAD

**Issue by dims** [kubernetes/k8s.io#5715]
account `226543828060` AKA account for scalability jobs needs higher quota limits

slack discussion thread with @hakman :
https://kubernetes.slack.com/archives/CCK68P2Q2/p1691857294826629?thread_ts=1691839199.907579&cid=CCK68P2Q2

regions:
```
	"ap-northeast-1",
	"ap-northeast-2",
	"ap-south-1",
	"ap-southeast-1",
	"ap-southeast-2",
	"ca-central-1",
	"eu-central-1",
	"eu-west-1",
	"eu-west-2",
	"eu-west-3",
	"sa-east-1",
	"us-east-1",
	"us-east-2",
	"us-west-1",
	"us-west-2",
```

specifically the kops scalability job as configured, needs the following:
```
3 x c6g.16xlarge and 500 x c6g.medium
```

**Comment by dims** [comment]
cc @ameukam @pkprzekwas

**Comment by dims** [comment]
create case id `13542169821` and `13541952831` from `k8s-infra-aws-root-account` (`266690972299`)

```
[US East (Ohio)]: EC2 Instances / All G instances, New Limit = 800
``

and 

```
[US East (Northern Virginia)]: EC2 Instances / All G instances, New Limit = 800
```

**Comment by hakman** [comment]
@dims Shouldn't the requests be for `All Standard (A, C, D, H, I, M, R, T, Z) Spot Instance Requests` ?

**Comment by dims** [comment]
we use spot?

**Comment by hakman** [comment]
Sorry, meant `Running On-Demand Standard (A, C, D, H, I, M, R, T, Z) instances` - `L-1216C47A`.

**Comment by dims** [comment]
looks like that's bumped already

<img width="725" alt="image" src="https://github.com/kubernetes/k8s.io/assets/23304/15070281-6093-497d-9976-c5bacf1aa612">

**Comment by hakman** [comment]
@dims I tested specifically in us-east-1 and works ok, just that it needs still more quota.

**Comment by ameukam** [comment]
The quotas were already increased for a specific region (us-east-2) in https://github.com/kubernetes/k8s.io/issues/5071. why not fix the region used for the prowjob using kops ? AFAIK for some scalability tests in GCP, the region is predefined.

**Comment by hakman** [comment]
@ameukam Not sure what the right region is, but in us-east-2 I get this:
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kops/15778/presubmit-kops-aws-scale-amazonvpc-using-cl2/1691244356519858176
```
InstanceGroup "nodes-us-east-2a" did not have enough nodes 200 vs 500
```

**Comment by ameukam** [comment]
Opened case `13561229021` in `226543828060` for region `us-east-2` to bump again the limit. We were somehow downgraded to `384` without notification.

**Comment by ameukam** [comment]
@dims I think we are done with this ?

**Comment by dims** [comment]
yes!

/close
