### ISSUE TITLE
cdn.dl.k8s.io doesn't seem to be cutting bandwidth to the backing GCS bucket

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/k8s.io#5726]
I suspect the objects are too large for the current cache configuration? Not an expert with fastly.

cc @dims @ameukam 

We don't have super good visibility on the bucket end of things just because I don't know anyone that currently has e.g. audit log access, but I can provide bandwidth graphs (there's a lot of noise) and we have graphs on the fastly side.

Best I can tell looking at the fastly UI and the GCS bandwidth graphs .... we're basically operating in pull-through mode w/o caching.

We'll need to fix this before we can rotate to a kubernetes.io GCS bucket (or S3 on AWS or ...).

**Comment by BenTheElder** [comment]
Concretely: I think we need to improve our fastly configuration to ensure binaries are actually cached. There was a slack thread suggesting the default is <20MB but that would exclude most or all of kubernetes core binaries ...

**Comment by BenTheElder** [comment]
For context: https://github.com/kubernetes/k8s.io/pull/5603 merged July 24th.

This may be working better than we thought, but we should still be confirming if we have suitable caching parameters etc.

requests:
<img width="794" alt="Screenshot 2023-08-23 at 11 59 14 AM" src="https://github.com/kubernetes/k8s.io/assets/917931/a797ac45-e579-4eed-9d67-cb300494360d">

sent bytes:
<img width="797" alt="Screenshot 2023-08-23 at 11 59 55 AM" src="https://github.com/kubernetes/k8s.io/assets/917931/e4b0b098-87c7-4041-98fb-77864f9cabe8">

**Comment by BenTheElder** [comment]
I think we should replace this with new issues about revisiting the config, the bandwidth is definitely down.

@xmudrii mentioned an issue with slow downloads, but I don't think we have a tracking issue yet.

**Comment by xmudrii** [comment]
I created #5755 to track the problem with slow downloads.

**Comment by xmudrii** [comment]
I created #5757 to track increasing cache TTL, this might further reduce bandwidth to the origin bucket.
