### ISSUE TITLE
address GCS bucket for downloads in host instead of url path prefix

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/k8s.io#5727]
We discussed with Fastly that we should probably address the bucket name in the host instead of the URL path so we can more easily switch buckets later without busting the cache.

This is a low-prio backlog item as due to https://github.com/kubernetes/k8s.io/issues/5726 there doesn't appear to be much of a cache to bust.

**Comment by BenTheElder** [comment]
cc @ameukam (also present in the discussion w/ fastly)

**Comment by BenTheElder** [comment]
Is this done now? https://github.com/kubernetes/k8s.io/pull/6509

**Comment by ameukam** [comment]
> Is this done now? #6509

No. Need to be deployed in prod. 
Will get some bandwidth soon to get this deployed.
