### ISSUE TITLE
aaa: Migrate to Gateway API.

### ISSUE THREAD

**Issue by ameukam** [kubernetes/k8s.io#5862]
we currently serve all workloads using the default GKE ingress controller. we should migrate to Gateway API when it reaches 1.0 on the GKE cluster.

Reference:
 - https://cloud.google.com/kubernetes-engine/docs/concepts/gateway-api

**Comment by BenTheElder** [comment]
Hmm, what's the argument here? The gateway project is great, but we're doing very simple things and migrating has a cost.

**Comment by ameukam** [comment]
Nothing very specific. 
Happy to close this if we don't think there is a need to migrate to `HTTPRoutes`.

**Comment by ameukam** [comment]
Not strong argument to do this. Ingress is stable API and will not be deprecated.

/close
