### ISSUE TITLE
Investigate usage of VMC for CAPV tests

### ISSUE THREAD

**Issue by ameukam** [kubernetes/k8s.io#5864]
CAPV currently run tests inside VMware-owned AWS account using vSphere Cloud on AWS service(VMC). The service can be used on the community infrastructure. 

It's still unclear to me how VMC is integrated to [VMware Cloud](https://console.cloud.vmware.com/csp/gateway/discovery). 

Update: projects eligible :
- https://github.com/kubernetes-sigs/cluster-api-provider-vsphere
- https://github.com/kubernetes-sigs/image-builder
- https://github.com/kubernetes/cloud-provider-vsphere

/sig cluster-lifecycle
/area infra/aws
/priority important-longterm
/milestone v1.29

**Comment by ameukam** [comment]
cc @sbueringer @chrischdi @killianmuldoon @fabriziopandini

**Comment by dims** [comment]
supportive for sure. Let's come up with some numbers for how much it costs for helping with the decision making process.

**Comment by chrischdi** [comment]
*Adding cloud-provider-vsphere to the list, because they use the same environment / capabilities (share the same environment)

**Comment by ameukam** [comment]
> supportive for sure. Let's come up with some numbers for how much it costs for helping with the decision making process.

@dims I think for the transition we will need an environment with 6 hosts. According to the [pricing calculator](https://www.vmware.com/products/vmc-on-aws/pricing-calculator.html), we estimate the monthly cost of $32k per month.

**Comment by dims** [comment]
@ameukam wow, that's quite a lot per year. especially if we add some head room (say 40k/month means close to half-a-million)

**Comment by dims** [comment]
@ameukam can you please check if there's something can be done from VMware side?

**Comment by ameukam** [comment]
Closing this in favor of https://github.com/kubernetes/k8s.io/issues/6877.

/close
