### ISSUE TITLE
AWS: setup account for windows operational readiness

### ISSUE THREAD

**Issue by ameukam** [kubernetes/k8s.io#5873]
Setup an AWS account to fullfill the goal defined in:
  - https://github.com/kubernetes/funding/issues/40. 

/sig windows
/milestone v1.29
/priority important-soon

**Comment by ameukam** [comment]
cc @dims

**Comment by ameukam** [comment]
cc @jayunit100 @aroradaman

**Comment by dims** [comment]
👍🏾

**Comment by ameukam** [comment]
This is done.

/close
