### ISSUE TITLE
Requesting Elastic IP address quota increase

### ISSUE THREAD

**Issue by torredil** [kubernetes/k8s.io#5909]
Requesting Elastic IP address quota increase.

- Account: `209411653980`
- Region: `us-west-2`

-----

We've seen some CI failures over at https://github.com/kubernetes-sigs/aws-ebs-csi-driver recently as a result of the following error:
```
2023-09-28 19:15:43 [✖]  AWS::EC2::EIP/NATIP: CREATE_FAILED – "Resource handler returned message: \"The maximum number of addresses has been reached. (Service: Ec2, Status Code: 400, Request ID: 6f4747f2-4b50-4f63-ae47-8e2d0119a66f)\" (RequestToken: 389d630d-6885-082b-8899-77d9456bd0f7, HandlerErrorCode: GeneralServiceException)"
```

See an example test run here: https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_aws-ebs-csi-driver/1764/pull-aws-ebs-csi-driver-test-e2e-external-eks-windows/1707467686071504896/build-log.txt

Also reporting this on behalf of `aws-load-balancer-controller` folks who are also running into this: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_aws-load-balancer-controller/3407/pull-aws-load-balancer-controller-e2e-test/1707485234976526336

cc: @dims @oliviassss

**Comment by dims** [comment]
@torredil does this look right?

<img width="717" alt="image" src="https://github.com/kubernetes/k8s.io/assets/23304/8c44780d-ad42-47f6-87e2-0e375df209f5">

**Comment by torredil** [comment]
lgtm, might need to follow up with support folks to get that request approved but can certainly be done https://github.com/kubernetes/k8s.io/issues/5390#issuecomment-1586892334.

**Comment by dims** [comment]
```
Limit increase request 1
Service: Elastic IPs
Region: US West (Oregon)
Limit name: New VPC Elastic IP Address Limit
New limit value: 100
```
✅
