### ISSUE TITLE
Automation service accounts for `k8s-artifacts-` buckets

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes/k8s.io#5957]
SIG Release (aka @kubernetes/release-managers) maintains various buckets in the `k8s-artifacts-prod` project:

- [k8s-artifacts-sig-release](https://console.cloud.google.com/storage/browser/k8s-artifacts-sig-release)
- [k8s-artifacts-cni](https://console.cloud.google.com/storage/browser/k8s-artifacts-cni)
- [k8s-artifacts-cri-tools](https://console.cloud.google.com/storage/browser/k8s-artifacts-cri-tools)

It would be good to have a dedicated service account to automatically publish binaries for each tag and repository to avoid manually invocations of [`kpromo gh`](https://github.com/kubernetes-sigs/promo-tools#kpromo).

The tokens could be stored in our 1Password vault.

**Comment by xmudrii** [comment]
+1 as a Release Manager

**Comment by ameukam** [comment]
We could also reuse existing service accounts and grant them permissions to push to those buckets.

**Comment by saschagrunert** [comment]
> We could also reuse existing service accounts and grant them permissions to push to those buckets.

Would it be better security wise to have a dedicated service account per bucket?

**Comment by ameukam** [comment]
> > We could also reuse existing service accounts and grant them permissions to push to those buckets.
> 
> Would it be better security wise to have a dedicated service account per bucket?

it depends on the entities that use these service accounts. As long we are inside the GCP perimeter, IMHO, reuse existing service accounts is fine. 
However, it's recommended to use short-lived tokens rather than JSON creds.

**Comment by saschagrunert** [comment]
> However, it's recommended to use short-lived tokens rather than JSON creds.

How would that work, for example when using GitHub actions?

**Comment by saschagrunert** [comment]
The only service account I can see is `k8s-infra-promoter@k8s-artifacts-prod.iam.gserviceaccount.com` which has write access to the buckets. Should we use this one?

**Comment by xmudrii** [comment]
I prefer that we create a new service account, especially because this SA might be used outside Prow (e.g. with GitHub Actions)

**Comment by ameukam** [comment]
> > However, it's recommended to use short-lived tokens rather than JSON creds.
> 
> How would that work, for example when using GitHub actions?

I remember @upodroid mentioned this article. https://cloud.google.com/blog/products/identity-security/enabling-keyless-authentication-from-github-actions which in resume means the Github Actions will assume an existing SA.

We can start with a new and single SA to cover all the buckets handled by RelEng.

**Comment by ameukam** [comment]
From the convo on Slack, we can start with one single GCP Service Account to handle artifacts publication.

@xmudrii @saschagrunert Feel free to open PR against the repo and I'll actuate it.

**Comment by saschagrunert** [comment]
Ref https://github.com/kubernetes/k8s.io/pull/5997
