### ISSUE TITLE
Scripts should not require GOOGLE_APPLICATION_CREDENTIALS

### ISSUE THREAD

**Issue by fejta** [kubernetes/k8s.io#597]
Best practice is to use workload identity on GCP: 

https://github.com/kubernetes/k8s.io/blob/5cf0052cc18f6a6d00eb449ffdeb22451eb366f2/infra/gcp/backup_tools/backup_lib.sh#L58-L60

kubernetes/test-infra#15806

/assign @listx

**Comment by bartsmykla** [comment]
I think it was fixed/changed via: https://github.com/kubernetes/k8s.io/commit/df93036f1ce09b8be632c74c81a2d6ebd7082324

I'm closing the issue for now, but @listx @fejta feel free to reopen it if I'm wrong
