### ISSUE TITLE
`https://dl.k8s.io/release/v1.28.3/bin/linux/amd64/kubectl` partially missing

### ISSUE THREAD

**Issue by omertuc** [kubernetes/k8s.io#5996]
In our CI we've recently started seeing `curl -L https://dl.k8s.io/release/v1.28.3/bin/linux/amd64/kubectl ` is returning a 404 with:

```xml
<?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Details>No such object: kubernetes-release/release/v1.28.3/bin/linux/amd64/kubectl</Details></Error>
```

In some countries, when we try to run this `curl` command on our laptops, we get the 404.
In other countries, when we try to run this `curl` command on our laptops, we get the binary.

Is there some issue with the CDN?

This has been [ongoing](https://prow.ci.openshift.org/job-history/gs/origin-ci-test/pr-logs/directory/pull-ci-openshift-assisted-service-master-edge-e2e-metal-assisted) almost 20 hours now

**Comment by ameukam** [comment]
I was able to reproduce this in a GCP environment:

```bash
 curl -L https://dl.k8s.io/release/v1.28.3/bin/linux/amd64/kubectl
<?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Details>No such object: kubernetes-release/release/v1.28.3/bin/linux/amd64/kubectl
```

**Comment by pmcgrath** [comment]
This seems to be working for me at least
```
$ curl -Ls https://dl.k8s.io/release/v1.28.3/bin/linux/amd64/kubectl -o /tmp/kubectl -w "%{http_code}\n"
200

$ chmod +x /tmp/kubectl

$ /tmp/kubectl version
Client Version: v1.28.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
The connection to the server 127.0.0.1:39647 was refused - did you specify the right host or port?
```

**Comment by omertuc** [comment]
Yeah, it works for me too in my home using my laptop, but as stated it doesn't work in both our CI and some user laptops we tried it on

**Comment by dims** [comment]
xref https://github.com/kubernetes/k8s.io/issues/6003

**Comment by ameukam** [comment]
/close
/duplicate

Issue already reported in https://github.com/kubernetes/k8s.io/issues/6020.
