### ISSUE TITLE
Request cleanup leaked EIPs

### ISSUE THREAD

**Issue by oliviassss** [kubernetes/k8s.io#5999]
Please help to clean up unused Elastic IP addresses:

    Account: 209411653980
    Region: us-west-2

We are seeing ci e2e test failure for aws-load-balancer-controller since yesterday:
```
2023-10-19 17:54:56 [✖]  AWS::EC2::EIP/NATIP: CREATE_FAILED – "Resource handler returned message: \"The maximum number of addresses has been reached. (Service: Ec2, Status Code: 400, Request ID: 8bbbad6a-90a7-4d1d-b098-f4c3f25924eb)\" (RequestToken: 340f7d33-375b-bf56-9957-f783d091e76b, HandlerErrorCode: GeneralServiceException)"
```

error log: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_aws-load-balancer-controller/3436/pull-aws-load-balancer-controller-e2e-test/1715063599556202496#1:build-log.txt%3A211

Ideally, we should consider a mechanism to cleanup the leaked resources in the AWS account.

**Comment by ameukam** [comment]
cc @dims

**Comment by dims** [comment]
https://testgrid.k8s.io/sig-testing-maintenance#ci-shared-aws-janitor&width=20 seems green!

**Comment by dims** [comment]
weird, got turned down twice for bumping # of EIP(s), trying again

<img width="1185" alt="image" src="https://github.com/kubernetes/k8s.io/assets/23304/f70f3d21-a405-4b61-912a-4fdd7a53bb27">

**Comment by dims** [comment]
<img width="985" alt="image" src="https://github.com/kubernetes/k8s.io/assets/23304/85052616-4622-4fea-98f1-cd6a01079b63">
