### ISSUE TITLE
v1.27.7 linux amd64 kubectl binary seems to be missing

### ISSUE THREAD

**Issue by pmcgrath** [kubernetes/k8s.io#6003]
As reported on the k8s #release-management slack channel

Seeing consistent 404s for the v1.27.7 `linux amd64 kubectl` binary, assumed I would have to wait some time, but would be fully distributed at this stage, 1 day after the release

I have tried this from a few different machines and can consistently see most of the files are available, except kubectl linux amd64 - have never got a 200 for this one

```
# Get kubectl linux amd64 sha256 file - SUCCESS 
$ curl -Ls https://dl.k8s.io/release/v1.27.7/bin/linux/amd64/kubectl.sha256 -o /tmp/kubectl.sha256 -w "%{http_code}\n"
200


# Content for above - SUCCESS
$ cat /tmp/kubectl.sha256
e5fe510ba6f421958358d3d43b3f0b04c2957d4bc3bb24cf541719af61a06d79


# Get kubectl linux amd64 file - FAILURE
$ curl -Ls https://dl.k8s.io/release/v1.27.7/bin/linux/amd64/kubectl -o /tmp/kubectl -w "%{http_code}\n"
404


# Content for above - CDN key not found
$ cat /tmp/kubectl
<?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Details>No such object: kubernetes-release/release/v1.27.7/bin/linux/amd64/kubectl</Details></Error>


# Get kubectl linux arm64 file - SUCCESS - just to illustrate other binaries are available
$ curl -Ls https://dl.k8s.io/release/v1.27.7/bin/linux/arm64/kubectl -o /tmp/kubectl -w "%{http_code}\n"
200


# File system entry for above - as expected indicating success
$ ls -al /tmp/kubectl
-rw-rw-r-- 1 pmcgrath pmcgrath 47054848 Oct 19 23:00 /tmp/kubectl
```

So I can the binaries for the `linux arm64` kubelet, but getting 404s for the `linux amd64` kubelet
Can get kubeadm binaries, only one I see failing is this one

**Comment by ameukam** [comment]
There is an issue with our current CDN provider. We are currently taking a look.

**Comment by dims** [comment]
xref https://github.com/kubernetes/k8s.io/issues/5996

**Comment by pmcgrath** [comment]
xref https://github.com/kubernetes/k8s.io/issues/6010
Same issue and as indicated in above issue, just seeing in AWS eu-west-1 region, getting a 200 on AWS us-east-1

**Comment by ameukam** [comment]
A fix was rolled out and cache was purged for this path. I think it should be ok now

**Comment by pmcgrath** [comment]
Thanks, working as expected now, closing this issue
