### ISSUE TITLE
Download of latest k8s kubectl artefacts failing

### ISSUE THREAD

**Issue by bb-Ricardo** [kubernetes/k8s.io#6020]
Not sure where exactly to report this.

**What happened**:
Since the release of 1.27.7, 1.26.10 and 1.25.15 the download for certain binaries from https://dl.k8s.io seems broken.

**What you expected to happen**:
That the download of released binaries works as usual.

**How to reproduce it (as minimally and precisely as possible)**:
1. go to https://www.downloadkubernetes.com
2. try to download `kubectl` version 1.27.7 for linux amd64

**Anything else we need to know?**:
This seems to apply only for certain files.

The file `https://dl.k8s.io/v1.27.7/bin/linux/amd64/kubectl.sha256` is present but the actual `kubectl` binary is missing.
```
ERROR: 	download of 'https://dl.k8s.io/v1.27.7/bin/linux/amd64/kubectl' failed
ERROR: 	download of 'https://dl.k8s.io/v1.26.10/bin/linux/amd64/kubectl' failed
ERROR: 	download of 'https://dl.k8s.io/v1.25.15/bin/linux/amd64/kubectl.sha256' failed
ERROR: 	download of 'https://dl.k8s.io/v1.25.15/bin/linux/amd64/kubectl' failed
ERROR: 	download of 'https://dl.k8s.io/v1.26.10/bin/windows/amd64/kubectl.exe' failed
```

**Comment by bb-Ricardo** [comment]
That was my suspicion as well. 

I'm located in Germany. 

Wrote a little test script:
```bash
A_P=0; A_F=0
for BIN in $(curl -sL https://github.com/kubernetes-sigs/downloadkubernetes/raw/master/dist/release_binaries.json | \
jq -r '.Binaries[] | ("https://dl.k8s.io/" +.Version+"/bin/"+.OperatingSystem+"/"+.Architecture+"/"+.Name)'); do 
    for BIN_URL in $BIN ${BIN}.sha256 ${BIN}.sig ${BIN}.cert; do
        HTTP_STATUS=$(curl -w "%{http_code}" -o /dev/null -LIs "$BIN_URL")
        if [[ $HTTP_STATUS -eq 200 ]]; then ((A_P++)) else ((A_F++)); fi
        printf "HTTP status %s : %s\n" "$HTTP_STATUS" "$BIN_URL"
    done
    [[ $((A_P+A_F)) -gt 20 ]] && break 
done
printf "num artefacts: %s, artefacts present: %s, artefacts failed: %s, fail rate: %s%%\n" "$((A_P+A_F))" "$A_P" "$A_F" "$(((100/(A_P+A_F))*A_F))"
```

result (only failures):
```
HTTP status 404 : https://dl.k8s.io/v1.28.3/bin/darwin/arm64/kubectl
HTTP status 404 : https://dl.k8s.io/v1.26.10/bin/linux/amd64/kubectl
HTTP status 404 : https://dl.k8s.io/v1.26.10/bin/windows/amd64/kubectl.exe

num artefacts: 1136, artefacts present: 1133, artefacts failed: 3, fail rate: 0%
```

**Comment by BenTheElder** [comment]
Are we setting this still after https://github.com/kubernetes/k8s.io/pull/6014 ?

**Comment by ameukam** [comment]
@bb-Ricardo Can we close this ?

**Comment by bb-Ricardo** [comment]
@ameukam: the missing artefacts seem to be available now.

Do you have an idea what caused the issue or how to prevent it in the future?

I guess we can close the issue

**Comment by BenTheElder** [comment]
> Do you have an idea what caused the issue or how to prevent it in the future?



https://github.com/kubernetes/k8s.io/pull/6014 + needing to purge stale cache after that
