### ISSUE TITLE
flake: kubectl 1.28.3 (arm64) is sometimes reported as missing

### ISSUE THREAD

**Issue by maxdanilov** [kubernetes/k8s.io#6025]
**What happened**:

I was following the instructions [here](https://kubernetes.io/docs/tasks/tools/install-kubectl-macos/) to download the latest version of kubectl for Mac M1:

```bash
curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/darwin/arm64/kubectl"
```

(`curl -L -s https://dl.k8s.io/release/stable.txt` resolves to `v1.28.3`)

The following is the contents of the resulting file instead of a binary (`cat kubectl`):

```
<?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Details>No such object: kubernetes-release/release/v1.28.3/bin/darwin/arm64/kubectl</Details></Error>%
```

The same error happens for the ARM64 Linux version.
The error is not happening for the Mac Intel version or x86 version for Linux.

**What you expected to happen**:

The Apple Silicon and Linux ARM `kubectl` binaries for 1.28.3 are available for download.

**How to reproduce it (as minimally and precisely as possible)**:

Run 

```
curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/darwin/arm64/kubectl"
```

and `cat kubectl`

**Anything else we need to know?**:

**Environment**:
- Kubernetes client and server versions (use `kubectl version`): 1.28.3 for ARM
- Cloud provider or hardware configuration: (not applicable)
- OS (e.g: `cat /etc/os-release`): MacOS 13.5 (M1) - but can be reproduced on any machine

**Comment by neolit123** [comment]
/retitle flake: kubectl 1.28.3 (arm64) is sometimes reported as missing

**Comment by maxdanilov** [comment]
I believe the issue is only with `darwin` (MacOS) flavour now.

This fails 100% of the time:

```
wget https://dl.k8s.io/release/v1.28.3/bin/darwin/arm64/kubectl
```
```
--2023-10-26 17:04:38--  https://dl.k8s.io/release/v1.28.3/bin/darwin/arm64/kubectl
Resolving dl.k8s.io (dl.k8s.io)... 34.107.204.206
Connecting to dl.k8s.io (dl.k8s.io)|34.107.204.206|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://cdn.dl.k8s.io/release/v1.28.3/bin/darwin/arm64/kubectl [following]
--2023-10-26 17:04:38--  https://cdn.dl.k8s.io/release/v1.28.3/bin/darwin/arm64/kubectl
Resolving cdn.dl.k8s.io (cdn.dl.k8s.io)... 151.101.129.55, 151.101.1.55, 151.101.65.55, ...
Connecting to cdn.dl.k8s.io (cdn.dl.k8s.io)|151.101.129.55|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-10-26 17:04:39 ERROR 404: Not Found.
```
(1.28.2 works)

**Comment by neolit123** [comment]
> I believe the issue is only with darwin (MacOS) flavour now.

it works for me:

```
wget https://dl.k8s.io/release/v1.28.3/bin/darwin/arm64/kubectl
--2023-10-26 18:10:56--  https://dl.k8s.io/release/v1.28.3/bin/darwin/arm64/kubectl
Resolving dl.k8s.io (dl.k8s.io)... 34.107.204.206, 2600:1901:0:26f3::
Connecting to dl.k8s.io (dl.k8s.io)|34.107.204.206|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://cdn.dl.k8s.io/release/v1.28.3/bin/darwin/arm64/kubectl [following]
--2023-10-26 18:10:56--  https://cdn.dl.k8s.io/release/v1.28.3/bin/darwin/arm64/kubectl
Resolving cdn.dl.k8s.io (cdn.dl.k8s.io)... 146.75.53.55, 2a04:4e42:7d::311
Connecting to cdn.dl.k8s.io (cdn.dl.k8s.io)|146.75.53.55|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 55363714 (53M) [application/octet-stream]
Saving to: ‘kubectl’

kubectl             100%[===================>]  52,80M  2,22MB/s    in 25s     

2023-10-26 18:11:21 (2,11 MB/s) - ‘kubectl’ saved [55363714/55363714]
```

**Comment by neolit123** [comment]
> (cdn.dl.k8s.io)|151.101.129.55

likely a CDN problem and likely the k8s.io team already know about it.

this sounds like a separate issue:
https://github.com/kubernetes/k8s.io/issues/6025#issuecomment-1781243084

**Comment by ameukam** [comment]
@maxdanilov Still seeing this problem happening ?

**Comment by maxdanilov** [comment]
Seems like it has been resolved, works for me now 👍

**Comment by ameukam** [comment]
Closing this for the moment. Thanks for your patience.

/close
