### ISSUE TITLE
Requesting NATGateway quota increase

### ISSUE THREAD

**Issue by torredil** [kubernetes/k8s.io#6027]
Requesting NATGateway quota increase.

- Account: `209411653980`
- Region: `us-west-2`
-----

We are frequently running into the following over at `kubernetes-sigs/aws-ebs-csi-driver`:

```
2023-10-26 18:01:04 [✖]  AWS::EC2::NatGateway/NATGateway: CREATE_FAILED – "Resource handler returned message: \"Performing this operation would exceed the limit of 5 NAT gateways (Service: Ec2, Status Code: 400, Request ID: 813d64cd-fecc-4b79-9831-86da84e28989)\" (RequestToken: 3a961337-8a6d-6e8d-4c45-290ba9e92dc9, HandlerErrorCode: ServiceLimitExceeded)"
```

See example affected PR: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/1806

cc: @dims @oliviassss

**Comment by oliviassss** [comment]
We are seeing the ci e2e job failure for `aws-load-balancer-controller` since yesterday, not sure if it's related to this issue
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_aws-load-balancer-controller/3453/pull-aws-load-balancer-controller-e2e-test/1717679338473656320#1:build-log.txt%3A373

**Comment by dims** [comment]
@torredil asked for a bump

![image](https://github.com/kubernetes/k8s.io/assets/23304/b9f4760d-0098-4ec5-9755-bf2d4bfa8f1c)

**Comment by dims** [comment]
i do not see any leaks, so it's probably just many tests running at the same time. So the bump should help

**Comment by dims** [comment]
![image](https://github.com/kubernetes/k8s.io/assets/23304/b4eecabf-1fa5-40f2-85a9-ff30587ddbae)

All set. please run as many as you wish in parallel and we can request a bump if this is not enough

**Comment by dims** [comment]
@oliviassss please reopen if you still run into the same issue. looks like the logs clearly should show what is failing, right?

/close
