### ISSUE TITLE
Need a script to generate service account keys for k8s-conform project

### ISSUE THREAD

**Issue by dims** [kubernetes/k8s.io#604]
Thanks to https://blog.csanchez.org/2019/06/11/google-container-registry-service-account-permissions/ for coming up with the following snippet

```
#!/bin/bash

set -xeu

FOR=cri-o
PROJECT_ID=k8s-conform

ACCOUNT=service-${FOR}
BUCKET=${PROJECT_ID}-${FOR}

# enable Google Cloud Storage JSON API for project
gcloud services enable storage-api.googleapis.com --project=$PROJECT_ID

# delete the existing service account and policy binding
gcloud -q iam service-accounts delete ${ACCOUNT}@${PROJECT_ID}.iam.gserviceaccount.com || true
gsutil iam ch -d serviceAccount:${ACCOUNT}@${PROJECT_ID}.iam.gserviceaccount.com gs://${BUCKET} || true

# create a new one
gcloud -q iam service-accounts create ${ACCOUNT} --project ${PROJECT_ID} --display-name ${ACCOUNT}
gcloud -q iam service-accounts keys create "${ACCOUNT}.json" --iam-account=${ACCOUNT}@${PROJECT_ID}.iam.gserviceaccount.com
gsutil iam ch serviceAccount:${ACCOUNT}@${PROJECT_ID}.iam.gserviceaccount.com:objectCreator gs://${BUCKET}
gsutil iam get gs://${BUCKET}

echo "key json is ${ACCOUNT}.json"


```

**Comment by dims** [comment]
related to https://github.com/kubernetes/k8s.io/pull/501#issuecomment-591332061

**Comment by dims** [comment]
Another tip from https://stackoverflow.com/questions/51678745/how-to-restrict-a-google-service-account-to-a-single-bucket-in-google-cloud-stor

**Comment by dims** [comment]
also related to https://github.com/kubernetes/k8s.io/pull/459

**Comment by dims** [comment]
I've generated a key for each of
- cri-o ( handed to @saschagrunert )
- huaweicloud ( handed to @RainbowMango )
- capi-openstack ( handed to @sbueringer )

**Comment by dims** [comment]
related to https://github.com/kubernetes/test-infra/pull/16515

**Comment by thockin** [comment]
Can you say more about why they need keys rather than just being in the correct googlegroup?

**Comment by thockin** [comment]
@saschagrunert @RainbowMango @sbueringer

It seems like there was a bug that the correct groups were not given enough permissions.  Is that why we have keys, rather than just being a member of a googlegroup?  If groups works now, would that be a replacement for you (so we could turn off the keys) ?

**Comment by dims** [comment]
@thockin these keys are to upload results to test grid from CI jobs NOT running on prow

https://github.com/kubernetes/test-infra/tree/master/testgrid/conformance#usage-guide

**Comment by sbueringer** [comment]
@thockin @dims Exactly. So in my case I need to be able to upload logs from OpenLab to https://console.cloud.google.com/storage/browser/k8s-conform-capi-openstack

**Comment by dims** [comment]
@thockin earlier @BenTheElder minted some gcs buckets on google account and shared service accounts for those ... we just migrated those to community buckets.

**Comment by dims** [comment]
@thockin more background in https://github.com/kubernetes/test-infra/issues/15081

**Comment by thockin** [comment]
grrr... I guess I don't see any real alternative, then.

Dims, can we canonize this flow into the existing conform script (maybe the key download is just a comment)?  We have some functions for ensuring an SA exists.

**Comment by BenTheElder** [comment]
> @thockin earlier @BenTheElder minted some gcs buckets on google account and shared service accounts for those ... we just migrated those to community buckets.

some of them ... I think we need to migrate the rest still. not sure how to approach that.

I definitely don't like this FWIW, but I don't see a better option for letting people contribute data to testgrid from e.g. openstack CI.

**Comment by RainbowMango** [comment]
@thockin @dims 

My understanding is if my email in the correct groups then I can upload results by manual. 

After @dims generated a key for me, that makes it possible to upload the result in CI Job, like Travis.

Am I right?

**Comment by dims** [comment]
yep @RainbowMango don't worry we are good here. Just making sure we are filling in the details for @thockin based on the periodic audit

**Comment by bartsmykla** [comment]
So if we have to generate the keys maybe we should store them encrypted in the repository too?

Wdyt @thockin @dims?

**Comment by bartsmykla** [comment]
As discussed with @dims on slack, I'm gonna help with the script

/assign

**Comment by spiffxp** [comment]
bart may not have time this week, look to next week
