### ISSUE TITLE
Enable file removal for staging buckets

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes/k8s.io#605]
As a follow-up of https://github.com/kubernetes/k8s.io/pull/501, I'd like to be able to remove files from the bucket manually. This is currently prevented by the file-retention of 10years:

![screenshot](https://user-images.githubusercontent.com/695473/75347329-ce74e380-58a0-11ea-9371-299512bd93df.png)

/cc @dims

**Comment by stp-ip** [comment]
This feels intentional for a conformance specific bucket. What specifically do you wanna remove and why? Adding manual overwrite in some form or another seems to go against the intended idea of retention set to 10y, but maybe I'm missing something here.

**Comment by saschagrunert** [comment]
I’d like to provide something similar than a `latest.txt` file which points to some changing content. I also played around with the bucket (for testing) and now I have files there which cannot be deleted for years. 🥺

**Comment by stp-ip** [comment]
Might be ok to do a full reset or manual removal of files by the admin team, but adding editing opportunity feels problematic.

Latest.txt to link to or what usage? You could use the go.k8s.io url shortener as an option.

**Comment by saschagrunert** [comment]
Closing for now since I guess the retention policy cannot be changed.
