### ISSUE TITLE
Enable SIG Docs access to the kubernetes.io search console

### ISSUE THREAD

**Issue by zacharysarah** [kubernetes/k8s.io#613]
## What's the request?

SIG Docs would like access to search console data for the kubernetes.io domain. 

To [quote](https://kubernetes.slack.com/archives/C1J0BPD2M/p1582821278047700) @remyleone: 
> I’m especially interested in the search and the pattern of view. By looking at the stats and the most popular pages (kubectl cheat sheet) maybe there is a way to optimize the traffic by having page that are designed to drive even more traffic. It would be also interesting to see what are the search items that are not that well covered by current documentation. (Useful for new terms, new usage patterns and so on...)

## How do we grant it?

1. Go to https://search.google.com/search-console. 

2. Enter "kubernetes.io" in the domain box.

3. Follow the instructions to verify domain ownership via DNS record.

/cc @BenTheElder

**Comment by BenTheElder** [comment]
so I can help roll out the DNS records / anyone can PR dns records in this repo, I'm not sure what account should be doing the search.google.com bit, IIRC that is tied to the google account used to access the page, right?

**Comment by BenTheElder** [comment]
cc @dims @thockin

**Comment by stp-ip** [comment]
Usually after verification it is assigned as admin to an account should we do this via a group? Is that even possible?
So we could have an search console admin and one read-only group?

**Comment by BenTheElder** [comment]
ping @dims @thockin @spiffxp 
this seems like a reasonable request, but I'm not sure what account should be verified.

**Comment by dims** [comment]
@BenTheElder we can use sc1@kubernetes.io Sorry i missed the ping on this one.

**Comment by spiffxp** [comment]
/remove-lifecycle rotten
I don't have the bandwidth to get to this but I still think it would be useful for sig-docs

**Comment by spiffxp** [comment]
/remove-lifecycle rotten
/reopen
I feel like someone has already verified the domain, but I don't know who it is?

**Comment by spiffxp** [comment]
/priority important-soon
/milestone v1.23
We're trying to figure out who / which account has already claimed the domain, ref: https://github.com/kubernetes/k8s.io/pull/2489

**Comment by ameukam** [comment]
@jimangel With https://github.com/kubernetes/k8s.io/pull/2995, it's now possible to add more people to the console. If it still needed, can you drop the emails of the people that need access to it ? 
If not, can we close it ?

**Comment by jimangel** [comment]
> @jimangel With #2995, it's now possible to add more people to the console.

I'll message you with details in slack with other folks. I think this is safe to close. thanks!

**Comment by ameukam** [comment]
Added @jimangel and @divya-mohan0209 will full permissions to the console for `kubernetes.io`. 

/close
