### ISSUE TITLE
Investigate AWS 5k Node e2e Scale costs

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/k8s.io#6165]
We're spending around 50% of our budget on AWS on the 5k node scale tests, this is disproportionate.

We should investigate if there's knobs we can tune with the cluster configuration to bring this down, or otherwise reduce the interval again.

For a very rough comparison in November 2022 the 5k node project on GCP spend ~$22k, we spent > $142k in the 5k node AWS account for November 2023. These **aren't** equivalent, but I wouldn't expect this order of magnitude difference which suggests there's room to run the job more efficiently (e.g. perhaps we have public IPs on each worker node?), I know there was some tuning on the kube-up jobs.

/sig k8s-infra scalability
cc @dims

**Comment by ameukam** [comment]
cc @hakman @hakuna-matatah @upodroid

**Comment by ameukam** [comment]
AFAIK, we are talking about a single test: [ci-kubernetes-e2e-kops-aws-scale-amazonvpc-using-cl2](https://testgrid.k8s.io/sig-cluster-lifecycle-kops#ec2-master-scale-performance)

**Comment by ameukam** [comment]
The test runs in a single account `k8s-infra-e2e-boskos-scale-001`.

Breaking down some services used:

| Service | November 23 |
|--------|--------|
| EC2-Instances | 118,494.91 |
| EC2-Other | 15,299.39 |
| Support (Business) | 8,603.50 |
| Elastic Load Balancing | 258.91 |
| Key Management Service | 13.66 | 
| S3 | 3.16 |

**Comment by ameukam** [comment]
So what's `EC2-Other` ?

![image](https://github.com/kubernetes/k8s.io/assets/2343515/615c6bc1-ca1b-4263-ae32-135662c3b37d)


So EBS volumes on the EC2 instances and [Data Transfer within the region](https://docs.aws.amazon.com/cur/latest/userguide/cur-data-transfers-charges.html#data-transfer-within-region).

**Comment by hakuna-matatah** [comment]
One reason was that we were running 2 periodics vs 1 periodic on GCP. 
Other reason is that we kicked off one off tests using pre-submits as well while making  code changes and fixing some issues before we saw successful runs.

We are also running statefulsets in our cl2 tests, haven't looked into if GCP is running stateful sets as part of scale tests.

**Comment by BenTheElder** [comment]
> One reason was that we were running 2 periodics vs 1 periodic on GCP.

I don't think that was true in November '22? 
But either way that doesn't account for using ~50% of budget on AWS and a _much_ smaller fraction on GCP.

> Other reason is that we kicked off one off tests using pre-submits as well while making code changes and fixing some issues before we saw successful runs.

My understanding is that was true in the past, but in November we were not developing anymore?
This was discussed in today's meeting.

> We are also running statefulsets in our cl2 tests, haven't looked into if GCP is running stateful sets as part of scale tests.

If this can account for a dramatic cost increase, we should consider not doing it.
I doubt it, since the GCP tests have been extremely long running (like > 10h), so it's mostly down to the size and shape of the cluster under test.


I suspect we can run smaller worker nodes or something else along those lines?

**Comment by dims** [comment]
cc @hakuna-matatah @mengqiy

**Comment by hakuna-matatah** [comment]
>I don't think that was true in November '22?
But either way that doesn't account for using ~50% of budget on AWS and a much smaller fraction on GCP.

I think we have been running 2 tests until 2 days back, this [PR](https://github.com/kubernetes/test-infra/pull/31371/files) 2 days back moved it to one test for every 24 hrs.
 
>My understanding is that was true in the past, but in November we were not developing anymore?
This was discussed in today's meeting.

I remember kicking off one off tests when working on experimenting with Networking SLOs in Novemeber.

>Maybe smaller worker node volumes are in order? Or a different volume type?
We can definitely improve cost basis on the instance types we choose,  we are having a discussion on slack around this here - https://kubernetes.slack.com/archives/C09QZTRH7/p1701906151681289?thread_ts=1701899708.933279&cid=C09QZTRH7

**Comment by hakuna-matatah** [comment]
>Dumping log and other info: 60 min

I was wondering if it's feasible to keep just 500 nodes and cleanup 4,500 nodes and then dump the logs for those 500 ? That way we would save 60mins on 4,500 nodes ? WDYT ?

**Comment by sftim** [comment]
Could we use spot instances at all? If not, let's document why not.

**Comment by sftim** [comment]
We can definitely do one of those two options :wink:

**Comment by BenTheElder** [comment]
For log dumping: The GCE scale test log dumper `ssh`es to the nodes and then actually push the logs out from each node, so the local command in the e2e pod is relatively cheap/quick

https://github.com/kubernetes/test-infra/blob/master/logexporter/cluster/log-dump.sh

To do this it currently writes a file to the results with a link to where the logs will be dumped in a separate bucket and just grants the test cluster nodes access to the scale log bucket.

https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-correctness/1732445180289617920/artifacts/master-and-node-logs.link.txt

In this way it is dumping all nodes:
```
$ gsutil ls gs://k8s-infra-scalability-tests-logs/ci-kubernetes-e2e-gce-scale-correctness/1732445180289617920 | wc -l
    5003
```

**Comment by marseel** [comment]
> For log dumping: The GCE scale test log dumper sshes to the nodes and then actually push the logs out from each node, so the local command in the e2e pod is relatively cheap/quick (plus parallel dumping mentioned above).

IIRC ssh thing is only done for nodes for which logexporter daemonset failed: https://github.com/kubernetes/test-infra/blob/master/logexporter/cluster/logexporter-daemonset.yaml

from scale test logs:
```
Dumping logs from nodes to GCS directly at 'gs://k8s-infra-scalability-tests-logs/ci-kubernetes-e2e-gce-scale-performance/1732082847704944640' using logexporter
```

**Comment by hakuna-matatah** [comment]
Looks like there is another improvement made by @rifelpet  w.r.t to parallelizing resource dumps to save cost [here](https://github.com/kubernetes/kops/pull/16196) , linking it here as it's related to this discussion we are having here.

**Comment by hakuna-matatah** [comment]
How does the cost look now a days given tests are pretty stable and no dev work as well ? Do we need one more round of optimization efforts ? Or are we within the budget allocation now ?

**Comment by ameukam** [comment]
@hakuna-matatah I think currently costs is Ok. We are within the monthly budget. 

@dims I think we are done here ?

**Comment by dims** [comment]
@ameukam yes we are done here for now.

**Comment by hakuna-matatah** [comment]
Another improvement that reduced the test-duration around ~30mins - https://github.com/kubernetes/kops/pull/16532

**Comment by smalleni** [comment]
@ameukam @hakuna-matatah @dims Do we have an idea what this currently costs after the optimizations? Thank you.

**Comment by BenTheElder** [comment]
AWS is currently on track for over budget by EOY .., I've stepped down from sig k8s infra leadership though. Might be worth a follow up in the sig-k8s-infra slack channel.

**Comment by upodroid** [comment]
Hey Sai

https://testgrid.k8s.io/sig-scalability-dra#ec2-dra-with-workload-master-scalability-500
https://testgrid.k8s.io/sig-scalability-dra#ec2-dra-with-workload-master-scalability-5000


```
 mahamed  Mac  tmp  1  $  cat toolbox-dump.yaml | grep InstanceType | sort | uniq -c
   1     InstanceType: c8i.24xlarge
  85     InstanceType: t3.medium
4915     InstanceType: t3a.medium
```

Also, these jobs haven't been green lately. Something is wrong with the DRA 5k jobs.

> Do we have an idea what this currently costs after the optimizations? Thank you.

The optimisations were done a long time ago, and the numbers are looking good. We'll do some calculations for the current cost and see what we can support.

**Comment by hakuna-matatah** [comment]
I think the optimizations are done for this job - https://testgrid.k8s.io/sig-scalability-aws#ec2-master-scale-performance iirc in the past, and i think this Job health is green, which is what was being discussed at that time on this issue.

DRA jobs [500](https://testgrid.k8s.io/sig-scalability-dra#ec2-dra-with-workload-master-scalability-500) and [5k](https://testgrid.k8s.io/sig-scalability-dra#ec2-dra-with-workload-master-scalability-5000)   is added a month ago fmu @upodroid  - https://github.com/kubernetes/test-infra/commits/f37f7a54d9c84e122ff742d327c003264c92596a/config/jobs/kubernetes/sig-scalability/DRA/sig-scalability-ec2-dra.yaml

And it looks like it has been failing on pod-startup-latency when i quickly skimmed through the logs
```
E0723 03:25:57.159414   22426 pod_startup_latency.go:290] PodStartupLatency: labelSelector(job-type = long-running): pod startup: too high latency 99th percentile: got 5.849872414s expected: 5s
```

**Comment by hakuna-matatah** [comment]
The net cost also may not have changed much given now we are alternating between 5k periodic load tests here https://github.com/kubernetes/test-infra/pull/37193/changes#diff-641a1110a37a68c7591fe7c9e4e3f83811031bb41c4254dd66396a5135bf8d7aR122 and newly added DRA tests.

IOW we are running load tests now on alternate days since the DRA tests are added.

**Comment by hakuna-matatah** [comment]
Some more marginal reduction in costs with last week changes (https://github.com/kubernetes/kops/pull/18742 , https://github.com/kubernetes/kops/pull/18742)  I made as part of this issue - https://github.com/kubernetes/kubernetes/issues/141447

This reduced the cost roughly by O(~10 mins * 5k*EC2 instaces) for each run , more details in this comment - https://github.com/kubernetes/kubernetes/issues/141447#issuecomment-5430135824



@smalleni fyi ^^^
