### ISSUE TITLE
Add a `go.k8s.io` redirect for contact information

### ISSUE THREAD

**Issue by MadhavJivrajani** [kubernetes/k8s.io#6242]
There have been many instances where contact information of a particular SIG or just avenues of communication in the community need to be conveyed either to new contributors or just having the link handy helps.

Having said that, we could probably add a redirect to the existing `go.k8s.io` redirect to handle this:

https://github.com/kubernetes/k8s.io/blob/a2717cb3e792e43fb039b77f690cbdedbaaff8be/apps/k8s-io/configmap-nginx.yaml#L258

### Step 1: Add in the redirects

The following redirects would help:
1. `go.k8s.io/contact` goes to https://github.com/kubernetes/community/tree/master/communication 
2. `go.k8s.io/contact/<sig|wg|committee-name>` goes to https://github.com/kubernetes/community/tree/master/group-name#contact
  i. Example: `go.k8s.io/contact/sig-contributor-experience` would go to https://github.com/kubernetes/community/tree/master/sig-contributor-experience#contact

### Step 2: Update README.md

Update the README [here](https://github.com/kubernetes/k8s.io/tree/a2717cb3e792e43fb039b77f690cbdedbaaff8be/apps/k8s-io#redirections) to mention the redirects.

### Step 3: Add in tests for the redirects

Subsequently, add in tests for this new redirect here: 

https://github.com/kubernetes/k8s.io/blob/a2717cb3e792e43fb039b77f690cbdedbaaff8be/apps/k8s-io/test.py#L172

/sig contributor-experience
/good-first-issue

**Comment by SD-13** [comment]
Hey @MadhavJivrajani I just tried `go.k8s.io/contact` but it is giving 404 Not found error even with a sig name. It is also not in the redirects list.

**Comment by MadhavJivrajani** [comment]
@SD-13 yes, changes still need to be made in order for it to be a valid redirect. Please see the steps I've outlined in the issue.

@haripriya9647 feel free to ask questions here in case you need to as you work on this!

**Comment by haripriya9647** [comment]
Sure @MadhavJivrajani

**Comment by haripriya9647** [comment]
1. "https://go.k8s.io/pr-dashboard" 
2. "https://go.k8s.io/test-health"
3. "https://go.k8s.io/logo"
  link are broken

**Comment by nitishfy** [comment]
Hi, Is this issue still open to work on? If yes, I'd like to take this up.

**Comment by haripriya9647** [comment]
Yes Nitish , i have some issues you can take this up..

**Comment by MadhavJivrajani** [comment]
Thanks folks

@nitishfy pls assign the PR to me once you have it ready!

**Comment by nitishfy** [comment]
[PR raised](https://github.com/kubernetes/k8s.io/pull/6502), I've assigned this to you @MadhavJivrajani 

Sorry for the delay. There can be things in the PR that might go wrong, happy to review and fix the suggestions.

**Comment by ameukam** [comment]
@nitishfy @MadhavJivrajani is there a side effect on the tests changed https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-k8sio-deploy-app-k8s-io/1763952879321747456 ?

**Comment by MadhavJivrajani** [comment]
@ameukam 👋🏼 

Hmm..I don't think this is related, a different test seems to be failing (`test_docs`) than what was added to (`test_go`). I see the failure being a mismatch in the status code, the test got a `502`, is it possible this could be a flake? I also can't reproduce this locally. Let's maybe wait for the next run.
