### ISSUE TITLE
Documentation of audit

### ISSUE THREAD

**Issue by bartsmykla** [kubernetes/k8s.io#627]
Hi everyone!

When I was doing code review for the https://github.com/kubernetes/k8s.io/pull/536 I started reading whole https://github.com/kubernetes/k8s.io/tree/master/audit
The problem is I don't exactly understand what is the output of that audit so I would like to suggest improvements in the documentation.

I'm volunteering myself to do it but I have to have better understanding of the whole process, why we need it and what we expect from it.

I know @thockin you are a busy men, but would you be so kind and give me some more information about this topic and also maybe put some other folks and/or places to get more knowledge about it?

/assign @bartsmykla @thockin

**Comment by puerco** [comment]
I think I can provide a bit of insight here.

What the audit script does is go through all the projects in the kubernetes organization, then it reads from each service it has enabled to try to produce useful data that can be diffed with previous states. The Idea is that if anything has changed, a PR can be created to detect changes in the infrastructure.

I also think that documentation on what is being audited would be useful, I can help with that if you want

**Comment by puerco** [comment]
I did some research into what services are enabled in the 43 projects our org currently has and here is the list. (number of projects » service)

```
     40 storage-component
     40 storage-api*
     38 pubsub
     38 containerregistry
     36 logging
     31 cloudbuild
     18 bigquery* 
     15 oslogin
     15 compute*
     10 serviceusage
     10 monitoring
      9 containeranalysis
      9 bigquerystorage
      8 sql-component
      8 servicemanagement
      8 datastore
      8 cloudtrace
      8 clouddebugger
      8 cloudapis
      3 stackdriver
      3 containerscanning
      3 cloudresourcemanager
      3 clouderrorreporting
      2 run
      2 cloudkms
      1 iamcredentials
      1 iam
      1 groupssettings
      1 dns*
      1 container*
      1 admin
```
Those with a star are the ones which have some sort of handling in the audit script now (except for BigQuery which is yet to merge in #536 ) maybe from this list we can decide which ones make sense to audit.

**Comment by thockin** [comment]
The medium-term goal would be a cronjob that runs the audit every few hours
and if it finds a diff, sends a PR or an alert or something like that.  I
am mostly concerned about IAM, but any metadata that is roughly stable over
time is good.  The vast majority of these runs should find no diffs at all,
so anything it DOES find is "exceptional" and warrants human intervention.
