### ISSUE TITLE
VPC Limit Reached in AWS account eks-e2e-boskos-005

### ISSUE THREAD

**Issue by richardcase** [kubernetes/k8s.io#6321]
We are running into `VpcLimitExceeded: The maximum number of VPCs has been reached` errors when the CAPA e2e tests are run in the **eks-e2e-boskos-005 (568640253687)** AWS account. If boskos hands us another account we don't see this error.

A few examples:

- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-cluster-api-provider-aws-e2e/1748057537573294080#1:build-log.txt%3A1776
-  https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-aws/4619/pull-cluster-api-provider-aws-e2e/1748262646076936192

The CAPA e2e tests request an increase in the VPC limit when they run.  And if aws-janitor is running ok in this account we shouldn't see this error.

Could it be we have an issue with aws-janitor in this account?

**Comment by ameukam** [comment]
/area infra/aws
cc @xmudrii @dims

**Comment by xmudrii** [comment]
Discussion ongoing on Slack: https://kubernetes.slack.com/archives/CCK68P2Q2/p1706111409475109
It seems like we're leaking ENIs and that's preventing subnets and VPCs from being removed. It looks like aws-janitor is properly working for that account
