### ISSUE TITLE
Cluster API Infra Provider AWS (CAPA) e2e tests regularly because the maximum number of EventBridge Rules has been reached

### ISSUE THREAD

**Issue by dlipovetsky** [kubernetes/k8s.io#6381]
CAPA uses EventBridge to be notified by AWS of changes to VM state; this is an alternative to polling the AWS API.

CAPA [creates 1 EventBridge Rule per cluster](https://github.com/kubernetes-sigs/cluster-api-provider-aws//blob/58c2d5886666fc208548ce0e312846935b2b9d3d/pkg/cloud/services/instancestate/rule.go#L50-L53).

During an e2e test, CAPA creates a cluster, tries to create an EventBridge Rule for that cluster, but receives the following error from AWS:

```
LimitExceededException: The requested resource exceeds the maximum number allowed.
```

The e2e tests sometimes pass, but often fail. See, for example: https://prow.k8s.io/job-history/gs/kubernetes-jenkins/pr-logs/directory/pull-cluster-api-provider-aws-e2e. While the test logs report that control plane not deploying, the CAPA controller logs, available in the artifacts ([example](https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-aws/4746/pull-cluster-api-provider-aws-e2e/1754115651997274112/artifacts/clusters/bootstrap/controllers/capa-controller-manager/capa-controller-manager-6b8f8b488c-bft66/manager.log)) show the EventBridge rule limit as the root cause of the failure.

I'm not sure what the underlying issue is. Here are some theories I have:

1. The EventBridge rules quota is too low to support the number of CAPA clusters being deployed in parallel.
2. The EventBridge rules quota is too low to support non-CAPA tests that create EventBridge rules in the same AWS account.
3. The AWS Janitor does not clean up EventBridge rules quickly enough. Note that CAPA [deletes EventBridge rules](https://github.com/kubernetes-sigs/cluster-api-provider-aws//blob/58c2d5886666fc208548ce0e312846935b2b9d3d/pkg/cloud/services/instancestate/rule.go#L147) when it deletes a cluster, so ordinarily, no rules are left behind.

**Comment by nrb** [comment]
Also worth nothing that the AWS janitor also [tries to delete EventBridge rules](https://github.com/kubernetes-sigs/boskos/blob/ec8f2b01bbf34d8c7d2528c0e1cf591e0cdba1af/aws-janitor/resources/sqs.go#L117)

**Comment by ameukam** [comment]
cc @xmudrii @dims

**Comment by xmudrii** [comment]
This seems similar to #6321, I'll take a look tomorrow
/assign

**Comment by dlipovetsky** [comment]
> This seems similar to #6321, I'll take a look tomorrow /assign

Thank you! If there's anything I can help with on the CAPA side, please ping me on Kubernetes slack.

**Comment by xmudrii** [comment]
After adding the needed IAM permissions to the `boskos` user, EventBridge Rules are properly cleaned up. I'll be adding the following policy to all AWS accounts used by boskos in eks-prow-build-cluster:

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "sqs:Get*",
                "sqs:List*",
                "sqs:Delete*",
                "events:List*",
                "events:Delete*",
                "events:Remove*"
            ],
            "Resource": "*"
        }
    ]
}
```

**Comment by dlipovetsky** [comment]
I'm paying attention to CAPA e2e tests today. I'll close this once I see the problem go away.

**Comment by dlipovetsky** [comment]
Looks like this issue is resolved. I'll re-open if I see it again.

Thank you! :pray:
