### ISSUE TITLE
k8s-infra-prow-build: Deploy KubeCost and integrate it with the existing KubeCost installation on EKS

### ISSUE THREAD

**Issue by xmudrii** [kubernetes/k8s.io#6413]
We deployed KubeCost on the EKS Prow build cluster recently (#5164). This issue tracks:

- deploying KubeCost on the GKE community Prow build cluster (k8s-infra-prow-build)
- integrating it with the existing KubeCost installation so that we have all information in the single dashboard and API

/assign @koksay 
/priority important-soon
/milestone v1.30
/sig k8s-infra
/area infra
/area infra/gcp

**Comment by koksay** [comment]
Commenting, so that it can be assigned to me.

**Comment by xmudrii** [comment]
@koksay I think we decided not to proceed with this one or is it still relevant?

**Comment by koksay** [comment]
Yes, this is not relevant anymore. I was even thinking about removing Kubecost from the EKS cluster as we have already got the info we needed.

**Comment by xmudrii** [comment]
@koksay Okay, I'll create a new issue to track that.
/close
