### ISSUE TITLE
peribolos jobs using incorrect token

### ISSUE THREAD

**Issue by cblecker** [kubernetes/k8s.io#6503]
It appears that the peribolos jobs for kubernetes orgs are running with the incorrect account/token. They are using @k8s-ci-robot when they should be using @k8s-github-robot .

How do we go about fixing this?

/sig contributor-experience
cc @kubernetes/sig-contributor-experience-leads @kubernetes/owners

**Comment by BenTheElder** [comment]
https://prow.k8s.io/?job=*peribolos*

->
post-org-peribolos, 
ci-org-peribolos


These both set `cluster: test-infra-trusted` and `secretName: oauth-token`

https://github.com/search?q=repo%3Akubernetes%2Ftest-infra+peribolos+language%3AYAML+path%3A%2F%5Econfig%5C%2F%2F&type=code

**Comment by ameukam** [comment]
- Setup a new secret with the right token on `k8s-infra-prow-build-trusted`
  - create a GCP Secret Manager secret
  - sync the secret to the cluster with a `ExternalSecret`
- Migrate the prowjobs affected by this issue

**Comment by cblecker** [comment]
This has been fixed!
