### ISSUE TITLE
community infra for kubernetes/KIND CI

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/k8s.io#654]
We require:
- a GCP project to host:
  - GCB (for trusted building, currently we have a prototype running from prow in `bentheelder-kind-dev`)
  - a GCS bucket to host CI binary builds of `kind` for use in Kubernetes testing (currently we use `gs://bentheelder-kind-ci-builds`). These are ~9MB / platform

Prow needs access to GCB, and GCB needs write access to the bucket. The bucket should be public read.

xref: https://github.com/kubernetes-sigs/kind/issues/1392
cc @justaugustus @spiffxp @dims

**Comment by bartsmykla** [comment]
@BenTheElder I think I can help with that. I'll try to write soon how we should proceed.

**Comment by BenTheElder** [comment]
gentle ping, I'd really like to get this out of google.com infra and stop having github.com/kubernetes/kubernetes CI download from a `bentheelder...` bucket w/o detrimentally impacting CI...

we essentially just need a staging project 😅 
cc @dims @spiffxp @justaugustus

**Comment by listx** [comment]
Our existing instructions for subprojects needing a [GCR](https://github.com/kubernetes/k8s.io/tree/master/k8s.gcr.io#creating-staging-repos), have [provisions](https://github.com/kubernetes/k8s.io/blob/master/infra/gcp/ensure-staging-storage.sh#L104) for creating GCS buckets for humans and for GCB. Also, Katharine's automated [cloudbuild instructions](https://github.com/kubernetes/test-infra/blob/master/config/jobs/image-pushing/README.md) have detailed instructions for setting up Prow integration for building in GCB (in the subproject). So it looks like just creating the subproject using the GCR directions will give you what you need. I think we should minimize special-casing our infra rules where possible.

**Comment by bartsmykla** [comment]
@BenTheElder I'm gonna get back to this today, I promise!

**Comment by bartsmykla** [comment]
@BenTheElder so [every staging project](https://github.com/kubernetes/k8s.io/blob/master/infra/gcp/ensure-staging-storage.sh#L41-L81) as @listx wrote have access to two GCS buckets - [one for humans](https://github.com/kubernetes/k8s.io/blob/master/infra/gcp/ensure-staging-storage.sh#L104) and [one for GCB](https://github.com/kubernetes/k8s.io/blob/master/infra/gcp/ensure-staging-storage.sh#L105). They have retention policy set to 60 days though.
Do you think it would be enough to use the existing `staging` buckets as we don't have currently any solution for artifacts promotion (we have started discussion about it at last community call)?

**Comment by BenTheElder** [comment]
That should be sufficient. Sorry for the delay.

I need one publicly readable bucket that I can write to from a GCB build with at least some retention.

You can see what we're doing (currently from prow instead of GCB) here:
https://github.com/kubernetes-sigs/kind/blob/master/hack/ci/push-latest-cli.sh

Ideally this moves to a trusted cluster / GCB job.
Kubernetes / Kubernetes CI (and humans doing debugging) will download these artifacts.

**Comment by BenTheElder** [comment]
IMHO we need a better entrypoint to finding these docs, I have no interest in a GCR at this time so I'd not have found this... I am not doing image builds here. There are probably many other projects doing something roughly like "nightly binary build".

**Comment by bartsmykla** [comment]
@BenTheElder agree with documentation and I'm trying to solve that, about retention maybe we could start the topic at tomorrows zoom call?

**Comment by BenTheElder** [comment]
filed https://github.com/kubernetes/k8s.io/pull/744 to create a staging project

**Comment by thockin** [comment]
It sounds like what you want is "prod" (with approximately infinite retention).  The medium-term goal is a GCS promoter process that parallels the GCR promoter, but we don't have that yet.

In the absence of that, we have been giving GCS "prod" access to a small set of closely-guarded subprojects.  I would be OK to give you a dedicated "prod" GCS bucket and access to it.  When we eventually have a GCS promoter, we would ask that you move to that.

Fair?

**Comment by thockin** [comment]
How does "gs://k8s-artifacts-kind" sound?

**Comment by BenTheElder** [comment]
It sounds great 👍

**Comment by thockin** [comment]
PTAL https://github.com/kubernetes/k8s.io/pull/749

**Comment by bartsmykla** [comment]
I think it means we can close this issue. Wdyt @BenTheElder?

**Comment by BenTheElder** [comment]
Yes, thanks all.
The first iteration is up and running. https://prow.k8s.io/?job=post-kind-push-binaries
