### ISSUE TITLE
audit-gcp.sh failing (not enough permissions for k8s-infra-gcp-auditors@kubernetes.io)

### ISSUE THREAD

**Issue by bartsmykla** [kubernetes/k8s.io#668]
@thockin I tried to do gcp audit today and it looks like group: `k8s-infra-gcp-auditors@kubernetes.io` doesn't have enough permissions.

```
ERROR: (gcloud.dns.project-info.describe) User [bartek@smykla.com] does not have permission to access project [kubernetes-public] (or it may not exist): Forbidden
```

@thockin question: I couldn't find it in our scripts, but maybe I was looking wrong. Are we managing permissions for group `k8s-infra-gcp-auditors@kubernetes.io` with our scripts? If not, do you think we could?

/assign @thockin

**Comment by thockin** [comment]
The auditor permissions are NOT currently managed by scripts.  That should be on the list of things to scriptize.  Menawhile, I will add it manually.

**Comment by thockin** [comment]
Do you know which step of the audit script failied?  Maybe run it under `bash -x` ?

**Comment by puerco** [comment]
`gcloud.dns.project-info.describe`:
ERROR: (gcloud.dns.project-info.describe) User [adolfo.garcia@uservers.net] does not have permission to access project [kubernetes-public] (or it may not exist): Forbidden

**Comment by thockin** [comment]
weird.  You have project viewer.  That error does not say which permission is actually needed (sigh, helpful).

**Comment by thockin** [comment]
I tried adding DNS reader - try now?
Looking at this script, it seems we may be missing some `--project` flags

**Comment by puerco** [comment]
It works now I can get the DNS data with both

`gcloud --project=kubernetes-public dns managed-zones list --format=json`
and
`dns project-info describe "kubernetes-public" --project=kubernetes-public --format=json  `

**Comment by thockin** [comment]
ok.  Weird that project viewer did not cover that.  Closing this, scream if there's more :)

**Comment by puerco** [comment]
Thanks !

**Comment by puerco** [comment]
Just to confirm: I just finished a run of the audit script and all service handlers ran successfully on all 48 projects. A lot of modified files came out because of all the new projects.
