### ISSUE TITLE
Account used for aws-ebs-csi-driver ECR public repository

### ISSUE THREAD

**Issue by dims** [kubernetes/k8s.io#6683]
@jlbutler and the EBS team figured out that there is another AWS account `406135939448` that used primarily for hosting EBS CSI driver's ECR public repository:

https://gallery.ecr.aws/ebs-csi-driver?page=1

A while ago @jaypipes had set this up with owner mailing list set to:

[aws-ebs-csi-driver@lists.cncf.io](mailto:aws-ebs-csi-driver@lists.cncf.io)

We need to figure out how to get this into our overall AWS org

**Comment by dims** [comment]
cc @torredil @AndrewSirenko @ConnorJC3

**Comment by jlbutler** [comment]
Current status, we're going to get @dims and I added to the list so we can reset credentials, then we can take steps to bring this account back into the org. Not sure why it was removed, but that should get us the right outcome.

This account only has the public repo in it, but that's a very important resource to the overall project. So, it's important to reestablish oversight for it.

**Comment by ameukam** [comment]
@dims @jlbutler can someone from your org send an org invite ? 
we have the credentials for this account stored in our vault.

**Comment by dims** [comment]
> @dims @jlbutler can someone from your org send an org invite ?

Shouldn't this be part of our existing org? 

![image](https://github.com/kubernetes/k8s.io/assets/23304/0c186893-b401-495f-a711-e368b39eec7c)

**Comment by ameukam** [comment]
Yes. Commented because I don't think this step:
> I added to the list so we can reset credentials,

is needed.

**Comment by jlbutler** [comment]
Yes for some reason it was removed from the org. @dims if you send an invite, it can be accepted on the `9448` account and it should come back into the fold.

**Comment by dims** [comment]
Ah! thanks @ameukam

**Comment by ameukam** [comment]
> Yes for some reason it was removed from the org. @dims if you send an invite, it can be accepted on the `9448` account and it should come back into the fold.

@jlbutler CNCF or AWS Internal org ?

**Comment by jlbutler** [comment]
Nothing internal, I'm just referring to the AWS Organization. This account was removed at one point - unsure why, but adding it back will get it back under project oversight and admin capability.

**Comment by dims** [comment]
Just checked, looks like it is already part of the k8s-infra mgmt org!!! 

```
[cloudshell-user@ip-10-138-184-45 ~]$ aws organizations list-accounts | jq -r '.Accounts[] | "\(.Id) \(.Name)"'
855606814420 k8s-infra-e2e-aws-playground-01
568640253687 k8s-infra-eks-e2e-boskos-005
634972135556 cncf-k8s-external-dns-aws
819546954734 cncf-k8s-infra-aws-capa-ami
678544613731 k8s-infra-shared-services
027487054958 k8s-infra-sandbox-capa
665903963701 cncf-k8s-infra-aws-capa-demo
336527747262 k8s-infra-e2e-boskos-003
348685125169 Kubernetes AWS Admins
226543828060 k8s-infra-e2e-boskos-scale-001
468027687836 k8s-infra-registry-k8s-io-prod
128476729677 k8s-infra-security-audit
573772537124 k8s-infra-security-incident-response
581954596586 k8s-infra-policy-staging-account-1
819381709038 k8s-infra-eks-e2e-boskos-007
433650573627 sig-release-leads
309501585971 k8s-infra-obs-k8s-io-prod
406135939448 aws-ebs-csi-driver Infra
757254795865 k8s-infra-eks-e2e-boskos-003
354561287328 k8s-infra-artifacts-k8s-io-prod
334474631674 kops-infra-services
610906833592 windows_operational_readiness
054318140392 k8s-infra-prow-canary
013800559357 CNCF K8s Minikube
502839862640 k8s-infra-eks-e2e-boskos-010
808842816990 kops-infra-ci
080553712153 k8s-infra-eks-e2e-boskos-008
236737742629 k8s-infra-eks-e2e-boskos-004
867921711297 k8s-infra-e2e-boskos-002
585803375430 k8s-infra-aws-admins+accounts
580784499913 k8s-infra-security-engineering
468814281478 k8s-infra-prow
144171684817 k8s-infra-e2e-boskos-001
405186867737 k8s-infra-e2e-boskos-scale-002
995654820765 k8s-infra-eks-e2e-boskos-001
209411653980 k8s_infra_eks_e2e_shared_001
513428760722 k8s-infra-aws-admins+registry-k8s-io
187041256112 k8s-infra-eks-e2e-boskos-009
759415916157 k8s-infra-security-logs
203865341587 k8s-infra-networking
215077277647 k8s-infra-legacy-pkgs-k8s-io-prod
252228595925 k8s-infra-eks-e2e-boskos-002
325389058785 k8s-infra-eks-e2e-boskos-006
266690972299 k8s-infra-aws-root-account
```

**Comment by dims** [comment]
Thanks @ameukam @jlbutler We can follow up in another issue about what the EBS CSI driver team needs to be done in this account.
