### ISSUE TITLE
DNS REQUEST: kubebuilder.io

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes/k8s.io#6703]
### Type of DNS update:
Update

### Domain being modified:
kubebuilder.io

### Existing DNS Record:

We use the domain `kubebuilder.io` to publish the docs.
Then, we have entries to keep published OLD versions/legacy documentation
See: 

- [book.kubebuilder.io](https://book.kubebuilder.io/) -- current docs
- [book-v2.book.kubebuilder.io](https://book-v2.book.kubebuilder.io/) -- legacy docs
- [book-v1.book.kubebuilder.io](https://book-v1.book.kubebuilder.io/) -- legacy docs
- [master.book.kubebuilder.io](https://master.book.kubebuilder.io/) -- "nightly" docs

We need a new entry because we will push a MAJOR release. 
That means we need to add:

- [book-v3.book.kubebuilder.io](https://book-v3.book.kubebuilder.io/) -- legacy docs

### Reason for update:

After the MAJOR release Kubebuilder CLI 4x
We want to keep the legacy doc available for Kubebuilder CLI 3x
But we need the entry to be able to properly configure the book-v3 branch to server [book-v3.book.kubebuilder.io](https://book-v3.book.kubebuilder.io/) -- legacy docs

@mrbobbytables can help us to configure the netlify but he has no access to the DNS to add the new entry.

**Comment by BenTheElder** [comment]
the config for this is in `dns/` in this repo, it will be a bit faster if you can implement the PR for us and we can just review, but previously we have also helped author PRs (today is 1.30 release as well though 😅)

**Comment by camilamacedo86** [comment]
Hi @BenTheElder 

Thank you a lot for let me know. Could you please when you have time just give a hand where I should create it? I cannot find any record from the domains that we have already.

**Comment by BenTheElder** [comment]
Oh, sigh, kubebuilder.io is not a kubernetes owned domain, k8s.io, kubernetes.io and others are.

**Comment by BenTheElder** [comment]
We have:

etcd.io
x-k8s.io (reserved for experimental / unapproved APIs)
kubernetes.io
kubernetes.dev
k8s.io
k8s.dev
k8s-e2e.com

I don't know who owns kubebuilder.io but I suspect it's not the CNCF or Kubernetes project, if it was it would be in `dns/zone-configs` in thsi repo.

**Comment by BenTheElder** [comment]
The pattern we have for subproject docs is like http://kind.sigs.k8s.io (I helped establish this!), we have a shared netlify account that SIG docs can setup against a subdomain and the subdomains of sigs.k8s.io are self-service (or we can help you) in this repo.

We don't take over whole new domains often and I'm not sure where we'd start there ... first we'd have to know who owns it and if they can transfer it.

It may be easier to update the existing host to serve a redirect to a project controlled domain like kubebuilder.sigs.k8s.io

**Comment by camilamacedo86** [comment]
Hi @BenTheElder 

Looking at whois: https://who.is/whois/kubebuilder.io it is register with the LinuxFoundation. We need help to know who can manage the DNS. Have you any clue?

**Comment by BenTheElder** [comment]
We can ping @jeefy, the CNCF liason for the Kubernetes project, but I would still recommend switching to kubebuilder.sigs.k8s.io so we can manage it like other subprojects.

**Comment by BenTheElder** [comment]
I think this was solved for now?

**Comment by camilamacedo86** [comment]
Yes kudos for @jeefy !!!
