### ISSUE TITLE
`kubeadm, kubelet` install file for MacOS exists in CDN?

### ISSUE THREAD

**Issue by young-hun-jo** [kubernetes/k8s.io#6783]
Currently, I am planning to build a Kubernetes cluster using a Linux server and a MacBook laptop. I intend to configure the MacBook as the master node. To do this, I'm trying to set up a Kubernetes cluster on my MacBook. For the container runtime, I have already installed cri-dockerd. I want to install kubeadm and kubelet on my MacBook for network communication with the Linux server. However, are there MacOS versions of kubeadm and kubelet available on the CDN? I downloaded the Linux versions and tried to run the kubeadm command on my MacBook terminal, but encountered the error "zsh: exec format error: kubeadm". I suspect this is because I ran a Linux file on MacOS. So, the question is, does the CDN provide MacOS versions of kubeadm and kubelet?
(CDN url is here :  https://cdn.dl.k8s.io/ )

**Comment by neolit123** [comment]
note that k8s does not support macos natively. projects like kind and minikube can use containerization/virtualization to run there. only kubectl can safely run on macos.

/kind support

**Comment by young-hun-jo** [comment]
I got it. [this is similar issue](https://github.com/kubernetes/kubernetes/issues/59105#issuecomment-440836463). I will close it. thanks!
