### ISSUE TITLE
apiGroup in role applied by ensure-namespaces.sh script is probably wrong

### ISSUE THREAD

**Issue by bartsmykla** [kubernetes/k8s.io#681]
Doing some research today one thought came to me.

@munnerz: [This Pull Request](https://github.com/kubernetes/k8s.io/pull/635) changes the apiGroups from `certmanager.k8s.io` to `cert-manager.io`. I think we should also change it at [`infra/gcp/namespaces/namespace-user-role.yml`](https://github.com/kubernetes/k8s.io/blob/master/infra/gcp/namespaces/namespace-user-role.yml#L11) which is applied for every project at [`aaa` cluster](https://github.com/kubernetes/k8s.io/tree/master/infra/gcp/clusters/kubernetes-public/aaa) when [`ensure-namespaces.sh`](https://github.com/kubernetes/k8s.io/blob/master/infra/gcp/namespaces/ensure-namespaces.sh] script is ran.

I'll followup with the PR, but please confirm my thoghts are right

/assign @munnerz

**Comment by munnerz** [comment]
I've responded over in #682 :)
