### ISSUE TITLE
Policy around granularity and grouping for artifact storage paths

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/k8s.io#696]
Pulling out some choice quotes from the discussion that started in https://github.com/kubernetes/k8s.io/pull/658#pullrequestreview-374651405

@thockin
>Should we force grouping? E.g. should sig- get a quota on stagings? Or something?
>Or should we nest "directories" in GCR? E.g. instead of k8s.gcr.io/csi-foobar and k8s.gcr.io/csi-quuxzorb, should we encourage k8s.gcr.io/csi/{foobar,quuxzorb}?

@listx
>If we do end up reorganizing some of the final prod image paths, we should not delete the old (existing) promoter manifests because they will serve as a historical record. (I.e., let's not be forced to do this again).

@detiber
>If we do organize under a single staging bucket for cluster-api, building on what @ncdc mentioned, I think it should be organized something like this:
>`cluster-api/`<- hosts all images that are built from cluster-api project directly
>`cluster-api/<provider-type>/<provider-name>` <- hosts images related to that provider
>This would allow for separation of ownership/access for sig-sponsored sub-projects that might have separate ownership on individual repos.
>Should we rally around a doc/issue for hashing a concrete proposal, including transition plan and maintaining the historical record (as well as maintaining backward compat)?

Yes, we should, hence this issue.

From my perspective:
- What's motivating this?
- Repos have migrated from one SIG to another, and one subproject to another. If we encode that grouping in the storage path, are we planning on reconciling it when repos migrate in the future?
- Did I get the scope of this correct? Is this just about GCR, or does this include GCS, groups, projects, etc?

/assign @thockin @detiber @listx @spiffxp

**Comment by ncdc** [comment]
Was grouping by SIG proposed somewhere? If so, I must have missed that. I think it makes sense to group by related projects (e.g. the various Cluster API images), but probably not by SIG.

**Comment by detiber** [comment]
+1 to grouping on related projects/subprojects rather than SIG as well.

**Comment by listx** [comment]
I just want to clarify around not deleting old manifests --- we can still rename e.g. the deprecated folders to mark them as such. The promoter doesn't care about folder names, as long as they line up within in the `manifests`/`images` toplevel folder names. E.g., if `manifests/foo/promoter-manifest.yaml` and `images/foo/images.yaml` is deprecated in favor of `bar`, `foo` itself can still be renamed to something like `foo-deprecated` (while leaving the yaml contents intact). At least this way we know pretty clearly from within either the `images` or `manifests` folders that it is deprecated.

**Comment by thockin** [comment]
The SIGs issue is mostly unrelated to the hierarchy issue.

question 1: Is there any limit or guidance we want to give to SIGs around
staging?  Probably not, but worth considering.

question 2: Is there value is using directories to group related efforts.
To me, I think so, but the horse is already out of the barn, kind of...

**Comment by spiffxp** [comment]
We discussed this during the April 1st meeting of wg-k8s-infra.  Basically I was coming from the perspective of do we _need_ grouping?  If so, is it something we should enforce? If so, I think we should lean into the community's existing sig/subproject/repo hierarchy.  If not, is there additional maintenance burden of allowing arbitrary grouping? How does that compare to the maintenance burden of the existing everything-is-split-up approach?

The notes say:
- we'll wait to see what cluster-api wants
- this sounds nice but probably not a priority
- we're not sure if there are tests to cover the migration path (https://github.com/kubernetes-sigs/k8s-container-image-promoter/issues/207 covers adding them)

**Comment by thockin** [comment]
I think we can just nix this idea.
