### ISSUE TITLE
Moving projects - how to do test with temporary subdomain before final move

### ISSUE THREAD

**Issue by bartsmykla** [kubernetes/k8s.io#697]
Hi everyone. I had time today I wanted to move perfdash to `aaa` cluster so I deployed manifests to `perfdash` namespace.

I wanted test everything is working well before I'm gonna create a PR with DNS change request so I used temporary subdomain .`perf-dash-test.k8s.io`. To use it though I would have to create DNS update request.
Question is, do we have any procedure to create some temporary dns records (for example to create: `perf-dash.staging.k8s.io`) which would be used to confirm everything works correctly before switching proper subdomain (`perf-dash.k8s.io`) to the new cluster?

What are your thoughts about it?

/cc @thockin @BenTheElder @munnerz @spiffxp @dims

**Comment by munnerz** [comment]
For completeness I feel like any domain regardless of purpose should be added into the config stored in this repo before applying, especially considering the sensitivity of the `k8s.io` and `kubernetes.io` domains.

Having a dedicated `staging` subdomain seems like it might be a good idea, but what would the restrictions/guidelines about how this is used be? I'd be concerned users may start using these links if they stumble across them, or search engines may start indexing them or something.

For now we could always use a completely separate domain, even one of your own, during tests. By pointing a DNS name at the ingress controller provisioned for the service we can fetch a TLS certificate using HTTP01. We'd just need to set the Ingress definition to use the 'testing' domain, and when we are ready to switch, update it accordingly.

Keen to hear what others think and feelings around the need for a `staging` subdomain and its implications :)

**Comment by BenTheElder** [comment]
> For completeness I feel like any domain regardless of purpose should be added into the config stored in this repo before applying, especially considering the sensitivity of the k8s.io and kubernetes.io domains.

💯 

just create a temporary entry, we did this with prow just fine (prow-canary.k8s.io IIRC)

**Comment by spiffxp** [comment]
/area dns
/close
I think we've decided to just not support a staging subdomain for now, and use `foo-staging.k8s.io` when trying to stage something destined for `foo.k8s.io`.  Please /reopen if you disasgree

**Comment by bartsmykla** [comment]
Completely aggree. :-)
