### ISSUE TITLE
Remove old google groups

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/k8s.io#698]
Back in May 2019, we removed our use of googlegroups.com groups in favor of kubernetes.io groups that we manage via automation (ref: https://github.com/kubernetes/k8s.io/pull/260).  I think it's time to get rid of the old groups.

I've confirmed these aren't in use by looking at our latest audit, which I refreshed locally out of extra paranoia (ref: https://github.com/kubernetes/k8s.io/pull/678)

Before I came to my senses and realized I should probably get a sanity check, the following were deleted:
- k8s-infra-gcr-admins@googlegroups.com
- k8s-infra-alerts@googlegroups.com

I'd like to confirm we're OK deleting the rest:
- k8s-infra-dns-admins@googlegroups.com
- k8s-infra-gcp-accounting@googlegroups.com
- k8s-infra-gcp-auditors@googlegroups.com
- k8s-infra-gcr-staging-cip-test@googlegroups.com
- k8s-infra-gcr-staging-kops@googlegroups.com
- k8s-infra-sig-release-prototype@googlegroups.com

/assign
I'll delete these if I hear nothing by Monday March 30th, or sooner if I get a +1 from the following assignees

**Comment by spiffxp** [comment]
/assign @dims @bartsmykla @thockin @cblecker 
For +1's

**Comment by bartsmykla** [comment]
+1 from me

**Comment by thockin** [comment]
+1 - I removed the last thing I found in the audit

**Comment by dims** [comment]
+1 from me

**Comment by spiffxp** [comment]
/close
Thanks all.  The groups listed above have been deleted
