### ISSUE TITLE
AWS: Investigate Saving Plans purchases 

### ISSUE THREAD

**Issue by ameukam** [kubernetes/k8s.io#7074]
we had multiple conversations about this. 

We should take a look at saving plans for either AWS Compute in general or specifically EC2 instances family so we can potentially purchase them in early 2025.

Refs:
  - https://aws.amazon.com/savingsplans/
  - https://kubernetes.slack.com/archives/CCK68P2Q2/p1706741926091069
  
 cc @dims @BenTheElder @upodroid 
 
 /milestone v1.32
 /area infra
/area infra/aws
/priority backlog
/lifecycle frozen

**Comment by ameukam** [comment]
cc @xmudrii

**Comment by ameukam** [comment]
cc @bryantbiggs @sftim 
In case you are interested

**Comment by bryantbiggs** [comment]
I've pinged a few folks who are knowledgeable in this area (spot, compute savings plans, etc.)

**Comment by ameukam** [comment]
@bryantbiggs Thank you! I think we have time to have a long conversation (arm64 scheduling, mix nodepools, etc...) about this and ensure we can buy on Jan 2025 or sooner.

**Comment by ameukam** [comment]
> I've pinged a few folks who are knowledgeable in this area (spot, compute savings plans, etc.)

Any feedback from your pings ?

**Comment by ameukam** [comment]
Feedback from AWS:

> Unfortunately AWS Credits cannot be used to purchase Savings Plans. AWS Credits can be applied to many AWS services and pay-as-you-go pricing, but they cannot be used for Savings Plans purchases. Savings Plans require an upfront commitment and must be paid for with actual currency rather than credits.

/close
