### ISSUE TITLE
Grant staging groups access to see container vulnerabilties

### ISSUE THREAD

**Issue by thockin** [kubernetes/k8s.io#715]
To get vuln info we need to grant role "Container Analysis Occurrences Viewer".

I see 2 paths:

1) Make a group which holds all the staging groups.  Every new group has to be added there.
2) Just grant every group that role on k8s-artifacts-prod

**Comment by spiffxp** [comment]
related: https://github.com/kubernetes/k8s.io/issues/803

**Comment by spiffxp** [comment]
Near as I can tell this hasn't been done yet.  We're talking about `roles/containeranalysis.occurrences.viewer` I assume.

**Comment by thockin** [comment]
correct

**Comment by spiffxp** [comment]
Ask PSC, we think this isn't secret information but let's confirm before moving with option 2

**Comment by spiffxp** [comment]
/close
We've disabled automated scanning, ref: https://github.com/kubernetes/k8s.io/issues/1963
