### ISSUE TITLE
eks-prow-build-cluster: Remove the KubeCost deployment

### ISSUE THREAD

**Issue by xmudrii** [kubernetes/k8s.io#7226]
We didn't manage to utilize KubeCost to gather data about ProwJobs because ProwJobs are non-managed Pods (e.g. not part of a ReplicaSet/Deployment) and this is not supported well by KubeCost. For that reason, gathering data required a lot of effort and we got similar data to what we have in our dashboards.

@koksay proposed that we remove the KubeCost deployment from the EKS Prow build cluster, so I'm created a ticket to track that.

/priority important-longterm
/area infra/aws
/area infra
/sig k8s-infra

**Comment by koksay** [comment]
I created PR #7234

**Comment by xmudrii** [comment]
@koksay Is this done?

**Comment by xmudrii** [comment]
@koksay Yes, let's clean up fully, we don't use it any longer and I don't expect that we'll need that data.

**Comment by koksay** [comment]
@xmudrii ok, I removed the S3 buckets and policies on both prod and canary environments.

**Comment by xmudrii** [comment]
@koksay Thanks a lot!
/close
