### ISSUE TITLE
TODO: remove "bart-test" namespace in "aaa" and linked workload-identity grants

### ISSUE THREAD

**Issue by thockin** [kubernetes/k8s.io#728]
Filing this as a reminder to clean up after Bart's testing of DNS and audit automation.

**Comment by spiffxp** [comment]
This will happen when we're done with automating DNS...

**Comment by spiffxp** [comment]
/remove-lifecycle rotten
ref: https://github.com/kubernetes/k8s.io/issues/783 for automating DNS

**Comment by bartsmykla** [comment]
As it's not needed anymore I deleted it.

/close
