### ISSUE TITLE
TLS certificates not found in account 209411653980

### ISSUE THREAD

**Issue by shraddhabang** [kubernetes/k8s.io#7328]
AWS LBC e2e test fail with the error:

`{"level":"error","ts":"2024-09-20T01:25:10Z","msg":"Reconciler error","controller":"service","namespace":"service-ip-e2e-a7769f","name":"ip-e2e-tls","reconcileID":"6837ce8d-1f4b-47a5-aa59-4d52e2451896","error":"operation error Elastic Load Balancing v2: CreateListener, https response error StatusCode: 400, RequestID: a0b9ab1b-b855-4e39-8e43-1628d5fe3e5c, CertificateNotFound: Certificate 'arn:aws:acm:us-west-2:209411653980:certificate/d39a65e5-44f6-4734-9034-6c82ae7df73b' not found"}`

https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_aws-load-balancer-controller/3844/pull-aws-load-balancer-controller-e2e-test/1836911585373720576/build-log.txt#:~:text=%7B%22level%22%3A%22error%22%2C%22ts%22%3A%222024%2D09%2D20T01%3A25,d39a65e5%2D44f6%2D4734%2D9034%2D6c82ae7df73b%27%20not%20found%22%7D

Can we check if this certificate are there in the account `209411653980`? 
We added 3 certs for the aws-load-balancer-controller ci jobs when migrating to the new AWS CI account: https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/3391#issuecomment-1724676041

CC: @dims

**Comment by dims** [comment]
@shraddhabang if they are missing then i have to re-do the steps in https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/3391#issuecomment-1724672485 ?

( you need a total of 3 certs? )

**Comment by shraddhabang** [comment]
Yes.

**Comment by dims** [comment]
The certs were expired, i re-imported with a fresh cert/key reusing the same id(s). Looks like we'll have to this periodically :)

![image](https://github.com/user-attachments/assets/34424a67-460d-49ba-8999-5db78de78bd9)

**Comment by shraddhabang** [comment]
Let me restart these tests and will let you know. Thanks for this.

**Comment by dims** [comment]
No `CertificateNotFound` errors in:

https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_aws-load-balancer-controller/3844/pull-aws-load-balancer-controller-e2e-test/1837275283338563584/build-log.txt

/close
