### ISSUE TITLE
How to force restart a POD based on init-container 

### ISSUE THREAD

**Issue by gball14** [kubernetes/k8s.io#737]
I want to restart the **pod** if the init container can not execute nslookup successfully i.e. there is an issue with dns set up for the pod. I tried the below command for init-container to understand the behaviour. But, kubernetes just restart the container and not the pod. 

command: ['sh', '-c', 'echo The app is running! && exit 1;']

**Comment by bartsmykla** [comment]
Hi @gball14 
I'm not sure if I understand yout problem correctly but if so I think the better place to ask would be: https://github.com/kubernetes/kubernetes/ repository.
Here we are mostly working on stuff related to [`k8s-infra-wg`](https://github.com/kubernetes/community/tree/master/wg-k8s-infra)

**Comment by bartsmykla** [comment]
@gball14 I'm closing the issue for now. If you think I misunderstood the problem feel free to write here and I'm gonna reopen it
/close
