### ISSUE TITLE
[Failing Test] ci-k8sio-image-promo

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/k8s.io#7390]
https://testgrid.k8s.io/sig-release-releng-blocking#ci-k8sio-image-promo

/sig release 

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-k8sio-image-promo/1827239539731599360

```

time="07:00:45.398" level=error msg="multiple edges want to promote *different* images (digests) to the same destination endpoint europe-west8-docker.pkg.dev/k8s-artifacts-prod/images/releng/releng-ci:1.22.5-bookworm-0:" diff=2.909s
time="07:00:45.398" level=error msg="  for digest sha256:eab458e01e6b09a1123de9d8739341ed4470f779996fe0e7e6bb3bf63b0b4d3f:\n" diff=0s
```

The test started to fail since https://github.com/kubernetes/k8s.io/pull/7214?
- https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/ci-k8sio-image-promo?buildId=1829776232279969792

/cc @nilekhc @aramase

**Comment by ameukam** [comment]
@pacoxu the job is now green for a while now. Do we still need this ?

**Comment by pacoxu** [comment]
/close
@ameukam  thanks for the update.
