### ISSUE TITLE
Subscribe to AWS shield protection service for account 209411653980

### ISSUE THREAD

**Issue by oliviassss** [kubernetes/k8s.io#7419]
Hi, the [aws-load-balancer-controller](https://github.com/kubernetes-sigs/aws-load-balancer-controller) uses account `209411653980` to run integration e2e tests. Can the account owner help to subscribe to AWS shield service following this instruction: https://docs.aws.amazon.com/waf/latest/developerguide/enable-ddos-prem.html
Since the controller has shield enabled by default, we want to make sure our CI tests cover this service. We had a recent miss in our release during migration to aws-sdk-go v2: https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/3888

**Comment by ameukam** [comment]
cc @dims

**Comment by dims** [comment]
@oliviassss @shraddhabang Seems to cost $3k per year for "Advanced" .. is that what you are looking for?

![image](https://github.com/user-attachments/assets/ae964d0d-c6ad-4e05-9e77-82783d73392d)

**Comment by dims** [comment]
Also a 12 month minimum commitment...

![image](https://github.com/user-attachments/assets/e3b36d59-0fbe-4516-8e4e-29f327e00fcd)

**Comment by BenTheElder** [comment]
> Seems to cost $3k per year for "Advanced" .. is that what you are looking for?

Don't those screenshots show $3k *per month* ?

**Comment by dims** [comment]
updated my comment!

**Comment by dims** [comment]
xref: slack thread - https://kubernetes.slack.com/archives/CCK68P2Q2/p1729706041952769?thread_ts=1729696095.211869&cid=CCK68P2Q2

good call for now @oliviassss i don't think you see the $3k in your dev account as it is covered at the org level probably. I agree we need to test this properly, for now downstream dev account seems like the best idea. Still looking at pricing etc, but it is better to start the conversation to test this outside of community CI account as well.
