### ISSUE TITLE
Migrate slack-infra services to aaa cluster

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/k8s.io#751]
- origin gcp-project: kubernetes-tools
- origin cluster-name: tools-cluster
- apps:
  - [ ] slackin (slack.k8s.io)
  - [ ] slack-event-log
  - [ ] slack-moderator
  - [ ] slack-welcomer
- repo: https://github.com/kubernetes-sigs/slack-infra

/wg k8s-infra
/area cluster-infra
/assign @bartsmykla @ameukam

**Comment by nikhita** [comment]
fyi @Katharine @BenTheElder @jeefy @mrbobbytables

**Comment by BenTheElder** [comment]
there's also the tempellis image hosting, we should move that to a staging project probably.

**Comment by bartsmykla** [comment]
My step by step plan to move slack infra to the `aaa` cluster:

1. Creating PR with updated instructions about [how to deploy the `slack-infra`](/slack-infra#todo-how-to-deploy) and two missing resource manifests (ingress and certificate)
2. Deploying ingress resource to receive efemeral IP address
3. Updating DNSes with temporary domains (slack-staging.k8s.io and slack-staging.kubernetes.io) pointing to the address from the point above
4. Asking a person with permission (@thockin probably) to mark received, efemeral address as static (with name: `slack-infra-ingress-prod`)
5. Updating the ingress resource created in point 1 with annotation: `kubernetes.io/ingress.global-static-ip-name: slack-infra-ingress-prod`
6. Asking one of the people who have access to encrypted secrets (@dims, @spiffxp, @thockin) to deploy them to the `slack-infra` namespace:
```shell
# Commands needs to be run from the slack-infra directory
# Secrets
    git-crypt unlock

    # slack-event-log
    kubectl apply -n slack-infra -f slack-event-log/slack-event-log-config-secret.yaml

    # slack-moderator
    kubectl apply -n slack-infra -f slack-moderator/slack-moderator-config-secret.yaml

    # slack-welcomer
    kubectl apply -n slack-infra -f slack-welcomer/slack-welcomer-config-secret.yaml

    # slackin
    kubectl apply -n slack-infra -f slackin/recaptcha-secret.yaml
    kubectl apply -n slack-infra -f slackin/slackin-token-secret.yaml

    git-crypt lock
```
7. Figuring out if deploying `slack-event-log`, `slack-moderator` and `slack-welcomer` without first turning off the already existing instances is possible
   - [if not]:
      1. Figuring out who can shut down these services
      2. Figuring out when it would be the best time to shutdown these services
      3. Figuring out who should be informed about this and informing these groups
      4. Shuting down these services
   - [if yes]: moving to the next step
8. Deploying the rest of resources:
```shell
# Basic resources
    kubectl apply -n slack-infra -f ingress.yaml
    kubectl apply -n slack-infra -f certificate.yaml

    # slack-event-log
    kubectl apply -n slack-infra -f slack-event-log/deployment.yaml
    kubectl apply -n slack-infra -f slack-event-log/service.yaml

    # slack-moderator
    kubectl apply -n slack-infra -f slack-moderator/deployment.yaml
    kubectl apply -n slack-infra -f slack-moderator/service.yaml

    # slack-welcomer
    kubectl apply -n slack-infra -f slack-welcomer/deployment.yaml
    kubectl apply -n slack-infra -f slack-welcomer/message.yaml
    kubectl apply -n slack-infra -f slack-welcomer/service.yaml

    # slackin
    kubectl apply -n slack-infra -f slackin/deployment.yaml
    kubectl apply -n slack-infra -f slackin/service.yaml
```
9. If everything will work fine, updating the DNSes and certificate with proper subdomains (slack.k8s.io and slack.kubernetes.io) pointing to the new ingress (`slack-infra-ingress-prod` IP address)
10. After confirmation everything works as expected removing dns records for subdomains: slack-staging.k8s.io and slack-staging.kubernetes.io
11. Getting consensus if we can remove resource manifests (listed below) from our repository and update deploy instructions to use the ones existing at [k-sigs/slack-infra/cluster](https://github.com/kubernetes-sigs/slack-infra/blob/master/cluster):
```
slack-infra/slack-event-log/deployment.yaml
slack-infra/slack-event-log/service.yaml

slack-infra/slack-moderator/deployment.yaml
slack-infra/slack-moderator/service.yaml

slack-infra/slack-welcomer/deployment.yaml
slack-infra/slack-welcomer/message.yaml
slack-infra/slack-welcomer/service.yaml

slack-infra/slackin/deployment.yaml
slack-infra/slackin/service.yaml
```
12. If agreed implementing the changes from the point 11

**Comment by bartsmykla** [comment]
@dims, @spiffxp, @thockin can one of you deploy the secrets ([step 6](https://github.com/kubernetes/k8s.io/issues/751#issuecomment-617833729)) as it doesn't conflicts with other steps?

**Comment by spiffxp** [comment]
/assign
taking a look

**Comment by spiffxp** [comment]
```
spiffxp@cloudshell:~/k8s.io (kubernetes-public)$ for f in slack-infra/*/*-secret.yaml; do kubectl apply -n slack-infra -f $f; done
secret/slack-event-log-config created
secret/recaptcha created
secret/slackin-token created
secret/slack-moderator-config created
secret/slack-welcomer-config created
```
```
spiffxp@cloudshell:~/k8s.io (kubernetes-public)$ kubectl get secrets -n slack-infra
NAME                     TYPE                                  DATA   AGE
default-token-dtsxg      kubernetes.io/service-account-token   3      17h
recaptcha                Opaque                                2      18s
slack-event-log-config   Opaque                                1      19s
slack-moderator-config   Opaque                                1      17s
slack-welcomer-config    Opaque                                1      16s
slackin-token            Opaque                                1      18s
```

**Comment by spiffxp** [comment]
/unassign
I would ask #slack-admins about 7

I'm... marginally ok with 11, but I don't want us to get to a point where answering "what's the source of what is deployed in our cluster" becomes a byzantine task of manually tracking everything down.  In an ideal world it's a machine-answerable question.

How can we re-use those externally defined resources + patch in / overlay our own needs? kustomize? kpt?

**Comment by ameukam** [comment]
Sounds like a good plan @bartsmykla.:)

**Comment by ameukam** [comment]
@spiffxp can you deploy the ConfigMap `bad-domains` in `slack-infra` : https://github.com/kubernetes-sigs/slack-infra/blob/master/cluster/slackin/deployment.yaml#L51-L54 ?

**Comment by bartsmykla** [comment]
Yes, it looks like we are missing this to run the `slackin`

**Comment by bartsmykla** [comment]
So @spiffxp applied the ConfigMap and I just have to update the repository with the missing manfest

**Comment by bartsmykla** [comment]
When I today checked what's the status of `slack-infra` I realized we can't use existing images which are hosted at internal-accesible only GCR registry so we have to start deploying them to registries managed by us.

```
Warning  Failed     16s (x2 over 30s)  kubelet, gke-aaa-pool2-20200316195138785800000-fafa121a-zhw5  Failed to pull image "gcr.io/kubernetes-tools/slackin-kubernetes@sha256:d1a9b02239e690d5cbd78c76475a112aedf279dbd8ef401de1b8394f817a23b3": rpc error: code = Unknown desc = Error response from daemon: pull access denied for gcr.io/kubernetes-tools/slackin-kubernetes, repository does not exist or may require 'docker login'
```

ref. #802

**Comment by bartsmykla** [comment]
As suggested and discussed [at slack](https://kubernetes.slack.com/archives/C4M06S5HS/p1587979163078600), we proceed with @munnerz with DNS update (ref. #814, #815 and #817), all four tools are right now working at the `aaa` cluster.

We have tested inviting the new members via [slack.k8s.io](https://slack.k8s.io) and reporting messages. We are also in the process od checking if event-log works as expected (I'll need confirmation from @munnerz as access to that channel is restricted to slack admins). 

I suggest to leave the old infrastructure still running for the next two weeks to be sure everything is fine, and then we can get rid of another cluster.

I will followup with the PR updarting the certificate.yaml file and one removing the temporary slack-staging.k8s.io subdomain.

**Comment by bartsmykla** [comment]
Following up PR for removal of slack-staging.k8s.ip dns record and also with update of the certificate.yaml #818

**Comment by bartsmykla** [comment]
There are two things I would like to still do, even if the whole `slack-infra` already works in out new infra.

1. Get consensus if we can remove manifests of basic resources (like deplyoments and services) from our repository and instead use the ones from [k-sigs/slack-infra/cluster](https://github.com/kubernetes-sigs/slack-infra/tree/master/cluster) and do it if we'll decide it's a good idea.
2. Currently every image which slack tools are using are still pointing to the registry not managed by us, so I would like to create the staging registry and then configure the automate builds for the images and use them in our cluster

**Comment by spiffxp** [comment]
/close
slack-infra has been migrated over, there is followup to be done re:images and certs
