### ISSUE TITLE
Migrate node-perf-dash to aaa cluster (or retire)

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/k8s.io#753]
- origin gcp-project: kubernetes-site
- origin cluster-name: utilicluster
- apps:
  - [ ] node-perf-dash (https://node-perf-dash.k8s.io)
- repo: https://github.com/kubernetes-retired/contrib/tree/master/node-perf-dash

/wg k8s-infra
/sig node
/sig scalability
(I don't actually know which of these sigs this belongs to, if any)
/area cluster-infra
/assign @bartsmykla

**Comment by spiffxp** [comment]
Bart has been pinging in kubernetes slack on #sig-node and #sig-scalability trying to find owners or users of this service

**Comment by bartsmykla** [comment]
Also @thockin is pinging people who I heard wanted to take ownership of this project.

/assign @thockin

**Comment by bartsmykla** [comment]
@spiffxp @dims we discussed yesterday with @thockin that despite our efforts to communicate with people who can be interested in `node-perf-dash` there is no response and we are close to the decision to retire the project. We think about setting a deadline as a last day of this month for someone to pick this up and if note we would just retire it and remove the cluster completely (#754) as it's the last project there. Wdyt?

**Comment by dims** [comment]
@bartsmykla give it 2 weeks please. just in case folks are dealing with other emergencies. hope you have already notified sig-node mailing list

**Comment by bartsmykla** [comment]
@dims You are right. Do you think we should give people more than 2 weeks? It's not that crutial to turn it down immidiately but I would like to not lose it from the horisont.

**Comment by dims** [comment]
2 weeks is reasonable to me. we can always resurrect it if needed.

**Comment by spiffxp** [comment]
/assign @bartsmykla 
To send message to sig-node mailing list

**Comment by bartsmykla** [comment]
I have sent the email: https://groups.google.com/forum/#!topic/kubernetes-sig-node/lNR6RiPzYYY

Lazy consensus final date is set to May 14, 2020

**Comment by spiffxp** [comment]
Just to update here, someone did claim ownership and so it's being moved.  Based on discussion in today's meeting it sounds like we're waiting on confirmation to cutover and turn down the old deployment.

**Comment by bartsmykla** [comment]
So after #903 was merged. The project is now fully migrated and https://node-perf-dash.k8s.io points to the `aaa`

/close

**Comment by MHBauer** [comment]
Who claimed ownership? 

I think to myself, "how useful could the dashboard be if the backing data is filled by a bunch of failing tests".

Are they going to fix the tests? They can't be getting good data.

**Comment by bartsmykla** [comment]
@MHBauer @lorqor claimed ownership
