### ISSUE TITLE
Turn down kubernetes-site/utilicluster cluster

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/k8s.io#754]
We can do this once:
- [x] cert-manager has been migrated
- [x] gcsweb has been migrated (#204)
- [x] k8s.io redirector has been migrated
- [ ] node-perf-dash has been migrated (or retired) (#753)
- [x] velodrome has been migrated (or retired)

/wg k8s-infra
/area cluster-mgmt
/assign @thockin
I feel like @thockin deserves the honor here
/assign @spiffxp 
I need to figure out if we're ok deleting velodrome

**Comment by spiffxp** [comment]
velodrome is down due to security reasons, I tried to outline what a rewrite might look like https://github.com/kubernetes/test-infra/issues/16836#issuecomment-614340375

would deleting the current instance of velodrome hurt us?
- influx's persistent data can be repopulated/backfilled as long as the k8s-gubernator.builds dataset exists
- grafana's persistent data is mainly dashboards, which we have saved off in the kubernetes/test-infra repo
- we don't really want to redploy velodrome in its current form so it's likely going to need to be redone anyway

yeah we can delete velodrome

**Comment by bartsmykla** [comment]
Project was migrated, we can turn down the cluster

ref. #753 #903

**Comment by thockin** [comment]
The old utilicluster is deleting now.
