### ISSUE TITLE
coordinate rotating k8s-ci-robot credentials

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/k8s.io#7604]
These are available in a few of the clusters k8s-infra provides. They need to be rotated and any old access tokens removed from the account.

See also this thread: https://kubernetes.slack.com/archives/C09QZ4DQB/p1733947637418569

TLDR: There's some old automation nobody knows anything about that is using @k8s-ci-robot to create git tags in [kubernetes-sigs/structured-merge-diff](https://github.com/kubernetes-sigs/structured-merge-diff), presumably it is not getting patched and isn't strictly necessary.

Given that we have had unknown automation accessing the account we should really rotate the creds.

For other repo automation we usually use accounts like @k8s-publishing-bot @k8s-infra-ci-robot @k8s-triage-robot etc with limited or no permissions. k8s-github-robot is too permissioned to have unknown automation and generally the clusters we know about are pretty locked down:
1. The cluster hosting prow / SIG Testing CI services and nothing else
2. The "trusted" CI job cluster which currently has jobs restricted to https://github.com/kubernetes/test-infra/tree/master/config/jobs/kubernetes/sig-k8s-infra/trusted with limited approver set

The account is also in a shared 1password with SIG Testing leads and the Kubernetes github management team, anywhere else is unexpected IMO.

cc @kubernetes/sig-testing-leads @kubernetes/sig-k8s-infra-leads @kubernetes/owners 

I'm not going to do this in the middle of winding up the release, but we need to start looking at this soon.

**Comment by dims** [comment]
cc @kubernetes/owners

**Comment by aojea** [comment]
👀

**Comment by ameukam** [comment]
I have no idea. Are we sure this is not some account impersonation using an old PAT ?

**Comment by BenTheElder** [comment]
> Are we sure this is not some account impersonation using an old PAT ?

I'm assuming an old PAT is in use, we should revoke them.

even if that's not the case, the fact that we're not sure is a problem

**Comment by BenTheElder** [comment]
the mystery automation is misleading github ui, will say the tag is "created by" the author of the underlying commit, absent an annotated tag. this is not accurate, and makes it appear the robot is creating tags, when it is not.

case closed. thanks @VannTen
