### ISSUE TITLE
wg-data-protection-leads@kubernetes.io and wg-data-protection@kubernetes.io are not created

### ISSUE THREAD

**Issue by xing-yang** [kubernetes/k8s.io#7631]
wg-data-protection-leads@kubernetes.io and wg-data-protection@kubernetes.io are added to the groups.yaml:
https://github.com/kubernetes/k8s.io/blob/main/groups/wg-data-protection/groups.yaml#L2
https://github.com/kubernetes/k8s.io/blob/main/groups/wg-data-protection/groups.yaml#L17

However, I don't see them here:
https://groups.google.com/a/kubernetes.io/g/wg-data-protection-leads
https://groups.google.com/a/kubernetes.io/g/wg-data-protection

**Comment by ameukam** [comment]
Do you mind replicate what's done here https://github.com/kubernetes/k8s.io/blob/main/groups/wg-serving/groups.yaml ? 
Looks there is some kind of misconfiguration to prevent the groups creation ?

Given we are close to the EoY, I can't guarantee you will get some assistance before 2025.

**Comment by xing-yang** [comment]
Sure, let me update the groups.yaml config.  Thanks @ameukam!

**Comment by ameukam** [comment]
@xing-yang can you confirm it's fixed ?

**Comment by xing-yang** [comment]
@ameukam, yes, it works now.  Thank you!
