### ISSUE TITLE
Static IP Management

### ISSUE THREAD

**Issue by bartsmykla** [kubernetes/k8s.io#775]
When you want to run something in community cluster and need subdomain, we are recomending to mark IP which will be assigned to `Ingress` resource you'll deploy as static.
Currently it's not clear to me who except @thockin can do it and it needs to be done manually.
I think doing it manually is unnecessary and I would like to suggest using our current terraform configuration to handle that.

There are currently [4 static addresses](https://console.cloud.google.com/networking/addresses/list?authuser=0&organizationId=758905017065&project=kubernetes-public):

```shell
gcsweb-k8s-io                 -> 35.190.8.208
k8s-io-ingress-canary         -> 34.102.239.89
k8s-io-ingress-prod           -> 34.107.204.206
perf-dash-k8s-io-ingress-prod -> 34.102.200.94
```

and moving them to be managed by terraform would look something like:

1. Adding blocks for each of the addresses into [the cluster config file](https://github.com/kubernetes/k8s.io/blob/master/infra/gcp/clusters/kubernetes-public/aaa/10-cluster-configuration.tf):
```terraform
resource "google_compute_global_address" "gcsweb-k8s-io" {
  name = "gcsweb-k8s-io"
}

resource "google_compute_global_address" "k8s-io-ingress-canary" {
  name = "k8s-io-ingress-canary"
}

resource "google_compute_global_address" "k8s-io-ingress-prod" {
  name = "k8s-io-ingress-prod"
}

resource "google_compute_global_address" "perf-dash-k8s-io-ingress-prod" {
  name = "perf-dash-k8s-io-ingress-prod"
}
```
2. Running import commands to include our already existing IP addresses in terraform's state file
```shell
terraform import google_compute_global_address.gcsweb-k8s-io kubernetes-public/gcsweb-k8s-io
terraform import google_compute_global_address.k8s-io-ingress-canary kubernetes-public/k8s-io-ingress-canary
terraform import google_compute_global_address.k8s-io-ingress-prod kubernetes-public/k8s-io-ingress-prod
terraform import google_compute_global_address.perf-dash-k8s-io-ingress-prod kubernetes-public/perf-dash-k8s-io-ingress-prod
```
3. Running the `terraform plan` command to see how the configuration compares to the imported resources
4. Changing [the documentation about how to run something in community clusters](https://github.com/kubernetes/k8s.io/blob/master/running-in-community-clusters.md#public-ips)

In first step we are not specyfiing the exact addresses but there are two approaches we can take:

1. Someone creates the PR adding new resource block in the terraform configuration (in the same PR there can be also edded instructions about deploying the project and google group for people to access the project's namespace) and when the IP will be created by running the terraform the person would have to create another PR and update the DNSes.
2. Someone creates the PR adding the namespace for the project. After deploying the project with the Ingress resource the efemeral IP address will be created automatically by GCP and assigned to the ingress. The person have to create another PR adding the resource block to terraform configuration and as we already know the IP adress we can put it inside the resource block:
```terraform
resource "google_compute_global_address" "gcsweb-k8s-io" {
  name    = "gcsweb-k8s-io"
  address = "35.190.8.208"
}
```
In the same PR the person can update DNSes too. After the PR will be merged somebody with permissions would have to run `terraform import ...` command to include the IP address in terraform's state file.

The only benefit in the second approach I see is to have better documentation as the IP addresses would be explicitly visible in our codebase, but I'm not convinced it's a deal breaker.

I would like to ask about your opinion and also suggest the deadline for opinions for this Friday.

/cc @thockin @dims @spiffxp @cblecker @munnerz

**Comment by thockin** [comment]
What if we just stopped allocating them static, and just relied on the idea that we don't delete the Ingress?

**Comment by bartsmykla** [comment]
So what I saw today is GCP will still alocate the addresses for Ingresses as static but assign them some randomish name, which is suboptimal so as we are currently creating the addresses I prepared small script for it till we'll decide what we want to do with it: #798

**Comment by thockin** [comment]
Let's discuss tomorrow

**Comment by bartsmykla** [comment]
sgtm

**Comment by thockin** [comment]
Did you discuss after I dropped?  Sorry, forgot this topic.

**Comment by spiffxp** [comment]
@thockin We punted since you dropped

**Comment by spiffxp** [comment]
ignore the terraform idea, just use existing script, continue the pattern of pre-allocating static ips
