### ISSUE TITLE
Turn down kubernetes-public/development2 cluster

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/k8s.io#785]
We can do this once:
- [x] publishing-bot has been migrated to aaa (ref: https://github.com/kubernetes/k8s.io/issues/503)

/wg k8s-infra
/area cluster-mgmt
/assign @thockin
I feel like @thockin deserves the honor here
/assign @nikhita
to confirm if the publishing-bot instance running on development2 has been migrated

**Comment by nikhita** [comment]
> /assign @nikhita 
to confirm if the publishing-bot instance running on development2 has been migrated

Confirming that the publishing-bot instance running on `development2` has been migrated to `aaa` (https://github.com/kubernetes/k8s.io/issues/503)

/unassign

@thockin heads up that everything in the k8s-publishing-bot namespace has been [cleared out](https://console.cloud.google.com/kubernetes/workload?organizationId=758905017065&project=kubernetes-public), but it looks like the namespace is still stuck in `Terminating`...

Also, related: https://github.com/kubernetes/k8s.io/issues/395

**Comment by spiffxp** [comment]
@thockin turn down at your leisure

**Comment by thockin** [comment]
Done
