### ISSUE TITLE
Change the name of slack-infra's IP address

### ISSUE THREAD

**Issue by bartsmykla** [kubernetes/k8s.io#793]
As I deployed Ingress resource for `slack-infra` to receive IP address which will be used during the rest of the process it was done and the IP address assigned is:
```
k8s-fw-slack-infra-slack-infra--ea949c440a044527 | 34.102.202.147
```
@thockin as you are I think the only person with enough permissions so far, can you rename the IP address from `k8s-fw-slack-infra-slack-infra--ea949c440a044527` to `slack-infra-ingress-prod` please?

/assign @thockin

**Comment by stp-ip** [comment]
Renaming resources isn't possible within GCP for the most part. This includes static IPs. This means afaik we are stuck with the name or have to recreate it with a new IP.

**Comment by bartsmykla** [comment]
Oh, great to know @stp-ip thank you for your comment!

**Comment by bartsmykla** [comment]
@thockin would you be able to create a new static IP with the name `slack-infra-ingress-prod` address instead?

**Comment by thockin** [comment]
I can, but maybe we should just give cluster-admins that power?

**Comment by bartsmykla** [comment]
@thockin sgtm
@dims @spiffxp wdyt?

**Comment by thockin** [comment]
I gave cluster admins load-balancer admin perms.  Does that seem like a bad
idea?  Try it out, if happy I have a script diff I can send

**Comment by bartsmykla** [comment]
Added address:
```
slack-infra-ingress-prod | 34.107.195.71
```

**Comment by bartsmykla** [comment]
I think we can close it now as we have the address created

/close
