### ISSUE TITLE
Grant GKE service account "Container Analysis Occurrences Viewer" role

### ISSUE THREAD

**Issue by listx** [kubernetes/k8s.io#803]
It appears that [Container Analysis Service](https://cloud.google.com/container-registry/docs/container-analysis) is already turned on for `k8s-artifacts-prod`. But in order to consume this information (e.g., cloud vendors such as GKE), the "Container Analysis Occurrences Viewer" role must be granted to the vendor. For GKE, the service account that needs this role is `vulnerability@gke-release-staging.iam.gserviceaccount.com`.

/cc @thockin @destijl @simony-gke

**Comment by listx** [comment]
I think ultimately the PR for this boils down to adding another special-cased grant in `infra/gcp/ensure-prod-storage.sh`, but I wonder if we need to think about separating permissions tied to vendor-specific needs (third party organizations) to a separate script or separate hierarchical system. AFAIK all of the current grants deal with giving community groups (such as the artifact admins), not third parties.

**Comment by thockin** [comment]
I wonder if we can turn that into pub-sub or something less intrusive

**Comment by listx** [comment]
> I wonder if we can turn that into pub-sub or something less intrusive

Do you mean adding a pub-sub layer and letting third parties consume those pub-sub messages (instead of having direct access as `Container Analysis Occurrences Viewer`)?
