### ISSUE TITLE
Downloading k8s.io go packages

### ISSUE THREAD

**Issue by JeanMertz** [kubernetes/k8s.io#82]
I'm not sure this is the right place to ask, but it seems like the closest I can get to where the issue probably stems from, so here goes.

I'm trying to make a [Homebrew](https://brew.sh) (macOS package manager) package out of a [go tool I wrote](https://github.com/blendle/kubecrt). In order to do this, I mark packages as dependencies in the package config file for Homebrew.

This looks like this:

```ruby
go_resource "github.com/spf13/pflag" do
  url "https://github.com/spf13/pflag",
      :revision => "e57e3eeb33f795204c1ca35f56c44f83227c6e66"
end

go_resource "golang.org/x/crypto" do
  url "https://golang.org/x/crypto",
      :revision => "7d9177d70076375b9a59c8fde23d52d9c4a7ecd5"
end

go_resource "gopkg.in/yaml.v2" do
  url "https://gopkg.in/yaml.v2",
      :revision => "eb3733d160e74a9c7e442f435eb3bea458e1d19f"
end

go_resource "k8s.io/apimachinery" do
  url "https://k8s.io/apimachinery",
      :revision => "1168e538ea3ccf444854d1fdd5681d2d876680a7"
end
```

When installing the dependencies using Homebrew, things work as expected, _except_ for packages prepended with `k8s.io`:

```
==> Downloading https://github.com/spf13/pflag
######################################################################## 100.0%
Warning: Cannot verify integrity of kubecrt--github.com-spf13-pflag-0.6.0
A checksum was not provided for this resource
For your reference the SHA256 is: cac4d7d9b0cf76aa2cb2277b2f3c120d35ce56fba36f050d54b828d6eefac136
==> Downloading https://golang.org/x/crypto
######################################################################## 100.0%
Warning: Cannot verify integrity of kubecrt--golang.org-x-crypto-0.6.0
A checksum was not provided for this resource
For your reference the SHA256 is: 237552c607b93d6e682100183d059b6f104a07b5ec4958148c3db9aaf0a0a09d
==> Downloading https://gopkg.in/yaml.v2
######################################################################## 100.0%
Warning: Cannot verify integrity of kubecrt--gopkg.in-yaml.v2-2.v2
A checksum was not provided for this resource
For your reference the SHA256 is: cb3c370a44d64e289fbc6c802b4e7eee1f4b800cd315bac15c111163b6671206
==> Downloading https://k8s.io/apimachinery
==> Downloading from https://kubernetes.io/apimachinery

curl: (22) The requested URL returned error: 404 
Error: Failed to download resource "kubecrt--k8s.io-apimachinery"
Download failed: https://k8s.io/apimachinery
```

Looking at this repository, it seems there's an Nginx instance behind `k8s.io` that does some rewriting/redirecting logic based on provided request details.

Since `go get k8s.io/apimachinery` works as expected, I'm wondering if what I want to do is even possible, or not, but I just wanted to point this out, and see if there's a way to make this work.

Now, after hitting this error, I went and refactored my package, so now it only depends on the official Golang package manager `dep`, and I use that to install the required dependencies. In the end, this is the way to go, but I was still interested in the above issues, and wanted to report them here, in case this is something you want to tackle.

**Comment by thockin** [comment]
Are you passing "go-get=1" on the URL?  All the others happen to be code
hosting sites.  k8s.io is not.  It only responds if you set the param, and
then it responds with Go's metadata to redirect to github.  If you want to
pull go code, you have to do it like Go does :)

**Comment by JeanMertz** [comment]
Thanks @thockin. I wasn't aware go added the `go-get` a param. You learn something new every day 😄 

Thank you for your pointer, this will help me (and others at our company) be aware of this in the future 👍
