### ISSUE TITLE
Setup ghproxy in k8s-infra-prow-build-trusted

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/k8s.io#843]
(ghProxy)[https://github.com/kubernetes/test-infra/tree/master/ghproxy] is a reverse proxy HTTP cache optimized for use with the GitHub API.  Jobs that manage our github orgs and repos (label_sync, peribolos) greatly benefit from this, and at this point probably won't run without it.

Today, the google.com prow.k8s.io cluster acting as "trusted build cluster" (k8s-prow/prow)has it deployed to its own nodepool (label dedicate:ghproxy)
- node: n1-standard-8, 100 GB pd-standard, COS
- volume: 100Gi, pd-ssd, gce-ssd-retain storageclass (defined in test-infra/config/prow/cluster)

ref: https://github.com/kubernetes/k8s.io/issues/752, followup to: https://github.com/kubernetes/k8s.io/pull/830

**Comment by ameukam** [comment]
@spiffxp I started to look at ghproxy and I'm curious about something: is [pushgateway](https://github.com/kubernetes/test-infra/blob/master/config/prow/cluster/ghproxy.yaml#L60) a hard requirement for ghproxy ?

**Comment by bartsmykla** [comment]
@ameukam it looks like it's an endpoint for prometheus metrics to be exposed, but looking at: [`k/test-infra/ghproxy/ghproxy.go#L122`](https://github.com/kubernetes/test-infra/blob/d7e9546a3edf043ef8ab6a74a79ce2416e810b85/ghproxy/ghproxy.go#L122) I would understand it can be ommited and I would suggest to to it at this point.

Looking at [`k/test-infra/prow/metrics/metrics.go`](https://github.com/kubernetes/test-infra/blob/d7e9546a3edf043ef8ab6a74a79ce2416e810b85/prow/metrics/metrics.go#L40-L45) to not expose the metrics there still needs to be passed `--push-gateway` flag with no `--serve-metrics` flag or it set to `false` as when `--push-gateway` is not set it would ignore `--serve-metrics` set to `false`.

BTW. @fejta should it work that way or is it a bug?

**Comment by spiffxp** [comment]
/assign
need to provide token to trusted cluster for ghproxy

**Comment by spiffxp** [comment]
Blocked on https://github.com/kubernetes/test-infra/issues/11402#issuecomment-760350837

**Comment by ameukam** [comment]
ghproxy is up and running on `k8s-infra-prow-builder-cluster-trusted`. 
Auto-upgrade is enabled for it : https://github.com/kubernetes/k8s.io/pull/2402. 
The k8s-triage-robot prowjobs use it: https://github.com/kubernetes/test-infra/pull/23103. 

Considered done when https://github.com/kubernetes/test-infra/issues/11402#issuecomment-709517484 is addressed.

**Comment by ameukam** [comment]
we can resume this now we have control of `k8s-ci-robot`

**Comment by ameukam** [comment]
This can be closed.

https://github.com/kubernetes/test-infra/issues/11402#issuecomment-2167796217

/close
