### ISSUE TITLE
Migrate jobs away from gs://kubernetes-release-dev

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/k8s.io#846]
There are a number of jobs that assume they have write access to `gs://kubernetes-release-dev`, and then a bunch of other jobs that assume they should be downloading builds from `gs://kubernetes-release-dev`

Unfortunately, this bucket will not allow non-google.com service accounts to write to it.  We need to use a new bucket, and develop a plan for using it that doesn't involve all jobs being cut over in lock step.  

I am pretty sure this overlaps with ongoing work by the release-engineering subproject

ref: https://github.com/kubernetes/k8s.io/issues/752, https://github.com/kubernetes/k8s.io/issues/841 - followup to https://github.com/kubernetes/k8s.io/pull/830

**Comment by spiffxp** [comment]
https://cs.k8s.io/?q=latest-green.txt&i=nope&files=&repos=

It _looks_ like `gs://kubernetes-release-dev/ci/latest-green.txt` isn't actually consumed by automation

**Comment by justaugustus** [comment]
@spiffxp -- Carrying the convo from https://kubernetes.slack.com/archives/CJH2GBF7Y/p1590088139329000...

Yep, we've identified this as a need, but slowed down because the Prow bits weren't in place yet (ref: https://kubernetes.slack.com/archives/CJH2GBF7Y/p1590088139329000).

So, broad strokes/first guess on a plan:
- We need a new GCP project (shared ownership between SIG Release (Release Engineering), SIG Testing, WG K8s Infra). I don't know who "owns" `kubernetes-release-dev` today.
- New GCS bucket
- **insert infra script updates/actuation here**
- Add a new [scenario](https://github.com/kubernetes/test-infra/tree/master/scenarios) that defaults to publish to the new bucket
- Create canary `ci-kubernetes-build` jobs for all branches to start seeding the new bucket
- Start cutting over some e2e jobs to pull from the canary buckets (maybe some of the `release-*` e2es?)
- Migrate the other e2es
- Flip the `ci-kubernetes-build` jobs over to point to the new scenario (and turn down the canary build jobs)
- Flip release tooling to use the new bucket

Again, that's an incredible rough draft, but let me know what you think.

**Comment by justaugustus** [comment]
(I should assign myself here as well)
/assign

**Comment by justaugustus** [comment]
FYI: @kubernetes/release-engineering @kubernetes/ci-signal

**Comment by spiffxp** [comment]
Are there any strong opinions about:
- which GCP project the new bucket(s) should live under?
- what the new bucket(s) should be called?

Existing buckets I want to consider in this context are:
- gs://kubernetes-release-dev - used by periodics to store release artifacts (google-containers project, only google.com allowed)
- gs://kubernetes-release-pull - used by presubmits to stage release artifacts for launching e2e tests (kubernetes-jenkins project, allows non-google.com, but eventually we'll need to move away from this too)

**Comment by tpepper** [comment]
I somewhat wish the -pull, -dev buckets mapped directly to the ci-, periodic-, pull- test name pattern, but that's probably non-trivial to resolve?

**Comment by spiffxp** [comment]
Opened https://github.com/kubernetes/k8s.io/pull/1110 with my proposal

**Comment by tpepper** [comment]
Relative to my [comment](https://github.com/kubernetes/k8s.io/issues/846#issuecomment-668806467) earlier in the issue and pulling discussion from the PR closer to this comment:

> The "stops at a project+SKU" is why I'm proposing something (`k8s-release`) instead of `k8s-artifacts-prod`. The dividing line in my head is `k8s-artifacts-prod` is for final/static release artifacts for every single kubernetes subproject; `k8s-release` is for all the intermediary stuff (per-pr, postsubmits, nightlies, etc) related to kubernetes

...makes sense to me and explains the "-dev" as synonym/summary name for the ci-, periodic-, pull- tests' artifacts.  Dev as meaning not prod is logical.

**Comment by spiffxp** [comment]
And to answer a question that came up in my chat with @justaugustus: why one bucket for postsubmit/periodic and a different bucket for presubmit?
- For ACL's: 
  - it's much easier to manage ACL's per-bucket, there is a limit on per-path
  - presubmits run untrusted code, postsubmit/periodic runs ostensibly more trusted code since it's been allowed to merge after human review
  - using ACL's we can prevent presubmits from writing postsubmit artifacts
- For retention: 
  - lifecycle policies only work bucket
  - presubmit builds are much higher volume but also more ephemeral
  - in the current setup `-pull` expires after 14d, `-dev` after 90d

**Comment by spiffxp** [comment]
Picking back up on this for a bit now that we're out of v1.19.  The only remaining release-blocking and merge-blocking jobs that have yet to be migrated over to k8s-infra-prow-build are jobs that depend on these buckets.

We may be able to drop our existing use of gs://kubernetes-release-pull (ref: https://github.com/kubernetes/test-infra/issues/18789), so at present I haven't been migrated jobs to k8s-release-pull when migrating them over to k8s-infra-prow-build

I'm going to see if this can be as simple as starting with copies of the periodics/postsubmits that push builds into gs://kubernetes-release-dev, and have them push to gs://k8s-release-dev instead.

**Comment by spiffxp** [comment]
What has been done:
- created gs://k8s-release-dev (replacement for gs://kubernetes-release-dev) (done via: #1110)
- created gs://k8s-release-pull (replacement for gs://kubernetes-release-pull) (done via: #1110)

What needs to be done:
- ensure ACL's are correct on the new buckets for CI
  - k8s-infra-prow-build should be able to write to them
  - the world should be able to read from them
- setup duplicate build jobs that write to gs://k8s-release-dev instead of gs://kubernetes-release-dev
  - ci-kubernetes-build-fast (ref: https://github.com/kubernetes/test-infra/issues/19484)
  - ci-kubernetes-build (ref: https://github.com/kubernetes/test-infra/issues/19483)
  - other jobs tbd
- migrate postsubmit/periodic jobs to consume artifacts from gs://k8s-release-dev instead of gs://kubernetes-release-dev
- merge-blocking jobs need to either:
  - (preferred option) be modified to stop using gs://kubernetes-release-pull entirely, it's redundant/wasted storage/bandwidth (see: https://github.com/kubernetes/test-infra/issues/18789)
  - write to gs://k8s-release-pull instead of gs://kubernetes-release-pull

What should also be done:
- setup region replication for gs://k8s-release-dev (I created the regionals, gs://k8s-release-dev-{eu,asia}, but am not sure what's involved in setting up replication)

**Comment by spiffxp** [comment]
I think ACL's are correct, we should try running a job and verify whether prow needs privileges than this:
https://github.com/kubernetes/k8s.io/blob/6d3494a9b92999e2d0bbd911b962140cc56328ec/infra/gcp/ensure-release-projects.sh#L161-L164

**Comment by spiffxp** [comment]
https://github.com/kubernetes/test-infra/issues/19483#issuecomment-733277378 - points out there are many references to `kubernetes-release-dev` across the project

I'd like to scope this issue to just the job configs in kubernetes/test-infra.  We can consider this closable once all job configs have migrated to reference k8s-release-dev (except those necessary to maintain kubernetes-release-dev during deprecation window).

**Comment by spiffxp** [comment]
Opened https://github.com/kubernetes/test-infra/pull/20885
- adds tests to log whether job configs that use `--extract=` are pulling from community-owned buckets
- updated release-blocking tests to use gs://k8s-release, fail on any future release-blocking tests that don't

**Comment by spiffxp** [comment]
https://github.com/kubernetes/test-infra/pull/20964#issuecomment-784354491

Analysis from a while ago:
- as long as 
  - dl.k8s.io/ci continues to point to kubernetes-release-dev
  - there are parallel jobs pushing to kubernetes-release-dev, k8s-release-dev respectively
  - the build / either job occasionally flake
- people using dl.k8s.io/ci/*.txt version markers may try pulling something that doesn't exist in k8s-release-dev
- (and vice-versa, if you use k8s-release-dev/ci/*.txt but pull from kubernetes-release-dev)

We should either sync (one-way), move dl.k8s.io and other things aggressively (post-v1.21), or make it really really clear when and why this happens

**Comment by spiffxp** [comment]
Opened https://github.com/kubernetes/k8s.io/pull/2291 with a script I've been using to keep an eye on the delta between gs://k8s-release-dev and gs://kubernetes-release-dev

**Comment by spiffxp** [comment]
I'm going to consider this closed if https://github.com/kubernetes/test-infra/pull/22840 lands without breaking anything

I've opened https://github.com/kubernetes/k8s.io/issues/2318 as the umbrella issue to track "what else besides jobs"

**Comment by spiffxp** [comment]
/close
We caused some breakage but at this point I think anything remaining that nobody's noticed yet can be tracked in the umbrella issue.

I have a timeline of what landed / broke / fixed when: https://github.com/kubernetes/k8s.io/issues/2318#issuecomment-878609309
