### ISSUE TITLE
Cost of StackDriver

### ISSUE THREAD

**Issue by bartsmykla** [kubernetes/k8s.io#863]
As we discussed at todays community call, we should investigate why StackDriver costs that much (ref. https://datastudio.google.com/s/ny7d3ctsyxw) and if we can and should do something about it

**Comment by spiffxp** [comment]
This is focused on just charges coming from k8s-e2e-infra-boskos-*

It's weird that the daily burn rate of logging is going up over time

![Screen Shot 2020-05-13 at 4 36 28 PM](https://user-images.githubusercontent.com/49258/81876656-0ef70b80-9538-11ea-8dc6-55e0ca57bb89.png)

While the run rate of tests is basically constant
![Screen Shot 2020-05-13 at 4 39 59 PM](https://user-images.githubusercontent.com/49258/81876874-8a58bd00-9538-11ea-905a-9880ba89203f.png)

https://cloud.google.com/stackdriver/pricing

>For pricing purposes, Logging measures the quantity of logs data loaded and processed by Logging or other Google Cloud services. This pricing applies to all log data except for non-chargeable logs.

I fail to see how running the same amount of tests per day would cause us to generate more logs _per day_.  More logs _over time_, sure.  I wonder if mixed units are being plotted on this graph?

Either way, logs are stored in GCS as part of test results, e.g https://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce/1260537321967587329/artifacts/bootstrap-e2e-master/

We don't need to be ingesting them into StackDriver.  We suspect this should be a matter of finding the right env var to set for k/k's `cluster/kube-up.sh`

**Comment by dims** [comment]
we set `ENABLE_NODE_LOGGING=false`?
https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/config-default.sh#L234

**Comment by spiffxp** [comment]
I opened https://github.com/kubernetes/test-infra/pull/17662 to disable this at the `kubetest` level, in case folks who run kube-up.sh manually (either regularly or via make node-e2e-test) rely on the default logging behavior

**Comment by spiffxp** [comment]
It appears stackdriver's billing may lag a bit, it did end up leveling off as compute usage remained constant (this is for all projects, excluding those that run long-lived kubernetes clusters)
<img width="671" alt="Screen Shot 2020-05-20 at 2 22 55 PM" src="https://user-images.githubusercontent.com/49258/82498914-9cd97600-9aa5-11ea-9705-5af4c61ed68a.png">

**Comment by spiffxp** [comment]
Looks like https://github.com/kubernetes/test-infra/pull/17662 did the trick, calling this done
<img width="683" alt="Screen Shot 2020-05-26 at 12 16 23 PM" src="https://user-images.githubusercontent.com/49258/82941174-c6cde500-9f4a-11ea-8a0d-20e3d272b335.png">
/close

**Comment by dims** [comment]
very cool!
