### ISSUE TITLE
Create a project/bucket for cert-manager image mirroring

### ISSUE THREAD

**Issue by vincepri** [kubernetes/k8s.io#887]
All Kubebuilder projects, including Cluster API use cert-manager to generate certificates. I'd like to request a mirror from the current repository to a k8s.io-owned project/bucket that we can reference in our components.

**Comment by dims** [comment]
+1 to mirror what we do for etcd / coredns

cc @bartsmykla

**Comment by spiffxp** [comment]
We're still trying to work out whether we think this is an appropriate use of project resources, ref: https://github.com/kubernetes/k8s.io/issues/915
