### ISSUE TITLE
Migrate slack-infra to community built/hosted images

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/k8s.io#905]
@bartsmykla @ameukam 

https://github.com/kubernetes/test-infra/pull/17461 switched the job to push images to community hosting, but nothing's actually been built yet
```
$ gcloud container images list --repository gcr.io/k8s-staging-slack-infra
Listed 0 items
```

And our slack-infra deployment still uses the `gcr.io/kubernetes-tools` images (ref: https://cs.k8s.io/?q=kubernetes-tools&i=nope&files=&repos=kubernetes/k8s.io)

Can we open a PR to slack-infra to cause new images builds, and update our deployment to use the new images?

/wg k8s-infra

**Comment by ameukam** [comment]
I was waiting https://github.com/kubernetes-sigs/slack-infra/pull/31 to get merge. I'll make another PR.

**Comment by bartsmykla** [comment]
Done. I redeployed slack infra with the new images.
/close

**Comment by bartsmykla** [comment]
/open reopening till we'll also migrate the slackin
