### ISSUE TITLE
hosting google/triage-party for sig-release

### ISSUE THREAD

**Issue by ameukam** [kubernetes/k8s.io#906]
SIG-Release is exploring https://github.com/google/triage-party as a triage tool that will help the bug-triage team during release cycles. triage-party is optimized for k8s (or Google Cloud Run) deployments.

What's needed :
* a namespace in `aaa` cluster and a google group: https://github.com/kubernetes/k8s.io/pull/916/
* DNS entries
* TLS certificate
* an `Ingress` with GCP ip global adress

Persistence need to be discuss but we can start by using local disk. 

Ref. https://github.com/kubernetes/sig-release/issues/1073

/assign @spiffxp @thockin @bartsmykla @justaugustus @markyjackson-taulia 
/sig release
/area release-eng

**Comment by thockin** [comment]
No objection - I've been meaning to play with it :)

**Comment by ameukam** [comment]
triage-party is deployed (see #967) but we're facing an issue with the ingress controller on `aaa` cluster. Discussion abou this on slack : https://kubernetes.slack.com/archives/CCK68P2Q2/p1593722658371200.

**Comment by justaugustus** [comment]
@ameukam -- triage-party v1.2.0 is out, so we should be able to clear up the health-checking now: https://github.com/google/triage-party/releases/tag/v1.2.0

**Comment by ameukam** [comment]
@justaugustus `1.2.0` of triage-party is deployed : https://github.com/kubernetes/k8s.io/pull/1022.

**Comment by ameukam** [comment]
This is can be closed.
/close
