### ISSUE TITLE
blog.k8s.io:443 providing the wrong cert

### ISSUE THREAD

**Issue by mml** [kubernetes/k8s.io#91]
![jfqetblz8wp](https://user-images.githubusercontent.com/3115/32810405-9c86ef2c-c94f-11e7-9316-f919df3728a0.png)

cc @ixdy

**Comment by thockin** [comment]
Uggh, did that SAN not get registered?

**Comment by ixdy** [comment]
It did not, because we never set up a redirector for blog.k8s.io, so it was missed in audits.

It's about time to renew the cert anyway, so it's easy to add blog.* to the list.

**Comment by thockin** [comment]
Right!  We're not actually redirecting that URL.  Oops.  Once the cert is
up, we can add it.
