### ISSUE TITLE
Provide GCP accounts for SIG Node CI maintainers

### ISSUE THREAD

**Issue by alejandrox1** [kubernetes/k8s.io#956]
Hi all,
logging this issue to discuss the possibility of providing GCP accounts for SIG Node CI maintainers to be able to run e2e node tests.

In a lot of cases, node e2e tests can be executed locally but there are instances in which it is necessary to use specific VM images; to have machines with certain amount of vCPUs and memory; or to have specific hardware components.

The basic workflow that node ci maintainers would need, would be to be able to create VMs, SSH into them, and delete them.
See https://github.com/kubernetes/community/blob/master/contributors/devel/sig-node/e2e-node-tests.md#remotely

/cc @kubernetes/sig-node-test-failures

**Comment by bart0sh** [comment]
@alejandrox1 @dims @bsdnet @vpickard @MHBauer  Any suggestion how to speed up this?

**Comment by bartsmykla** [comment]
Today is our community call (http://bit.ly/wg-k8s-infra-notes) and we can discuss this topic. As far as I know there are no processes established to grant someone permissions to create instances or other resources manually.

**Comment by spiffxp** [comment]
/remove-lifecycle stale
When provisioning projects for e2e I set aside an instance of each type of project for manual debugging.  Technically, there doesn't need to be a node-e2e-project pool separate from the (default) node-e2e-project pool, but at the moment there is a k8s-infra-e2e-node-e2e-project for manual use (ref: https://github.com/kubernetes/k8s.io/blob/master/infra/gcp/ensure-e2e-projects.sh#L72)

We could setup a k8s-infra-node-e2e-oncall@kubernetes.io group and give them owner access to this project. I'm less clear whether the tests play well with N users running the same tests in the same project

/assign @thockin 
I'm also less clear whether setting aside GCP projects for manual maintainer usage is in scope for our budget.  Until we have fully migrated everything over in terms of hosting and automation, I'm less inclined to go this route until we can better understand costs.  Could someone maybe use the billing data from our billing report to come up with an estimate of node-e2e costs?

**Comment by spiffxp** [comment]
> We could setup a k8s-infra-node-e2e-oncall@kubernetes.io group and give them owner access to this project. I'm less clear whether the tests play well with N users running the same tests in the same project

I'm still open to doing this

/assign @SergeyKanzhelev @alejandrox1 @MHBauer 
Would like some input from SIG Node CI Subgroup

**Comment by spiffxp** [comment]
/milestone v1.22
/remove-priority important-longterm
/priority backlog
Still open to doing this, but bumping down priority since I haven't heard anything

**Comment by spiffxp** [comment]
/milestone v1.23
/remove-lifecycle stale
/unassign @thockin 
/assign @ehashman 
I'm led to believe you're also involved with the SIG Node CI subgroup.  Would be interested in hashing out what the specific request is here.

**Comment by SergeyKanzhelev** [comment]
I think enabling more tests to run from PRs solved some pain points.

**Comment by endocrimes** [comment]
> I'm less clear whether the tests play well with N users running the same tests in the same project

these tests play p well with that, I run the test suite in parallel in the same project ~daily. We'd need a robot to delete vms after some period though, as the suite doesn't clean up after itself.

---

I can see this being potentially useful for folks who don't have a work budget for working on node - A lot of the node_e2e suite doesn't particularly work well outside of the expected GCP configuration as they rely on knowing roughly how many resources are available, and don't tend to handle changes well.

I'm not sure what the active ask is though (or who would want/need access to it).

**Comment by SergeyKanzhelev** [comment]
We didn't come up with a specific requests here. 

I see more and more people using WIP PRs to troubleshoot small test failures. We may embrace this as a legitimate way to do this for "easy" troubleshooting. Maybe extending the number of tests that can run optionally on PRs and improve `/test` command to further scope what to run be helpful.

The biggest problem I see is developing new tests that require specific environment. I'd assume test would be developed locally on whatever available (this will help: https://github.com/kubernetes/kubernetes/pull/105764). When writing test definition and such, I'm not sure how much providing creds will help vs. allowing to run tests using the new/modified test definitions on PR to test-infra would help.

I suggest to remove it from this milestone or maybe even close to wait for more specific asks.

**Comment by ameukam** [comment]
No follow-up on this. Let's reopen a new one if needed.

/close
