### ISSUE TITLE
DNS tools/scripts rewriting from bash to python

### ISSUE THREAD

**Issue by bartsmykla** [kubernetes/k8s.io#966]
As there was (ref. #862) discussion started by @spiffxp about instead of extensive refactoring current bash scripts used to update DNS we should rewrite them to python.

At the beginning I was kind of reluctant for introducing another technology to our already not-small stack but then I realized we are already using python to check if dns zones were propagated correctly (cc. [`dns/check-zone.py`](https://github.com/kubernetes/k8s.io/blob/60ab594bbc6ddda9b90ba20d65c437b5b244e67b/dns/check-zone.py) it probably wouldn't be such a big deal.

I'm opening this issue to track the progress as I wouldn't considered this work as priority.
I would like to volunteer to do it (as I plan to play with it during my weekends) but I'm open for anyone who would like to be involved.
/assign

What I currently don't like is the way our scripts handle logging as we are logging everything to files `log.canary` and `log.prod` and if anything will fail the files will be shown. What I think would be better is improving a little bit logging at [`dns/check-zone.py`](https://github.com/kubernetes/k8s.io/blob/60ab594bbc6ddda9b90ba20d65c437b5b244e67b/dns/check-zone.py) as now they are very noisy and hard to read and then in new python version of the tools just display the logs to STDOUT/STDERR

**Comment by tcordeu** [comment]
Hey @bartsmykla can I work on this? If so, would you point me to the right direction?

**Comment by bartsmykla** [comment]
Hi @tcordeu, apologies as I was on PTO. Definitely you can work on it. I'll try to help next week with some directions. :-)
