### ISSUE TITLE
Need IAM permissions for Session Manager added to Boskos-managed AWS accounts

### ISSUE THREAD

**Issue by randomvariable** [kubernetes/k8s.io#984]
Porting over from https://github.com/kubernetes/test-infra/issues/17190 by @detiber 

What would you like to be added:

Recently we removed creation of a Bastion host by default from cluster-api-provider-aws and would prefer to avoid creating one for the purposes of testing and would rather use ssh proxied over AWS Session Manager to connect to remote instances for retrieving logs during testing instead.

Will need one of the below done against each AWS subaccount users that is registered as an aws-account resource in Boskos:

Attach the AmazonSSMFullAccess policy
Create a policy with the permissions outlined in docs.aws.amazon.com/systems-manager/latest/userguide/session-manager-getting-started-restrict-access.html and attach it, or add it as an inline policy

**Comment by randomvariable** [comment]
Is there anything we can do to get this moving? We kind of missed an upgrade bug for Kubernetes 1.19 for a few reasons, but would have been compounded by not having the logs that SSM would have provided.

**Comment by justinsb** [comment]
I added the permission to #1016 (and it's in the latest accounts that I just created, but we should wait till #1016 merges before applying to boskos)

**Comment by spiffxp** [comment]
/priority backlog
I have lost track of where we're at with AWS account management

**Comment by ameukam** [comment]
All of the related tests to AWS have been migrated to a dedicated AWS organization.
A new issue will open if needed again.

/close
